SUBROUTINE DYSON
! TRANSFORM TWO-ELECTRON INTEGRALS BY O(N**5) ALGORITHM AND EVALUATE THE INVERSE DYSON QUASI-PARTICLE ENERGIES
! USING THE DIAGONAL APPROXIMATION TO THE SELF-ENERGY TERM.
! AO-BASED TWO-ELECTRON INTEGRALS ARE RETRIEVED FROM DISK.

   USE MPI
   USE CONSTANTS
   USE CONTROL
   USE STRUCTURE
   USE BASISSET
   USE INTEGRAL
   USE GRADIENT
   
   IMPLICIT NONE
   INCLUDE "mpif.h"
   DOUBLE PRECISION :: ICPUS,ICPUE
   INTEGER,PARAMETER :: CASHESIZE = 1000 ! CASHE SIZE MUST BE EXACTLY THE SAME IN THE STORE & RESTORE SUBROUTINES
   INTEGER,PARAMETER :: MAXITR = 100     ! MAXIMUM NUMBER OF THE DYSON ITERATIONS
   DOUBLE PRECISION :: DYSONCNV          ! CONVERGENCE CRITERION FOR THE DYSON ITERATIONS
   DOUBLE PRECISION :: DYSONETA          ! DAMPING FACTOR TO AVOID ZERO DENOMINATOR
   INTEGER :: ITR
   INTEGER :: MOI,MOJ,MOA,MOB,MOG,MOH,MOTARGET,MOTARGET2
   INTEGER :: KIX,KIY,KIZ,KJX,KJY,KJZ,KAX,KAY,KAZ,KBX,KBY,KBZ,KGX,KGY,KGZ
   INTEGER :: Q1X,Q1Y,Q1Z,Q2X,Q2Y,Q2Z,Q3X,Q3Y,Q3Z
   INTEGER :: I,J,K,L,PX,PY,PZ,QX,QY,QZ,RX,RY,RZ
   INTEGER :: EOF
   INTEGER :: ICASHECOUNT
   DOUBLE PRECISION :: ICOUNT,ICOUNTTOTAL
   INTEGER(4),ALLOCATABLE :: ICASHE1X(:),ICASHE1Y(:),ICASHE1Z(:),ICASHE2(:)
   DOUBLE PRECISION,ALLOCATABLE :: DCASHE(:)
   DOUBLE PRECISION,ALLOCATABLE :: TEPSILON(:,:,:,:)
   DOUBLE PRECISION,ALLOCATABLE :: DEPSILON_TMP(:,:,:,:)
   DOUBLE PRECISION,ALLOCATABLE :: DPOLE_TMP(:,:,:,:)
   DOUBLE PRECISION,ALLOCATABLE :: QEPSILON_TMP(:,:,:,:)
   DOUBLE COMPLEX,ALLOCATABLE :: FEPSILON_TMP(:,:,:,:,:,:)
   DOUBLE COMPLEX,ALLOCATABLE :: FPOLE_TMP(:,:,:,:,:,:)
   DOUBLE PRECISION,ALLOCATABLE :: E(:)
   DOUBLE COMPLEX,ALLOCATABLE :: WC(:,:)
   DOUBLE PRECISION :: POLE
   DOUBLE PRECISION :: MAXOVERLAP,OVERLAP
   INTEGER :: MAXJ
   DOUBLE PRECISION :: EMP2,EMP2S,EMP2T,EMP2S_TMP,EMP2T_TMP
   DOUBLE PRECISION :: MAXDEV
   DOUBLE COMPLEX,ALLOCATABLE :: PHASEX(:),PHASEY(:),PHASEZ(:)
   DOUBLE COMPLEX,ALLOCATABLE :: TNNNKK(:,:,:,:,:),TOK(:,:)
   DOUBLE COMPLEX,ALLOCATABLE :: TVOKK(:,:,:,:),TOVOKK(:,:,:,:,:)
   INTEGER :: KVCX2,KVCY2,KVCZ2
   INTEGER :: NMOD
   INTEGER :: TICKET
   INTEGER :: NFILES,IFILE,JFILE
   LOGICAL :: LEXIST
   CHARACTER(6) :: FILEAPPENDIX
! -- HELIX 
   DOUBLE COMPLEX,ALLOCATABLE :: CO_HELIX(:,:,:,:)
! -- HELIX

! -- HELIX 
   IF (HELIX /= 0.0D0) THEN
    ALLOCATE(CO_HELIX(NCGS,NCGS,-KVCX:KVCX,-CEL1X-CEL2X:CEL1X+CEL2X))
    DO KIX=-KVCX,MAX(0,KVCX-1)
     DO MOI=ICORE+1,IALL(KIX,0,0)
      DO PX=-CEL1X-CEL2X,CEL1X+CEL2X
       DO I=1,NCGS
        CO_HELIX(I,MOI,KIX,PX)=DCMPLX(0.0D0,0.0D0)
        DO J=1,NCGS
         CO_HELIX(I,MOI,KIX,PX)=CO_HELIX(I,MOI,KIX,PX)+CO(J,MOI,KIX,0,0)*C2H(J,I,PX)
        ENDDO
       ENDDO
      ENDDO
     ENDDO
    ENDDO
   ENDIF
! -- HELIX 

   NMOD = IOPTN(99)
   DYSONCNV = DOPTN(107)
   IF (NMOD < 1) CALL PABORT('ILLEGAL MODULO PARAMETER')
   IF (NMOD > 1) THEN
    IF (MYID == 0) WRITE(6,'(A)')      '**********************************************************'
    IF (MYID == 0) WRITE(6,'(A,I3,A)') '* DYSON QUASI-PARTICLE ENERGY CORRECTIONS WITH MOD = ',NMOD,' *'
    IF (MYID == 0) WRITE(6,'(A)')      '**********************************************************'
    IF (KVCX/NMOD*NMOD /= KVCX) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG X')
    IF (KVCY/NMOD*NMOD /= KVCY) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG Y')
    IF (KVCZ/NMOD*NMOD /= KVCZ) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG Z')
    KVCX2=KVCX/NMOD
    KVCY2=KVCY/NMOD
    KVCZ2=KVCZ/NMOD
   ELSE
    KVCX2=KVCX
    KVCY2=KVCY
    KVCZ2=KVCZ
   ENDIF

   ALLOCATE(ICASHE1X(CASHESIZE),ICASHE1Y(CASHESIZE),ICASHE1Z(CASHESIZE),ICASHE2(CASHESIZE),DCASHE(CASHESIZE))
   ALLOCATE(PHASEX(-(CEL1X+CEL2X)*KVCX2:(CEL1X+CEL2X)*KVCX2))
   ALLOCATE(PHASEY(-(CEL1Y+CEL2Y)*KVCY2:(CEL1Y+CEL2Y)*KVCY2))
   ALLOCATE(PHASEZ(-(CEL1Z+CEL2Z)*KVCZ2:(CEL1Z+CEL2Z)*KVCZ2))
   ALLOCATE(TEPSILON(NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))
   ALLOCATE(DEPSILON_TMP(NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))
   ALLOCATE(DPOLE_TMP(NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))
   ALLOCATE(QEPSILON_TMP(NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))
   IF (.NOT.LOPTN(106)) THEN
    ALLOCATE(FEPSILON_TMP(NCGS,NCGS,NCGS,-KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2))
    ALLOCATE(FPOLE_TMP(NCGS,NCGS,NCGS,-KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2))
    ALLOCATE(WC(NCGS,NCGS),E(NCGS))
   ENDIF

   IF (LOPTN(106)) THEN
    IF (MYID == 0) WRITE(6,'(A)') 'CALCULATE DYSON QUASI-PARTICLE ENERGIES WITH DIAGONAL, FREQ-DEPENDENT SELF-ENERGY'
   ELSE
    IF (MYID == 0) WRITE(6,'(A)') 'CALCULATE DYSON QUASI-PARTICLE ENERGIES WITH NONDIAGONAL, FREQ-DEPENDENT SELF-ENERGY'
   ENDIF
   IF (IOPTN(27) /= 0) CALL WARNING('FROZEN CORE APPROXIMATION WILL BE USED')
   IF (IOPTN(55) /= 0) CALL WARNING('FROZEN VIRTUAL APPROXIMATION WILL BE USED')
   IF (IALLMAX-IOCC-IVIRTCORE <= 0) THEN
    CALL WARNING('THERE IS NO VIRTUAL ORBITAL --- MP2 CORRECTION IS NULL')
    RETURN
   ENDIF
   IF (IOPTN(44) == 0) THEN
    CALL PABORT('NO DYSON QUASI-PARTICLE ENERGY CALCULATION REQUESTED')
   ELSE IF (IOPTN(44) <= NCGS) THEN
    IF (MYID == 0) WRITE(6,'(A,I3,A,I3,A)') 'DYSON QUASI-PARTICLE ENERGY CALCULATIONS FOR',IOPTN(44), &
     ' OCCUPIED AND',IOPTN(44),' VIRTUAL BANDS WILL BE PERFORMED'
   ELSE
    IF (MYID == 0) WRITE(6,'(A)') &
     'DYSON QUASI-PARTICLE ENERGY CALCULATIONS FOR ALL OCCUPIED AND VIRTUAL BANDS WILL BE PERFORMED'
   ENDIF
   DYSONETA=DOPTN(45)

   NFILES=0
   IF (MYID == 0) THEN
    DO WHILE (.TRUE.)
     WRITE(FILEAPPENDIX,'(I6)') 100000+NFILES
     INQUIRE(FILE=TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6),EXIST=LEXIST)
     IF (LEXIST) THEN
      WRITE(6,'(A)') TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6)//' IS FOUND'
      NFILES=NFILES+1
     ELSE
      EXIT
     ENDIF
    ENDDO
   ENDIF
   CALL MPI_BCAST(NFILES,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   IF (NFILES == 0) CALL PABORT('NO ERI FILES WAS FOUND')

   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT(NCGS**3*(2*CEL1X+1)*(2*CEL1Y+1)*(2*CEL1Z+1)*(2*CEL2X+1)*(2*CEL2Y+1)*(2*CEL2Z+1)) &
    /1.0D3,' K WORDS (TNNNKK)'
   CALL PFLUSH(6)
   ALLOCATE(TNNNKK(NCGS,NCGS,NCGS,(2*CEL1X+1)*(2*CEL1Y+1)*(2*CEL1Z+1),(2*CEL2X+1)*(2*CEL2Y+1)*(2*CEL2Z+1)))
   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT((MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE)-ICORE-2)*(2*KVCX2+1)*(2*KVCY2+1)*(2*KVCZ2+1)) &
    /1.0D3,' K WORDS (TOK)'
   CALL PFLUSH(6)
   ALLOCATE(TOK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2)))
   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT((IALLMAX-IVIRTCORE-MAX(IOCC+1-IOPTN(44),ICORE+1)-1) &
    *(MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE)-ICORE-2)*MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2) &
    *MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2))/1.0D3,' K WORDS (TVOKK)'
   CALL PFLUSH(6)
   ALLOCATE(TVOKK(MAX(IOCC+1-IOPTN(44),ICORE+1):IALLMAX-IVIRTCORE,ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),&
                  MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2),MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2)))
   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT(IALLMAX-IVIRTCORE-MAX(IOCC+1-IOPTN(44),ICORE+1)-1) &
                                      *DFLOAT(MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE)-ICORE-2)**2 &
                                      *DFLOAT(MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2) &
                                             *MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2))/1.0D3,' K WORDS (TOVOKK)'
   CALL PFLUSH(6)
   ALLOCATE(TOVOKK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),MAX(IOCC+1-IOPTN(44),ICORE+1):IALLMAX-IVIRTCORE, &
                   ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE), &
                   MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2),MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2)))

   DO I=-(CEL1X+CEL2X)*KVCX2,(CEL1X+CEL2X)*KVCX2
    IF (KVCX2 == 0) THEN
     PHASEX(I)=DCMPLX(1.0D0,0.0D0)
    ELSE
     PHASEX(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCX2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCX2)*PI))
    ENDIF
   ENDDO
   DO I=-(CEL1Y+CEL2Y)*KVCY2,(CEL1Y+CEL2Y)*KVCY2
    IF (KVCY2 == 0) THEN
     PHASEY(I)=DCMPLX(1.0D0,0.0D0)
    ELSE
     PHASEY(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCY2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCY2)*PI))
    ENDIF
   ENDDO
   DO I=-(CEL1Z+CEL2Z)*KVCZ2,(CEL1Z+CEL2Z)*KVCZ2
    IF (KVCZ2 == 0) THEN
     PHASEZ(I)=DCMPLX(1.0D0,0.0D0)
    ELSE
     PHASEZ(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCZ2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCZ2)*PI))
    ENDIF
   ENDDO

   EMP2S=0.0D0
   EMP2T=0.0D0
   EMP2S_TMP=0.0D0
   EMP2T_TMP=0.0D0
   QEPSILON=0.0D0
   QEPSILON_TMP=0.0D0
   TEPSILON=EPSILON

   ! COMPUTE E(2) AND QUASI-PARTICLE ENERGY BANDS
   DYSONETA=DOPTN(45)
   DO ITR=1,MAXITR
    DEPSILON=0.0D0
    DEPSILON_TMP=0.0D0
    DPOLE=0.0D0
    DPOLE_TMP=0.0D0
    IF (.NOT.LOPTN(106)) THEN
     FEPSILON_TMP=DCMPLX(0.0D0,0.0D0)
     FPOLE_TMP=DCMPLX(0.0D0,0.0D0)
    ENDIF
    CALL PCPU_TIME(ICPUS)
    TICKET=0
    DO KBX=-KVCX2,MAX(0,KVCX2-1)
    DO KBY=-KVCY2,MAX(0,KVCY2-1)
    DO KBZ=-KVCZ2,MAX(0,KVCZ2-1)
     DO MOB=IOCC+1,IALL(KBX,KBY,KBZ)-IVIRTCORE
! --- PARALLEL LOOP
      TICKET=TICKET+1
      IF (TICKET == NUMPROCS) TICKET=TICKET-NUMPROCS
      IF (MYID == TICKET) THEN
!write(*,*) 'Process:',myid,'KBs = ',KBX,KBY,KBZ,'MOB = ',MOB
! --- PARALLEL LOOP
       TNNNKK=DCMPLX(0.0D0,0.0D0)
       DO IFILE=1,NFILES
        JFILE=IFILE+MYID-1
        JFILE=JFILE-JFILE/NFILES*NFILES
        WRITE(FILEAPPENDIX,'(I6)') 100000+JFILE
!write(*,*) 'Process:',myid,' reading from ',TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6)
        OPEN(31,FILE=TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6),FORM='UNFORMATTED')
        REWIND(31)
        ICOUNT=0
        DO
         READ(31,IOSTAT=EOF) ICASHE1X,ICASHE1Y,ICASHE1Z,ICASHE2,DCASHE
         IF (EOF /= 0) EXIT
         DO ICASHECOUNT=1,CASHESIZE
          IF (ICASHE1X(ICASHECOUNT) == -1) EXIT
          ICOUNT=ICOUNT+1.0D0
          PX=0
          QX=0
          RX=0
          PY=0
          QY=0
          RY=0
          PZ=0
          QZ=0
          RZ=0
          I=0
          J=0
          K=0
          L=0
          CALL MVBITS(ICASHE1X(ICASHECOUNT),16,8,PX,0)
          CALL MVBITS(ICASHE1X(ICASHECOUNT), 8,8,QX,0)
          CALL MVBITS(ICASHE1X(ICASHECOUNT), 0,8,RX,0)
          CALL MVBITS(ICASHE1Y(ICASHECOUNT),16,8,PY,0)
          CALL MVBITS(ICASHE1Y(ICASHECOUNT), 8,8,QY,0)
          CALL MVBITS(ICASHE1Y(ICASHECOUNT), 0,8,RY,0)
          CALL MVBITS(ICASHE1Z(ICASHECOUNT),16,8,PZ,0)
          CALL MVBITS(ICASHE1Z(ICASHECOUNT), 8,8,QZ,0)
          CALL MVBITS(ICASHE1Z(ICASHECOUNT), 0,8,RZ,0)
          CALL MVBITS(ICASHE2(ICASHECOUNT),24,8,I,0)
          CALL MVBITS(ICASHE2(ICASHECOUNT),16,8,J,0)
          CALL MVBITS(ICASHE2(ICASHECOUNT), 8,8,K,0)
          CALL MVBITS(ICASHE2(ICASHECOUNT), 0,8,L,0)
          Q1X=PX-CEL1X
          Q2X=QX-CEL1X
          Q3X=RX-CEL2X
          Q1Y=PY-CEL1Y
          Q2Y=QY-CEL1Y
          Q3Y=RY-CEL2Y
          Q1Z=PZ-CEL1Z
          Q2Z=QZ-CEL1Z
          Q3Z=RZ-CEL2Z
          IF ((Q1X < -REDUCED_CEL1X).OR.(Q1X > REDUCED_CEL1X).OR.(Q2X < -REDUCED_CEL1X).OR.(Q2X > REDUCED_CEL1X).OR. &
              (Q1Y < -REDUCED_CEL1Y).OR.(Q1Y > REDUCED_CEL1Y).OR.(Q2Y < -REDUCED_CEL1Y).OR.(Q2Y > REDUCED_CEL1Y).OR. &
              (Q1Z < -REDUCED_CEL1Z).OR.(Q1Z > REDUCED_CEL1Z).OR.(Q2Z < -REDUCED_CEL1Z).OR.(Q2Z > REDUCED_CEL1Z).OR. &
              (Q3X < -CEL2X).OR.(Q3X > CEL2X).OR.(Q3Y < -CEL2Y).OR.(Q3Y > CEL2Y).OR.(Q3Z < -CEL2Z).OR.(Q3Z > CEL2Z)) &
          CALL PABORT('INTEGRAL FILE HAS BEEN DEGRADED')
          IF (HELIX == 0.0D0) THEN
           TNNNKK(I,J,K,((Q1X+CEL1X)*(2*CEL1Y+1)+(Q1Y+CEL1Y))*(2*CEL1Z+1)+(Q1Z+CEL1Z)+1, &
                        ((Q3X+CEL2X)*(2*CEL2Y+1)+(Q3Y+CEL2Y))*(2*CEL2Z+1)+(Q3Z+CEL2Z)+1)= &
           TNNNKK(I,J,K,((Q1X+CEL1X)*(2*CEL1Y+1)+(Q1Y+CEL1Y))*(2*CEL1Z+1)+(Q1Z+CEL1Z)+1, &
                        ((Q3X+CEL2X)*(2*CEL2Y+1)+(Q3Y+CEL2Y))*(2*CEL2Z+1)+(Q3Z+CEL2Z)+1) &
                        +CO(L,MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD) &
                        *PHASEX(KBX*(Q2X+Q3X))*PHASEY(KBY*(Q2Y+Q3Y))*PHASEZ(KBZ*(Q2Z+Q3Z))*DCMPLX(DCASHE(ICASHECOUNT),0.0D0)
          ELSE ! -- HELIX
           TNNNKK(I,J,K,((Q1X+CEL1X)*(2*CEL1Y+1)+(Q1Y+CEL1Y))*(2*CEL1Z+1)+(Q1Z+CEL1Z)+1, &
                        ((Q3X+CEL2X)*(2*CEL2Y+1)+(Q3Y+CEL2Y))*(2*CEL2Z+1)+(Q3Z+CEL2Z)+1)= &
           TNNNKK(I,J,K,((Q1X+CEL1X)*(2*CEL1Y+1)+(Q1Y+CEL1Y))*(2*CEL1Z+1)+(Q1Z+CEL1Z)+1, &
                        ((Q3X+CEL2X)*(2*CEL2Y+1)+(Q3Y+CEL2Y))*(2*CEL2Z+1)+(Q3Z+CEL2Z)+1) &
                        +CO_HELIX(L,MOB,KBX*NMOD,Q2X+Q3X) &
                        *PHASEX(KBX*(Q2X+Q3X))*PHASEY(KBY*(Q2Y+Q3Y))*PHASEZ(KBZ*(Q2Z+Q3Z))*DCMPLX(DCASHE(ICASHECOUNT),0.0D0)
          ENDIF ! -- HELIX
         ENDDO
        ENDDO
        CLOSE(31)
       ENDDO
       IF ((IOPTN(9) >= 2).AND.(MYID == 0)) WRITE(6,'(F20.0,A,F7.3,A)') ICOUNT, &
       ' ERIS (',ICOUNT/DFLOAT((CEL1X*2+1)**2*(CEL2X+1)*(CEL1Y*2+1)**2*(CEL2Y+1)*(CEL1Z*2+1)**2*(CEL2Z+1)*NCGS**4)*100.0, &
       '% OF TOTAL ERIS) HAVE BEEN RESTORED'
       TOVOKK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),MAX(IOCC+1-IOPTN(44),ICORE+1):IALLMAX-IVIRTCORE, &
              ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE), &
              1:MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2),1:MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2))=DCMPLX(0.0D0,0.0D0)
       DO I=1,NCGS
        TVOKK(MAX(IOCC+1-IOPTN(44),ICORE+1):IALLMAX-IVIRTCORE,ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE), &
        1:MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2),1:MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2))=DCMPLX(0.0D0,0.0D0)
        DO Q1X=-CEL1X,CEL1X
        DO Q1Y=-CEL1Y,CEL1Y
        DO Q1Z=-CEL1Z,CEL1Z
         DO J=1,NCGS
          TOK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),1:MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2))=DCMPLX(0.0D0,0.0D0)
          DO Q3X=-CEL2X,CEL2X
          DO Q3Y=-CEL2Y,CEL2Y
          DO Q3Z=-CEL2Z,CEL2Z
           DO K=1,NCGS
            DO KJX=-KVCX2,MAX(0,KVCX2-1)
            DO KJY=-KVCY2,MAX(0,KVCY2-1)
            DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
             DO MOJ=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KJX,KJY,KJZ)-IVIRTCORE)
              IF (HELIX == 0.0D0) THEN
               TOK(MOJ,((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)= &
               TOK(MOJ,((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)+ &
               TNNNKK(I,J,K,((Q1X+CEL1X)*(2*CEL1Y+1)+(Q1Y+CEL1Y))*(2*CEL1Z+1)+(Q1Z+CEL1Z)+1, &
                            ((Q3X+CEL2X)*(2*CEL2Y+1)+(Q3Y+CEL2Y))*(2*CEL2Z+1)+(Q3Z+CEL2Z)+1) &
               *DCONJG(CO(K,MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD))*PHASEX(-KJX*Q3X)*PHASEY(-KJY*Q3Y)*PHASEZ(-KJZ*Q3Z)
              ELSE ! -- HELIX
               TOK(MOJ,((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)= &
               TOK(MOJ,((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)+ &
               TNNNKK(I,J,K,((Q1X+CEL1X)*(2*CEL1Y+1)+(Q1Y+CEL1Y))*(2*CEL1Z+1)+(Q1Z+CEL1Z)+1, &
                            ((Q3X+CEL2X)*(2*CEL2Y+1)+(Q3Y+CEL2Y))*(2*CEL2Z+1)+(Q3Z+CEL2Z)+1) &
               *DCONJG(CO_HELIX(K,MOJ,KJX*NMOD,Q3X))*PHASEX(-KJX*Q3X)*PHASEY(-KJY*Q3Y)*PHASEZ(-KJZ*Q3Z)
              ENDIF ! -- HELIX
             ENDDO
            ENDDO
            ENDDO
            ENDDO
           ENDDO
          ENDDO
          ENDDO
          ENDDO
          DO KJX=-KVCX2,MAX(0,KVCX2-1)
          DO KJY=-KVCY2,MAX(0,KVCY2-1)
          DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
           DO KAX=-KVCX2,MAX(0,KVCX2-1)
           DO KAY=-KVCY2,MAX(0,KVCY2-1)
           DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
            DO MOJ=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KJX,KJY,KJZ)-IVIRTCORE)
             DO MOA=MAX(IOCC+1-IOPTN(44),ICORE+1),IALL(KAX,KAY,KAZ)-IVIRTCORE
              IF (HELIX == 0.0D0) THEN
               TVOKK(MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                             ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)= &
               TVOKK(MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                             ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               +TOK(MOJ,((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *CO(J,MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)*PHASEX(KAX*Q1X)*PHASEY(KAY*Q1Y)*PHASEZ(KAZ*Q1Z)
              ELSE ! -- HELIX
               TVOKK(MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                             ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)= &
               TVOKK(MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                             ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               +TOK(MOJ,((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *CO_HELIX(J,MOA,KAX*NMOD,Q1X)*PHASEX(KAX*Q1X)*PHASEY(KAY*Q1Y)*PHASEZ(KAZ*Q1Z)
              ENDIF ! -- HELIX
             ENDDO
            ENDDO
           ENDDO
           ENDDO
           ENDDO
          ENDDO
          ENDDO
          ENDDO
         ENDDO
        ENDDO
        ENDDO
        ENDDO
        DO KJX=-KVCX2,MAX(0,KVCX2-1)
        DO KJY=-KVCY2,MAX(0,KVCY2-1)
        DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
         DO KAX=-KVCX2,MAX(0,KVCX2-1)
         DO KAY=-KVCY2,MAX(0,KVCY2-1)
         DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
          KIX=KAX-KJX+KBX
          KIY=KAY-KJY+KBY
          KIZ=KAZ-KJZ+KBZ
          IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
          IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
          IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
          IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
          IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
          IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
          DO MOJ=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KJX,KJY,KJZ)-IVIRTCORE)
           DO MOA=MAX(IOCC+1-IOPTN(44),ICORE+1),IALL(KAX,KAY,KAZ)-IVIRTCORE
            DO MOI=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KIX,KIY,KIZ)-IVIRTCORE)
             IF (HELIX == 0.0D0) THEN
              TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                 ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)= &
              TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                 ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
              +TVOKK(MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                             ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
              *DCONJG(CO(I,MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD))
             ELSE ! -- HELIX
              TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                 ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)= &
              TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                 ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
              +TVOKK(MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                             ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
              *DCONJG(CO_HELIX(I,MOI,KIX*NMOD,0))
             ENDIF ! -- HELIX
            ENDDO
           ENDDO
          ENDDO
         ENDDO
         ENDDO
         ENDDO
        ENDDO
        ENDDO
        ENDDO
       ENDDO
       IF (ITR == 1) THEN
        DO KJX=-KVCX2,MAX(0,KVCX2-1)
        DO KJY=-KVCY2,MAX(0,KVCY2-1)
        DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
         DO KAX=-KVCX2,MAX(0,KVCX2-1)
         DO KAY=-KVCY2,MAX(0,KVCY2-1)
         DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
          KIX=KAX-KJX+KBX
          KIY=KAY-KJY+KBY
          KIZ=KAZ-KJZ+KBZ
          IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
          IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
          IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
          IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
          IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
          IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
          DO MOJ=ICORE+1,IOCC
           DO MOA=IOCC+1,IALL(KAX,KAY,KAZ)-IVIRTCORE
            DO MOI=ICORE+1,IOCC
!write(*,'(8i3,2f20.10)') kix,kjx,kax,kbx,moi,moj,moa,mob,tovokk(moi,moa,moj,kax,kay,kaz,kjx,kjy,kjz)
             EMP2S_TMP=EMP2S_TMP &
               +(0.5D0*TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
                      *DCONJG(TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                                 ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
               + 0.5D0*DREAL(TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                                ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
                      *DCONJG(TOVOKK(MOJ,MOA,MOI,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                                 ((KIX+KVCX2)*MAX(1,2*KVCY2)+(KIY+KVCY2))*MAX(1,2*KVCZ2)+KIZ+KVCZ2+1)))) &
               /(EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
                -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))
             EMP2T_TMP=EMP2T_TMP &
               +(1.5D0*TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
                      *DCONJG(TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                                 ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
               - 1.5D0*DREAL(TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                                ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
                      *DCONJG(TOVOKK(MOJ,MOA,MOI,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                                 ((KIX+KVCX2)*MAX(1,2*KVCY2)+(KIY+KVCY2))*MAX(1,2*KVCZ2)+KIZ+KVCZ2+1)))) &
               /(EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
                -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))
            ENDDO
           ENDDO
          ENDDO
         ENDDO
         ENDDO
         ENDDO
        ENDDO
        ENDDO
        ENDDO
! ----  DIAGONAL FREQUENCY-INDEPENDENT 
        DO KJX=-KVCX2,MAX(0,KVCX2-1)
        DO KJY=-KVCY2,MAX(0,KVCY2-1)
        DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
         DO KAX=-KVCX2,MAX(0,KVCX2-1)
         DO KAY=-KVCY2,MAX(0,KVCY2-1)
         DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
          KGX=KAX-KJX+KBX
          KGY=KAY-KJY+KBY
          KGZ=KAZ-KJZ+KBZ
          IF (KGX >= KVCX2) KGX=KGX-2*KVCX2
          IF (KGY >= KVCY2) KGY=KGY-2*KVCY2
          IF (KGZ >= KVCZ2) KGZ=KGZ-2*KVCZ2
          IF (KGX < -KVCX2) KGX=KGX+2*KVCX2
          IF (KGY < -KVCY2) KGY=KGY+2*KVCY2
          IF (KGZ < -KVCZ2) KGZ=KGZ+2*KVCZ2
          DO MOJ=ICORE+1,IOCC
           DO MOA=IOCC+1,IALL(KAX,KAY,KAZ)-IVIRTCORE
            DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
             QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
               +(2.0D0*TOVOKK(MOG,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOG,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
               - DREAL(TOVOKK(MOG,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOJ,MOA,MOG,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1)))) &
               /(EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
                -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))
            ENDDO
           ENDDO
          ENDDO
         ENDDO
         ENDDO
         ENDDO
        ENDDO
        ENDDO
        ENDDO
        DO KJX=-KVCX2,MAX(0,KVCX2-1)
        DO KJY=-KVCY2,MAX(0,KVCY2-1)
        DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
         DO KGX=-KVCX2,MAX(0,KVCX2-1)
         DO KGY=-KVCY2,MAX(0,KVCY2-1)
         DO KGZ=-KVCZ2,MAX(0,KVCZ2-1)
          KIX=KGX-KJX+KBX
          KIY=KGY-KJY+KBY
          KIZ=KGZ-KJZ+KBZ
          IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
          IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
          IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
          IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
          IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
          IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
          DO MOJ=ICORE+1,IOCC
           DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
            DO MOI=ICORE+1,IOCC
             QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
               +(2.0D0*TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
               - DREAL(TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOJ,MOG,MOI,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KIX+KVCX2)*MAX(1,2*KVCY2)+(KIY+KVCY2))*MAX(1,2*KVCZ2)+KIZ+KVCZ2+1)))) &
               /(EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD) &
                -EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)-EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD))
            ENDDO
           ENDDO
          ENDDO
         ENDDO
         ENDDO
         ENDDO
        ENDDO
        ENDDO
        ENDDO
       ENDIF
! ---- DIAGONAL FREQUENCY-DEPENDENT 
       IF (LOPTN(106)) THEN
        DO KJX=-KVCX2,MAX(0,KVCX2-1)
        DO KJY=-KVCY2,MAX(0,KVCY2-1)
        DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
         DO KAX=-KVCX2,MAX(0,KVCX2-1)
         DO KAY=-KVCY2,MAX(0,KVCY2-1)
         DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
          KGX=KAX-KJX+KBX
          KGY=KAY-KJY+KBY
          KGZ=KAZ-KJZ+KBZ
          IF (KGX >= KVCX2) KGX=KGX-2*KVCX2
          IF (KGY >= KVCY2) KGY=KGY-2*KVCY2
          IF (KGZ >= KVCZ2) KGZ=KGZ-2*KVCZ2
          IF (KGX < -KVCX2) KGX=KGX+2*KVCX2
          IF (KGY < -KVCY2) KGY=KGY+2*KVCY2
          IF (KGZ < -KVCZ2) KGZ=KGZ+2*KVCZ2
          DO MOJ=ICORE+1,IOCC
           DO MOA=IOCC+1,IALL(KAX,KAY,KAZ)-IVIRTCORE
            DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
             DEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=DEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
               +(2.0D0*TOVOKK(MOG,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOG,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
               - DREAL(TOVOKK(MOG,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOJ,MOA,MOG,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1)))) &
               *(TEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
                -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD)) &
               /((TEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
                -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))**2+DYSONETA)
             DPOLE_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=DPOLE_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
               -(2.0D0*TOVOKK(MOG,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOG,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
               - DREAL(TOVOKK(MOG,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOJ,MOA,MOG,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1)))) &
               /((TEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
                -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))**2)
            ENDDO
           ENDDO
          ENDDO
         ENDDO
         ENDDO
         ENDDO
        ENDDO
        ENDDO
        ENDDO
        DO KJX=-KVCX2,MAX(0,KVCX2-1)
        DO KJY=-KVCY2,MAX(0,KVCY2-1)
        DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
         DO KGX=-KVCX2,MAX(0,KVCX2-1)
         DO KGY=-KVCY2,MAX(0,KVCY2-1)
         DO KGZ=-KVCZ2,MAX(0,KVCZ2-1)
          KIX=KGX-KJX+KBX
          KIY=KGY-KJY+KBY
          KIZ=KGZ-KJZ+KBZ
          IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
          IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
          IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
          IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
          IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
          IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
          DO MOJ=ICORE+1,IOCC
           DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
            DO MOI=ICORE+1,IOCC
             DEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=DEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
               +(2.0D0*TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
               - DREAL(TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOJ,MOG,MOI,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KIX+KVCX2)*MAX(1,2*KVCY2)+(KIY+KVCY2))*MAX(1,2*KVCZ2)+KIZ+KVCZ2+1)))) &
               *(TEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD) &
                -EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)-EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD)) &
               /((TEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD) &
                -EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)-EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD))**2+DYSONETA)
             DPOLE_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=DPOLE_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
               -(2.0D0*TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
               - DREAL(TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOJ,MOG,MOI,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KIX+KVCX2)*MAX(1,2*KVCY2)+(KIY+KVCY2))*MAX(1,2*KVCZ2)+KIZ+KVCZ2+1)))) &
               /((TEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD) &
                -EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)-EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD))**2)
            ENDDO
           ENDDO
          ENDDO
         ENDDO
         ENDDO
         ENDDO
        ENDDO
        ENDDO
        ENDDO
       ELSE
! ---- NONDIAGONAL FREQUENCY-DEPENDENT 
        DO KJX=-KVCX2,MAX(0,KVCX2-1)
        DO KJY=-KVCY2,MAX(0,KVCY2-1)
        DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
         DO KAX=-KVCX2,MAX(0,KVCX2-1)
         DO KAY=-KVCY2,MAX(0,KVCY2-1)
         DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
          KGX=KAX-KJX+KBX
          KGY=KAY-KJY+KBY
          KGZ=KAZ-KJZ+KBZ
          IF (KGX >= KVCX2) KGX=KGX-2*KVCX2
          IF (KGY >= KVCY2) KGY=KGY-2*KVCY2
          IF (KGZ >= KVCZ2) KGZ=KGZ-2*KVCZ2
          IF (KGX < -KVCX2) KGX=KGX+2*KVCX2
          IF (KGY < -KVCY2) KGY=KGY+2*KVCY2
          IF (KGZ < -KVCZ2) KGZ=KGZ+2*KVCZ2
          DO MOJ=ICORE+1,IOCC
           DO MOA=IOCC+1,IALL(KAX,KAY,KAZ)-IVIRTCORE
            DO MOTARGET=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
            DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
            DO MOH=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
             FEPSILON_TMP(MOG,MOH,MOTARGET,KGX,KGY,KGZ)=FEPSILON_TMP(MOG,MOH,MOTARGET,KGX,KGY,KGZ) &
               +(2.0D0*TOVOKK(MOH,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOG,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
               - (TOVOKK(MOH,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOJ,MOA,MOG,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1)))) &
               *(TEPSILON(MOTARGET,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
                -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD)) &
               /((TEPSILON(MOTARGET,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
                -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))**2+DYSONETA)
             FPOLE_TMP(MOG,MOH,MOTARGET,KGX,KGY,KGZ)=FPOLE_TMP(MOG,MOH,MOTARGET,KGX,KGY,KGZ) &
               -(2.0D0*TOVOKK(MOH,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOG,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
               - (TOVOKK(MOH,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOJ,MOA,MOG,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                          ((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1)))) &
               /((TEPSILON(MOTARGET,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
                -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))**2)
            ENDDO
            ENDDO
            ENDDO
           ENDDO
          ENDDO
         ENDDO
         ENDDO
         ENDDO
        ENDDO
        ENDDO
        ENDDO
        DO KJX=-KVCX2,MAX(0,KVCX2-1)
        DO KJY=-KVCY2,MAX(0,KVCY2-1)
        DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
         DO KGX=-KVCX2,MAX(0,KVCX2-1)
         DO KGY=-KVCY2,MAX(0,KVCY2-1)
         DO KGZ=-KVCZ2,MAX(0,KVCZ2-1)
          KIX=KGX-KJX+KBX
          KIY=KGY-KJY+KBY
          KIZ=KGZ-KJZ+KBZ
          IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
          IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
          IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
          IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
          IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
          IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
          DO MOJ=ICORE+1,IOCC
           DO MOI=ICORE+1,IOCC
            DO MOTARGET=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
            DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
            DO MOH=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
             FEPSILON_TMP(MOG,MOH,MOTARGET,KGX,KGY,KGZ)=FEPSILON_TMP(MOG,MOH,MOTARGET,KGX,KGY,KGZ) &
               +(2.0D0*TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOI,MOH,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
               - (TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOJ,MOH,MOI,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KIX+KVCX2)*MAX(1,2*KVCY2)+(KIY+KVCY2))*MAX(1,2*KVCZ2)+KIZ+KVCZ2+1)))) &
               *(TEPSILON(MOTARGET,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD) &
                -EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)-EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD)) &
               /((TEPSILON(MOTARGET,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD) &
                -EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)-EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD))**2+DYSONETA)
             FPOLE_TMP(MOG,MOH,MOTARGET,KGX,KGY,KGZ)=FPOLE_TMP(MOG,MOH,MOTARGET,KGX,KGY,KGZ) &
               -(2.0D0*TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOI,MOH,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
               - (TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
               *DCONJG(TOVOKK(MOJ,MOH,MOI,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                          ((KIX+KVCX2)*MAX(1,2*KVCY2)+(KIY+KVCY2))*MAX(1,2*KVCZ2)+KIZ+KVCZ2+1)))) &
               /((TEPSILON(MOTARGET,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD) &
                -EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)-EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD))**2)
            ENDDO
            ENDDO
            ENDDO
           ENDDO
          ENDDO
         ENDDO
         ENDDO
         ENDDO
        ENDDO
        ENDDO
        ENDDO
       ENDIF
! --- PARALLEL LOOP
!      CALL PCPU_TIME(ICPUE)
!      IF (MYID == 0) WRITE(6,'(A,F6.2,A,F10.1,A)') ' ... ', &
!        DFLOAT((((KBX+KVCX2)*MAX(1,2*KVCY2)+(KBY+KVCY2))*MAX(1,2*KVCZ2)+(KBZ+KVCZ2))*(IALL(KBX,KBY,KBZ)-IVIRTCORE-IOCC) &
!        +(MOB-IOCC))/DFLOAT((IALL(KBX,KBY,KBZ)-IVIRTCORE-IOCC)*MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2))*100.0D0, &
!        ' % OF MP2 ENERGY EVALUATION (CPU / SEC = ',ICPUE-ICPUS,')'
!      CALL PCPU_TIME(ICPUS)
!      CALL PFLUSH(6)
      ENDIF
! --- PARALLEL LOOP
!write(*,*) emp2s_tmp,emp2t_tmp
     ENDDO
    ENDDO
    ENDDO
    ENDDO

    IF (ITR == 1) THEN
     CALL MPI_ALLREDUCE(EMP2S_TMP,EMP2S,1,MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERR)
     CALL MPI_ALLREDUCE(EMP2T_TMP,EMP2T,1,MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERR)
     EMP2S=EMP2S/DFLOAT(MAX(1,8*KVCX2**3))/DFLOAT(MAX(1,8*KVCY2**3))/DFLOAT(MAX(1,8*KVCZ2**3))
     EMP2T=EMP2T/DFLOAT(MAX(1,8*KVCX2**3))/DFLOAT(MAX(1,8*KVCY2**3))/DFLOAT(MAX(1,8*KVCZ2**3))
     EMP2=EMP2S+EMP2T
     CALL MPI_ALLREDUCE(QEPSILON_TMP,QEPSILON,NCGS*(KVCX*2+1)*(KVCY*2+1)*(KVCZ*2+1), &
      MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERR)
     DO KGX=-KVCX2,MAX(0,KVCX2-1)
     DO KGY=-KVCY2,MAX(0,KVCY2-1)
     DO KGZ=-KVCZ2,MAX(0,KVCZ2-1)
      DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
       QEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
        +QEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)/DFLOAT(MAX(1,4*KVCX2**2))/DFLOAT(MAX(1,4*KVCY2**2))/DFLOAT(MAX(1,4*KVCZ2**2))
      ENDDO
     ENDDO
     ENDDO
     ENDDO
    ENDIF

    IF (LOPTN(106)) THEN
     ! DIAGONAL
     MAXDEV=0.0D0
     CALL MPI_ALLREDUCE(DEPSILON_TMP,DEPSILON,NCGS*(KVCX*2+1)*(KVCY*2+1)*(KVCZ*2+1), &
      MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERR)
     DO KGX=-KVCX2,MAX(0,KVCX2-1)
     DO KGY=-KVCY2,MAX(0,KVCY2-1)
     DO KGZ=-KVCZ2,MAX(0,KVCZ2-1)
      DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
       DEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
        +DEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)/DFLOAT(MAX(1,4*KVCX2**2))/DFLOAT(MAX(1,4*KVCY2**2))/DFLOAT(MAX(1,4*KVCZ2**2))
       IF (DABS(DEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)-TEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)) > MAXDEV) &
        MAXDEV=DABS(DEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)-TEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD))
      ENDDO
     ENDDO
     ENDDO
     ENDDO
     CALL MPI_ALLREDUCE(DPOLE_TMP,DPOLE,NCGS*(KVCX*2+1)*(KVCY*2+1)*(KVCZ*2+1), &
      MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERR)
     DO KGX=-KVCX2,MAX(0,KVCX2-1)
     DO KGY=-KVCY2,MAX(0,KVCY2-1)
     DO KGZ=-KVCZ2,MAX(0,KVCZ2-1)
      DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
       DPOLE(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=1.0D0/ &
        (1.0D0-DPOLE(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)/DFLOAT(MAX(1,4*KVCX2**2))/DFLOAT(MAX(1,4*KVCY2**2))/DFLOAT(MAX(1,4*KVCZ2**2)))
      ENDDO
     ENDDO
     ENDDO
     ENDDO
    ELSE
     ! NONDIAGONAL
     MAXDEV=0.0D0
     CALL MPI_ALLREDUCE(MPI_IN_PLACE,FEPSILON_TMP,NCGS**3*(KVCX2*2+1)*(KVCY2*2+1)*(KVCZ2*2+1), &
      MPI_DOUBLE_COMPLEX,MPI_SUM,MPI_COMM_WORLD,IERR)
     CALL MPI_ALLREDUCE(MPI_IN_PLACE,FPOLE_TMP,NCGS**3*(KVCX2*2+1)*(KVCY2*2+1)*(KVCZ2*2+1), &
      MPI_DOUBLE_COMPLEX,MPI_SUM,MPI_COMM_WORLD,IERR)
     DO KGX=-KVCX2,MAX(0,KVCX2-1)
     DO KGY=-KVCY2,MAX(0,KVCY2-1)
     DO KGZ=-KVCZ2,MAX(0,KVCZ2-1)
      DO MOTARGET=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
       DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
        DO MOH=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
         FEPSILON_TMP(MOG,MOH,MOTARGET,KGX,KGY,KGZ)=FEPSILON_TMP(MOG,MOH,MOTARGET,KGX,KGY,KGZ) &
          /DFLOAT(MAX(1,4*KVCX2**2))/DFLOAT(MAX(1,4*KVCY2**2))/DFLOAT(MAX(1,4*KVCZ2**2))
        ENDDO
        FEPSILON_TMP(MOG,MOG,MOTARGET,KGX,KGY,KGZ)= &
         FEPSILON_TMP(MOG,MOG,MOTARGET,KGX,KGY,KGZ)+EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)
       ENDDO
!if (kgx==0) then
!call dump7(FEPSILON_TMP(:,:,MOTARGET,KGX,KGY,KGZ),NCGS)
!endif
       CALL HHBS(NCGS,NCGS,FEPSILON_TMP(:,:,MOTARGET,KGX,KGY,KGZ),E,WC)
       DO I=1,NCGS
        MAXOVERLAP=0.0D0
        DO J=1,NCGS
         OVERLAP=DREAL(DCONJG(WC(J,I))*WC(J,I))
         IF (OVERLAP > MAXOVERLAP) THEN
          MAXOVERLAP=OVERLAP
          MAXJ=J
         ENDIF
        ENDDO
        IF (MAXJ == MOTARGET) MOTARGET2=I
       ENDDO
!if (kgx==0) then
!write(*,*) 'target = ',motarget
!write(*,*) 'target2= ',motarget2
!write(*,*) dreal(FEPSILON_TMP(MOTARGET,MOTARGET,MOTARGET,KGX,KGY,KGZ)),e(motarget2)
!endif
       DEPSILON(MOTARGET,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=E(MOTARGET2)
       IF (DABS(DEPSILON(MOTARGET,KGX*NMOD,KGY*NMOD,KGZ*NMOD)-TEPSILON(MOTARGET,KGX*NMOD,KGY*NMOD,KGZ*NMOD)) > MAXDEV) &
        MAXDEV=DABS(DEPSILON(MOTARGET,KGX*NMOD,KGY*NMOD,KGZ*NMOD)-TEPSILON(MOTARGET,KGX*NMOD,KGY*NMOD,KGZ*NMOD))
       POLE=0.0D0
       DO MOG=1,NCGS
        DO MOH=1,NCGS
         POLE=POLE+DREAL(DCONJG(WC(MOG,MOTARGET2))*FPOLE_TMP(MOG,MOH,MOTARGET,KGX,KGY,KGZ)*WC(MOH,MOTARGET2)) &
          /DFLOAT(MAX(1,4*KVCX2**2))/DFLOAT(MAX(1,4*KVCY2**2))/DFLOAT(MAX(1,4*KVCZ2**2))
        ENDDO
       ENDDO
       DPOLE(MOTARGET,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=1.0D0/(1.0D0-POLE)
      ENDDO
     ENDDO
     ENDDO
     ENDDO
    ENDIF

    CALL PCPU_TIME(ICPUE)
    IF ((ITR == 1).AND.(MYID == 0)) THEN
     WRITE(6,'(A,F20.15,A)') 'E(2) SINGLET = ',EMP2S,' HARTREE'
     WRITE(6,'(A,F20.15,A)') 'E(2) TRIPLET = ',EMP2T,' HARTREE'
     WRITE(6,'(A,F20.15,A)') 'E(2)         = ',EMP2, ' HARTREE'
     WRITE(6,'(A,F20.15,A)') 'EMP2         = ',EHFKS+EMP2,' HARTREE'
     WRITE(6,'(A,F16.10)') 'CONVERGENCE CRITERION = ',DYSONCNV
     WRITE(6,'(A)') '------------------------------------------------'
     WRITE(6,'(A)') 'ITR DIAG  DAMPING       DEVIATION       CPU TIME'
    ENDIF
    IF (MYID == 0) WRITE(6,'(I3,L5,F9.5,F16.10,5X,F10.1)') ITR,LOPTN(106),DYSONETA,MAXDEV,ICPUE-ICPUS
    CALL PFLUSH(6)
    IF (MAXDEV < DYSONCNV) THEN
     EXIT
    ELSE
     DYSONETA=DYSONETA/2.0D0
     TEPSILON=DEPSILON
    ENDIF
    IF (ITR == MAXITR) CALL PABORT('DYSON ROOT SEARCH FAILED')
   ENDDO
   IF (MYID == 0) THEN
    WRITE(6,'(A)') '------------------------------------------------'
    WRITE(6,'(A)') 'DYSON QUASI-PARTICLE ENERGIES CONVERGED'
   ENDIF
 
   IF (.NOT.LOPTN(106)) DEALLOCATE(FPOLE_TMP,FEPSILON_TMP,WC,E)
   DEALLOCATE(DPOLE_TMP,DEPSILON_TMP,QEPSILON_TMP,TEPSILON)
   DEALLOCATE(ICASHE1X,ICASHE1Y,ICASHE1Z,ICASHE2,DCASHE)
   DEALLOCATE(PHASEX,PHASEY,PHASEZ)
   DEALLOCATE(TNNNKK,TOK,TVOKK,TOVOKK)
   IF (HELIX /= 0.0D0) DEALLOCATE(CO_HELIX)

   RETURN
END SUBROUTINE



!SUBROUTINE DYSON_DEBUG
!! TRANSFORM TWO-ELECTRON INTEGRALS BY O(N**5) ALGORITHM AND EVALUATE THE INVERSE DYSON QUASI-PARTICLE ENERGIES
!! USING THE DIAGONAL APPROXIMATION TO THE SELF-ENERGY TERM.
!! AO-BASED TWO-ELECTRON INTEGRALS ARE RETRIEVED FROM DISK.
!
!   USE MPI
!   USE CONSTANTS
!   USE CONTROL
!   USE STRUCTURE
!   USE BASISSET
!   USE INTEGRAL
!   USE GRADIENT
!   
!   IMPLICIT NONE
!   INCLUDE "mpif.h"
!   INTEGER :: IOMEGA,IOMEGAS,IOMEGAE
!   DOUBLE PRECISION :: OMEGA
!   DOUBLE PRECISION :: ICPUS,ICPUE
!   INTEGER,PARAMETER :: CASHESIZE = 1000 ! CASHE SIZE MUST BE EXACTLY THE SAME IN THE STORE & RESTORE SUBROUTINES
!   INTEGER,PARAMETER :: MAXITR = 100     ! MAXIMUM NUMBER OF THE DYSON ITERATIONS
!   DOUBLE PRECISION,PARAMETER :: DYSONCNV = 0.0001D0 ! CONVERGENCE CRITERION FOR THE DYSON ITERATIONS
!   DOUBLE PRECISION :: DYSONETA          ! DAMPING FACTOR TO AVOID ZERO DENOMINATOR
!   INTEGER :: ITR
!   INTEGER :: MOI,MOJ,MOA,MOB,MOG,MOH
!   INTEGER :: KIX,KIY,KIZ,KJX,KJY,KJZ,KAX,KAY,KAZ,KBX,KBY,KBZ,KGX,KGY,KGZ
!   INTEGER :: Q1X,Q1Y,Q1Z,Q2X,Q2Y,Q2Z,Q3X,Q3Y,Q3Z
!   INTEGER :: I,J,K,L,PX,PY,PZ,QX,QY,QZ,RX,RY,RZ
!   INTEGER :: EOF
!   INTEGER :: ICASHECOUNT
!   DOUBLE PRECISION :: ICOUNT,ICOUNTTOTAL
!   INTEGER(4),ALLOCATABLE :: ICASHE1X(:),ICASHE1Y(:),ICASHE1Z(:),ICASHE2(:)
!   DOUBLE PRECISION,ALLOCATABLE :: DCASHE(:)
!   DOUBLE PRECISION,ALLOCATABLE :: DEPSILON_TMP(:,:,:,:)
!   DOUBLE PRECISION,ALLOCATABLE :: QEPSILON_TMP(:,:,:,:)
!   DOUBLE COMPLEX,ALLOCATABLE :: FEPSILON(:,:,:,:,:),WC(:,:)
!   DOUBLE PRECISION,ALLOCATABLE :: E(:)
!   DOUBLE PRECISION :: EMP2,EMP2S,EMP2T,EMP2S_TMP,EMP2T_TMP
!   DOUBLE PRECISION :: MAXDEV
!   DOUBLE COMPLEX,ALLOCATABLE :: PHASEX(:),PHASEY(:),PHASEZ(:)
!   DOUBLE COMPLEX,ALLOCATABLE :: TNNNKK(:,:,:,:,:,:,:,:,:),TOK(:,:,:,:)
!   DOUBLE COMPLEX,ALLOCATABLE :: TVOKK(:,:,:,:,:,:,:,:),TOVOKK(:,:,:,:,:,:,:,:,:)
!   DOUBLE PRECISION,ALLOCATABLE :: FSAVE(:,:),ESAVE(:,:)
!   DOUBLE PRECISION :: POLE1,POLE2
!   INTEGER :: KVCX2,KVCY2,KVCZ2
!   INTEGER :: NMOD
!   INTEGER :: TICKET
!   INTEGER :: NFILES,IFILE,JFILE
!   LOGICAL :: LEXIST
!   CHARACTER(6) :: FILEAPPENDIX
!
!   IOMEGAS=-380
!   IOMEGAE=-370
!
!   NMOD = IOPTN(99)
!   IF (NMOD < 1) CALL PABORT('ILLEGAL MODULO PARAMETER')
!   IF (NMOD > 1) THEN
!    IF (MYID == 0) WRITE(6,'(A)')      '**********************************************************'
!    IF (MYID == 0) WRITE(6,'(A,I3,A)') '* DYSON QUASI-PARTICLE ENERGY CORRECTIONS WITH MOD = ',NMOD,' *'
!    IF (MYID == 0) WRITE(6,'(A)')      '**********************************************************'
!    IF (KVCX/NMOD*NMOD /= KVCX) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG X')
!    IF (KVCY/NMOD*NMOD /= KVCY) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG Y')
!    IF (KVCZ/NMOD*NMOD /= KVCZ) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG Z')
!    KVCX2=KVCX/NMOD
!    KVCY2=KVCY/NMOD
!    KVCZ2=KVCZ/NMOD
!   ELSE
!    KVCX2=KVCX
!    KVCY2=KVCY
!    KVCZ2=KVCZ
!   ENDIF
!
!   ALLOCATE(FSAVE(NCGS,IOMEGAS:IOMEGAE),ESAVE(NCGS,IOMEGAS:IOMEGAE))
!
!   ALLOCATE(ICASHE1X(CASHESIZE),ICASHE1Y(CASHESIZE),ICASHE1Z(CASHESIZE),ICASHE2(CASHESIZE),DCASHE(CASHESIZE))
!   ALLOCATE(PHASEX(-(CEL1X+CEL2X)*KVCX2:(CEL1X+CEL2X)*KVCX2))
!   ALLOCATE(PHASEY(-(CEL1Y+CEL2Y)*KVCY2:(CEL1Y+CEL2Y)*KVCY2))
!   ALLOCATE(PHASEZ(-(CEL1Z+CEL2Z)*KVCZ2:(CEL1Z+CEL2Z)*KVCZ2))
!   ALLOCATE(DEPSILON_TMP(NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))
!   ALLOCATE(QEPSILON_TMP(NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))
!   ALLOCATE(FEPSILON(NCGS,NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ),WC(NCGS,NCGS),E(NCGS))
!
!   IF (MYID == 0) WRITE(6,'(A)') 'CALCULATE DYSON QUASI-PARTICLE ENERGIES'
!   IF (IOPTN(27) /= 0) CALL WARNING('FROZEN CORE APPROXIMATION WILL BE USED')
!   IF (IOPTN(55) /= 0) CALL WARNING('FROZEN VIRTUAL APPROXIMATION WILL BE USED')
!   IF (IALLMAX-IOCC-IVIRTCORE <= 0) THEN
!    CALL WARNING('THERE IS NO VIRTUAL ORBITAL --- MP2 CORRECTION IS NULL')
!    RETURN
!   ENDIF
!   IF (IOPTN(44) == 0) THEN
!    CALL PABORT('NO DYSON QUASI-PARTICLE ENERGY CALCULATION REQUESTED')
!   ELSE IF (IOPTN(44) <= NCGS) THEN
!    IF (MYID == 0) WRITE(6,'(A,I3,A,I3,A)') 'DYSON QUASI-PARTICLE ENERGY CALCULATIONS FOR',IOPTN(44), &
!     ' OCCUPIED AND',IOPTN(44),' VIRTUAL BANDS WILL BE PERFORMED'
!   ELSE
!    IF (MYID == 0) WRITE(6,'(A)') &
!     'DYSON QUASI-PARTICLE ENERGY CALCULATIONS FOR ALL OCCUPIED AND VIRTUAL BANDS WILL BE PERFORMED'
!   ENDIF
!   DYSONETA=DOPTN(45)
!
!   NFILES=0
!   IF (MYID == 0) THEN
!    DO WHILE (.TRUE.)
!     WRITE(FILEAPPENDIX,'(I6)') 100000+NFILES
!     INQUIRE(FILE=TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6),EXIST=LEXIST)
!     IF (LEXIST) THEN
!      WRITE(6,'(A)') TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6)//' IS FOUND'
!      NFILES=NFILES+1
!     ELSE
!      EXIT
!     ENDIF
!    ENDDO
!   ENDIF
!   CALL MPI_BCAST(NFILES,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
!   IF (NFILES == 0) CALL PABORT('NO ERI FILES WAS FOUND')
!
!   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT(NCGS**3*(2*CEL1X+1)*(2*CEL1Y+1)*(2*CEL1Z+1)*(2*CEL2X+1)*(2*CEL2Y+1)*(2*CEL2Z+1)) &
!    /1.0D3,' K WORDS (TNNNKK)'
!   CALL PFLUSH(6)
!   ALLOCATE(TNNNKK(NCGS,NCGS,NCGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z,-CEL2X:CEL2X,-CEL2Y:CEL2Y,-CEL2Z:CEL2Z))
!   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT((MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE)-ICORE-2)*(2*KVCX2+1)*(2*KVCY2+1)*(2*KVCZ2+1)) &
!    /1.0D3,' K WORDS (TOK)'
!   CALL PFLUSH(6)
!   ALLOCATE(TOK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),-KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2))
!   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT((IALLMAX-IVIRTCORE-MAX(IOCC+1-IOPTN(44),ICORE+1)-1) &
!    *(MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE)-ICORE-2)*(2*KVCX2+1)*(2*KVCY2+1)*(2*KVCZ2+1)*(2*KVCX2+1)*(2*KVCY2+1)*(2*KVCZ2+1)) &
!    /1.0D3,' K WORDS (TVOKK)'
!   CALL PFLUSH(6)
!   ALLOCATE(TVOKK(MAX(IOCC+1-IOPTN(44),ICORE+1):IALLMAX-IVIRTCORE,ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),&
!            -KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2,-KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2))
!   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT(IALLMAX-IVIRTCORE-MAX(IOCC+1-IOPTN(44),ICORE+1)-1) &
!                                      *DFLOAT(MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE)-ICORE-2)**2 &
!                                      *DFLOAT((2*KVCX2+1)*(2*KVCY2+1)*(2*KVCZ2+1)*(2*KVCX2+1)*(2*KVCY2+1)*(2*KVCZ2+1))/1.0D3,&
!    ' K WORDS (TOVOKK)'
!   CALL PFLUSH(6)
!   ALLOCATE(TOVOKK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),MAX(IOCC+1-IOPTN(44),ICORE+1):IALLMAX-IVIRTCORE, &
!                   ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE), &
!                   -KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2,-KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2))
!
!   DO I=-(CEL1X+CEL2X)*KVCX2,(CEL1X+CEL2X)*KVCX2
!    IF (KVCX2 == 0) THEN
!     PHASEX(I)=DCMPLX(1.0D0,0.0D0)
!    ELSE
!     PHASEX(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCX2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCX2)*PI))
!    ENDIF
!   ENDDO
!   DO I=-(CEL1Y+CEL2Y)*KVCY2,(CEL1Y+CEL2Y)*KVCY2
!    IF (KVCY2 == 0) THEN
!     PHASEY(I)=DCMPLX(1.0D0,0.0D0)
!    ELSE
!     PHASEY(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCY2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCY2)*PI))
!    ENDIF
!   ENDDO
!   DO I=-(CEL1Z+CEL2Z)*KVCZ2,(CEL1Z+CEL2Z)*KVCZ2
!    IF (KVCZ2 == 0) THEN
!     PHASEZ(I)=DCMPLX(1.0D0,0.0D0)
!    ELSE
!     PHASEZ(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCZ2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCZ2)*PI))
!    ENDIF
!   ENDDO
!
!   EMP2S=0.0D0
!   EMP2T=0.0D0
!   EMP2S_TMP=0.0D0
!   EMP2T_TMP=0.0D0
!   QEPSILON=0.0D0
!   QEPSILON_TMP=0.0D0
!
!   ! COMPUTE E(2) AND QUASI-PARTICLE ENERGY BANDS
!   DYSONETA=DOPTN(45)
!   CALL PCPU_TIME(ICPUS)
!   TICKET=0
!   DO IOMEGA=IOMEGAS,IOMEGAE
!    OMEGA=DFLOAT(IOMEGA)/1000.0D0
!    FEPSILON=DCMPLX(0.0D0,0.0D0)
!    DO KGX=-KVCX2,KVCX2
!    DO KGY=-KVCY2,KVCY2
!    DO KGZ=-KVCZ2,KVCZ2
!     DO MOG=1,NCGS
!      FEPSILON(MOG,MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=DCMPLX(EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD),0.0D0)
!     ENDDO
!    ENDDO
!    ENDDO
!    ENDDO
!! --- PARALLEL LOOP
!    TICKET=TICKET+1
!    IF (TICKET == NUMPROCS) TICKET=TICKET-NUMPROCS
!    IF (MYID == TICKET) THEN
!! --- PARALLEL LOOP
!     DO KBX=-KVCX2,MAX(0,KVCX2-1)
!     DO KBY=-KVCY2,MAX(0,KVCY2-1)
!     DO KBZ=-KVCZ2,MAX(0,KVCZ2-1)
!      DO MOB=IOCC+1,IALL(KBX,KBY,KBZ)-IVIRTCORE
!       TNNNKK=DCMPLX(0.0D0,0.0D0)
!       DO IFILE=1,NFILES
!        JFILE=IFILE+MYID-1
!        JFILE=JFILE-JFILE/NFILES*NFILES
!        WRITE(FILEAPPENDIX,'(I6)') 100000+JFILE
!!write(*,*) 'Process:',myid,' reading from ',TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6)
!        OPEN(31,FILE=TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6),FORM='UNFORMATTED')
!        REWIND(31)
!        ICOUNT=0
!        DO
!         READ(31,IOSTAT=EOF) ICASHE1X,ICASHE1Y,ICASHE1Z,ICASHE2,DCASHE
!         IF (EOF /= 0) EXIT
!         DO ICASHECOUNT=1,CASHESIZE
!          IF (ICASHE1X(ICASHECOUNT) == -1) EXIT
!          ICOUNT=ICOUNT+1.0D0
!          PX=0
!          QX=0
!          RX=0
!          PY=0
!          QY=0
!          RY=0
!          PZ=0
!          QZ=0
!          RZ=0
!          I=0
!          J=0
!          K=0
!          L=0
!          CALL MVBITS(ICASHE1X(ICASHECOUNT),16,8,PX,0)
!          CALL MVBITS(ICASHE1X(ICASHECOUNT), 8,8,QX,0)
!          CALL MVBITS(ICASHE1X(ICASHECOUNT), 0,8,RX,0)
!          CALL MVBITS(ICASHE1Y(ICASHECOUNT),16,8,PY,0)
!          CALL MVBITS(ICASHE1Y(ICASHECOUNT), 8,8,QY,0)
!          CALL MVBITS(ICASHE1Y(ICASHECOUNT), 0,8,RY,0)
!          CALL MVBITS(ICASHE1Z(ICASHECOUNT),16,8,PZ,0)
!          CALL MVBITS(ICASHE1Z(ICASHECOUNT), 8,8,QZ,0)
!          CALL MVBITS(ICASHE1Z(ICASHECOUNT), 0,8,RZ,0)
!          CALL MVBITS(ICASHE2(ICASHECOUNT),24,8,I,0)
!          CALL MVBITS(ICASHE2(ICASHECOUNT),16,8,J,0)
!          CALL MVBITS(ICASHE2(ICASHECOUNT), 8,8,K,0)
!          CALL MVBITS(ICASHE2(ICASHECOUNT), 0,8,L,0)
!          Q1X=PX-CEL1X
!          Q2X=QX-CEL1X
!          Q3X=RX-CEL2X
!          Q1Y=PY-CEL1Y
!          Q2Y=QY-CEL1Y
!          Q3Y=RY-CEL2Y
!          Q1Z=PZ-CEL1Z
!          Q2Z=QZ-CEL1Z
!          Q3Z=RZ-CEL2Z
!          IF ((Q1X < -REDUCED_CEL1X).OR.(Q1X > REDUCED_CEL1X).OR.(Q2X < -REDUCED_CEL1X).OR.(Q2X > REDUCED_CEL1X).OR. &
!              (Q1Y < -REDUCED_CEL1Y).OR.(Q1Y > REDUCED_CEL1Y).OR.(Q2Y < -REDUCED_CEL1Y).OR.(Q2Y > REDUCED_CEL1Y).OR. &
!              (Q1Z < -REDUCED_CEL1Z).OR.(Q1Z > REDUCED_CEL1Z).OR.(Q2Z < -REDUCED_CEL1Z).OR.(Q2Z > REDUCED_CEL1Z).OR. &
!              (Q3X < -CEL2X).OR.(Q3X > CEL2X).OR.(Q3Y < -CEL2Y).OR.(Q3Y > CEL2Y).OR.(Q3Z < -CEL2Z).OR.(Q3Z > CEL2Z)) &
!          CALL PABORT('INTEGRAL FILE HAS BEEN DEGRADED')
!          TNNNKK(I,J,K,Q1X,Q1Y,Q1Z,Q3X,Q3Y,Q3Z)=TNNNKK(I,J,K,Q1X,Q1Y,Q1Z,Q3X,Q3Y,Q3Z)+CO(L,MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD) &
!                       *PHASEX(KBX*(Q2X+Q3X))*PHASEY(KBY*(Q2Y+Q3Y))*PHASEZ(KBZ*(Q2Z+Q3Z))*DCMPLX(DCASHE(ICASHECOUNT),0.0D0)
!         ENDDO
!        ENDDO
!        CLOSE(31)
!       ENDDO
!       IF ((IOPTN(9) >= 2).AND.(MYID == 0)) WRITE(6,'(F20.0,A,F7.3,A)') ICOUNT, &
!       ' ERIS (',ICOUNT/DFLOAT((CEL1X*2+1)**2*(CEL2X+1)*(CEL1Y*2+1)**2*(CEL2Y+1)*(CEL1Z*2+1)**2*(CEL2Z+1)*NCGS**4)*100.0, &
!       '% OF TOTAL ERIS) HAVE BEEN RESTORED'
!       TOVOKK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),MAX(IOCC+1-IOPTN(44),ICORE+1):IALLMAX-IVIRTCORE, &
!              ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE), &
!              -KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2,-KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2)=DCMPLX(0.0D0,0.0D0)
!       DO I=1,NCGS
!        TVOKK(MAX(IOCC+1-IOPTN(44),ICORE+1):IALLMAX-IVIRTCORE,ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE), &
!        -KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2,-KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2)=DCMPLX(0.0D0,0.0D0)
!        DO Q1X=-CEL1X,CEL1X
!        DO Q1Y=-CEL1Y,CEL1Y
!        DO Q1Z=-CEL1Z,CEL1Z
!         DO J=1,NCGS
!          TOK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),-KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2)=DCMPLX(0.0D0,0.0D0)
!          DO Q3X=-CEL2X,CEL2X
!          DO Q3Y=-CEL2Y,CEL2Y
!          DO Q3Z=-CEL2Z,CEL2Z
!           DO K=1,NCGS
!            DO KJX=-KVCX2,MAX(0,KVCX2-1)
!            DO KJY=-KVCY2,MAX(0,KVCY2-1)
!            DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
!             DO MOJ=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KJX,KJY,KJZ)-IVIRTCORE)
!              TOK(MOJ,KJX,KJY,KJZ)=TOK(MOJ,KJX,KJY,KJZ)+TNNNKK(I,J,K,Q1X,Q1Y,Q1Z,Q3X,Q3Y,Q3Z) &
!                *DCONJG(CO(K,MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD))*PHASEX(-KJX*Q3X)*PHASEY(-KJY*Q3Y)*PHASEZ(-KJZ*Q3Z)
!             ENDDO
!            ENDDO
!            ENDDO
!            ENDDO
!           ENDDO
!          ENDDO
!          ENDDO
!          ENDDO
!          DO KJX=-KVCX2,MAX(0,KVCX2-1)
!          DO KJY=-KVCY2,MAX(0,KVCY2-1)
!          DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
!           DO KAX=-KVCX2,MAX(0,KVCX2-1)
!           DO KAY=-KVCY2,MAX(0,KVCY2-1)
!           DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
!            DO MOJ=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KJX,KJY,KJZ)-IVIRTCORE)
!             DO MOA=MAX(IOCC+1-IOPTN(44),ICORE+1),IALL(KAX,KAY,KAZ)-IVIRTCORE
!              TVOKK(MOA,MOJ,KAX,KAY,KAZ,KJX,KJY,KJZ)=TVOKK(MOA,MOJ,KAX,KAY,KAZ,KJX,KJY,KJZ) &
!                +TOK(MOJ,KJX,KJY,KJZ)*CO(J,MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)*PHASEX(KAX*Q1X)*PHASEY(KAY*Q1Y)*PHASEZ(KAZ*Q1Z)
!             ENDDO
!            ENDDO
!           ENDDO
!           ENDDO
!           ENDDO
!          ENDDO
!          ENDDO
!          ENDDO
!         ENDDO
!        ENDDO
!        ENDDO
!        ENDDO
!        DO KJX=-KVCX2,MAX(0,KVCX2-1)
!        DO KJY=-KVCY2,MAX(0,KVCY2-1)
!        DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
!         DO KAX=-KVCX2,MAX(0,KVCX2-1)
!         DO KAY=-KVCY2,MAX(0,KVCY2-1)
!         DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
!          KIX=KAX-KJX+KBX
!          KIY=KAY-KJY+KBY
!          KIZ=KAZ-KJZ+KBZ
!          IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
!          IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
!          IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
!          IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
!          IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
!          IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
!          DO MOJ=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KJX,KJY,KJZ)-IVIRTCORE)
!           DO MOA=MAX(IOCC+1-IOPTN(44),ICORE+1),IALL(KAX,KAY,KAZ)-IVIRTCORE
!            DO MOI=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KIX,KIY,KIZ)-IVIRTCORE)
!             TOVOKK(MOI,MOA,MOJ,KAX,KAY,KAZ,KJX,KJY,KJZ)=TOVOKK(MOI,MOA,MOJ,KAX,KAY,KAZ,KJX,KJY,KJZ) &
!               +TVOKK(MOA,MOJ,KAX,KAY,KAZ,KJX,KJY,KJZ)*DCONJG(CO(I,MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD))
!            ENDDO
!           ENDDO
!          ENDDO
!         ENDDO
!         ENDDO
!         ENDDO
!        ENDDO
!        ENDDO
!        ENDDO
!       ENDDO
!! ---  NONDIAGONAL FREQUENCY-INDEPENDENT 
!       DO KJX=-KVCX2,MAX(0,KVCX2-1)
!       DO KJY=-KVCY2,MAX(0,KVCY2-1)
!       DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
!        DO KAX=-KVCX2,MAX(0,KVCX2-1)
!        DO KAY=-KVCY2,MAX(0,KVCY2-1)
!        DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
!         KGX=KAX-KJX+KBX
!         KGY=KAY-KJY+KBY
!         KGZ=KAZ-KJZ+KBZ
!         IF (KGX >= KVCX2) KGX=KGX-2*KVCX2
!         IF (KGY >= KVCY2) KGY=KGY-2*KVCY2
!         IF (KGZ >= KVCZ2) KGZ=KGZ-2*KVCZ2
!         IF (KGX < -KVCX2) KGX=KGX+2*KVCX2
!         IF (KGY < -KVCY2) KGY=KGY+2*KVCY2
!         IF (KGZ < -KVCZ2) KGZ=KGZ+2*KVCZ2
!         DO MOJ=ICORE+1,IOCC
!          DO MOA=IOCC+1,IALL(KAX,KAY,KAZ)-IVIRTCORE
!           DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
!            DO MOH=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
!             FEPSILON(MOG,MOH,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=FEPSILON(MOG,MOH,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
!               +(2.0D0*TOVOKK(MOH,MOA,MOJ,KAX,KAY,KAZ,KJX,KJY,KJZ)*DCONJG(TOVOKK(MOG,MOA,MOJ,KAX,KAY,KAZ,KJX,KJY,KJZ)) &
!               - (TOVOKK(MOH,MOA,MOJ,KAX,KAY,KAZ,KJX,KJY,KJZ)*DCONJG(TOVOKK(MOJ,MOA,MOG,KAX,KAY,KAZ,KGX,KGY,KGZ)))) &
!               /(OMEGA+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
!                -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD)) &
!               /DFLOAT(MAX(1,4*KVCX2**2))/DFLOAT(MAX(1,4*KVCY2**2))/DFLOAT(MAX(1,4*KVCZ2**2))
!            ENDDO
!           ENDDO
!          ENDDO
!         ENDDO
!        ENDDO
!        ENDDO
!        ENDDO
!       ENDDO
!       ENDDO
!       ENDDO
!       DO KJX=-KVCX2,MAX(0,KVCX2-1)
!       DO KJY=-KVCY2,MAX(0,KVCY2-1)
!       DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
!        DO KGX=-KVCX2,MAX(0,KVCX2-1)
!        DO KGY=-KVCY2,MAX(0,KVCY2-1)
!        DO KGZ=-KVCZ2,MAX(0,KVCZ2-1)
!         KIX=KGX-KJX+KBX
!         KIY=KGY-KJY+KBY
!         KIZ=KGZ-KJZ+KBZ
!         IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
!         IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
!         IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
!         IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
!         IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
!         IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
!         DO MOJ=ICORE+1,IOCC
!          DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
!           DO MOH=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
!            DO MOI=ICORE+1,IOCC
!             FEPSILON(MOG,MOH,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=FEPSILON(MOG,MOH,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
!              +(2.0D0*TOVOKK(MOI,MOG,MOJ,KGX,KGY,KGZ,KJX,KJY,KJZ)*DCONJG(TOVOKK(MOI,MOH,MOJ,KGX,KGY,KGZ,KJX,KJY,KJZ)) &
!              - (TOVOKK(MOI,MOG,MOJ,KGX,KGY,KGZ,KJX,KJY,KJZ)*DCONJG(TOVOKK(MOJ,MOH,MOI,KGX,KGY,KGZ,KIX,KIY,KIZ)))) &
!              /(OMEGA+EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD) &
!               -EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)-EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD)) &
!              /DFLOAT(MAX(1,4*KVCX2**2))/DFLOAT(MAX(1,4*KVCY2**2))/DFLOAT(MAX(1,4*KVCZ2**2))
!            ENDDO
!           ENDDO
!          ENDDO
!         ENDDO
!        ENDDO
!        ENDDO
!        ENDDO
!       ENDDO
!       ENDDO
!       ENDDO
!!write(*,*) emp2s_tmp,emp2t_tmp
!      ENDDO
!!write(*,*) kbx*nmod,kby*nmod,kbz*nmod
!     ENDDO
!     ENDDO
!     ENDDO
!!call dump7(fepsilon(:,:,4,0,0),ncgs)
!     DO KGX=1,1
!     DO KGY=0,0
!     DO KGZ=0,0
!      CALL HHBS(NCGS,NCGS,FEPSILON(:,:,KGX*NMOD,KGY*NMOD,KGZ*NMOD),E,WC)
!      DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
!!      WRITE(300+MOG,*) OMEGA,KGX,KGY,KGZ,DREAL(FEPSILON(MOG,MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)),E(MOG)
!       FSAVE(MOG,IOMEGA)=DREAL(FEPSILON(MOG,MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD))
!       ESAVE(MOG,IOMEGA)=E(MOG)
!!write(*,*) DREAL(FEPSILON(MOG,MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)),E(MOG)
!      ENDDO
!     ENDDO
!     ENDDO
!     ENDDO
!! --- PARALLEL LOOP
!     CALL PCPU_TIME(ICPUE)
!     IF (MYID == 0) WRITE(6,'(A,F6.2,A,F10.1,A)') ' ... ',DFLOAT(IOMEGA-IOMEGAS)/DFLOAT(IOMEGAE-IOMEGAS)*100.0D0,' % ',ICPUE-ICPUS
!     CALL PCPU_TIME(ICPUS)
!     CALL PFLUSH(6)
!    ENDIF
!! --- PARALLEL LOOP
!   ENDDO
!   DO IOMEGA=IOMEGAS,IOMEGAE
!    OMEGA=DFLOAT(IOMEGA)/1000.0D0
!    DO KGX=1,1
!    DO KGY=0,0
!    DO KGZ=0,0
!     DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
!      IF ((IOMEGA > IOMEGAS).AND.(IOMEGA < IOMEGAE)) THEN
!       POLE1=(FSAVE(MOG,IOMEGA+1)-FSAVE(MOG,IOMEGA-1))/0.002D0
!!      POLE1=1.0D0/(1.0D0-POLE1)
!       POLE2=(ESAVE(MOG,IOMEGA+1)-ESAVE(MOG,IOMEGA-1))/0.002D0
!!      POLE2=1.0D0/(1.0D0-POLE2)
!       WRITE(300+MOG,*) OMEGA,FSAVE(MOG,IOMEGA),POLE1,ESAVE(MOG,IOMEGA),POLE2
!      ENDIF
!     ENDDO
!    ENDDO
!    ENDDO
!    ENDDO
!   ENDDO
!
!   DEALLOCATE(FSAVE,ESAVE)
!   DEALLOCATE(DEPSILON_TMP,QEPSILON_TMP,FEPSILON,E,WC)
!   DEALLOCATE(ICASHE1X,ICASHE1Y,ICASHE1Z,ICASHE2,DCASHE)
!   DEALLOCATE(PHASEX,PHASEY,PHASEZ)
!   DEALLOCATE(TNNNKK,TOK,TVOKK,TOVOKK)
!
!   RETURN
!END SUBROUTINE
