SUBROUTINE GENERATE_EA_CONFIGURATIONS(ORDER)
! GENERATE CONFIGURATIONS FOR (N+1) ALPHA ELECTRONS

   USE CONTROL
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI
   
   IMPLICIT NONE
   INTEGER :: ORDER
   INTEGER :: I,J,K,L,M
   INTEGER :: I1,I2,I3,I4,I5,I6,I7,I8
   INTEGER(4) :: ICF
   INTEGER :: COMBINATION
   REAL :: MEM
   
   WRITE(6,'(A,I3,A,I3,A)') 'GENERATE AND ORDER CONFIGURATIONS FOR BETA ELECTRONS UP TO ',&
   ORDER-1,'-HOLE ',ORDER,'-PARTICLE EXCITATIONS'
   IF (ICORE > 0) WRITE(6,'(A,I3,A)') '***** WARNING : ',ICORE,' CORE BETA ORBITALS ARE ALWAYS OCCUPIED'
   IF (IVIRTCORE > 0) WRITE(6,'(A,I3,A)') '***** WARNING : ',IVIRTCORE,' HIGHEST VIRTUAL BETA ORBITALS ARE ALWAYS UNOCCUPIED'
   WRITE(6,'(A,I3,A,I3,A)') 'THERE ARE ',IOCC-ICORE+1,' ACTIVE BETA ELECTRONS IN ',IALL(0,0,0)-ICORE-IVIRTCORE,' ACTIVE ORBITALS'
   MEM=4.0*2**(IALL(0,0,0)-IVIRTCORE)
   IF (MEM > 1000000.0) WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE FOR THE BETA STRINGS WILL BE ',MEM/1000000.0,' MB'  
   IF (MEM > DOPTN(28)*1000000.0) CALL PABORT('OUT OF MEMORY')
   EA_NCF=0
   DO I=1,ORDER
    J=COMBINATION(IOCC-ICORE,I-1)*COMBINATION(IALL(0,0,0)-IOCC-IVIRTCORE,I)
    WRITE(6,'(I4,A,I3,A,I7)') I-1,'-HOLE ',I,'-PARTICLE EXCITATIONS ',J
    EA_NCF=EA_NCF+J
   ENDDO
   WRITE(6,'(A,I7)') '    TOTAL BETA CONFIGURATIONS ',EA_NCF
   IF (EA_NCF /= COMBINATION(IALL(0,0,0)-ICORE-IVIRTCORE,IOCC-ICORE+1)) CALL PABORT('AN ERROR OCCURRED IN COMBINATION FUNCTION')

   ALLOCATE(EA_CFHALF(EA_NCF),EA_NORDER(EA_NCF),EA_ADDRSS(2**(IALLMAX-IVIRTCORE)))
   EA_ADDRSS=0
   I=0
   IF (IOCC == 1) THEN
    DO I1=1,IALL(0,0,0)-IVIRTCORE-1
     DO I2=I1+1,IALL(0,0,0)-IVIRTCORE
      J=0
      IF (I1 <= ICORE) J=J+1
      IF (I2 <= ICORE) J=J+1
      IF (J /= ICORE) CYCLE
      J=IOCC+1
      IF (I1 <= IOCC) J=J-1
      IF (I2 <= IOCC) J=J-1
      IF (J > ORDER) CYCLE
      ICF=0
      ICF=IBSET(ICF,I1-1) 
      ICF=IBSET(ICF,I2-1) 
      I=I+1
      EA_CFHALF(I)=ICF
      EA_NORDER(I)=J
      EA_ADDRSS(ICF)=I
      IF (EA_NORDER(I) <= 3) THEN
       K=0
       DO L=0,IALL(0,0,0)-IVIRTCORE-1
        IF (BTEST(ICF,L)) K=K+10**L
        IF (BTEST(ICF,L)) M=L
       ENDDO
       IF (M < 10) WRITE(6,'(I6,A,I3,A,I6,A,I12)') I,' PARTICLES = ',J,' CF(NUM) = ',ICF,' CF(BIT) = ',K
      ENDIF
     ENDDO
    ENDDO
   ELSE IF (IOCC == 2) THEN
    DO I1=1,IALL(0,0,0)-IVIRTCORE-2
     DO I2=I1+1,IALL(0,0,0)-IVIRTCORE-1
      DO I3=I2+1,IALL(0,0,0)-IVIRTCORE
       J=0
       IF (I1 <= ICORE) J=J+1
       IF (I2 <= ICORE) J=J+1
       IF (I3 <= ICORE) J=J+1
       IF (J /= ICORE) CYCLE
       J=IOCC+1
       IF (I1 <= IOCC) J=J-1
       IF (I2 <= IOCC) J=J-1
       IF (I3 <= IOCC) J=J-1
       IF (J > ORDER) CYCLE
       ICF=0
       ICF=IBSET(ICF,I1-1) 
       ICF=IBSET(ICF,I2-1) 
       ICF=IBSET(ICF,I3-1) 
       I=I+1
       EA_CFHALF(I)=ICF
       EA_NORDER(I)=J
       EA_ADDRSS(ICF)=I
       IF (EA_NORDER(I) <= 3) THEN
        K=0
        DO L=0,IALL(0,0,0)-IVIRTCORE-1
         IF (BTEST(ICF,L)) K=K+10**L
         IF (BTEST(ICF,L)) M=L
        ENDDO
        IF (M < 10) WRITE(6,'(I6,A,I3,A,I6,A,I12)') I,' PARTICLES = ',J,' CF(NUM) = ',ICF,' CF(BIT) = ',K
       ENDIF
      ENDDO
     ENDDO
    ENDDO
   ELSE IF (IOCC == 3) THEN
    DO I1=1,IALL(0,0,0)-IVIRTCORE-3
     DO I2=I1+1,IALL(0,0,0)-IVIRTCORE-2
      DO I3=I2+1,IALL(0,0,0)-IVIRTCORE-1
       DO I4=I3+1,IALL(0,0,0)-IVIRTCORE
        J=0
        IF (I1 <= ICORE) J=J+1
        IF (I2 <= ICORE) J=J+1
        IF (I3 <= ICORE) J=J+1
        IF (I4 <= ICORE) J=J+1
        IF (J /= ICORE) CYCLE
        J=IOCC+1
        IF (I1 <= IOCC) J=J-1
        IF (I2 <= IOCC) J=J-1
        IF (I3 <= IOCC) J=J-1
        IF (I4 <= IOCC) J=J-1
        IF (J > ORDER) CYCLE
        ICF=0
        ICF=IBSET(ICF,I1-1) 
        ICF=IBSET(ICF,I2-1) 
        ICF=IBSET(ICF,I3-1) 
        ICF=IBSET(ICF,I4-1) 
        I=I+1
        EA_CFHALF(I)=ICF
        EA_NORDER(I)=J
        EA_ADDRSS(ICF)=I
        IF (EA_NORDER(I) <= 3) THEN
         K=0
         DO L=0,IALL(0,0,0)-IVIRTCORE-1
          IF (BTEST(ICF,L)) K=K+10**L
          IF (BTEST(ICF,L)) M=L
         ENDDO
         IF (M < 10) WRITE(6,'(I6,A,I3,A,I6,A,I12)') I,' PARTICLES = ',J,' CF(NUM) = ',ICF,' CF(BIT) = ',K
        ENDIF
       ENDDO
      ENDDO
     ENDDO
    ENDDO
   ELSE IF (IOCC == 4) THEN
    DO I1=1,IALL(0,0,0)-IVIRTCORE-4
     DO I2=I1+1,IALL(0,0,0)-IVIRTCORE-3
      DO I3=I2+1,IALL(0,0,0)-IVIRTCORE-2
       DO I4=I3+1,IALL(0,0,0)-IVIRTCORE-1
        DO I5=I4+1,IALL(0,0,0)-IVIRTCORE
         J=0
         IF (I1 <= ICORE) J=J+1
         IF (I2 <= ICORE) J=J+1
         IF (I3 <= ICORE) J=J+1
         IF (I4 <= ICORE) J=J+1
         IF (I5 <= ICORE) J=J+1
         IF (J /= ICORE) CYCLE
         J=IOCC+1
         IF (I1 <= IOCC) J=J-1
         IF (I2 <= IOCC) J=J-1
         IF (I3 <= IOCC) J=J-1
         IF (I4 <= IOCC) J=J-1
         IF (I5 <= IOCC) J=J-1
         IF (J > ORDER) CYCLE
         ICF=0
         ICF=IBSET(ICF,I1-1) 
         ICF=IBSET(ICF,I2-1) 
         ICF=IBSET(ICF,I3-1) 
         ICF=IBSET(ICF,I4-1) 
         ICF=IBSET(ICF,I5-1) 
         I=I+1
         EA_CFHALF(I)=ICF
         EA_NORDER(I)=J
         EA_ADDRSS(ICF)=I
         IF (EA_NORDER(I) <= 3) THEN
          K=0
          DO L=0,IALL(0,0,0)-IVIRTCORE-1
           IF (BTEST(ICF,L)) K=K+10**L
           IF (BTEST(ICF,L)) M=L
          ENDDO
          IF (M < 10) WRITE(6,'(I6,A,I3,A,I6,A,I12)') I,' PARTICLES = ',J,' CF(NUM) = ',ICF,' CF(BIT) = ',K
         ENDIF
        ENDDO
       ENDDO
      ENDDO
     ENDDO
    ENDDO
   ELSE IF (IOCC == 5) THEN
    DO I1=1,IALL(0,0,0)-IVIRTCORE-5
     DO I2=I1+1,IALL(0,0,0)-IVIRTCORE-4
      DO I3=I2+1,IALL(0,0,0)-IVIRTCORE-3
       DO I4=I3+1,IALL(0,0,0)-IVIRTCORE-2
        DO I5=I4+1,IALL(0,0,0)-IVIRTCORE-1
         DO I6=I5+1,IALL(0,0,0)-IVIRTCORE
          J=0
          IF (I1 <= ICORE) J=J+1
          IF (I2 <= ICORE) J=J+1
          IF (I3 <= ICORE) J=J+1
          IF (I4 <= ICORE) J=J+1
          IF (I5 <= ICORE) J=J+1
          IF (I6 <= ICORE) J=J+1
          IF (J /= ICORE) CYCLE
          J=IOCC+1
          IF (I1 <= IOCC) J=J-1
          IF (I2 <= IOCC) J=J-1
          IF (I3 <= IOCC) J=J-1
          IF (I4 <= IOCC) J=J-1
          IF (I5 <= IOCC) J=J-1
          IF (I6 <= IOCC) J=J-1
          IF (J > ORDER) CYCLE
          ICF=0
          ICF=IBSET(ICF,I1-1) 
          ICF=IBSET(ICF,I2-1) 
          ICF=IBSET(ICF,I3-1) 
          ICF=IBSET(ICF,I4-1) 
          ICF=IBSET(ICF,I5-1) 
          ICF=IBSET(ICF,I6-1) 
          I=I+1
          EA_CFHALF(I)=ICF
          EA_NORDER(I)=J
          EA_ADDRSS(ICF)=I
          IF (EA_NORDER(I) <= 3) THEN
           K=0
           DO L=0,IALL(0,0,0)-IVIRTCORE-1
            IF (BTEST(ICF,L)) K=K+10**L
            IF (BTEST(ICF,L)) M=L
           ENDDO
           IF (M < 10) WRITE(6,'(I6,A,I3,A,I6,A,I12)') I,' PARTICLES = ',J,' CF(NUM) = ',ICF,' CF(BIT) = ',K
          ENDIF
         ENDDO
        ENDDO
       ENDDO
      ENDDO
     ENDDO
    ENDDO
   ELSE IF (IOCC == 6) THEN
    DO I1=1,IALL(0,0,0)-IVIRTCORE-6
     DO I2=I1+1,IALL(0,0,0)-IVIRTCORE-5
      DO I3=I2+1,IALL(0,0,0)-IVIRTCORE-4
       DO I4=I3+1,IALL(0,0,0)-IVIRTCORE-3
        DO I5=I4+1,IALL(0,0,0)-IVIRTCORE-2
         DO I6=I5+1,IALL(0,0,0)-IVIRTCORE-1
          DO I7=I6+1,IALL(0,0,0)-IVIRTCORE
           J=0
           IF (I1 <= ICORE) J=J+1
           IF (I2 <= ICORE) J=J+1
           IF (I3 <= ICORE) J=J+1
           IF (I4 <= ICORE) J=J+1
           IF (I5 <= ICORE) J=J+1
           IF (I6 <= ICORE) J=J+1
           IF (I7 <= ICORE) J=J+1
           IF (J /= ICORE) CYCLE
           J=IOCC+1
           IF (I1 <= IOCC) J=J-1
           IF (I2 <= IOCC) J=J-1
           IF (I3 <= IOCC) J=J-1
           IF (I4 <= IOCC) J=J-1
           IF (I5 <= IOCC) J=J-1
           IF (I6 <= IOCC) J=J-1
           IF (I7 <= IOCC) J=J-1
           IF (J > ORDER) CYCLE
           ICF=0
           ICF=IBSET(ICF,I1-1) 
           ICF=IBSET(ICF,I2-1) 
           ICF=IBSET(ICF,I3-1) 
           ICF=IBSET(ICF,I4-1) 
           ICF=IBSET(ICF,I5-1) 
           ICF=IBSET(ICF,I6-1) 
           ICF=IBSET(ICF,I7-1) 
           I=I+1
           EA_CFHALF(I)=ICF
           EA_NORDER(I)=J
           EA_ADDRSS(ICF)=I
           IF (EA_NORDER(I) <= 3) THEN
            K=0
            DO L=0,IALL(0,0,0)-IVIRTCORE-1
             IF (BTEST(ICF,L)) K=K+10**L
             IF (BTEST(ICF,L)) M=L
            ENDDO
            IF (M < 10) WRITE(6,'(I6,A,I3,A,I6,A,I12)') I,' PARTICLES = ',J,' CF(NUM) = ',ICF,' CF(BIT) = ',K
           ENDIF
          ENDDO
         ENDDO
        ENDDO
       ENDDO
      ENDDO
     ENDDO
    ENDDO
   ELSE IF (IOCC == 7) THEN
    DO I1=1,IALL(0,0,0)-IVIRTCORE-7
     DO I2=I1+1,IALL(0,0,0)-IVIRTCORE-6
      DO I3=I2+1,IALL(0,0,0)-IVIRTCORE-5
       DO I4=I3+1,IALL(0,0,0)-IVIRTCORE-4
        DO I5=I4+1,IALL(0,0,0)-IVIRTCORE-3
         DO I6=I5+1,IALL(0,0,0)-IVIRTCORE-2
          DO I7=I6+1,IALL(0,0,0)-IVIRTCORE-1
           DO I8=I7+1,IALL(0,0,0)-IVIRTCORE
            J=0
            IF (I1 <= ICORE) J=J+1
            IF (I2 <= ICORE) J=J+1
            IF (I3 <= ICORE) J=J+1
            IF (I4 <= ICORE) J=J+1
            IF (I5 <= ICORE) J=J+1
            IF (I6 <= ICORE) J=J+1
            IF (I7 <= ICORE) J=J+1
            IF (I8 <= ICORE) J=J+1
            IF (J /= ICORE) CYCLE
            J=0
            IF (I1 > IOCC) J=J+1
            IF (I2 > IOCC) J=J+1
            IF (I3 > IOCC) J=J+1
            IF (I4 > IOCC) J=J+1
            IF (I5 > IOCC) J=J+1
            IF (I6 > IOCC) J=J+1
            IF (I7 > IOCC) J=J+1
            IF (I8 > IOCC) J=J+1
            IF (J > ORDER) CYCLE
            ICF=0
            ICF=IBSET(ICF,I1-1)
            ICF=IBSET(ICF,I2-1)
            ICF=IBSET(ICF,I3-1)
            ICF=IBSET(ICF,I4-1)
            ICF=IBSET(ICF,I5-1)
            ICF=IBSET(ICF,I6-1)
            ICF=IBSET(ICF,I7-1)
            ICF=IBSET(ICF,I8-1)
            I=I+1
            EA_CFHALF(I)=ICF
            EA_NORDER(I)=J
            EA_ADDRSS(ICF)=I
            IF (EA_NORDER(I) <= 3) THEN
             K=0
             DO L=0,IALL(0,0,0)-IVIRTCORE-1
              IF (BTEST(ICF,L)) K=K+10**L
              IF (BTEST(ICF,L)) M=L
             ENDDO
             IF (M < 10) WRITE(6,'(I6,A,I3,A,I6,A,I12)') I,' PARTICLES = ',J,' CF(NUM) = ',ICF,' CF(BIT) = ',K
            ENDIF
           ENDDO
          ENDDO
         ENDDO
        ENDDO
       ENDDO
      ENDDO
     ENDDO
    ENDDO
   ELSE
    CALL PABORT('NUMBER OF ELECTRONS IS TOO LARGE')
   ENDIF

   RETURN
END SUBROUTINE



SUBROUTINE EA_HAMILTONIAN_PRODUCT(INFILE,OUTFILE,OFFSET,ORDER)
! FORM THE PRODUCT OF HAMILTONIAN MATRIX AND A TRIAL VECTOR IN INFILE
! AND STORE THE PRODUCT VECTOR IN OUTFILE.  THE ORDER LIMITS THE NUMBER
! EXCITATION IN THE CONFIGURATIONS CONSIDERED.  A BETA ELECTRON IS
! ALWAYS ASSUMED TO BE ADDED.  NOTICE THAT TRL(BETA,ALPHA) AND LIKEWISE
! FOR PRD ARRAYS.

   USE CONTROL
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI
   
   IMPLICIT NONE
   INTEGER :: INFILE,OUTFILE,OFFSET
   INTEGER :: ORDER
   INTEGER :: ISIGN,JSIGN
   INTEGER :: I,J,K,L,M
   INTEGER :: IA,IB,IC,ID
   INTEGER :: NIA,NIB,NJA,NJB
   INTEGER(4) :: CFONE,CFTWO
   REAL :: MEM,ICPUS,ICPUE,EST
   DOUBLE PRECISION :: X,Y
   DOUBLE PRECISION,ALLOCATABLE :: TRL(:,:),PRD(:,:)
   INTEGER,ALLOCATABLE :: EA_PSIGN(:,:,:),EA_PADRS(:,:,:)

   CALL CPU_TIME(ICPUS)
   MEM=16.0*2.0*NCF*EA_NCF+4.0*2.0*NCF*(IALL(0,0,0)-IVIRTCORE)**2
!  IF (MEM > 1000000.0) THEN
!   WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000000.0,' MB'
!  ELSE IF (MEM > 1000.0) THEN
!   WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000.0,' KB'
!  ELSE
!   WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM,' B'
!  ENDIF
   IF (MEM > DOPTN(28)*1000000.0) CALL PABORT('OUT OF MEMORY') 

   ALLOCATE(TRL(EA_NCF,NCF),PRD(EA_NCF,NCF))
   ALLOCATE(EA_PSIGN(IALLMAX-IVIRTCORE,IALLMAX-IVIRTCORE,EA_NCF),EA_PADRS(IALLMAX-IVIRTCORE,IALLMAX-IVIRTCORE,EA_NCF))

   ! READ TRIAL VECTOR FROM FILE INFILE
   REWIND(INFILE)
   DO I=0,OFFSET
    READ(INFILE) TRL
   ENDDO

   ! ZERO SCRATCH TRIAL VECTOR ELEMENTS ASSOCIATED WITH EXCITATION HIGHER THAN THE ORDER
   DO IA=1,NCF
    DO IB=1,EA_NCF
     IF (NORDER(IA)+EA_NORDER(IB) > ORDER) TRL(IB,IA)=0.0D0
    ENDDO
   ENDDO

   ! ZERO SCRATCH PRODUCT VECTOR
   PRD=0.0D0

   ! DIAGONAL ELEMENTS
   DO IA=1,NCF
    DO IB=1,EA_NCF
     DO I=1,IALL(0,0,0)-IVIRTCORE
      IF (BTEST(CFHALF(IA),I-1))    PRD(IB,IA)=PRD(IB,IA)+H(I,I)*TRL(IB,IA)
      IF (BTEST(EA_CFHALF(IB),I-1)) PRD(IB,IA)=PRD(IB,IA)+H(I,I)*TRL(IB,IA)
     ENDDO
     DO I=1,IALL(0,0,0)-IVIRTCORE
      DO J=1,IALL(0,0,0)-IVIRTCORE
       IF (BTEST(CFHALF(IA),I-1)) THEN
        NIA=1
       ELSE
        NIA=0
       ENDIF
       IF (BTEST(CFHALF(IA),J-1)) THEN
        NJA=1
       ELSE
        NJA=0
       ENDIF
       IF (BTEST(EA_CFHALF(IB),I-1)) THEN
        NIB=1
       ELSE
        NIB=0
       ENDIF
       IF (BTEST(EA_CFHALF(IB),J-1)) THEN
        NJB=1
       ELSE
        NJB=0
       ENDIF
       PRD(IB,IA)=PRD(IB,IA)+0.5D0*(DFLOAT((NJA+NJB)*(NIA+NIB))*G(J,J,I,I) &
                 -DFLOAT(NJA*NIA+NJB*NIB)*G(J,I,I,J))*TRL(IB,IA)
      ENDDO
     ENDDO
    ENDDO
   ENDDO

   ! ONE SPIN ORBITAL DIFFERENCE
   DO IA=1,NCF
    DO I=ICORE+1,IALL(0,0,0)-IVIRTCORE
     IF (BTEST(CFHALF(IA),I-1)) THEN
      DO K=1,IALL(0,0,0)-IVIRTCORE
       IF (.NOT.(BTEST(CFHALF(IA),K-1))) THEN
        CFONE=IBCLR(CFHALF(IA),I-1)
        CFONE=IBSET(CFONE,K-1)
        IC=ADDRSS(CFONE)
        X=H(K,I)
        DO J=1,IALL(0,0,0)-IVIRTCORE
         IF ((J /= I).AND.(J /= K).AND.(BTEST(CFONE,J-1))) X=X+G(K,I,J,J)-G(K,J,J,I)
        ENDDO
        ISIGN=1
        DO J=1,I
         IF (BTEST(CFHALF(IA),J-1)) ISIGN=-ISIGN
        ENDDO
        DO J=1,K
         IF (BTEST(CFONE,J-1)) ISIGN=-ISIGN
        ENDDO
        DO IB=1,EA_NCF
         IF (DABS(TRL(IB,IA)) > 1.0D-15) THEN
          Y=0.0D0
          DO J=1,IALL(0,0,0)-IVIRTCORE
           IF (BTEST(EA_CFHALF(IB),J-1)) Y=Y+G(K,I,J,J)
          ENDDO
          PRD(IB,IC)=PRD(IB,IC)+(X+Y)*DFLOAT(ISIGN)*TRL(IB,IA)
         ENDIF
        ENDDO
       ENDIF
      ENDDO
     ENDIF
    ENDDO
   ENDDO
   DO IB=1,EA_NCF
    DO I=ICORE+1,IALL(0,0,0)-IVIRTCORE
     IF (BTEST(EA_CFHALF(IB),I-1)) THEN
      DO K=1,IALL(0,0,0)-IVIRTCORE
       IF (.NOT.(BTEST(EA_CFHALF(IB),K-1))) THEN
        CFONE=IBCLR(EA_CFHALF(IB),I-1)
        CFONE=IBSET(CFONE,K-1)
        IC=EA_ADDRSS(CFONE)
        X=H(K,I)
        DO J=1,IALL(0,0,0)-IVIRTCORE
         IF ((J /= I).AND.(J /= K).AND.(BTEST(CFONE,J-1))) X=X+G(K,I,J,J)-G(K,J,J,I)
        ENDDO
        ISIGN=1
        DO J=1,I
         IF (BTEST(EA_CFHALF(IB),J-1)) ISIGN=-ISIGN
        ENDDO
        DO J=1,K
         IF (BTEST(CFONE,J-1)) ISIGN=-ISIGN
        ENDDO
        DO IA=1,NCF
         IF (DABS(TRL(IB,IA)) > 1.0D-15) THEN
          Y=0.0D0
          DO J=1,IALL(0,0,0)-IVIRTCORE
           IF (BTEST(CFHALF(IA),J-1)) Y=Y+G(K,I,J,J)
          ENDDO
          PRD(IC,IA)=PRD(IC,IA)+(X+Y)*DFLOAT(ISIGN)*TRL(IB,IA)
         ENDIF
        ENDDO
       ENDIF
      ENDDO
     ENDIF
    ENDDO
   ENDDO

   ! TWO SPIN ORBITAL DIFFERENCES, CASE 1
   DO IA=1,NCF
    DO I=ICORE+1,IALL(0,0,0)-IVIRTCORE-1
     IF (BTEST(CFHALF(IA),I-1)) THEN
      DO J=I+1,IALL(0,0,0)-IVIRTCORE
       IF (BTEST(CFHALF(IA),J-1)) THEN
        DO K=1,IALL(0,0,0)-IVIRTCORE-1
         IF (.NOT.(BTEST(CFHALF(IA),K-1))) THEN
          DO L=K+1,IALL(0,0,0)-IVIRTCORE
           IF (.NOT.(BTEST(CFHALF(IA),L-1))) THEN
            CFTWO=IBCLR(CFHALF(IA),I-1)
            CFTWO=IBCLR(CFTWO,J-1)
            CFTWO=IBSET(CFTWO,K-1)
            CFTWO=IBSET(CFTWO,L-1)
            IC=ADDRSS(CFTWO)
            ISIGN=1
            DO M=1,I
             IF (BTEST(CFHALF(IA),M-1)) ISIGN=-ISIGN
            ENDDO
            DO M=1,J
             IF (BTEST(CFHALF(IA),M-1)) ISIGN=-ISIGN
            ENDDO
            DO M=1,K
             IF (BTEST(CFTWO,M-1)) ISIGN=-ISIGN
            ENDDO
            DO M=1,L
             IF (BTEST(CFTWO,M-1)) ISIGN=-ISIGN
            ENDDO
            Y=DFLOAT(ISIGN)*(G(K,I,L,J)-G(K,J,L,I))
            DO IB=1,EA_NCF
             PRD(IB,IC)=PRD(IB,IC)+Y*TRL(IB,IA)
            ENDDO
           ENDIF
          ENDDO
         ENDIF
        ENDDO
       ENDIF
      ENDDO
     ENDIF
    ENDDO
   ENDDO
   DO IB=1,EA_NCF
    DO I=ICORE+1,IALL(0,0,0)-IVIRTCORE-1
     IF (BTEST(EA_CFHALF(IB),I-1)) THEN
      DO J=I+1,IALL(0,0,0)-IVIRTCORE
       IF (BTEST(EA_CFHALF(IB),J-1)) THEN
        DO K=1,IALL(0,0,0)-IVIRTCORE-1
         IF (.NOT.(BTEST(EA_CFHALF(IB),K-1))) THEN
          DO L=K+1,IALL(0,0,0)-IVIRTCORE
           IF (.NOT.(BTEST(EA_CFHALF(IB),L-1))) THEN
            CFTWO=IBCLR(EA_CFHALF(IB),I-1)
            CFTWO=IBCLR(CFTWO,J-1)
            CFTWO=IBSET(CFTWO,K-1)
            CFTWO=IBSET(CFTWO,L-1)
            IC=EA_ADDRSS(CFTWO)
            ISIGN=1
            DO M=1,I
             IF (BTEST(EA_CFHALF(IB),M-1)) ISIGN=-ISIGN
            ENDDO
            DO M=1,J
             IF (BTEST(EA_CFHALF(IB),M-1)) ISIGN=-ISIGN
            ENDDO
            DO M=1,K
             IF (BTEST(CFTWO,M-1)) ISIGN=-ISIGN
            ENDDO
            DO M=1,L
             IF (BTEST(CFTWO,M-1)) ISIGN=-ISIGN
            ENDDO
            Y=DFLOAT(ISIGN)*(G(K,I,L,J)-G(K,J,L,I))
            DO IA=1,NCF
             PRD(IC,IA)=PRD(IC,IA)+Y*TRL(IB,IA)
            ENDDO
           ENDIF
          ENDDO
         ENDIF
        ENDDO
       ENDIF
      ENDDO
     ENDIF
    ENDDO
   ENDDO
   CALL CPU_TIME(ICPUE)
   EST=ICPUE-ICPUS
   CALL CPU_TIME(ICPUS)

   ! TWO SPIN ORBITAL DIFFERENCES, CASE 2
   DO IB=1,EA_NCF
    DO K=ICORE+1,IALL(0,0,0)-IVIRTCORE
     DO L=1,IALL(0,0,0)-IVIRTCORE
      EA_PSIGN(L,K,IB)=0
      EA_PADRS(L,K,IB)=0
      IF ((BTEST(EA_CFHALF(IB),K-1)).AND.(.NOT.(BTEST(EA_CFHALF(IB),L-1)))) THEN
       CFONE=IBCLR(EA_CFHALF(IB),K-1)
       CFONE=IBSET(CFONE,L-1)
       EA_PADRS(L,K,IB)=EA_ADDRSS(CFONE)
       JSIGN=1
       DO M=1,K
        IF (BTEST(EA_CFHALF(IB),M-1)) JSIGN=-JSIGN
       ENDDO
       DO M=1,L
        IF (BTEST(CFONE,M-1)) JSIGN=-JSIGN
       ENDDO
       EA_PSIGN(L,K,IB)=JSIGN
      ENDIF
     ENDDO
    ENDDO
   ENDDO
   DO IA=1,NCF
    DO I=ICORE+1,IALL(0,0,0)-IVIRTCORE
     DO J=1,IALL(0,0,0)-IVIRTCORE
      IF ((BTEST(CFHALF(IA),I-1)).AND.(.NOT.(BTEST(CFHALF(IA),J-1)))) THEN
       CFONE=IBCLR(CFHALF(IA),I-1)
       CFONE=IBSET(CFONE,J-1)
       IC=ADDRSS(CFONE)
       ISIGN=1
       DO K=1,I
        IF (BTEST(CFHALF(IA),K-1)) ISIGN=-ISIGN
       ENDDO
       DO K=1,J
        IF (BTEST(CFONE,K-1)) ISIGN=-ISIGN
       ENDDO
       DO IB=1,EA_NCF
        IF (DABS(TRL(IB,IA)) > 1.0D-15) THEN
         DO K=ICORE+1,IALL(0,0,0)-IVIRTCORE
          DO L=1,IALL(0,0,0)-IVIRTCORE
           IF (EA_PADRS(L,K,IB) /= 0) PRD(EA_PADRS(L,K,IB),IC)=PRD(EA_PADRS(L,K,IB),IC) &
           +DFLOAT(ISIGN*EA_PSIGN(L,K,IB))*G(J,I,L,K)*TRL(IB,IA)
          ENDDO
         ENDDO
        ENDIF
       ENDDO
      ENDIF
     ENDDO
    ENDDO
    CALL CPU_TIME(ICPUE)
!   IF (IA == 1) THEN
!    EST=EST+(ICPUE-ICPUS)*NCF
!    EST=EST/3600.0
!    IF (EST > 0.1) WRITE(6,'(A,F20.1,A)') '***** WARNING : ESTIMATED PRODUCT FORMATION TIME = ',EST,' HOURS'
!   ENDIF
   ENDDO

   ! ZERO SCRATCH PRODUCT VECTOR ELEMENTS ASSOCIATED WITH EXCITATION HIGHER THAN THE ORDER
   DO IA=1,NCF
    DO IB=1,EA_NCF
     IF (NORDER(IA)+EA_NORDER(IB) > ORDER) PRD(IB,IA)=0.0D0
    ENDDO
   ENDDO

   ! STORE PRODUCT VECTOR
   REWIND(OUTFILE)
   IF (OFFSET == 0) THEN
    WRITE(OUTFILE) PRD
   ELSE
    DO I=1,OFFSET
     READ(OUTFILE) TRL
    ENDDO
    WRITE(OUTFILE) PRD
   ENDIF

   DEALLOCATE(TRL,PRD,EA_PSIGN,EA_PADRS)

   RETURN
END SUBROUTINE



SUBROUTINE FULL_EA_HAMILTONIAN(ORDER)
! FORM FULL HAMILTONIAN AND DIAGONALIZE IT BY THE STANDARD ALGORITHMS.
! CAUTION, DO NOT USE THIS FOR PRODUCTION RUN.

   USE CONTROL
   USE GRADIENT
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI

   IMPLICIT NONE
   LOGICAL :: LEVEC
   INTEGER :: ORDER
   INTEGER :: IA,IB,IC,ID
   INTEGER :: INFO
   INTEGER :: NDIM
   REAL :: MEM,DEV
   DOUBLE PRECISION,ALLOCATABLE :: HAM(:,:)
   DOUBLE PRECISION,ALLOCATABLE :: VL(:,:),VR(:,:),ER(:),EI(:),WK(:)
   DOUBLE PRECISION,ALLOCATABLE :: TRL(:,:)

   LEVEC=.FALSE.
   IF (IOPTN(97) > 0) LEVEC=.TRUE.
   WRITE(6,'(I2,A,I2,A)') ORDER-1,'-HOLE',ORDER,'-PARTICLE CONFIGURATION INTERACTION CALCULATION FOR ALL STATES'
   IF (LEVEC) THEN 
    MEM=16.0*(2.0*(NCF*EA_NCF)**2+8.0*NCF*EA_NCF)
   ELSE
    MEM=16.0*((NCF*EA_NCF)**2+9.0*NCF*EA_NCF)
   ENDIF
   IF (MEM > 1000000.0) THEN
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000000.0,' MB'
   ELSE IF (MEM > 1000.0) THEN
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000.0,' KB'
   ELSE
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM,' B'
   ENDIF
   IF (MEM > DOPTN(28)*1000000.0) CALL PABORT('OUT OF MEMORY') 
   ALLOCATE(HAM(NCF*EA_NCF,NCF*EA_NCF),VL(1,NCF*EA_NCF),ER(NCF*EA_NCF),EI(NCF*EA_NCF),WK(4*NCF*EA_NCF))
   IF (LEVEC) THEN 
    ALLOCATE(VR(NCF*EA_NCF,NCF*EA_NCF))
   ELSE
    ALLOCATE(VR(1,NCF*EA_NCF))
   ENDIF
   ALLOCATE(TRL(EA_NCF,NCF))

   OPEN(50,FILE=TRIM(COPTN(1))//'.fi0',FORM='UNFORMATTED')
   OPEN(60,FILE=TRIM(COPTN(1))//'.fo0',FORM='UNFORMATTED')

   ! FORM HAMILTONIAN AND KEEP IT IN MEMORY
   NDIM=0
   DO IA=1,NCF
    DO IB=1,EA_NCF
     TRL=0.0D0
     IF (NORDER(IA)+EA_NORDER(IB) <= ORDER) TRL(IB,IA)=1.0D0
     IF (NORDER(IA)+EA_NORDER(IB) <= ORDER) NDIM=NDIM+1
     REWIND(50)
     WRITE(50) TRL
     CALL EA_HAMILTONIAN_PRODUCT(50,60,0,ORDER)
     REWIND(60)
     READ(60) TRL
     DO IC=1,NCF
      DO ID=1,EA_NCF
       HAM((IA-1)*EA_NCF+IB,(IC-1)*EA_NCF+ID)=TRL(ID,IC)
      ENDDO
     ENDDO
    ENDDO
   ENDDO
   IF (NDIM==NCF*EA_NCF) WRITE(6,'(A)') 'FULL CI LIMIT IS REACHED'
!  CALL DUMP5(HAM,NCF*EA_NCF)

   DEALLOCATE(TRL)
   CLOSE(50)
   CLOSE(60)

   ! DIAGONALIZE HAMILTONIAN
   IF (LEVEC.OR.(IOPTN(97) > 0)) THEN
    CALL DGEEV('N','V',NCF*EA_NCF,HAM,NCF*EA_NCF,ER,EI,VL,1,VR,NCF*EA_NCF,WK,4*NCF*EA_NCF,INFO)
    IF (INFO /= 0) CALL PABORT('DGEEV FAILED TO DIAGONALIZE A MATRIX')
    DEV=0.0D0
    DO IA=1,NCF*EA_NCF
     DEV=DEV+EI(IA)**2
    ENDDO
    IF (DEV > 1.0E-5) THEN
     CALL WARNING('THE IMAGINARY PART OF THE EIGENVALUES IS NOT ZERO')
     WRITE(6,'(A,F20.10)') 'DEVIATION = ',DEV
    ENDIF
    CALL PIKSRT(NCF*EA_NCF,NCF*EA_NCF,ER,VR,EI)
!   DO IA=1,MIN(25,NCF*EA_NCF)
    DO IA=1,NCF*EA_NCF
!    WRITE(6,'(A,I3,A,F20.15,A)') 'STATE ',IA,' ENERGY = ', ER(IA)+NUCLEAR_REPULSION,' HARTREE'
!    DO IB=1,NCF*EA_NCF
!     WRITE(6,'(I10,F20.15)') IB,VR(IB,IA)
!    ENDDO
    ENDDO
    IF (IOPTN(97) > 0) THEN
     OPEN(97,FILE=TRIM(COPTN(1))//'.gf2',FORM='UNFORMATTED')
     REWIND(97)
     WRITE(97) ER
     WRITE(97) VR
     CLOSE(97)
     WRITE(6,'(A,A)') '(N+1)-ELECTRON ENERGIES AND WAVE FUNCTIONS FOR MBGF STORED IN ',TRIM(COPTN(1))//'.gf2'
    ENDIF
   ELSE
    CALL DGEEV('N','N',NCF*EA_NCF,HAM,NCF*EA_NCF,ER,EI,VL,1,VR,1,WK,4*NCF*EA_NCF,INFO)
    IF (INFO /= 0) CALL PABORT('DGEEV FAILED TO DIAGONALIZE A MATRIX')
    DEV=0.0D0
    DO IA=1,NCF*EA_NCF
     DEV=DEV+EI(IA)**2
    ENDDO
    IF (DEV > 1.0E-5) THEN
     CALL WARNING('THE IMAGINARY PART OF THE EIGENVALUES IS NOT ZERO')
     WRITE(6,'(A,F20.10)') 'DEVIATION = ',DEV
    ENDIF
    CALL PIKSRT_EVALONLY(NCF*EA_NCF,ER)
!   DO IA=1,MIN(25,NCF*EA_NCF)
    DO IA=1,NDIM
     WRITE(6,'(A,I3,A,F20.15,A)') 'STATE ',IA,' ENERGY = ', ER(IA)+NUCLEAR_REPULSION,' HARTREE'
    ENDDO
   ENDIF
   CALL PFLUSH(6)

   DEALLOCATE(HAM,VL,VR,ER,EI,WK)

   RETURN
END SUBROUTINE



SUBROUTINE CI_EA_GUESS(ORDER,NROOTS,NTRIALS)
! GENERATE INITIAL GUESS TRIAL VECTORS FOR CI CALCULATIONS.

   USE CONTROL
   USE GRADIENT
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI

   IMPLICIT NONE
   INTEGER :: ORDER
   INTEGER :: NROOTS
   INTEGER :: NTRIALS
   INTEGER :: IA,IB
   INTEGER :: I,J
   DOUBLE PRECISION,ALLOCATABLE :: VEC1(:,:)

   IF (NROOTS < 1) CALL PABORT('ILLEGAL NUMBER OF CI ROOTS')
   IF ((ORDER < 1).OR.(ORDER > MIN(IOCC-ICORE,IALL(0,0,0)-IOCC-IVIRTCORE)+MIN(IOCC-ICORE+1,IALL(0,0,0)-IOCC-IVIRTCORE))) &
   CALL PABORT('ILLEGAL NUMBER OF CI ORDER')

   WRITE(6,'(A)') 'INITIAL GUESS FOR THE CI/EOMCC VECTORS WILL BE GENERATED'

   OPEN(50,FILE=TRIM(COPTN(1))//'.fi0',FORM='UNFORMATTED')
   REWIND(50)

   ALLOCATE(VEC1(EA_NCF,NCF))
   ! GENERATE INITIAL GUESS
   IF (NROOTS <= IALL(0,0,0)-IOCC-IVIRTCORE) THEN
    REWIND(50)
    NTRIALS=0
    DO IB=1,EA_NCF
     IF (EA_NORDER(IB) == 1) THEN
      NTRIALS=NTRIALS+1
      VEC1=0.0D0
      VEC1(IB,1)=1.0D0
      WRITE(50) VEC1
     ENDIF
    ENDDO
   ELSE IF (ORDER > 1) THEN
    REWIND(50)
    NTRIALS=0
    DO IA=1,NCF
     IF (NORDER(IA) == 1) THEN
      NTRIALS=NTRIALS+1
      VEC1=0.0D0
      VEC1(1,IA)=1.0D0
      WRITE(50) VEC1
     ENDIF
    ENDDO
    DO IB=1,EA_NCF
     IF (EA_NORDER(IB) == 1) THEN
      NTRIALS=NTRIALS+1
      VEC1=0.0D0
      VEC1(IB,1)=1.0D0
      WRITE(50) VEC1
     ENDIF
    ENDDO
    IF (NTRIALS < NROOTS) THEN
     REWIND(50)
     NTRIALS=0
     DO IA=1,NCF
      DO IB=1,EA_NCF
       IF (NORDER(IA)+EA_NORDER(IB) <= 2) THEN
        NTRIALS=NTRIALS+1
        VEC1=0.0D0
        VEC1(IB,IA)=1.0D0
        WRITE(50) VEC1
       ENDIF
      ENDDO
     ENDDO
    ENDIF
   ELSE
    CALL PABORT('DECREASE THE NUMBER OF ROOTS')
   ENDIF
 
   IF (NROOTS > NTRIALS) CALL PABORT('DECREASE THE NUMBER OF ROOTS')

   DEALLOCATE(VEC1)
   CLOSE(50)

   RETURN
END SUBROUTINE



SUBROUTINE HIGHORDER_CI_EA(ORDER,NROOTS,NTRIALS)
! PERFORM HIGH-ORDER CONFIGURATION INTERACTION CALCULATIONS BY THE DAVIDSON'S ALGORITHM.

   USE CONSTANTS
   USE CONTROL
   USE GRADIENT
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI

   IMPLICIT NONE
   INTEGER,PARAMETER :: MAXFILE = 1000
   INTEGER,PARAMETER :: MAXCYCLE = 1000
   INTEGER :: ICYCLE
   INTEGER :: ORDER
   INTEGER :: NROOTS
   INTEGER :: NTRIALS
   INTEGER :: NTRIALS_NEXT
   INTEGER :: IA,IB
   INTEGER :: I,J,K,L,NOPEN
   INTEGER,ALLOCATABLE :: N(:)
   REAL :: MEM,ICPUS,ICPUE
   LOGICAL :: LDONE(MAXFILE)
   DOUBLE PRECISION :: DEVSQ,DEVMAX,D,F,S2
   DOUBLE PRECISION :: SMALLH(MAXFILE,MAXFILE),LAMBDA(MAXFILE),ECI(MAXFILE)
   DOUBLE PRECISION :: W1(MAXFILE,MAXFILE),W2(MAXFILE)
   DOUBLE PRECISION :: PERCENTS,PERCENTD
   DOUBLE PRECISION,ALLOCATABLE :: VEC1(:,:),VEC2(:,:)

   CALL CPU_TIME(ICPUS)
   WRITE(6,'(A)') 'HIGH-ORDER ELECTRON AFFINITY CONFIGURATION INTERACTION CALCULATIONS WILL BE PERFORMED'
   WRITE(6,'(A,I2,A,I2,A)') 'CI ORDER IS ',ORDER-1,'-HOLE ',ORDER,'-PARTICLE'
   WRITE(6,'(A,I4)') 'THE NUMBER OF CI ROOTS SOUGHT ',NROOTS
   WRITE(6,'(A,I4)') 'THE NUMBER OF INITIAL TRIAL VECTORS ',NTRIALS
   MEM=16.0*2.0*NCF*EA_NCF
   IF (MEM > 1000000.0) THEN
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000000.0,' MB'
   ELSE IF (MEM > 1000.0) THEN
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000.0,' KB'
   ELSE
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM,' B'
   ENDIF
   IF (MEM > DOPTN(28)*1000000.0) CALL PABORT('OUT OF MEMORY') 
   IF (NROOTS > 1) THEN
    WRITE(6,'(A)') '--------------------------------------------------------'
    WRITE(6,'(A)') '             DEVIATION          TOTAL ENERGY   CPU / SEC'
   ELSE
    WRITE(6,'(A)') '-------------------------------------------------'
    WRITE(6,'(A)') 'ITR    DEVIATION         TOTAL ENERGY   CPU / SEC'
   ENDIF
   ALLOCATE(VEC1(EA_NCF,NCF),VEC2(EA_NCF,NCF),N(IALLMAX-IVIRTCORE))
   OPEN(50,FILE=TRIM(COPTN(1))//'.fi0',FORM='UNFORMATTED')
   OPEN(51,FILE=TRIM(COPTN(1))//'.fi1',FORM='UNFORMATTED')

   ! INITIALIZE
   LDONE=.FALSE.
   IF (NTRIALS > MAXFILE) CALL PABORT('TOO MANY INITIAL TRIAL VECTORS')

   ! DAVIDSON ITERATION
   DO ICYCLE=1,MAXCYCLE

    ! CALCULATE H|0> AND STORE IT IN FILE 70
    DEALLOCATE(VEC1,VEC2)
    DO I=1,NTRIALS
     IF (.NOT.LDONE(I)) THEN
      CALL EA_HAMILTONIAN_PRODUCT(50,51,I-1,ORDER)
      LDONE(I)=.TRUE.
     ENDIF
    ENDDO
    ALLOCATE(VEC1(EA_NCF,NCF),VEC2(EA_NCF,NCF))

    ! CONSTRUCT SUBSPACE HAMILTONIAN MATRIX <N|N> FOR DEBUG
!   WRITE(6,'(A)') 'SUBSPACE REPRESENTATION OF METRIC'
!   DO I=1,NTRIALS
!    REWIND(50)
!    DO J=1,I
!     READ(50) VEC1
!    ENDDO
!    REWIND(50)
!    DO L=1,NTRIALS
!     READ(50) VEC2
!     SMALLH(I,L)=0.0D0
!     DO IA=1,NCF
!      DO IB=1,EA_NCF
!       SMALLH(I,L)=SMALLH(I,L)+VEC1(IB,IA)*VEC2(IB,IA)
!      ENDDO
!     ENDDO
!    ENDDO
!    WRITE(6,'(I3,100F10.5:)') I,(SMALLH(I,L),L=1,NTRIALS)
!   ENDDO

    ! CONSTRUCT SUBSPACE HAMILTONIAN MATRIX <N|H|N>
    REWIND(50)
!   WRITE(6,'(A)') 'SUBSPACE REPRESENTATION OF HAMILTONIAN'
    DO I=1,NTRIALS
     READ(50) VEC1
     REWIND(51)
     DO L=1,NTRIALS
      READ(51) VEC2
      SMALLH(I,L)=0.0D0
      DO IA=1,NCF
       DO IB=1,EA_NCF
        SMALLH(I,L)=SMALLH(I,L)+VEC1(IB,IA)*VEC2(IB,IA)
       ENDDO
      ENDDO
     ENDDO
!    WRITE(6,'(I3,100F10.5:)') I,(SMALLH(I,L),L=1,NTRIALS)
    ENDDO
      
    ! DIAGONALIZE SUBSPACE HAMILTONIAN
    IF (NTRIALS == 1) THEN
     LAMBDA(1)=SMALLH(1,1)
     W1(1,1)=1.0D0
    ELSE
     W1=SMALLH
     CALL TRED2(W1,NTRIALS,MAXFILE,LAMBDA,W2)
     CALL TQLI(LAMBDA,W2,NTRIALS,MAXFILE,W1)
     CALL PIKSRT(NTRIALS,MAXFILE,LAMBDA,W1,W2)
    ENDIF
      
    ! FORM RESIDUAL VECTORS
    CALL CPU_TIME(ICPUE)
    DEVMAX=0.0D0
    IF (NROOTS > 1) WRITE(6,'(A,I3)') ' ITER ',ICYCLE
    NTRIALS_NEXT=NTRIALS
    DO K=1,NROOTS
     VEC1=0.0D0
     REWIND(50)
     REWIND(51)
     DO L=1,NTRIALS
      READ(51) VEC2
      VEC1=VEC1+VEC2*W1(L,K)
      READ(50) VEC2
      VEC1=VEC1-LAMBDA(K)*VEC2*W1(L,K)
     ENDDO
     DEVSQ=0.0D0
     DO IA=1,NCF
      DO IB=1,EA_NCF
       DEVSQ=DEVSQ+VEC1(IB,IA)**2
      ENDDO
     ENDDO
     DEVSQ=DSQRT(DEVSQ)
     IF (DEVSQ > DEVMAX) DEVMAX=DEVSQ
     ECI(K)=LAMBDA(K)+NUCLEAR_REPULSION
     IF (NROOTS == 1) THEN
      WRITE(6,'(I2,F15.10,F20.10,F12.1)') ICYCLE,DEVSQ,ECI(K),ICPUE-ICPUS
     ELSE
      WRITE(6,'(A,I3,F15.10,F20.10,F12.1)') ' ROOT ',K,DEVSQ,ECI(K),(ICPUE-ICPUS)/DFLOAT(NROOTS)
     ENDIF
      
     IF (DEVSQ < DOPTN(67)) CYCLE

     ! FORM A NEW SUBSPACE VECTOR BY KNOWLES-HANDY SCHEME
     DO IA=1,NCF
      DO IB=1,EA_NCF
       NOPEN=0
       DO I=1,IALL(0,0,0)-IVIRTCORE
        N(I)=0
        IF (BTEST(CFHALF(IA),I-1)) N(I)=1
        IF (BTEST(EA_CFHALF(IB),I-1)) N(I)=N(I)+1
        NOPEN=NOPEN+N(I)*(2-N(I))
       ENDDO
       IF ((NOPEN == 0).OR.(NOPEN == 1)) THEN
        F=0.0D0
       ELSE
        F=(3.0D0-DFLOAT(NOPEN))/DFLOAT(NOPEN*(NOPEN-1))
       ENDIF
       D=0.0D0
       DO I=1,IALL(0,0,0)-IVIRTCORE
        D=D+DFLOAT(N(I))*H(I,I)-DFLOAT(N(I)*(2-N(I)))*G(I,I,I,I)/4.0D0
        DO J=1,IALL(0,0,0)-IVIRTCORE
         D=D+DFLOAT(N(I)*N(J))*(2.0D0*G(I,I,J,J)-G(I,J,J,I))/4.0D0
         IF (I /= J) D=D-F*DFLOAT(N(I)*(2-N(I))*N(J)*(2-N(J)))*G(I,J,J,I)/4.0D0
        ENDDO
       ENDDO
       IF ((LAMBDA(K)-D) /= 0.0D0) VEC1(IB,IA)=VEC1(IB,IA)/(LAMBDA(K)-D)
      ENDDO
     ENDDO
      
     ! ORTHONORMALIZE THE NEW SUBSPACE VECTOR
     REWIND(50)
     DO L=1,NTRIALS_NEXT
      READ(50) VEC2
      D=0.0D0
      DO IA=1,NCF
       DO IB=1,EA_NCF
        D=D+VEC1(IB,IA)*VEC2(IB,IA)
       ENDDO
      ENDDO
      VEC1=VEC1-D*VEC2
     ENDDO
     D=0.0D0
     DO IA=1,NCF
      DO IB=1,EA_NCF
       D=D+VEC1(IB,IA)**2
      ENDDO
     ENDDO
     D=DSQRT(D)
     IF (D > 1.0D-8) THEN
      VEC1=VEC1/D
      NTRIALS_NEXT=NTRIALS_NEXT+1
      IF (NTRIALS_NEXT > MAXFILE) CALL PABORT('TOO MANY TRIAL VECTORS')
      REWIND(50)
      DO L=1,NTRIALS_NEXT-1
       READ(50) VEC2
      ENDDO
      WRITE(50) VEC1
     ENDIF

    ENDDO

    CALL CPU_TIME(ICPUS)
    CALL PFLUSH(6)

    IF (DEVMAX < DOPTN(67)) THEN
     IF (NROOTS > 1) THEN
      WRITE(6,'(A)') '--------------------------------------------------------'
     ELSE
      WRITE(6,'(A)') '-------------------------------------------------'
     ENDIF
     REWIND(51)
     DO I=1,NROOTS
      WRITE(6,'(A,I3,F20.15,A)') 'ROOT ',I,ECI(I),' HARTREE'
      REWIND(50)
      VEC1=0.0D0
      DO L=1,NTRIALS
       READ(50) VEC2
       VEC1=VEC1+VEC2*W1(L,I)
      ENDDO
      D=0.0D0
      DO IA=1,NCF
       DO IB=1,EA_NCF
        D=D+VEC1(IB,IA)**2
       ENDDO
      ENDDO
      VEC1=VEC1/DSQRT(D)
      PERCENTS=0.0D0
      PERCENTD=0.0D0
      DO IA=1,NCF
       DO IB=1,EA_NCF
        IF (NORDER(IA)+EA_NORDER(IB) == 1) PERCENTS=PERCENTS+VEC1(IB,IA)**2
        IF (NORDER(IA)+EA_NORDER(IB) == 2) PERCENTD=PERCENTD+VEC1(IB,IA)**2
       ENDDO
      ENDDO
      WRITE(6,'(A,F6.2)') ' %SINGLES = ',PERCENTS*1.0D2
      WRITE(6,'(A,F6.2)') ' %DOUBLES = ',PERCENTD*1.0D2
      WRITE(51) VEC1
      CALL S_SQUARED_EA(51,I-1,ORDER,S2)
      WRITE(6,'(A,F8.4)') ' < S**2 > = ',S2
      DO IA=1,NCF
       DO IB=1,EA_NCF
        IF (DABS(VEC1(IB,IA)) > 0.1D0) WRITE(6,'(A,I6,A,I6,A,F8.4)') ' DETERMINANT (',IA,'-ALPHA ',IB,'-BETA ) ',VEC1(IB,IA)
       ENDDO
      ENDDO
     ENDDO
!    REWIND(50)
!    REWIND(51)
!    DO I=1,NROOTS
!     READ(51) VEC1
!     WRITE(50) VEC1
!    ENDDO
     DEALLOCATE(VEC1,VEC2,N)
     CLOSE(50)
     CLOSE(51)
     RETURN
    ELSE IF (NTRIALS_NEXT == NTRIALS) THEN
     CALL PABORT('ALGORITHM FAILED TO INCREASE THE SUBSPACE')
    ELSE IF (NROOTS > 1) THEN
     WRITE(6,'(I3,A)') NTRIALS_NEXT-NTRIALS,' TRIAL VECTORS HAVE BEEN ADDED'
    ENDIF
    NTRIALS=NTRIALS_NEXT

   ENDDO
   CALL PABORT('DAVIDSON ALGORITHM FAILED TO CONVERGE')

END SUBROUTINE



SUBROUTINE EA_EXPONENTIAL_OPERATOR(TFILE,INFILE,OUTFILE,ORDER,LMINUS)
! OPERATE WITH AN EXPONENTIAL OPERATOR ON ANY GIVEN (N+1)-ELECTRON WAVEFUNCTION.  
! THE T-AMPLITUDES ARE STORED IN TFILE, THE WAVEFUNCTION ON WHICH THE EXPONENTIAL OPERATOR ACTS IS 
! IN INFILE, AND THE EXPONENTIAL WAVEFUNCTION IS IN OUTFILE.  IF LMINUS=.TRUE.
! THE OPERATOR IS EXP(-T), OTHERWISE, EXP(T).  NOTE THAT THE T-AMPLITUDES ARE PREDETERMINED
! FOR THE CLOSED SHELL (N)-ELECTRON SYSTEM, BUT THE WAVEFUNCTION UPON WHICH EXP(T) OPERATES
! IS (N+1)-ELECTRON ONE.

   USE CONTROL
   USE GRADIENT
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI

   IMPLICIT NONE
   LOGICAL :: LMINUS
   LOGICAL :: LCYCLE
   INTEGER :: TFILE,INFILE,OUTFILE
   INTEGER :: ORDER
   INTEGER :: I,J,IPOWER
   INTEGER :: IA,IB,IC,ID
   INTEGER :: HOLEA(ORDER),HOLEB(ORDER),PARTA(ORDER),PARTB(ORDER)
   INTEGER :: KSIGN(0:MIN(IOCC,IALL(0,0,0)-IOCC-IVIRTCORE)+MIN(IOCC-ICORE+1,IALL(0,0,0)-IOCC-IVIRTCORE)),ISIGN,JSIGN
   INTEGER(4) :: CFALPH,CFBETA
   DOUBLE PRECISION,ALLOCATABLE :: VEC1(:,:),VEC2(:,:),VEC3(:,:)
   INTEGER,ALLOCATABLE :: AD1(:),EA_AD2(:),SN1(:),EA_SN2(:)
   LOGICAL,ALLOCATABLE :: LC1(:),EA_LC2(:)

   ALLOCATE(VEC1(NCF,NCF),VEC2(EA_NCF,NCF),VEC3(EA_NCF,NCF))
   ALLOCATE(AD1(NCF),EA_AD2(EA_NCF),SN1(NCF),EA_SN2(EA_NCF),LC1(NCF),EA_LC2(EA_NCF))

   ! SIGNS ASSOCIATED WITH THE PERMUTATION OF THE CLUSTER OPERATORS
   DO I=0,MIN(IOCC,IALL(0,0,0)-IOCC-IVIRTCORE)+MIN(IOCC-ICORE+1,IALL(0,0,0)-IOCC-IVIRTCORE)
    KSIGN(I)=(-1)**((I*(I-1))/2)
   ENDDO

   ! RETRIEVE T-AMPLITUDES FROM FILE
   REWIND(TFILE)
   READ(TFILE) VEC1
   IF (LMINUS) VEC1=-VEC1
   ! RETRIEVE INITIAL WAVEFUNCTION FROM FILE
   REWIND(INFILE)
   READ(INFILE) VEC2
   ! INITIALIZE OUTFILE WITH THE INITIAL WAVEFUNCTION
   REWIND(OUTFILE)
   WRITE(OUTFILE) VEC2

   ! LOOP OVER THE POWER
   DO IPOWER=1,MIN(IOCC-ICORE,IALL(0,0,0)-IOCC-IVIRTCORE)+MIN(IOCC-ICORE+1,IALL(0,0,0)-IOCC-IVIRTCORE)
    VEC3=0.0D0

    ! LOOP OVER ALPHA T-AMPLITUDE
    DO IA=1,NCF
     IF (NORDER(IA) > ORDER) CYCLE
     J=0
     DO I=1,IOCC
      IF (.NOT.BTEST(CFHALF(IA),I-1)) THEN
       J=J+1
       HOLEA(J)=I
      ENDIF
     ENDDO
     J=0
     DO I=IOCC+1,IALL(0,0,0)-IVIRTCORE
      IF (BTEST(CFHALF(IA),I-1)) THEN
       J=J+1
       PARTA(J)=I
      ENDIF
     ENDDO

     ! LOOP OVER ALPHA CONFIGURATIONS
     DO IC=1,NCF
      LCYCLE=.FALSE.
      CFALPH=CFHALF(IC)
      DO I=1,NORDER(IA)
       IF (.NOT.BTEST(CFALPH,HOLEA(I)-1)) LCYCLE=.TRUE.
       IF (BTEST(CFALPH,PARTA(I)-1)) LCYCLE=.TRUE.
      ENDDO
      LC1(IC)=LCYCLE
      IF (LCYCLE) CYCLE
      ISIGN=1
      DO I=1,NORDER(IA)
       IF (HOLEA(I) /= 1) THEN
        DO J=1,HOLEA(I)-1
         IF (BTEST(CFALPH,J-1)) ISIGN=-ISIGN
        ENDDO
       ENDIF
       CFALPH=IBCLR(CFALPH,HOLEA(I)-1)
      ENDDO
      DO I=1,NORDER(IA)
       DO J=1,PARTA(I)-1
        IF (BTEST(CFALPH,J-1)) ISIGN=-ISIGN
       ENDDO
       CFALPH=IBSET(CFALPH,PARTA(I)-1)
      ENDDO
      AD1(IC)=ADDRSS(CFALPH)
      SN1(IC)=ISIGN*KSIGN(NORDER(IA))
     ENDDO

     ! LOOP OVER BETA T-AMPLITUDE
     DO IB=1,NCF
      IF (NORDER(IA)+NORDER(IB) > ORDER) CYCLE
      IF (DABS(VEC1(IB,IA)) < 1.0D-15) CYCLE
      J=0
      DO I=1,IOCC
       IF (.NOT.BTEST(CFHALF(IB),I-1)) THEN
        J=J+1
        HOLEB(J)=I
       ENDIF
      ENDDO
      J=0
      DO I=IOCC+1,IALL(0,0,0)-IVIRTCORE
       IF (BTEST(CFHALF(IB),I-1)) THEN
        J=J+1
        PARTB(J)=I
       ENDIF
      ENDDO

      ! LOOP OVER BETA CONFIGURATIONS
      DO ID=1,EA_NCF
       LCYCLE=.FALSE.
       CFBETA=EA_CFHALF(ID)
       DO I=1,NORDER(IB)
        IF (.NOT.BTEST(CFBETA,HOLEB(I)-1)) LCYCLE=.TRUE.
        IF (BTEST(CFBETA,PARTB(I)-1)) LCYCLE=.TRUE.
       ENDDO
       EA_LC2(ID)=LCYCLE
       IF (LCYCLE) CYCLE
       JSIGN=1
       DO I=1,NORDER(IB)
        IF (HOLEB(I) /= 1) THEN
         DO J=1,HOLEB(I)-1
          IF (BTEST(CFBETA,J-1)) JSIGN=-JSIGN
         ENDDO
        ENDIF
        CFBETA=IBCLR(CFBETA,HOLEB(I)-1)
       ENDDO
       DO I=1,NORDER(IB)
        DO J=1,PARTB(I)-1
         IF (BTEST(CFBETA,J-1)) JSIGN=-JSIGN
        ENDDO
        CFBETA=IBSET(CFBETA,PARTB(I)-1)
       ENDDO
       EA_AD2(ID)=EA_ADDRSS(CFBETA)
       EA_SN2(ID)=JSIGN*KSIGN(NORDER(IB))
      ENDDO

      ! LOOP OVER ALPHA CONFIGURATIONS
      DO IC=1,NCF
       IF (LC1(IC)) CYCLE
       ! LOOP OVER BETA CONFIGURATIONS
       DO ID=1,EA_NCF
        IF (EA_LC2(ID)) CYCLE
        IF (DABS(VEC2(ID,IC)) < 1.0D-15) CYCLE
        VEC3(EA_AD2(ID),AD1(IC))=VEC3(EA_AD2(ID),AD1(IC))+DFLOAT(EA_SN2(ID)*SN1(IC))*VEC1(IB,IA)*VEC2(ID,IC)
       ENDDO
      ENDDO

     ENDDO
    ENDDO
    ! AT THIS POINT, VEC3 CONTAINS T TO THE POWER OF IPOWER.  VEC3 IS COPIED TO VEC2 FOR NEXT ITERATION,
    ! AND VEC3 IS ADDED TO THE VECTOR STORED IN 91.
    VEC3=VEC3/DFLOAT(IPOWER)
    REWIND(OUTFILE)
    READ(OUTFILE) VEC2
    VEC2=VEC2+VEC3
    REWIND(OUTFILE)
    WRITE(OUTFILE) VEC2
    VEC2=VEC3
   ENDDO
   
   DEALLOCATE(VEC1,VEC2,VEC3)
   DEALLOCATE(AD1,EA_AD2,SN1,EA_SN2,LC1,EA_LC2)

   RETURN
END SUBROUTINE



SUBROUTINE FULL_EA_EFF_H(TORDER,RORDER)
! FORM FULL EFFECTIVE HAMILTONIAN EXP(-T)HEXP(T) AND DIAGONALIZE IT BY LINPACK/LAPACK/BLAS SUBROUTINES.
! CAUTION, DO NOT USE THIS FOR PRODUCTION RUN.  THE ORDER OF CLUSTER EXPANSION SHOULD BE GIVEN BY TORDER
! AND THE CORRESPONDING T-AMPLITUDES MUST BE PROVIDED IN FILE 90.  THE ORDER OF LINEAR OPERATOR SHOULD BE
! GIVEN BY RORDER.  ELECTRON AFFINITY CALCULATIONS.

   USE CONTROL
   USE GRADIENT
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI

   IMPLICIT NONE
   LOGICAL,PARAMETER :: LEVEC = .FALSE.
   INTEGER :: RORDER,TORDER
   INTEGER :: IA,IB,IC,ID
   INTEGER :: INFO
   INTEGER :: NDIM
   REAL :: MEM,DEV
   DOUBLE PRECISION,ALLOCATABLE :: HAM(:,:),VL(:,:),VR(:,:),ER(:),EI(:),WK(:)
   DOUBLE PRECISION,ALLOCATABLE :: TRL(:,:)

   WRITE(6,'(A)') 'ELECTRON-AFFINITY EQUATION-OF-MOTION COUPLED CLUSTER CALCULATION FOR ALL STATES'
   WRITE(6,'(I2,A)') TORDER,'-ORDER COUPLED CLUSTER SIMILARITY TRANSFORMATION'
   WRITE(6,'(I2,A,I2,A)') RORDER-1,'-HOLE ',RORDER,'-PARTICLE LINEAR EXCITATION OPERATOR'
   IF (LEVEC) THEN
    MEM=16.0*(2.0D0*(NCF*EA_NCF)**2+8.0*NCF*EA_NCF)
   ELSE
    MEM=16.0*((NCF*EA_NCF)**2+9.0*NCF*EA_NCF)
   ENDIF
   IF (MEM > 1000000.0) THEN
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000000.0,' MB'
   ELSE IF (MEM > 1000.0) THEN
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000.0,' KB'
   ELSE
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM,' B'
   ENDIF
   IF (MEM > DOPTN(28)*1000000.0) CALL PABORT('OUT OF MEMORY') 
    ALLOCATE(HAM(NCF*EA_NCF,NCF*EA_NCF),VL(1,NCF*EA_NCF),ER(NCF*EA_NCF),EI(NCF*EA_NCF),WK(4*NCF*EA_NCF))
   IF (LEVEC) THEN
    ALLOCATE(VR(NCF*EA_NCF,NCF*EA_NCF))
   ELSE
    ALLOCATE(VR(1,NCF*EA_NCF))
   ENDIF
   ALLOCATE(TRL(EA_NCF,NCF))

   OPEN(50,FILE=TRIM(COPTN(1))//'.fi0',FORM='UNFORMATTED')
   OPEN(60,FILE=TRIM(COPTN(1))//'.fo0',FORM='UNFORMATTED')
   OPEN(90,FILE=TRIM(COPTN(1))//'.fq0',FORM='UNFORMATTED')

   ! FORM HAMILTONIAN AND KEEP IT IN MEMORY
   NDIM=0
   HAM=0.0D0
   DO IA=1,NCF
    DO IB=1,EA_NCF
     TRL=0.0D0
     IF (NORDER(IA)+EA_NORDER(IB) <= RORDER) TRL(IB,IA)=1.0D0
     IF (NORDER(IA)+EA_NORDER(IB) <= RORDER) NDIM=NDIM+1
     ! |B>=EXP(T)|A>
     REWIND(50)
     WRITE(50) TRL
     CALL EA_EXPONENTIAL_OPERATOR(90,50,60,TORDER,.FALSE.)
     REWIND(60)
     READ(60) TRL
     ! |C>=H|B>
     REWIND(50)
     WRITE(50) TRL
     CALL EA_HAMILTONIAN_PRODUCT(50,60,0,MIN(IOCC-ICORE,IALL(0,0,0)-IOCC-IVIRTCORE)+MIN(IOCC-ICORE+1,IALL(0,0,0)-IOCC-IVIRTCORE))
     REWIND(60)
     READ(60) TRL
     ! |D>=EXP(-T)|C>
     REWIND(50)
     WRITE(50) TRL
     CALL EA_EXPONENTIAL_OPERATOR(90,50,60,TORDER,.TRUE.)
     REWIND(60)
     READ(60) TRL
     DO IC=1,NCF
      DO ID=1,EA_NCF
       HAM((IA-1)*EA_NCF+IB,(IC-1)*EA_NCF+ID)=TRL(ID,IC)
      ENDDO
     ENDDO
    ENDDO
   ENDDO
   IF (NDIM==NCF*EA_NCF) WRITE(6,'(A)') 'FULL CI LIMIT IS REACHED'
!  CALL DUMP5(HAM,NCF*EA_NCF)

   DEALLOCATE(TRL)
   CLOSE(50)
   CLOSE(60)
   CLOSE(90)

   ! DIAGONALIZE HAMILTONIAN
   IF (LEVEC) THEN
    CALL DGEEV('N','V',NCF*EA_NCF,HAM,NCF*EA_NCF,ER,EI,VL,1,VR,NCF*EA_NCF,WK,4*NCF*EA_NCF,INFO)
    IF (INFO /= 0) CALL PABORT('DGEEV FAILED TO DIAGONALIZE A MATRIX')
    DEV=0.0D0
    DO IA=1,NCF*EA_NCF
     DEV=DEV+EI(IA)**2
    ENDDO
    IF (DEV > 1.0E-5) THEN
     CALL WARNING('THE IMAGINARY PART OF THE EIGENVALUES IS NOT ZERO')
     WRITE(6,'(A,F20.10)') 'DEVIATION = ',DEV
    ENDIF
    CALL PIKSRT(NCF*EA_NCF,NCF*EA_NCF,ER,VR,EI)
    DO IA=1,NCF*EA_NCF
     WRITE(6,'(A,I3,A,F20.15,A)') 'STATE ',IA,' ENERGY = ', ER(IA)+NUCLEAR_REPULSION,' HARTREE'
     DO IB=1,NCF*EA_NCF
      WRITE(6,'(I10,F20.15)') IB,VR(IB,IA)
     ENDDO
    ENDDO
   ELSE
    CALL DGEEV('N','N',NCF*EA_NCF,HAM,NCF*EA_NCF,ER,EI,VL,1,VR,1,WK,4*NCF*EA_NCF,INFO)
    IF (INFO /= 0) CALL PABORT('DGEEV FAILED TO DIAGONALIZE A MATRIX')
    DEV=0.0D0
    DO IA=1,NCF*EA_NCF
     DEV=DEV+EI(IA)**2
    ENDDO
    IF (DEV > 1.0E-5) THEN
     CALL WARNING('THE IMAGINARY PART OF THE EIGENVALUES IS NOT ZERO')
     WRITE(6,'(A,F20.10)') 'DEVIATION = ',DEV
    ENDIF
    CALL PIKSRT_EVALONLY(NCF*EA_NCF,ER)
    DO IA=1,NDIM
     WRITE(6,'(A,I3,A,F20.15,A)') 'STATE ',IA,' ENERGY = ', ER(IA)+NUCLEAR_REPULSION,' HARTREE'
    ENDDO
   ENDIF
   CALL PFLUSH(6)

   DEALLOCATE(HAM,ER,EI,VL,VR,WK)

   RETURN
END SUBROUTINE



SUBROUTINE EOMEACC(TORDER,RORDER,NROOTS,NTRIALS)
! PERFORM HIGH-ORDER ELECTRON AFFINITY EQUATION-OF-MOTION COUPLED CLUSTER CALCULATIONS BY HIRAO-NAKATSUJI ALGORITHM.
! K.HIRAO & H.NAKATSUJI,J.COMPUT.PHYS.45,246(1982).

   USE CONSTANTS
   USE CONTROL
   USE GRADIENT
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI

   IMPLICIT NONE
   INTEGER,PARAMETER :: MAXFILE = 1000
   INTEGER,PARAMETER :: MAXCYCLE = 1000
   INTEGER :: ICYCLE
   INTEGER :: TORDER
   INTEGER :: RORDER
   INTEGER :: NROOTS
   INTEGER :: NTRIALS
   INTEGER :: NTRIALS_NEXT
   INTEGER :: IA,IB
   INTEGER :: I,J,K,L,NOPEN
   INTEGER :: INFO
   INTEGER,ALLOCATABLE :: N(:)
   REAL :: MEM,ICPUS,ICPUE
   LOGICAL :: LDONE(MAXFILE)
   DOUBLE PRECISION :: DEVSQ,DEVMAX,D,F,S2
   DOUBLE PRECISION :: SMALLH(MAXFILE,MAXFILE),EEOMCC(MAXFILE)
   DOUBLE PRECISION :: VR(MAXFILE,MAXFILE),VL(1,MAXFILE),ER(MAXFILE),EI(MAXFILE),WK(4*MAXFILE)
   DOUBLE PRECISION :: PERCENTS,PERCENTD
   DOUBLE PRECISION,ALLOCATABLE :: VEC1(:,:),VEC2(:,:)

   CALL CPU_TIME(ICPUS)
   WRITE(6,'(A)') 'HIGH-ORDER ELECTRON-AFFINITY EQUATION-OF-MOTION COUPLED CLUSTER CALCULATIONS WILL BE PERFORMED'
   WRITE(6,'(A,I2)') 'THE ORDER OF COUPLED CLUSTER            = ',TORDER
   WRITE(6,'(A,I2,A,I2,A)') 'THE ORDER OF ELECTRON ATTACHMENT OPERATOR = ',RORDER-1,'-HOLE ',RORDER,'-PARTICLE'
   WRITE(6,'(A,I4)') 'THE NUMBER OF EAEOMCC ROOTS SOUGHT ',NROOTS
   WRITE(6,'(A,I4)') 'THE NUMBER OF INITIAL TRIAL VECTORS ',NTRIALS
   MEM=16.0*2.0*NCF*EA_NCF
   IF (MEM > 1000000.0) THEN
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000000.0,' MB'
   ELSE IF (MEM > 1000.0) THEN
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000.0,' KB'
   ELSE
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM,' B'
   ENDIF
   IF (MEM > DOPTN(28)*1000000.0) CALL PABORT('OUT OF MEMORY') 
   WRITE(6,'(A)') '--------------------------------------------------------'
   WRITE(6,'(A)') '             DEVIATION          TOTAL ENERGY   CPU / SEC'
   ALLOCATE(VEC1(EA_NCF,NCF),VEC2(EA_NCF,NCF),N(IALLMAX-IVIRTCORE))
   OPEN(50,FILE=TRIM(COPTN(1))//'.fi0',FORM='UNFORMATTED')
   OPEN(51,FILE=TRIM(COPTN(1))//'.fo0',FORM='UNFORMATTED')
   OPEN(60,FILE=TRIM(COPTN(1))//'.fw0',FORM='UNFORMATTED')
   OPEN(61,FILE=TRIM(COPTN(1))//'.fw1',FORM='UNFORMATTED')
   OPEN(90,FILE=TRIM(COPTN(1))//'.fq0',FORM='UNFORMATTED')

   ! INITIALIZE
   LDONE=.FALSE.
   IF (NTRIALS > MAXFILE) CALL PABORT('TOO MANY INITIAL TRIAL VECTORS')

   ! HIRAO-NAKATSUJI ITERATIONS
   DO ICYCLE=1,MAXCYCLE

    ! FORM EXP(-T) H EXP(T)|A> AND STORE THEM IN FILE 51
    REWIND(50)
    REWIND(51)
    DO I=1,NTRIALS
     READ(50) VEC1 ! RETRIEVE A TRIAL VECTOR
     IF (.NOT.LDONE(I)) THEN
      ! |B>=EXP(T)|A>
      REWIND(60)
      WRITE(60) VEC1
      CALL EA_EXPONENTIAL_OPERATOR(90,60,61,TORDER,.FALSE.)
      REWIND(61)
      READ(61) VEC1
      ! |C>=H|B>
      REWIND(60)
      WRITE(60) VEC1
      DEALLOCATE(VEC1,VEC2)
      CALL EA_HAMILTONIAN_PRODUCT(60,61,0,MIN(IOCC-ICORE,IALL(0,0,0)-IOCC-IVIRTCORE)+MIN(IOCC-ICORE+1,IALL(0,0,0)-IOCC-IVIRTCORE))
      ALLOCATE(VEC1(EA_NCF,NCF),VEC2(EA_NCF,NCF))
      REWIND(61)
      READ(61) VEC1
      ! |D>=EXP(-T)|C>
      REWIND(60)
      WRITE(60) VEC1
      CALL EA_EXPONENTIAL_OPERATOR(90,60,61,TORDER,.TRUE.)
      REWIND(61)
      READ(61) VEC1
      WRITE(51) VEC1
      LDONE(I)=.TRUE.
     ELSE
      READ(51) VEC2 ! DUMMY READING
     ENDIF
    ENDDO

    ! CONSTRUCT SUBSPACE HAMILTONIAN MATRIX <N|N> FOR DEBUG
!   DO I=1,NTRIALS
!    REWIND(50)
!    DO J=1,I
!     READ(50) VEC1
!    ENDDO
!    REWIND(50)
!    DO L=1,NTRIALS
!     READ(50) VEC2
!     SMALLH(I,L)=0.0D0
!     DO IA=1,NCF
!      DO IB=1,EA_NCF
!       SMALLH(I,L)=SMALLH(I,L)+VEC1(IB,IA)*VEC2(IB,IA)
!      ENDDO
!     ENDDO
!    ENDDO
!   ENDDO
!   CALL DUMP10(SMALLH,NTRIALS,MAXFILE)

    ! CONSTRUCT SUBSPACE HAMILTONIAN MATRIX <N|H|N>
    REWIND(50)
    DO I=1,NTRIALS
     READ(50) VEC1
     REWIND(51)
     DO L=1,NTRIALS
      READ(51) VEC2
      SMALLH(I,L)=0.0D0
      DO IA=1,NCF
       DO IB=1,EA_NCF
        SMALLH(I,L)=SMALLH(I,L)+VEC1(IB,IA)*VEC2(IB,IA)
       ENDDO
      ENDDO
     ENDDO
    ENDDO
!   CALL DUMP10(SMALLH,NTRIALS,MAXFILE)
      
    ! DIAGONALIZE SUBSPACE HAMILTONIAN
    IF (NTRIALS == 1) THEN
     ER(1)=SMALLH(1,1)
     VR(1,1)=1.0D0
    ELSE
     CALL DGEEV('N','V',NTRIALS,SMALLH,MAXFILE,ER,EI,VL,1,VR,MAXFILE,WK,4*MAXFILE,INFO)
     IF (INFO /= 0) CALL PABORT('DGEEV FAILED TO DIAGONALIZE A MATRIX')
     CALL PIKSRT(NTRIALS,MAXFILE,ER,VR,EI)
    ENDIF
!   DO I=1,NTRIALS
!    WRITE(6,'(A,I2,A,F20.15)') 'ROOT ',I,' = ',ER(I)+NUCLEAR_REPULSION
!   ENDDO
      
    ! FORM RESIDUAL VECTORS
    CALL CPU_TIME(ICPUE)
    DEVMAX=0.0D0
    WRITE(6,'(A,I3)') ' ITER ',ICYCLE
    NTRIALS_NEXT=NTRIALS
    DO K=1,NROOTS
     VEC1=0.0D0
     REWIND(50)
     REWIND(51)
     DO L=1,NTRIALS
      READ(51) VEC2
      VEC1=VEC1+VEC2*VR(L,K)
      READ(50) VEC2
      VEC1=VEC1-ER(K)*VEC2*VR(L,K)
     ENDDO
     DEVSQ=0.0D0
     DO IA=1,NCF
      DO IB=1,EA_NCF
       IF (NORDER(IA)+EA_NORDER(IB) > RORDER) VEC1(IB,IA)=0.0D0
       DEVSQ=DEVSQ+VEC1(IB,IA)**2
      ENDDO
     ENDDO
     DEVSQ=DSQRT(DEVSQ)
     IF (DEVSQ > DEVMAX) DEVMAX=DEVSQ
     EEOMCC(K)=ER(K)+NUCLEAR_REPULSION
     WRITE(6,'(A,I3,F15.10,F20.10,F12.1)') ' ROOT ',K,DEVSQ,EEOMCC(K),(ICPUE-ICPUS)/DFLOAT(NROOTS)
      
     IF (DEVSQ < DOPTN(67)) CYCLE

     ! FORM A NEW SUBSPACE VECTOR BY HIRAO-NAKATSUJI SCHEME
     DO IA=1,NCF
      DO IB=1,EA_NCF
       NOPEN=0
       DO I=1,IALL(0,0,0)-IVIRTCORE
        N(I)=0
        IF (BTEST(CFHALF(IA),I-1)) N(I)=1
        IF (BTEST(CFHALF(IB),I-1)) N(I)=N(I)+1
        NOPEN=NOPEN+N(I)*(2-N(I))
       ENDDO
       IF ((NOPEN == 0).OR.(NOPEN == 1)) THEN
        F=0.0D0
       ELSE
        F=(3.0D0-DFLOAT(NOPEN))/DFLOAT(NOPEN*(NOPEN-1))
       ENDIF
       D=0.0D0
       DO I=1,IALL(0,0,0)-IVIRTCORE
        D=D+DFLOAT(N(I))*H(I,I)-DFLOAT(N(I)*(2-N(I)))*G(I,I,I,I)/4.0D0
        DO J=1,IALL(0,0,0)-IVIRTCORE
         D=D+DFLOAT(N(I)*N(J))*(2.0D0*G(I,I,J,J)-G(I,J,J,I))/4.0D0
         IF (I /= J) D=D-F*DFLOAT(N(I)*(2-N(I))*N(J)*(2-N(J)))*G(I,J,J,I)/4.0D0
        ENDDO
       ENDDO
       IF ((ER(K)-D) /= 0.0D0) VEC1(IB,IA)=VEC1(IB,IA)/(ER(K)-D)
      ENDDO
     ENDDO
      
     ! ORTHONORMALIZE THE NEW SUBSPACE VECTOR
     REWIND(50)
     DO L=1,NTRIALS_NEXT
      READ(50) VEC2
      D=0.0D0
      DO IA=1,NCF
       DO IB=1,EA_NCF
        D=D+VEC1(IB,IA)*VEC2(IB,IA)
       ENDDO
      ENDDO
      VEC1=VEC1-D*VEC2
     ENDDO
     D=0.0D0
     DO IA=1,NCF
      DO IB=1,EA_NCF
       D=D+VEC1(IB,IA)**2
      ENDDO
     ENDDO
     D=DSQRT(D)
     IF (D > 1.0D-8) THEN
      VEC1=VEC1/D
      NTRIALS_NEXT=NTRIALS_NEXT+1
      IF (NTRIALS_NEXT > MAXFILE) CALL PABORT('TOO MANY TRIAL VECTORS')
      REWIND(50)
      DO L=1,NTRIALS_NEXT-1
       READ(50) VEC2
      ENDDO
      WRITE(50) VEC1
     ENDIF

    ENDDO

    CALL CPU_TIME(ICPUS)
    CALL PFLUSH(6)

    IF (DEVMAX < DOPTN(67)) THEN
     WRITE(6,'(A)') '--------------------------------------------------------'
!    REWIND(51)
     DO I=1,NROOTS
      WRITE(6,'(A,I3,F20.15,A)') 'ROOT ',I,EEOMCC(I),' HARTREE'
      REWIND(50)
      VEC1=0.0D0
      DO L=1,NTRIALS
       READ(50) VEC2
       VEC1=VEC1+VEC2*VR(L,I)
      ENDDO
      D=0.0D0
      DO IA=1,NCF
       DO IB=1,EA_NCF
        D=D+VEC1(IB,IA)**2
       ENDDO
      ENDDO
      VEC1=VEC1/DSQRT(D)
      PERCENTS=0.0D0
      PERCENTD=0.0D0
      DO IA=1,NCF
       DO IB=1,EA_NCF
        IF (NORDER(IA)+EA_NORDER(IB) == 1) PERCENTS=PERCENTS+VEC1(IB,IA)**2
        IF (NORDER(IA)+EA_NORDER(IB) == 2) PERCENTD=PERCENTD+VEC1(IB,IA)**2
       ENDDO
      ENDDO
      WRITE(6,'(A,F6.2)') ' %SINGLES (CC) = ',PERCENTS*1.0D2
      WRITE(6,'(A,F6.2)') ' %DOUBLES (CC) = ',PERCENTD*1.0D2
!     WRITE(51) VEC1
      REWIND(60)
      WRITE(60) VEC1
      CALL EA_EXPONENTIAL_OPERATOR(90,60,61,TORDER,.FALSE.)
      CALL S_SQUARED_EA(61,0,MIN(IOCC-ICORE,IALL(0,0,0)-IOCC-IVIRTCORE)+MIN(IOCC-ICORE+1,IALL(0,0,0)-IOCC-IVIRTCORE),S2)
      WRITE(6,'(A,F8.4)') ' < S**2 > = ',S2
      REWIND(61)
      READ(61) VEC2
      D=0.0D0
      DO IA=1,NCF
       DO IB=1,EA_NCF
        D=D+VEC2(IB,IA)**2
       ENDDO
      ENDDO
      VEC2=VEC2/DSQRT(D)
      PERCENTS=0.0D0
      PERCENTD=0.0D0
      DO IA=1,NCF
       DO IB=1,EA_NCF
        IF (NORDER(IA)+EA_NORDER(IB) == 1) PERCENTS=PERCENTS+VEC2(IB,IA)**2
        IF (NORDER(IA)+EA_NORDER(IB) == 2) PERCENTD=PERCENTD+VEC2(IB,IA)**2
       ENDDO
      ENDDO
      WRITE(6,'(A,F6.2)') ' %SINGLES (CI) = ',PERCENTS*1.0D2
      WRITE(6,'(A,F6.2)') ' %DOUBLES (CI) = ',PERCENTD*1.0D2
      DO IA=1,NCF
       DO IB=1,EA_NCF
        IF (DABS(VEC1(IB,IA)) > 0.1D0) WRITE(6,'(A,I6,A,I6,A,F8.4)') &
        ' EFFECTIVE DETERMINANT (',IA,'-ALPHA ',IB,'-BETA ) ',VEC1(IB,IA)
       ENDDO
      ENDDO
     ENDDO
!    REWIND(50)
!    REWIND(51)
!    DO I=1,NROOTS
!     READ(51) VEC1
!     WRITE(50) VEC1
!    ENDDO
     DEALLOCATE(VEC1,VEC2,N)
     CLOSE(50)
     CLOSE(51)
     CLOSE(60)
     CLOSE(61)
     CLOSE(90)
     RETURN
    ELSE IF (NTRIALS_NEXT == NTRIALS) THEN
     CALL PABORT('ALGORITHM FAILED TO INCREASE THE SUBSPACE')
    ELSE IF (NROOTS > 1) THEN
     WRITE(6,'(I3,A)') NTRIALS_NEXT-NTRIALS,' TRIAL VECTORS HAVE BEEN ADDED'
    ENDIF
    NTRIALS=NTRIALS_NEXT

   ENDDO
   CALL PABORT('HIRAO-NAKATSUJI ALGORITHM FAILED TO CONVERGE')

END SUBROUTINE



SUBROUTINE S_SQUARED_EA(INFILE,OFFSET,ORDER,S2)
! OPERATE WITH S**2 = S+ S- - SZ + SZ**2 A INPUT VECTOR IN INFILE
! AND INTEGRATE WITH ITSELF TO GET AN EXPECTATION VALUE OF S**2.  
! THE ORDER LIMITS THE NUMBER EXCITATION IN THE CONFIGURATIONS CONSIDERED.

   USE CONTROL
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI
   
   IMPLICIT NONE
   INTEGER :: INFILE,OFFSET
   INTEGER :: ORDER
   INTEGER :: ISIGN,JSIGN
   INTEGER :: I,J,K
   INTEGER :: IA,IB,IC,ID
   INTEGER(4) :: CFA0,CFB0,CFA1,CFB1,CFA2,CFB2
   REAL :: MEM
   DOUBLE PRECISION :: S2,NORM
   DOUBLE PRECISION,ALLOCATABLE :: INP(:,:),OUT(:,:)

   MEM=16.0*2.0*NCF*EA_NCF+4.0*2.0*NCF*(IALL(0,0,0)-IVIRTCORE)**2
!  IF (MEM > 1000000.0) THEN
!   WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000000.0,' MB'
!  ELSE IF (MEM > 1000.0) THEN
!   WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000.0,' KB'
!  ELSE
!   WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM,' B'
!  ENDIF
   IF (MEM > DOPTN(28)*1000000.0) CALL PABORT('OUT OF MEMORY') 

   ALLOCATE(INP(EA_NCF,NCF),OUT(EA_NCF,NCF))

   ! READ INPUT VECTOR FROM FILE INFILE
   REWIND(INFILE)
   DO I=0,OFFSET
    READ(INFILE) INP
   ENDDO

   ! ZERO SCRATCH INPUT VECTOR ELEMENTS ASSOCIATED WITH EXCITATION HIGHER THAN THE ORDER
   NORM=0.0D0
   DO IA=1,NCF
    DO IB=1,EA_NCF
     IF (NORDER(IA)+EA_NORDER(IB) > ORDER) INP(IB,IA)=0.0D0
     NORM=NORM+INP(IB,IA)**2
    ENDDO
   ENDDO

   ! ZERO SCRATCH OUTPUT VECTOR
   OUT=0.0D0

   ! S+ S-
   DO IA=1,NCF
    DO IB=1,EA_NCF
     CFA0=CFHALF(IA)
     CFB0=EA_CFHALF(IB)
     ! OPERATE WITH S-
     DO I=1,IALL(0,0,0)-IVIRTCORE
      IF (BTEST(CFA0,I-1).AND.(.NOT.BTEST(CFB0,I-1))) THEN
       CFA1=IBCLR(CFA0,I-1)
       CFB1=IBSET(CFB0,I-1)
       ISIGN=1
       DO J=1,I
        IF (BTEST(CFA0,J-1)) ISIGN=-ISIGN
        IF (BTEST(CFB1,J-1)) ISIGN=-ISIGN
       ENDDO
       ! OPERATE WITH S+
       DO J=1,IALL(0,0,0)-IVIRTCORE
        IF ((.NOT.BTEST(CFA1,J-1)).AND.BTEST(CFB1,J-1)) THEN
         CFA2=IBSET(CFA1,J-1)
         CFB2=IBCLR(CFB1,J-1)
         JSIGN=1
         DO K=1,J
          IF (BTEST(CFA2,K-1)) JSIGN=-JSIGN
          IF (BTEST(CFB1,K-1)) JSIGN=-JSIGN
         ENDDO
         IC=ADDRSS(CFA2)
         ID=EA_ADDRSS(CFB2)
         OUT(ID,IC)=OUT(ID,IC)+DFLOAT(ISIGN*JSIGN)*INP(IB,IA)
        ENDIF
       ENDDO
      ENDIF
     ENDDO
    ENDDO
   ENDDO

   ! SZ ( SZ-1 )
   DO IA=1,NCF
    DO IB=1,EA_NCF
     OUT(IB,IA)=OUT(IB,IA)+(3.0D0/4.0D0)*INP(IB,IA)
    ENDDO
   ENDDO

   S2=0.0D0
   DO IA=1,NCF
    DO IB=1,EA_NCF
     IF (NORDER(IA)+EA_NORDER(IB) > ORDER) CYCLE
     S2=S2+INP(IB,IA)*OUT(IB,IA)/NORM
    ENDDO
   ENDDO

   DEALLOCATE(INP,OUT)

   RETURN
END SUBROUTINE



SUBROUTINE HIGHORDER_MP_EA(ORDER)
! PERFORM HIGH-ORDER MOELLER-PLESSET PERTURBATION CALCULATIONS IN A RECURSIVE ALGORITHM
! FOR KOOPMANS-ELECTRON-ATTACHED INITIAL DETERMINANT TO BE USED TO DETERMINE THE DYSON SELF-ENERGY
! AT OMEGA = EPSILON_P.

   USE CONTROL
   USE GRADIENT
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI

   IMPLICIT NONE
   INTEGER,PARAMETER :: MAXFILE = 100
   INTEGER :: ORDER
   INTEGER :: MOI,MOJ
   INTEGER :: IA,IB,IR
   INTEGER :: I,J,K,IFILE
   INTEGER :: MOP
   REAL :: MEM,ICPUS,ICPUE
   DOUBLE PRECISION :: HA,HB
   DOUBLE PRECISION :: EMP,DMP(0:ORDER)
   DOUBLE PRECISION,ALLOCATABLE :: VEC1(:,:),VEC2(:,:)
   INTEGER :: NQP

   CALL CPU_TIME(ICPUS)
   WRITE(6,'(A)') 'RECURSIVE HIGH-ORDER MOELLER-PLESSET PERTURBATION CALCULATIONS WILL BE PERFORMED'
   MEM=16.0*2.0*NCF*EA_NCF
   IF (MEM > 1000000.0) THEN
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000000.0,' MB'
   ELSE IF (MEM > 1000.0) THEN
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000.0,' KB'
   ELSE
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM,' B'
   ENDIF
   IF (MEM > DOPTN(28)*1000000.0) CALL PABORT('OUT OF MEMORY')

   ! LOOP OVER ORBITALS TO BE ADDED AN ELECTRON
   NQP=IOPTN(44)
   IF (NQP < 1) NQP=IALL(0,0,0)-IVIRTCORE-IOCC
   DO MOP=IOCC+1,MIN(IOCC+NQP,IALL(0,0,0)-IVIRTCORE)

    EMP=NUCLEAR_REPULSION
    WRITE(6,'(A,I3)') 'STATE ELECTRON-ATTACHED TO ORBITAL ',MOP
    WRITE(6,'(A)') '--------------------------------------------------------------------------'
    WRITE(6,'(A)') 'ORDER      CORRELATION        TOTAL ENERGY         SELF-ENERGY   CPU / SEC'
    ALLOCATE(VEC1(EA_NCF,NCF),VEC2(EA_NCF,NCF))
    OPEN(50,FILE=TRIM(COPTN(1))//'.fi0',FORM='UNFORMATTED')
    OPEN(51,FILE=TRIM(COPTN(1))//'.fo0',FORM='UNFORMATTED')

    ! INITIALIZE WAVEFUNCTION TO THE HARTREE-FOCK DETERMINANT
    IR=EA_ADDRSS(IBSET(CFHALF(1),MOP-1))
    VEC1=0.0D0
    VEC1(IR,1)=1.0D0
    REWIND(50)
    WRITE(50) VEC1
    !CALL DUMP14(50,1)

    ! DMP(0)
    DMP(0)=0.0D0
    DO MOI=1,IOCC
     DMP(0)=DMP(0)+2.0D0*EPSILON(MOI,0,0,0)
    ENDDO
    DMP(0)=DMP(0)+EPSILON(MOP,0,0,0)
    EMP=EMP+DMP(0)
    WRITE(6,'(I2,F20.10,2F20.10,F12.1)') 0,DMP(0),EMP,EMP-MP_STORED(0),0.0

    ! DMP(1) ONWARD
    DO IFILE=0,ORDER-1
     IF (IOPTN(9) >= 3) THEN
      REWIND(50)
      DO I=0,IFILE
       READ(50) VEC1
      ENDDO
      WRITE(6,'(I3,A)') IFILE,'TH ORDER WAVE FUNCTION'
      CALL DUMP5(VEC1,NCF)
     ENDIF
     DEALLOCATE(VEC1,VEC2)
     CALL EA_HAMILTONIAN_PRODUCT(50,51,IFILE,MIN(IOCC-ICORE,IALL(0,0,0)-IOCC-IVIRTCORE) & 
                                            +MIN(IOCC-ICORE+1,IALL(0,0,0)-IOCC-IVIRTCORE))
     ALLOCATE(VEC1(EA_NCF,NCF),VEC2(EA_NCF,NCF))
     REWIND(51)
     DO I=0,IFILE
      READ(51) VEC1
     ENDDO
     IF (IOPTN(9) >= 3) THEN
      WRITE(6,'(A,I1,A)') 'H|',IFILE,'>'
      CALL DUMP5(VEC1,NCF)
     ENDIF
!    IF (IFILE == 0) THEN
!     DMP(1)=-DMP(0)
!     DO MOI=1,IOCC
!      DMP(1)=DMP(1)+2.0D0*H(MOI,MOI)
!     ENDDO
!     DMP(1)=DMP(1)-H(MOP,MOP)
!     DO MOI=1,IOCC
!      DO MOJ=1,IOCC
!       DMP(1)=DMP(1)+(2.0D0*G(MOI,MOI,MOJ,MOJ)-G(MOI,MOJ,MOJ,MOI))
!      ENDDO
!     ENDDO
!     DO MOJ=1,IOCC
!      DMP(1)=DMP(1)-(G(MOP,MOP,MOJ,MOJ)-0.5D0*G(MOP,MOJ,MOJ,MOP))
!     ENDDO
!    ELSE
!     DMP(IFILE+1)=VEC1(IR,1)
!    ENDIF
     DMP(IFILE+1)=VEC1(IR,1)
     IF (IFILE == 0) DMP(1)=DMP(1)-DMP(0)
     EMP=EMP+DMP(IFILE+1)
     CALL CPU_TIME(ICPUE)
     WRITE(6,'(I2,F20.10,2F20.10,F12.1)') IFILE+1,DMP(IFILE+1),EMP,EMP-MP_STORED(IFILE+1),ICPUE-ICPUS
     CALL CPU_TIME(ICPUS)
     CALL PFLUSH(6)
     IF (DABS(DMP(IFILE+1)) < 1.0D-15) EXIT
     VEC1=-VEC1
     REWIND(50)
     DO K=0,IFILE
      READ(50) VEC2
      DO IA=1,NCF
       HA=0.0D0
       IF (K == IFILE) THEN
        DO I=1,IALL(0,0,0)-IVIRTCORE
         IF (BTEST(CFHALF(IA),I-1)) HA=HA+EPSILON(I,0,0,0)
        ENDDO
       ENDIF
       DO IB=1,EA_NCF
        HB=0.0D0
        IF (K == IFILE) THEN
         DO I=1,IALL(0,0,0)-IVIRTCORE
          IF (BTEST(EA_CFHALF(IB),I-1)) HB=HB+EPSILON(I,0,0,0)
         ENDDO
        ENDIF
        IF (K == IFILE) THEN
         VEC1(IB,IA)=VEC1(IB,IA)+(DMP(IFILE-K+1)+HA+HB)*VEC2(IB,IA)
        ELSE
         VEC1(IB,IA)=VEC1(IB,IA)+DMP(IFILE-K+1)*VEC2(IB,IA)
        ENDIF
       ENDDO
      ENDDO
     ENDDO
     DO IA=1,NCF
      HA=0.0D0
      DO I=1,IALL(0,0,0)-IVIRTCORE
       IF (BTEST(CFHALF(IA),I-1)) HA=HA+EPSILON(I,0,0,0)
      ENDDO
      DO IB=1,EA_NCF
       HB=0.0D0
       DO I=1,IALL(0,0,0)-IVIRTCORE
        IF (BTEST(EA_CFHALF(IB),I-1)) HB=HB+EPSILON(I,0,0,0)
       ENDDO
       IF ((IA == 1).AND.(IB == IR)) THEN
        VEC2(IB,IA)=0.0D0
! SPECULATIVE 
       ELSE IF (DABS(HA+HB-DMP(0)) < 1.0D-10) THEN
        WRITE(6,'(A)') 'DEGENERACY DETECTED'
        VEC2(IB,IA)=0.0D0
       ELSE
        VEC2(IB,IA)=VEC1(IB,IA)/(HA+HB-DMP(0))
       ENDIF
      ENDDO
     ENDDO
     IF (IFILE == MAXFILE) EXIT
     WRITE(50) VEC2
    ENDDO

    WRITE(6,'(A)') '--------------------------------------------------------------------------'
    DEALLOCATE(VEC1,VEC2)
    CLOSE(50)
    CLOSE(51)

!   IF (IOPTN(97) > 0) THEN
!    OPEN(97,FILE=TRIM(COPTN(1))//'.gf0',FORM='UNFORMATTED')
!    VEC2=0.0D0
!    REWIND(50)
!    DO I=0,ORDER-1
!     READ(50) VEC1
!     VEC2=VEC2+VEC1
!    ENDDO
!    REWIND(97)
!    WRITE(97) VEC2
!    CLOSE(97)
!    WRITE(6,'(A,A)') 'REFERENCE WAVE FUNCTION FOR MBGF STORED IN ',TRIM(COPTN(1))//'.gf0'
!   ENDIF

   ENDDO

   RETURN
END SUBROUTINE



SUBROUTINE FULL_EA_HAMILTONIAN_SCALE(ORDER,SCALEFACTOR)
! FORM FULL HAMILTONIAN AND DIAGONALIZE IT BY THE STANDARD ALGORITHMS.
! CAUTION, DO NOT USE THIS FOR PRODUCTION RUN.

   USE CONTROL
   USE GRADIENT
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI

   IMPLICIT NONE
   LOGICAL :: LEVEC
   INTEGER :: ORDER
   INTEGER :: IA,IB,IC,ID
   INTEGER :: INFO
   REAL :: MEM,DEV
   DOUBLE PRECISION :: SCALEFACTOR
   DOUBLE PRECISION,ALLOCATABLE :: HAM(:,:)
   DOUBLE PRECISION,ALLOCATABLE :: VL(:,:),VR(:,:),ER(:),EI(:),WK(:)
   DOUBLE PRECISION,ALLOCATABLE :: TRL(:,:),PRD(:,:)

   LEVEC=.FALSE.
   IF (IOPTN(97) > 0) LEVEC=.TRUE.
!  WRITE(6,'(I2,A,I2,A)') ORDER-1,'-HOLE',ORDER,'-PARTICLE CONFIGURATION INTERACTION CALCULATION FOR ALL STATES'
   IF (SCALEFACTOR /= 1.0D0) THEN
!   WRITE(6,'(A)') '*************************************************************'
!   WRITE(6,'(A,F7.4,A)') '* WARNING: SCALE FACTOR FOR FLUCTUATION POTENTIAL = ',SCALEFACTOR,' *'
!   WRITE(6,'(A)') '*************************************************************'
   ENDIF
   IF (LEVEC) THEN 
    MEM=16.0*(2.0*(NCF*EA_NCF)**2+8.0*NCF*EA_NCF)
   ELSE
    MEM=16.0*((NCF*EA_NCF)**2+9.0*NCF*EA_NCF)
   ENDIF
   IF (MEM > 1000000.0) THEN
!   WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000000.0,' MB'
   ELSE IF (MEM > 1000.0) THEN
!   WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000.0,' KB'
   ELSE
!   WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM,' B'
   ENDIF
   IF (MEM > DOPTN(28)*1000000.0) CALL PABORT('OUT OF MEMORY') 
   ALLOCATE(HAM(NCF*EA_NCF,NCF*EA_NCF),VL(1,NCF*EA_NCF),ER(NCF*EA_NCF),EI(NCF*EA_NCF),WK(4*NCF*EA_NCF))
   IF (LEVEC) THEN 
    ALLOCATE(VR(NCF*EA_NCF,NCF*EA_NCF))
   ELSE
    ALLOCATE(VR(1,NCF*EA_NCF))
   ENDIF
   ALLOCATE(TRL(EA_NCF,NCF),PRD(EA_NCF,NCF))

   OPEN(50,FILE=TRIM(COPTN(1))//'.fi0',FORM='UNFORMATTED')
   OPEN(60,FILE=TRIM(COPTN(1))//'.fo0',FORM='UNFORMATTED')

   ! FORM HAMILTONIAN AND KEEP IT IN MEMORY
   DO IA=1,NCF
    DO IB=1,EA_NCF
     TRL=0.0D0
     IF (NORDER(IA)+EA_NORDER(IB) <= ORDER) TRL(IB,IA)=1.0D0
!    REWIND(50)
!    WRITE(50) TRL
!    CALL EA_HAMILTONIAN_PRODUCT(50,60,0,ORDER)
!    REWIND(60)
!    READ(60) TRL
     REWIND(50)
     WRITE(50) TRL
     CALL EA_HAMILTONIAN_PRODUCT(50,60,0,ORDER)
     REWIND(60)
     READ(60) TRL
     CALL H0_PRODUCT(50,60,-1)
     REWIND(60)
     READ(60) PRD
     TRL=PRD+(TRL-PRD)*SCALEFACTOR
     DO IC=1,NCF
      DO ID=1,EA_NCF
       HAM((IA-1)*EA_NCF+IB,(IC-1)*EA_NCF+ID)=TRL(ID,IC)
      ENDDO
     ENDDO
    ENDDO
   ENDDO
!  CALL DUMP5(HAM,NCF*EA_NCF)

   DEALLOCATE(TRL,PRD)
   CLOSE(50)
   CLOSE(60)

   ! DIAGONALIZE HAMILTONIAN
   IF (LEVEC.OR.(IOPTN(97) > 0)) THEN
    CALL DGEEV('N','V',NCF*EA_NCF,HAM,NCF*EA_NCF,ER,EI,VL,1,VR,NCF*EA_NCF,WK,4*NCF*EA_NCF,INFO)
    IF (INFO /= 0) CALL PABORT('DGEEV FAILED TO DIAGONALIZE A MATRIX')
    DEV=0.0D0
    DO IA=1,NCF*EA_NCF
     DEV=DEV+EI(IA)**2
    ENDDO
    IF (DEV > 1.0E-5) THEN
     CALL WARNING('THE IMAGINARY PART OF THE EIGENVALUES IS NOT ZERO')
!    WRITE(6,'(A,F20.10)') 'DEVIATION = ',DEV
    ENDIF
    CALL PIKSRT(NCF*EA_NCF,NCF*EA_NCF,ER,VR,EI)
    DO IA=1,MIN(25,NCF*EA_NCF)
!    WRITE(6,'(A,I3,A,F20.15,A)') 'STATE ',IA,' ENERGY = ', ER(IA)+NUCLEAR_REPULSION,' HARTREE'
!    DO IB=1,NCF*EA_NCF
!     WRITE(6,'(I10,F20.15)') IB,VR(IB,IA)
!    ENDDO
    ENDDO
    IF (IOPTN(97) > 0) THEN
     OPEN(97,FILE=TRIM(COPTN(1))//'.gf2',FORM='UNFORMATTED')
     REWIND(97)
     WRITE(97) ER
     WRITE(97) VR
     CLOSE(97)
!    WRITE(6,'(A,A)') '(N+1)-ELECTRON ENERGIES AND WAVE FUNCTIONS FOR MBGF STORED IN ',TRIM(COPTN(1))//'.gf2'
    ENDIF
   ELSE
    CALL DGEEV('N','N',NCF*EA_NCF,HAM,NCF*EA_NCF,ER,EI,VL,1,VR,1,WK,4*NCF*EA_NCF,INFO)
    IF (INFO /= 0) CALL PABORT('DGEEV FAILED TO DIAGONALIZE A MATRIX')
    DEV=0.0D0
    DO IA=1,NCF*EA_NCF
     DEV=DEV+EI(IA)**2
    ENDDO
    IF (DEV > 1.0E-5) THEN
     CALL WARNING('THE IMAGINARY PART OF THE EIGENVALUES IS NOT ZERO')
!    WRITE(6,'(A,F20.10)') 'DEVIATION = ',DEV
    ENDIF
    CALL PIKSRT_EVALONLY(NCF*EA_NCF,ER)
    DO IA=1,MIN(25,NCF*EA_NCF)
!    WRITE(6,'(A,I3,A,F20.15,A)') 'STATE ',IA,' ENERGY = ', ER(IA)+NUCLEAR_REPULSION,' HARTREE'
    ENDDO
   ENDIF
   CALL PFLUSH(6)

   DEALLOCATE(HAM,VL,VR,ER,EI,WK)

   RETURN
END SUBROUTINE



SUBROUTINE HIGHORDER_MP_EA_ALLSTATES_OBSOLETE(ORDER)
! PERFORM HIGH-ORDER MOELLER-PLESSET PERTURBATION CALCULATIONS IN A RECURSIVE ALGORITHM
! FOR ALL ELECTRON-ATTACHED DETERMINANTS AND STORE THE WAVE FUNCTIONS AND ENERGIES

   USE CONTROL
   USE GRADIENT
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI

   IMPLICIT NONE
   LOGICAL,PARAMETER :: SILENT = .TRUE.
   INTEGER,PARAMETER :: MAXFILE = 100
   INTEGER :: ORDER
   INTEGER :: MOI,MOJ
   INTEGER :: IA,IB
   INTEGER :: QA,QB,PA,PB
   INTEGER :: I,J,K,IFILE
   REAL :: MEM,ICPUS,ICPUE
   DOUBLE PRECISION :: HA,HB
   DOUBLE PRECISION :: EMP,DMP(0:ORDER),SIGMA(0:ORDER)
   DOUBLE PRECISION,ALLOCATABLE :: VEC1(:,:),VEC2(:,:)

   CALL CPU_TIME(ICPUS)
   IF (.NOT.SILENT) WRITE(6,'(A)') 'RECURSIVE HIGH-ORDER MOELLER-PLESSET PERTURBATION CALCULATIONS WILL BE PERFORMED'

   ALLOCATE(VEC1(EA_NCF,NCF),VEC2(EA_NCF,NCF))

   OPEN(60,FILE=TRIM(COPTN(1))//'.ea0',FORM='UNFORMATTED')
   OPEN(61,FILE=TRIM(COPTN(1))//'.ea1',FORM='UNFORMATTED')
   REWIND(60)
   REWIND(61)

   ! LOOP OVER EA CONFIGURATIONS
   DO PA=1,NCF
    DO PB=1,EA_NCF

     EMP=NUCLEAR_REPULSION
     IF (.NOT.SILENT) THEN
      IF (NORDER(PA)+EA_NORDER(PB)==1) WRITE(6,'(A,I3,A,I1,A,I3,A,I1,A)') &
       'INITIAL EA CONFIGURATION ',PA,' (',NORDER(PA),')',PB,' (',EA_NORDER(PB),') KOOPMANS'
      IF (NORDER(PA)+EA_NORDER(PB)/=1) WRITE(6,'(A,I3,A,I1,A,I3,A,I1,A)') &
       'INITIAL EA CONFIGURATION ',PA,' (',NORDER(PA),')',PB,' (',EA_NORDER(PB),')'
      WRITE(6,'(A)') '--------------------------------------------------------------------------'
      WRITE(6,'(A)') 'ORDER      CORRELATION        TOTAL ENERGY         SELF-ENERGY   CPU / SEC'
     ENDIF
     OPEN(50,FILE=TRIM(COPTN(1))//'.fi0',FORM='UNFORMATTED')
     OPEN(51,FILE=TRIM(COPTN(1))//'.fo0',FORM='UNFORMATTED')

     ! INITIALIZE WAVEFUNCTION TO THE HARTREE-FOCK DETERMINANT
     VEC1=0.0D0
     VEC1(PB,PA)=1.0D0
     REWIND(50)
     WRITE(50) VEC1
!    CALL DUMP14(50,1)

     ! DMP(0)
     CALL H0_PRODUCT(50,51,-1)
     REWIND(51)
     READ(51) VEC2
     DMP(0)=0.0D0
     DO QA=1,NCF
      DO QB=1,EA_NCF
       DMP(0)=DMP(0)+VEC1(QB,QA)*VEC2(QB,QA)
      ENDDO
     ENDDO
     EMP=EMP+DMP(0)
     IF (.NOT.SILENT) WRITE(6,'(I2,F20.10,2F20.10,F12.1)') 0,DMP(0),EMP,EMP-MP_STORED(0),0.0
     SIGMA(0)=EMP-MP_STORED(0)

     ! DMP(1) ONWARD
     DO IFILE=0,ORDER-1
      IF (IOPTN(9) >= 3) THEN
       REWIND(50)
       DO I=0,IFILE
        READ(50) VEC1
       ENDDO
       IF (.NOT.SILENT) WRITE(6,'(I3,A)') IFILE,'TH ORDER WAVE FUNCTION'
       CALL DUMP5(VEC1,NCF)
      ENDIF
      CALL EA_HAMILTONIAN_PRODUCT(50,51,IFILE,MIN(IOCC-ICORE,IALL(0,0,0)-IOCC-IVIRTCORE) &
                                             +MIN(IOCC-ICORE+1,IALL(0,0,0)-IOCC-IVIRTCORE))
      REWIND(51)
      DO I=0,IFILE
       READ(51) VEC1
      ENDDO
      IF (IOPTN(9) >= 3) THEN
       IF (.NOT.SILENT) WRITE(6,'(A,I1,A)') 'H|',IFILE,'>'
       CALL DUMP5(VEC1,NCF)
      ENDIF
      REWIND(50)
      READ(50) VEC2
      DMP(IFILE+1)=0.0D0
      DO QA=1,NCF
       DO QB=1,EA_NCF
        DMP(IFILE+1)=DMP(IFILE+1)+VEC1(QB,QA)*VEC2(QB,QA)
       ENDDO
      ENDDO
      IF (IFILE == 0) DMP(1)=DMP(1)-DMP(0)
      EMP=EMP+DMP(IFILE+1)
      CALL CPU_TIME(ICPUE)
      IF (.NOT.SILENT) WRITE(6,'(I2,F20.10,2F20.10,F12.1)') IFILE+1,DMP(IFILE+1),EMP,EMP-MP_STORED(IFILE+1),ICPUE-ICPUS
      SIGMA(IFILE+1)=EMP-MP_STORED(IFILE+1)
      CALL CPU_TIME(ICPUS)
      CALL PFLUSH(6)
!     IF (DABS(DMP(IFILE+1)) < 1.0D-15) EXIT
      VEC1=-VEC1
      REWIND(50)
      DO K=0,IFILE
       READ(50) VEC2
       DO IA=1,NCF
        HA=0.0D0
        IF (K == IFILE) THEN
         DO I=1,IALL(0,0,0)-IVIRTCORE
          IF (BTEST(CFHALF(IA),I-1)) HA=HA+EPSILON(I,0,0,0)
         ENDDO
        ENDIF
        DO IB=1,EA_NCF
         HB=0.0D0
         IF (K == IFILE) THEN
          DO I=1,IALL(0,0,0)-IVIRTCORE
           IF (BTEST(EA_CFHALF(IB),I-1)) HB=HB+EPSILON(I,0,0,0)
          ENDDO
         ENDIF
         IF (K == IFILE) THEN
          VEC1(IB,IA)=VEC1(IB,IA)+(DMP(IFILE-K+1)+HA+HB)*VEC2(IB,IA)
         ELSE
          VEC1(IB,IA)=VEC1(IB,IA)+DMP(IFILE-K+1)*VEC2(IB,IA)
         ENDIF
        ENDDO
       ENDDO
      ENDDO
      DO IA=1,NCF
       HA=0.0D0
       DO I=1,IALL(0,0,0)-IVIRTCORE
        IF (BTEST(CFHALF(IA),I-1)) HA=HA+EPSILON(I,0,0,0)
       ENDDO
       DO IB=1,EA_NCF
        HB=0.0D0
        DO I=1,IALL(0,0,0)-IVIRTCORE
         IF (BTEST(EA_CFHALF(IB),I-1)) HB=HB+EPSILON(I,0,0,0)
        ENDDO
        IF ((IA == PA).AND.(IB == PB)) THEN
         VEC2(IB,IA)=0.0D0
! SPECULATIVE 
        ELSE IF (DABS(HA+HB-DMP(0)) < 1.0D-10) THEN
         IF (.NOT.SILENT) WRITE(6,'(A,2I3)') 'DEGENERACY DETECTED',IA,IB
         VEC2(IB,IA)=0.0D0
        ELSE
         VEC2(IB,IA)=VEC1(IB,IA)/(HA+HB-DMP(0))
        ENDIF
       ENDDO
      ENDDO
      IF (IFILE == MAXFILE) EXIT
      WRITE(50) VEC2
     ENDDO

     IF (.NOT.SILENT) WRITE(6,'(A)') '--------------------------------------------------------------------------'

     REWIND(50)
     DO I=0,ORDER-1
      IF (I==0) THEN
       WRITE(60) SIGMA(0)
!if (pa==1) write(*,*) sigma(0)
      ELSE
       WRITE(60) SIGMA(I)-SIGMA(I-1)
!if (pa==1) write(*,*) sigma(i)-sigma(i-1)
      ENDIF
      READ(50) VEC1
      WRITE(61) VEC1
     ENDDO

     CLOSE(50)
     CLOSE(51)

    ENDDO
   ENDDO

   DEALLOCATE(VEC1,VEC2)
   CLOSE(60)
   CLOSE(61)

   RETURN
END SUBROUTINE



SUBROUTINE HIGHORDER_MP_EA_ALLSTATES(ORIGINALORDER)
! PERFORM HIGH-ORDER MOELLER-PLESSET PERTURBATION CALCULATIONS IN A RECURSIVE ALGORITHM
! FOR ALL IONIZED INITIAL DETERMINANTS AND STORE THE WAVE FUNCTIONS AND ENERGIES

   USE CONTROL
   USE GRADIENT
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI

   IMPLICIT NONE
   DOUBLE PRECISION,PARAMETER :: TOL = 1.0D-3
   LOGICAL,PARAMETER :: SILENT = .FALSE.
   INTEGER,PARAMETER :: MAXR = 3
   INTEGER,PARAMETER :: MAXFILE = 100
   INTEGER :: ORIGINALORDER
   INTEGER :: ORDER
   INTEGER :: IA,IB,IC,ID
   INTEGER :: IORDER,JORDER
   INTEGER :: INFO
   INTEGER :: N
   DOUBLE PRECISION,ALLOCATABLE :: EMP(:,:),DMP(:,:),SIGMA(:,:)
   DOUBLE PRECISION,ALLOCATABLE :: HEFF(:,:)
   DOUBLE PRECISION,ALLOCATABLE :: T1(:,:),T2(:,:),T3(:,:)
   DOUBLE PRECISION,ALLOCATABLE :: V1(:)
   DOUBLE PRECISION,ALLOCATABLE :: BAS(:,:,:,:),EPS(:,:)
   DOUBLE PRECISION,ALLOCATABLE :: RHS91(:,:),AMAT(:,:)
   DOUBLE PRECISION,ALLOCATABLE :: VL(:,:),VR(:,:),ER(:),EI(:),WK(:)
   DOUBLE PRECISION :: E1,E2
   LOGICAL,ALLOCATABLE :: LTAKEN(:)
   LOGICAL,ALLOCATABLE :: LDEGEN(:,:,:)
   LOGICAL,ALLOCATABLE :: LNONDEG(:,:)
   LOGICAL :: LNOCHANGE
   INTEGER :: Q,K,M,P,T
   INTEGER,ALLOCATABLE :: MAP(:)
   INTEGER,ALLOCATABLE :: NDEGEN(:,:)
   DOUBLE PRECISION,ALLOCATABLE :: LARGEEPS(:),LARGEVMAT(:,:)
   INTEGER :: NGROUPS,IG,NG
   INTEGER,ALLOCATABLE :: GROUPSIZE(:),GROUPMEMS(:,:),MAPG(:,:)
   INTEGER :: IR

   IF (.NOT.SILENT) WRITE(6,'(A)') &
    'RECURSIVE HIGH-ORDER MOELLER-PLESSET PERTURBATION CALCULATIONS WILL BE PERFORMED FOR ALL ELECTRON-ATTACHED STATES'

   OPEN(60,FILE=TRIM(COPTN(1))//'.ea0',FORM='UNFORMATTED')
   OPEN(61,FILE=TRIM(COPTN(1))//'.ea1',FORM='UNFORMATTED')
   REWIND(60)
   REWIND(61)

   ORDER=ORIGINALORDER+MAXR
   N=NCF*EA_NCF
   ALLOCATE(EMP(N,0:ORDER),DMP(N,0:ORDER),SIGMA(N,0:ORDER))
   EMP=NUCLEAR_REPULSION

   ! FORM <Det|H0|Det> AND <Det|V|Det> MATRIX
   ALLOCATE(LARGEVMAT(N,N),LARGEEPS(N))
   ALLOCATE(T1(EA_NCF,NCF),T2(EA_NCF,NCF),T3(EA_NCF,NCF))
   OPEN(50,FILE=TRIM(COPTN(1))//'.fi0',FORM='UNFORMATTED')
   OPEN(51,FILE=TRIM(COPTN(1))//'.fo0',FORM='UNFORMATTED')
   DO IA=1,NCF
    DO IB=1,EA_NCF
     T1=0.0D0
     T1(IB,IA)=1.0D0
     REWIND(50)
     WRITE(50) T1
     CALL EA_HAMILTONIAN_PRODUCT(50,51,0,MIN(IOCC-ICORE,IALL(0,0,0)-IOCC-IVIRTCORE)+MIN(IOCC-ICORE+1,IALL(0,0,0)-IOCC-IVIRTCORE))
     REWIND(51)
     READ(51) T2
     CALL H0_PRODUCT(50,51,-1)
     REWIND(51)
     READ(51) T3
     LARGEEPS((IA-1)*EA_NCF+IB)=T3(IB,IA)
     T2=T2-T3 ! V = H - H0
     DO IC=1,NCF
      DO ID=1,EA_NCF
       LARGEVMAT((IC-1)*EA_NCF+ID,(IA-1)*EA_NCF+IB)=T2(ID,IC)
      ENDDO
     ENDDO
    ENDDO
   ENDDO
   CLOSE(50)
   CLOSE(51)
!write(*,*) 'here'
!  WRITE(6,'(A)') 'UNSORTED EPSILON'
!  CALL DUMP16(LARGEEPS,N,1)
!  WRITE(6,'(A)') 'UNSORTED 0TH-ORDER V MATRIX'
!  CALL DUMP5(LARGEVMAT,N)

   ! FORM DEGENERACY PATTERN 
   ALLOCATE(GROUPSIZE(N),GROUPMEMS(N,N),LTAKEN(N))
   LTAKEN=.FALSE.
   NGROUPS=0
   DO IA=1,N
    IF (.NOT.LTAKEN(IA)) THEN
     NGROUPS=NGROUPS+1
     GROUPSIZE(NGROUPS)=1
     GROUPMEMS(1,NGROUPS)=IA
     LTAKEN(IA)=.TRUE.
     IF (IA < N) THEN
      DO IB=IA+1,N
!      IF ((DABS(LARGEEPS(IB)-LARGEEPS(IA)) < TOL).AND.(DABS(LARGEVMAT(IB,IA)) > TOL)) THEN
       IF (DABS(LARGEEPS(IB)-LARGEEPS(IA)) < TOL) THEN
        GROUPSIZE(NGROUPS)=GROUPSIZE(NGROUPS)+1
        GROUPMEMS(GROUPSIZE(NGROUPS),NGROUPS)=IB
        LTAKEN(IB)=.TRUE.
       ENDIF
      ENDDO
     ENDIF
    ENDIF
   ENDDO

!  WRITE(6,'(/,A,I3)') 'NUMBER OF STATE GROUPS =',NGROUPS
   ID=0
   DO IA=1,NGROUPS
!   WRITE(6,'(/,A,I3,A,20I10:)') ' GROUP',IA,':',(GROUPMEMS(IB,IA),IB=1,GROUPSIZE(IA))
!   WRITE(6,'(A,20F10.5:)') ' <H0>     ',(LARGEEPS(GROUPMEMS(IB,IA)),IB=1,GROUPSIZE(IA))
    ID=ID+GROUPSIZE(IA)
    ALLOCATE(AMAT(GROUPSIZE(IA),GROUPSIZE(IA)))
    DO IB=1,GROUPSIZE(IA)
     DO IC=1,GROUPSIZE(IA)
      AMAT(IC,IB)=LARGEVMAT(GROUPMEMS(IC,IA),GROUPMEMS(IB,IA))
     ENDDO
    ENDDO
!   WRITE(6,'(/,A)') 'MINI V MATRIX'
!   CALL DUMP5(AMAT,GROUPSIZE(IA))
    DEALLOCATE(AMAT)
   ENDDO
!  WRITE(6,'(/)') 
   IF (ID/=N) CALL PABORT('A BUG')
   DEALLOCATE(LTAKEN,T1,T2,T3) 

   ! LOOP OVER GROUPS
   DO IG=1,NGROUPS
!  DO IG=3,3



   ! INDENTATION SUPPRESSED




!  WRITE(6,'(/,A,20A10:)') '---------',('----------',IB=1,GROUPSIZE(IG))
!  WRITE(6,'(A,I3,A,20I10:)') 'GROUP',IG,':',(GROUPMEMS(IB,IG),IB=1,GROUPSIZE(IG))
!  WRITE(6,'(A,20F10.5:)') '<H0>     ',(LARGEEPS(GROUPMEMS(IB,IG)),IB=1,GROUPSIZE(IG))
!  WRITE(6,'(A,20A10:)') '---------',('----------',IB=1,GROUPSIZE(IG))
    
   NG=GROUPSIZE(IG)
   ALLOCATE(BAS(N,NG,0:ORDER,0:ORDER))
   ALLOCATE(HEFF(NG,NG),RHS91(N,NG),AMAT(NG,NG),MAP(NG))
   ALLOCATE(VR(NG,NG),VL(1,NG),ER(NG),EI(NG),WK(4*NG))
   ALLOCATE(LTAKEN(NG))
   ALLOCATE(LDEGEN(NG,NG,0:ORDER),LNONDEG(NG,0:ORDER),NDEGEN(NG,0:ORDER))
   ALLOCATE(EPS(NG,0:ORDER))
   ALLOCATE(MAPG(NG,2))

   DO IC=1,NG
    DO IA=1,NCF
     DO IB=1,EA_NCF
      IF ((IA-1)*EA_NCF+IB==GROUPMEMS(IC,IG)) THEN
       MAPG(IC,1)=IA
       MAPG(IC,2)=IB
      ENDIF
     ENDDO
    ENDDO
!   write(*,*) ic,mapg(ic,1),mapg(ic,2)
   ENDDO
   EPS=1.0D99 ! safety
   DO IA=1,NG
    EPS(IA,0)=LARGEEPS(GROUPMEMS(IA,IG))
   ENDDO

   ! FORM ZEROTH-ORDER BASIS 
   BAS=1.0D99 ! safety
   BAS(:,:,0,0)=0.0D0
   DO IA=1,NG
    BAS(GROUPMEMS(IA,IG),IA,0,0)=1.0D0 ! BASIS
   ENDDO
!  WRITE(6,'(A)') 'UNSORTED 0TH-ORDER BASIS'
!  CALL DUMP16(BAS(:,:,0,0),N,NG)
!  WRITE(6,'(A)') 'UNSORTED 0TH-ORDER EPSILON'
!  CALL DUMP16(EPS(:,0),NG,1)

   ! FORM LDEGEN ! true if belongs to [n]q ; false if belongs to [n]k
   DO IA=1,NG
    DO IB=1,NG
     LDEGEN(IB,IA,0)=.TRUE.
     IF (DABS(EPS(IA,0)-EPS(IB,0)) > TOL) CALL PABORT('A BUG 1')
!    IF (DABS(LARGEVMAT(GROUPMEMS(IA,IG),GROUPMEMS(IB,IG))) < TOL) CALL PABORT('A BUG 2')
    ENDDO
   ENDDO

   ! FORM ZEROTH-ORDER ENERGIES
!  WRITE(6,'(/,A)') 'ZEROTH-ORDER ENERGIES'
!  WRITE(6,'(A)') '---------------------------------------------------------------------------'
!  WRITE(6,'(A)') 'STATE       CORRELATION        TOTAL ENERGY         SELF-ENERGY   CPU / SEC'
   DO IA=1,NG
    DMP(GROUPMEMS(IA,IG),0)=EPS(IA,0)
    EMP(GROUPMEMS(IA,IG),0)=EMP(GROUPMEMS(IA,IG),0)+DMP(GROUPMEMS(IA,IG),0)
    SIGMA(GROUPMEMS(IA,IG),0)=EMP(GROUPMEMS(IA,IG),0)-MP_STORED(0)
!   IF (.NOT.SILENT) WRITE(6,'(I3,F20.10,2F20.10,F12.1)') &
!    IA,DMP(GROUPMEMS(IA,IG),0),EMP(GROUPMEMS(IA,IG),0),SIGMA(GROUPMEMS(IA,IG),0),0.0
   ENDDO
!  IF (.NOT.SILENT) WRITE(6,'(A)') '---------------------------------------------------------------------------'

   ! CHECK IF THE DEGENERECY IS RESOLVED FOR EACH STATE
   DO IA=1,NG
    LNONDEG(IA,0)=.TRUE.
    DO IB=1,NG
     IF (IB==IA) CYCLE
     IF (LDEGEN(IB,IA,0)) LNONDEG(IA,0)=.FALSE.
    ENDDO
!   IF (LNONDEG(IA,IORDER-1)) WRITE(6,'(A,I3,A)') 'STATE',IA,' IS NON-DEGENERATE'
   ENDDO

   ! SORT AND PRINT EPSILON AND DEGENERACY
!  WRITE(6,'(/,A,10(A,I3,A):)') 'STATE',('    ORDER',IB,'  ',IB=0,0)
   LTAKEN=.FALSE.
   DO IA=1,NG
    E1=1.0D99
    DO IB=1,NG
     IF ((EPS(IB,0) < E1).AND.(.NOT.LTAKEN(IB))) THEN
      E1=EPS(IB,0)
      IC=IB
     ENDIF
    ENDDO
    LTAKEN(IC)=.TRUE.
!   WRITE(6,'(I3,2X,10(F12.6,L2):)') IC,(EPS(IC,IB),LNONDEG(IC,IB),IB=0,0)
   ENDDO

   DO IORDER=1,ORDER

!   WRITE(6,'(A,I3)') 'ORDER =',IORDER

    ! FORM HEFF
    HEFF=0.0D0
    DO IA=1,NG
     DO IB=1,NG
       IF (LDEGEN(IB,IA,IORDER-1)) THEN
        IF (IORDER > 1) THEN
         ! t=1
         DO IC=1,N
          DO ID=1,N
           HEFF(IB,IA)=HEFF(IB,IA)+BAS(IC,IB,0,IORDER-1)*LARGEVMAT(IC,ID)*BAS(ID,IA,IORDER-1,IORDER-1)
          ENDDO
         ENDDO
         ! t=1,n-1
         DO T=1,IORDER-1
          DO IC=1,N
!          E1=0.0D0
!          DO ID=1,N
!           E1=E1+BAS(ID,IC,0,T)*BAS(ID,IA,IORDER-T,IORDER-1)
!          ENDDO
!          E2=0.0D0
!          DO ID=1,N
!           E2=E2+BAS(ID,IC,0,T)*BAS(ID,IB,0,IORDER-1)
!          ENDDO
!          HEFF(IB,IA)=HEFF(IB,IA)-EPS(IC,T)*E1*E2
           HEFF(IB,IA)=HEFF(IB,IA)-EPS(IA,T)*BAS(IC,IB,0,IORDER-1)*BAS(IC,IA,IORDER-T,IORDER-1)
          ENDDO
         ENDDO
        ELSE
         ! n=1
         DO IC=1,N
          DO ID=1,N
           HEFF(IB,IA)=HEFF(IB,IA)+BAS(IC,IB,0,IORDER-1)*LARGEVMAT(IC,ID)*BAS(ID,IA,0,IORDER-1)
          ENDDO
         ENDDO
        ENDIF
!      IF (IORDER==1) THEN
!       DO IC=1,N
!        DO ID=1,N
!         HEFF(IB,IA)=HEFF(IB,IA)+BAS(IC,IB,0,0)*VMAT(IC,ID)*BAS(ID,IA,0,0) ! the second term in Eq.(88)
!        ENDDO
!       ENDDO
!      ENDIF
!      IF (IORDER>=2) THEN
!       DO IC=1,N
!        DO ID=1,N
!         HEFF(IB,IA)=HEFF(IB,IA)+BAS(IC,IB,0,IORDER-1)*VMAT(IC,ID)*BAS(ID,IA,IORDER-1,IORDER-1) ! t=1 in Eq.(88)
!        ENDDO
!        HEFF(IB,IA)=HEFF(IB,IA)-BAS(IC,IB,0,IORDER-1)*EPS(IC,1)*BAS(IC,IA,IORDER-1,IORDER-1)    ! t=1 in Eq.(88)
!       ENDDO
!      ENDIF
!      IF (IORDER>=3) THEN
!       DO JORDER=2,IORDER-1
!        DO IC=1,N
!         HEFF(IB,IA)=HEFF(IB,IA)-BAS(IC,IB,0,IORDER-1)*EPS(IC,1)*BAS(IC,IA,IORDER-JORDER,IORDER-1) ! t=JORDER in Eq.(88)
!        ENDDO
!       ENDDO
!      ENDIF
      ENDIF
     ENDDO
    ENDDO
!   WRITE(6,'(A,I3)') 'EFFECTIVE HAMILTONIAN, ORDER=',IORDER
!   CALL DUMP5(HEFF,NG)

    ! DIAGONALIZE HEFF
    CALL DGEEV('N','V',NG,HEFF,NG,ER,EI,VL,1,VR,NG,WK,4*N,INFO)
    IF (INFO /= 0) CALL PABORT('DGEEV FAILED TO DIAGONALIZE A MATRIX')
    E1=0.0D0
    DO IA=1,NG
     E1=E1+EI(IA)**2
!write(*,*) IA,ER(IA)
!call dump16(vr(:,IA),N,1)
    ENDDO
    IF (E1 > 1.0E-5) THEN
     CALL WARNING('THE IMAGINARY PART OF THE EIGENVALUES IS NOT ZERO')
    ENDIF
!   CALL PIKSRT(N,N,ER,VR,EI)
!call dump16(ER,N,1)
!call dump5(vr,N)

    ! ORTHONORMALIZE NEW BASIS
    DO IA=1,NG
     E1=0.0D0
     DO IB=1,NG
      E1=E1+VR(IB,IA)*VR(IB,IA)
     ENDDO
     E1=DSQRT(E1)
     DO IB=1,NG
      VR(IB,IA)=VR(IB,IA)/E1
     ENDDO
    ENDDO
    DO IA=1,NG
     IF (IA < NG) THEN
      DO IB=IA+1,NG
       E1=0.0D0
       DO IC=1,NG
        E1=E1+VR(IC,IB)*VR(IC,IA)
       ENDDO
       DO IC=1,NG
        VR(IC,IA)=VR(IC,IA)-E1*VR(IC,IB)
       ENDDO
      ENDDO
     ENDIF
     E1=0.0D0
     DO IB=1,NG
      E1=E1+VR(IB,IA)*VR(IB,IA)
     ENDDO
     E1=DSQRT(E1)
     DO IB=1,NG
      VR(IB,IA)=VR(IB,IA)/E1
     ENDDO
!write(*,*) IA,ER(IA)
!call dump16(vr(:,IA),NG,1)
    ENDDO

!   WRITE(6,'(/,A)') 'EIGENVALUES BEFORE STATE-MATCHING'
!   CALL DUMP16(ER,NG,1)
!   WRITE(6,'(/,A)') 'EIGENVECTORS BEFORE STATE-MATCHING'
!   CALL DUMP5(VR,NG)

    ! SORT EIGENVALUES AND EIGENVECTORS BASED ON OVERLAP
    LTAKEN=.FALSE.
    DO IA=1,NG
     E2=0.0D0
     ID=-1
     DO IB=1,NG
      E1=VR(IB,IA)**2
!     E1=0.0D0
!     DO IC=1,NG
!      E1=E1+VR(IC,IA)*BAS(IC,IB,0,0)
!     ENDDO
      IF ((DABS(E1) > E2).AND.(.NOT.LTAKEN(IB))) THEN
       E2=DABS(E1)
       ID=IB
      ENDIF
     ENDDO
     IF (E2==0.0D0) CALL PABORT('NO MATCH')
!    ID=IA
     LTAKEN(ID)=.TRUE.
     EPS(ID,IORDER)=ER(IA)
     MAP(IA)=ID
    ENDDO
!   WRITE(6,'(A)') 'SORTING MAP'
!   DO IA=1,NG
!    WRITE(6,'(I3,A,I3)') IA,'->',MAP(IA)
!   ENDDO
!   WRITE(6,'(/,A)') 'MATCHED EPSILONS (ORDER IS SHIFTED BY 1)'
!   CALL DUMP16(EPS,NG,ORDER+1)

    ! FORM LDEGEN ! true if belongs to [n]q ; false if belongs to [n]k
    DO IA=1,NG
     DO IB=1,NG
      LDEGEN(IB,IA,IORDER)=.TRUE.
      DO JORDER=0,IORDER
       IF (DABS(EPS(IA,JORDER)-EPS(IB,JORDER)) > TOL) LDEGEN(IB,IA,IORDER)=.FALSE.
!      IF ((DABS(EPS(IA,JORDER)-EPS(IB,JORDER)) > TOL).OR.(DABS(VMAT(IA,IB)) < TOL)) &
!       LDEGEN(IB,IA,IORDER)=.FALSE.
      ENDDO
     ENDDO
    ENDDO

    ! CHECK IF THE DEGENERECY IS RESOLVED FOR EACH STATE
    DO IA=1,NG
     LNONDEG(IA,IORDER)=.TRUE.
     DO IB=1,NG
      IF (IB==IA) CYCLE
      IF (LDEGEN(IB,IA,IORDER)) LNONDEG(IA,IORDER)=.FALSE.
     ENDDO
!    IF (LNONDEG(IA,IORDER-1)) WRITE(6,'(A,I3,A)') 'STATE',IA,' IS NON-DEGENERATE'
    ENDDO

    ! SORT AND PRINT EPSILON AND DEGENERACY
!   WRITE(6,'(/,A,10(A,I3,A):)') 'STATE',('    ORDER',IB,'  ',IB=0,IORDER)
    LTAKEN=.FALSE.
    DO IA=1,NG
     E1=1.0D99
     DO IB=1,NG
      IF ((EPS(IB,0) < E1).AND.(.NOT.LTAKEN(IB))) THEN
       E1=EPS(IB,0)
       IC=IB
      ENDIF
     ENDDO
     LTAKEN(IC)=.TRUE.
!    WRITE(6,'(I3,2X,10(F12.6,L2):)') IC,(EPS(IC,IB),LNONDEG(IC,IB),IB=0,IORDER)
    ENDDO

!amat=0.0d0
!do ia=1,n
! amat(ia,ia)=eps(ia,iorder)
!enddo
!do ia=1,n
! do ib=1,n
!  if (ldegen(ia,ib,iorder-1).and.(.not.ldegen(ia,ib,iorder))) amat(ib,ia)=1.0d99
!  if (ldegen(ia,ib,iorder).and.(ia/=ib)) amat(ib,ia)=99.999999d0
! enddo
!enddo
!write(*,'(a,i1,a)') '[',iorder,']k/q MAP (**** = k; 99.999 = q)'
!call dump5(amat,n)
 
    DO M=0,IORDER-1 ! m of Eq.(91)
     RHS91=0.0D0

     ! Form RHS of Eq.(91) and (90)
     DO IA=1,NG
      DO IB=1,N
       ! Form [...] in RHS of Eq.(91) and also first factor in Eq.(90)
       RHS91(IB,IA)=BAS(IB,IA,M,IORDER-1) ! Eq.(90) and first term of Eq.(91)
      ENDDO
     ENDDO

     ! Second term of Eq.(91)
     IF (M >= 1) THEN
      DO P=0,M-1 ! p of Eq.(91)
       ! Form A of Eq.(92)
       DO IA=1,NG
        DO IB=1,NG
         AMAT(IB,IA)=0.0D0
         IF (LDEGEN(IB,IA,IORDER-M+P-1).AND.(.NOT.LDEGEN(IB,IA,IORDER-M+P))) THEN ! IB belongs to [n-m+p]k
          ! t=1 of Eq.(92)
          DO IC=1,N  
           DO ID=1,N  
            AMAT(IB,IA)=AMAT(IB,IA)+BAS(IC,IB,0,IORDER-M+P)*LARGEVMAT(IC,ID)*BAS(ID,IA,IORDER-1,IORDER-1)
           ENDDO
          ENDDO
          DO T=1,IORDER ! t >=1 of Eq.(92)
!          DO IC=1,N  
!           E1=0.0D0
!           DO ID=1,N
!            E1=E1+BAS(ID,IC,0,T)*BAS(ID,IA,IORDER-T,IORDER-1)
!           ENDDO
!           E2=0.0D0
!           DO ID=1,N
!            E2=E2+BAS(ID,IC,0,T)*BAS(ID,IB,0,IORDER-M+P)
!           ENDDO
!           AMAT(IB,IA)=AMAT(IB,IA)-EPS(IC,T)*E1*E2
!          ENDDO
           DO IC=1,N
            AMAT(IB,IA)=AMAT(IB,IA)-BAS(IC,IB,0,IORDER-M+P)*EPS(IA,T)*BAS(IC,IA,IORDER-T,IORDER-1)
           ENDDO
!          WRITE(6,'(A)') ' ---------- AMAT INVOLVED EPS'
          ENDDO
         ENDIF
        ENDDO
       ENDDO
       ! Check symmetry of A
!      DO IA=1,N
!       DO IB=1,N
!        IF (DABS(AMAT(IA,IB)-AMAT(IB,IA)) > TOL) THEN
!         WRITE(6,'(A)') '******************************* AMAT NON-SYMMETRIC'
!         CALL DUMP5(AMAT,N)
!         CALL PABORT('A MATRIX NON-SYMMETRIC')
!        ENDIF
!       ENDDO
!      ENDDO
!if (iorder==2) then
!write(*,*) 'M,P=',M,P
!write(*,*) 'AMAT'
!call dump5(amat,n)
!endif
       ! Apply fancy epsilon operator (higher-order resolvent) of Eq.(91)
       DO IA=1,NG
        DO IB=1,N 
         DO IC=1,NG
!         IF (LDEGEN(IC,IA,IORDER-M+P-1).AND.(.NOT.LDEGEN(IC,IA,IORDER-M+P))) THEN ! IC belongs to [n-m+p]k
           IF (DABS(EPS(IA,IORDER-M+P)-EPS(IC,IORDER-M+P)) < TOL) THEN
            IF (DABS(AMAT(IC,IA)) > TOL) WRITE(6,'(A,2I3,F15.10)') '*** EQ.91 DIVISION BY ZERO AT',IC,IA,AMAT(IC,IA)
           ELSE
            RHS91(IB,IA)=RHS91(IB,IA)+BAS(IB,IC,P,IORDER-M+P)*AMAT(IC,IA)/(EPS(IA,IORDER-M+P)-EPS(IC,IORDER-M+P))
           ENDIF
!         ENDIF
         ENDDO
        ENDDO
       ENDDO
      ENDDO
     ENDIF

     ! Eq.(91) second line
     DO IA=1,NG
      DO IB=1,N                  ! IB = determinant index
       BAS(IB,MAP(IA),M,IORDER)=0.0D0 ! MAP(IA) = l of Eq.(91) ... TO HERE (DO NOT DESTROY ID)
       DO IC=1,NG                      ! Q = q of Eq.(91)
!       IF (LDEGEN(Q,MAP(IA),IORDER-1)) BAS(IB,MAP(IA),M,IORDER)=BAS(IB,MAP(IA),M,IORDER)+RHS91(IB,Q)*VR(Q,IA)
        BAS(IB,MAP(IA),M,IORDER)=BAS(IB,MAP(IA),M,IORDER)+RHS91(IB,IC)*VR(IC,IA)
       ENDDO
      ENDDO
     ENDDO
    ENDDO
!   DO M=0,IORDER-1
!    WRITE(6,'(/,A,I3,A,I3,A)') '(',M,')[',IORDER,']-TH BASIS'
!    CALL DUMP5(BAS(:,:,M,IORDER),N)
!   ENDDO

    ! FORM HIGHEST-ORDER BASIS ! Eq.(94) of Hirschfelder-Certain
! test
!   DO IA=1,N
!    DO IB=1,N
!     HEFF(IB,IA)=0.0D0
!     DO IC=1,N
!      HEFF(IB,IA)=HEFF(IB,IA)+VMAT(IB,IC)*BAS(IC,IA,0,1)
!     ENDDO
!     HEFF(IB,IA)=HEFF(IB,IA)-EPS(IA,1)*BAS(IB,IA,0,1)
!    ENDDO
!   ENDDO
!   WRITE(*,*) '(H(1)-E(1)) Phi(1)'
!   CALL DUMP5(HEFF,N)
!   STOP
! end test
    ! FORM RIGHT-HAND SIDE
    ! t=1 V contribution
    DO IA=1,NG
     DO IB=1,N
      RHS91(IB,IA)=0.0D0
!     BAS(IB,IA,IORDER,IORDER)=0.0D0
      DO IC=1,N
       RHS91(IB,IA)=RHS91(IB,IA)+LARGEVMAT(IB,IC)*BAS(IC,IA,IORDER-1,IORDER)
!      BAS(IB,IA,IORDER,IORDER)=BAS(IB,IA,IORDER,IORDER)+VMAT(IB,IC)*BAS(IC,IA,IORDER-1,IORDER)
      ENDDO
     ENDDO
    ENDDO
    DO T=1,IORDER ! T=t in Eq.83
     DO IA=1,NG
      DO IB=1,N
!      DO IC=1,N
!       E1=0.0D0
!       DO ID=1,N
!        E1=E1+BAS(ID,IC,0,T)*BAS(ID,IA,IORDER-T,IORDER)
!       ENDDO
!       RHS91(IB,IA)=RHS91(IB,IA)-E1*EPS(IA,T)*BAS(IB,IC,0,T)
!      ENDDO
       RHS91(IB,IA)=RHS91(IB,IA)-EPS(IA,T)*BAS(IB,IA,IORDER-T,IORDER)
!      BAS(IB,IA,IORDER,IORDER)=BAS(IB,IA,IORDER,IORDER)-EPS(IA,T)*BAS(IB,IA,IORDER-T,IORDER)
      ENDDO
     ENDDO 
    ENDDO
!   WRITE(6,'(A)') 'RIGHT BEFORE RESOLVENT'
!   CALL DUMP16(RHS91,N,NG)
    ! APPLY RESOLVENT -- MOMENT OF TRUTH!
    DO IA=1,NG
     DO IB=1,N
      IF (DABS(EPS(IA,0)-LARGEEPS(IB)) < TOL) THEN
!      IF (DABS(RHS91(IB,IA)) > TOL) CALL WARNING('DIVISION BY ZERO')
       BAS(IB,IA,IORDER,IORDER)=0.0D0
      ELSE
       BAS(IB,IA,IORDER,IORDER)=RHS91(IB,IA)/(EPS(IA,0)-LARGEEPS(IB))
      ENDIF
     ENDDO
    ENDDO
!   WRITE(6,'(A,I3)') 'HIGHEST-ORDER BASIS, ORDER=',IORDER
!   CALL DUMP16(BAS(:,:,IORDER,IORDER),N,NG)
!   ! ORTHOGONALIZATION AS PER Eq.85
!   DO IA=1,NG
!    DO IB=1,NG
!     E1=0.0D0
!     DO IC=1,N
!      E1=E1+BAS(IC,IB,0,0)*BAS(IC,IA,IORDER,IORDER)
!     ENDDO
!     DO IC=1,N
!      BAS(IC,IA,IORDER,IORDER)=BAS(IC,IA,IORDER,IORDER)-E1*BAS(IC,IB,0,0)
!     ENDDO
!    ENDDO
!   ENDDO

!write(6,'(A,i3,a)') 'STATE 1 (m)[',iorder,'] basis functions'
!write(6,'(10i12:)') (M,m=0,iorder)
!do ia=1,n
! write(6,'(10f12.7:)') (BAS(ia,1,M,IORDER),m=0,iorder)
!enddo

!write(6,'(A,i3,a)') 'STATE 3 (m)[',iorder,'] basis functions'
!write(6,'(10i12:)') (M,m=0,iorder)
!do ia=1,n
! write(6,'(10f12.7:)') (BAS(ia,3,M,IORDER),m=0,iorder)
!enddo

!write(6,'(A,i3,a)') 'STATE 6 (m)[',iorder,'] basis functions'
!write(6,'(10i12:)') (M,m=0,iorder)
!do ia=1,n
! write(6,'(10f12.7:)') (BAS(ia,6,M,IORDER),m=0,iorder)
!enddo

    ! ORTHOGONALITY CHECK Eq.84,85
    DO M=0,IORDER
     DO IA=1,NG
      DO IB=1,NG
       AMAT(IB,IA)=0.0D0
       DO IC=1,N
        AMAT(IB,IA)=AMAT(IB,IA)+BAS(IC,IB,0,IORDER-M)*BAS(IC,IA,M,IORDER)
       ENDDO
      ENDDO
     ENDDO
     DO IA=1,NG
      DO IB=1,NG
       IF (M==0) THEN
        IF ((IA==IB).AND.(DABS(AMAT(IB,IA)-1.0D0) > TOL)) THEN
         WRITE(6,'(/,A,I3,A,I3,A,I3,A)') '<(0)[',IORDER-M,']|(',M,')[',IORDER,']>'
         CALL DUMP5(AMAT,NG)
         CALL PABORT('NON ORTHONORMAL 84 DIAG')
        ENDIF
        IF ((IA/=IB).AND.(DABS(AMAT(IB,IA)-0.0D0) > TOL)) THEN
         WRITE(6,'(/,A,I3,A,I3,A,I3,A)') '<(0)[',IORDER-M,']|(',M,')[',IORDER,']>'
         CALL DUMP5(AMAT,NG)
         CALL PABORT('NON ORTHONORMAL 84 OFF DIAG')
        ENDIF
       ELSE 
        IF ((LDEGEN(IA,IB,IORDER-M)).AND.(DABS(AMAT(IB,IA)) > TOL)) THEN
         WRITE(6,'(/,A,I3,A,I3,A,I3,A)') '<(0)[',IORDER-M,']|(',M,')[',IORDER,']>'
!        CALL DUMP5(AMAT,NG)
         WRITE(6,*) AMAT(IB,IA)
         CALL WARNING('NON ORTHONORMAL 85')
        ENDIF
       ENDIF
      ENDDO
     ENDDO
    ENDDO

!   WRITE(6,'(/,I3,A)') IORDER,'TH-ORDER ENERGIES'
!   WRITE(6,'(A)') '---------------------------------------------------------------------------'
!   WRITE(6,'(A)') 'STATE       CORRELATION        TOTAL ENERGY         SELF-ENERGY   CPU / SEC'
    DO IA=1,NG ! LOOP OVER STATE
     DMP(GROUPMEMS(IA,IG),IORDER)=EPS(IA,IORDER)
     EMP(GROUPMEMS(IA,IG),IORDER)=EMP(GROUPMEMS(IA,IG),IORDER-1)+DMP(GROUPMEMS(IA,IG),IORDER)
     SIGMA(GROUPMEMS(IA,IG),IORDER)=EMP(GROUPMEMS(IA,IG),IORDER)-MP_STORED(IORDER)
!    IF (.NOT.SILENT) WRITE(6,'(I3,F20.10,2F20.10,F12.1)') &
!     IA,DMP(GROUPMEMS(IA,IG),IORDER),EMP(GROUPMEMS(IA,IG),IORDER),SIGMA(GROUPMEMS(IA,IG),IORDER),0.0
    ENDDO
!   IF (.NOT.SILENT) WRITE(6,'(A)') '---------------------------------------------------------------------------'

   ENDDO

   ! FIGURE OUT 'r' OF Eq.140
   DO IORDER=0,ORIGINALORDER
    DO IA=1,NG
     IC=0
     DO IB=1,NG
      IF (DABS(EPS(IA,IORDER)-EPS(IB,IORDER)) < TOL) IC=IC+1
     ENDDO
     NDEGEN(IA,IORDER)=IC
    ENDDO
   ENDDO
   DO IORDER=0,ORIGINALORDER
    LNOCHANGE=.TRUE.
    DO IA=1,NG
     IF (NDEGEN(IA,IORDER) > NDEGEN(IA,IORDER+1)) LNOCHANGE=.FALSE.
    ENDDO
    IF (LNOCHANGE) THEN
     IR=IORDER
     EXIT
    ENDIF
   ENDDO
!  WRITE(6,'(/,A,I3)') 'HIRSCHFELDER-CERTAIN R = ',IR

   DO IA=1,NG
!   WRITE(6,'(/,A,I12)')   'ROOT  ',IA
!   WRITE(6,'(A,30I12:)')   'ORDER ',(IB,IB=0,ORIGINALORDER)
!   WRITE(6,'(A,30F12.6:)') 'EPS   ',(EPS(IA,IB),IB=0,ORIGINALORDER)
!   WRITE(6,'(A,30F12.6:)') 'SIGMA ',(SIGMA(GROUPMEMS(IA,IG),IB),IB=0,ORIGINALORDER)
!   WRITE(6,'(A,30I12:)')   'NDEGEN',(NDEGEN(IA,IB),IB=0,ORIGINALORDER)
!   WRITE(6,'(A,30L12:)')   'DEGEN?',(.NOT.LNONDEG(IA,IB),IB=0,ORIGINALORDER)
!   IF (IR > MAXR) CALL PABORT('WAVE FUNCTION NOT CONVERGED; MAXR TOO LOW')
!   WRITE(6,'(/,A,I3,A)') '(n)[',ORIGINALORDER+IR,']-TH BASIS'
!   WRITE(6,'(A,30I12:)') '(n)   ',(IB,IB=0,ORIGINALORDER)
!   DO IC=1,N
!    WRITE(6,'(A,30F12.6:)') '      ',(BAS(IC,IA,IB,ORIGINALORDER+IR),IB=0,ORIGINALORDER)
!   ENDDO
!   WRITE(6,'(A)') ' '

    ! CHECK IF WAVE FUNCTIONS SATISFY REGULAR RSPT RECURSION
    DO IORDER=1,ORIGINALORDER
     DO IB=1,N
      RHS91(IB,IA)=0.0D0
      DO IC=1,N
       RHS91(IB,IA)=RHS91(IB,IA)+LARGEVMAT(IB,IC)*BAS(IC,IA,IORDER-1,ORIGINALORDER+IR)
      ENDDO
     ENDDO
     E1=0.0D0
     DO IB=1,N
      E1=E1+BAS(IB,IA,0,ORIGINALORDER+IR)*RHS91(IB,IA)
     ENDDO
!WRITE(*,*) 'ENERGY',E1
     IF (DABS(E1-EPS(IA,IORDER)) > TOL) THEN
      WRITE(6,*) E1,EPS(IA,IORDER)
      CALL WARNING('ENERGY INCONSISTENCY')
     ENDIF
     DO JORDER=1,IORDER
      DO IB=1,N
       RHS91(IB,IA)=RHS91(IB,IA)-EPS(IA,JORDER)*BAS(IB,IA,IORDER-JORDER,ORIGINALORDER+IR)
      ENDDO
     ENDDO
!WRITE(*,*) 'RIGHT-HAND SIDE'
!DO IB=1,N
! WRITE(6,'(F12.6)') RHS91(IB,IA)
!ENDDO
     DO IB=1,N
      RHS91(IB,IA)=RHS91(IB,IA)-(EPS(IA,0)-LARGEEPS(IB))*BAS(IB,IA,IORDER,ORIGINALORDER+IR)
!     RHS91(IB,IA)=(EPS(IA,0)-LARGEEPS(IB))*BAS(IB,IA,IORDER,ORIGINALORDER+IR)
     ENDDO
!WRITE(*,*) 'LEFT-HAND SIDE'
!DO IB=1,N
! WRITE(6,'(F12.6)') RHS91(IB,IA)
!ENDDO
     E2=0.0D0
     DO IB=1,N
      E2=E2+RHS91(IB,IA)**2
     ENDDO
     IF (DABS(E2) > TOL) CALL PABORT('INCONSISTENCY 2')
!    WRITE(*,*) 'STATE=',IA,'ORDER=',IORDER,' ENERGY=',E1,' RESIDUAL=',E2
    ENDDO

    ! WRITE TO FILES
    DO IORDER=0,ORIGINALORDER-1
     IF (IORDER==0) THEN
      WRITE(60) SIGMA(GROUPMEMS(IA,IG),0)
     ELSE
      WRITE(60) SIGMA(GROUPMEMS(IA,IG),IORDER)-SIGMA(GROUPMEMS(IA,IG),IORDER-1)
     ENDIF
     WRITE(61) BAS(:,IA,IORDER,ORIGINALORDER+IR)
    ENDDO


   ENDDO

   DEALLOCATE(VR,VL,ER,EI,WK)
   DEALLOCATE(BAS,HEFF,EPS,LTAKEN,LDEGEN,RHS91,AMAT,MAP,LNONDEG,MAPG,NDEGEN)


   ! INDENTATION SUPPRESSED



   ENDDO

   DEALLOCATE(LARGEVMAT,LARGEEPS)
   DEALLOCATE(DMP,EMP,SIGMA)
   CLOSE(60)
   CLOSE(61)

   RETURN
END SUBROUTINE
