SUBROUTINE PCPU_TIME(CPUSEC)
! CALL MACHINE DEPENDENT CPU TIME RETREIVAL SUBROUTINE.
! THIS SUBROUTINE IS FOR IBM MACHINE.

   USE MPI_F08
   USE CONSTANTS

   IMPLICIT NONE
!  INCLUDE "mpif.h"
   DOUBLE PRECISION :: CPUSEC
!  INTEGER :: ICPU,MCLOCK

!--IBM MACHINE
!  ICPU=MCLOCK()
!  CPUSEC=FLOAT(ICPU)/100.0
!  CALL PFLUSH(6)
!--FORTRAN 90 INTRINSIC
!  CALL PCPU_TIME(CPUSEC)
!--MPI WALL TIME
   CPUSEC=MPI_WTIME()
   CALL PFLUSH(6)
   RETURN
END SUBROUTINE



SUBROUTINE PFLUSH(I)

   IMPLICIT NONE
   INTEGER :: I

   CALL FLUSH(I)

   RETURN
END SUBROUTINE
