PROGRAM POLYMER3D
! AB INITIO CRYSTAL ORBITAL PROGRAM FOR INFINITE THREE-DIMENSIONAL CRYSTALS.
! SO HIRATA, UNIVERSITY OF ILLINOIS AT URBANA-CHAMPAIGN, SEPTEMBER 2021.

   ! DECLARATION OF GLOBAL VARIABLES
   USE MPI
   USE CONTROL
   USE STRUCTURE
   USE BASISSET
   USE AUXILIARY
   USE GRADIENT
   USE INTEGRAL
   USE GRADIENT
   USE DFT
   USE MP2GRADIENT
   USE CIS

   ! MPI
   INCLUDE "mpif.h"
   CALL MPI_INIT(IERR)
   CALL MPI_COMM_RANK(MPI_COMM_WORLD,MYID,IERR)
   CALL MPI_COMM_SIZE(MPI_COMM_WORLD,NUMPROCS,IERR)
   IF (NUMPROCS > 99999) CALL PABORT('TOO MANY PROCESSES')
   WRITE(6,'(A,I6,A,I6)') 'PROCESSOR = ',MYID,' / ',NUMPROCS
   CALL MPI_BARRIER(MPI_COMM_WORLD,IERR)

   ! READ INPUT DATA FROM THE STANDARD INPUT
   CALL LEGEND
   CALL READ1

   ! BRANCH ACCORDING TO THE JOBTYPE
   SELECT CASE(IOPTN(7))
    CASE(0)
     IF (MYID == 0) WRITE(6,'(A)') 'A SINGLE-POINT ENERGY CALCULATION WILL BE PERFORMED'
     CALL SINGLEPOINT
    CASE(1)
     IF (MYID == 0) WRITE(6,'(A)') 'A SINGLE-POINT ENERGY GRADIENT CALCULATION WILL BE PERFORMED'
     CALL SINGLEPOINT
    CASE(2)
     IF (MYID == 0) WRITE(6,'(A)') 'A GEOMETRY OPTIMIZATION WILL BE PERFORMED'
     CALL OPTIMIZATION
!   CASE(3)
!    IF (MYID == 0) WRITE(6,'(A)') 'A VIBRATIONAL FREQUENCY CALCULATION WILL BE PERFORMED'
!    CALL FREQUENCY
    CASE DEFAULT
     CALL PABORT("INVALID VALUE FOR 'JOBTYPE'")
   END SELECT

   CALL MPI_FINALIZE(IERR)

END PROGRAM



SUBROUTINE WARNING(COMMENT)
! SHOW WARNINGS AND CONTINUE THE PROGRAM EXECUTION.

   USE MPI

   IMPLICIT NONE
   CHARACTER(*) :: COMMENT

   IF (MYID == 0) WRITE(6,'(A,A)') '***** WARNING : ',COMMENT

   RETURN
END SUBROUTINE



SUBROUTINE PABORT(COMMENT)
! ABORT THE PROGRAM EXECUTION.

   USE MPI
   USE CONTROL

   IMPLICIT NONE
   INCLUDE "mpif.h"
   CHARACTER(*) :: COMMENT

   IF (MYID == 0) WRITE(6,'(A,A)') '***** ABORT : ',COMMENT
   CLOSE(5)
   CLOSE(30)
   IF (.NOT.LOPTN(25)) CLOSE(31)
   IF (LOPTN(33).OR.LOPTN(34)) CLOSE(32)
   IF (LOPTN(34)) THEN
    CLOSE(33)
    CLOSE(34)
    CLOSE(35)
   ENDIF
   IF ((IOPTN(36) > 0).OR.(IOPTN(37) > 0)) THEN
    CLOSE(36)
    CLOSE(37)
   ENDIF

   CALL MPI_FINALIZE(IERR)

   STOP
END SUBROUTINE
