MODULE CONSTANTS
! DEFINE PHYSICAL CONSTANTS AND ATOMIC SYMBOLS.
   IMPLICIT NONE
   INTEGER :: IERR
   INTEGER :: MYID
   INTEGER :: NUMPROCS
   DOUBLE PRECISION,PARAMETER :: PI = 3.14159265358979D0
   DOUBLE PRECISION,PARAMETER :: RTTWO = 1.41421356237309504880D0
   DOUBLE PRECISION,PARAMETER :: ANG_BOHR = 0.529177249D0
   DOUBLE PRECISION,PARAMETER :: RIEMANN_ZETA3 = 1.20205690315032D0
   DOUBLE PRECISION,PARAMETER :: BOLTZMANN = 1.0D0/3.1577464D5
   DOUBLE PRECISION,PARAMETER :: EV = 27.2113957D0
   DOUBLE PRECISION,PARAMETER :: DEBYED = -2.5418D0  ! UNITS FOR DIPOLE MOMENTS
   DOUBLE PRECISION,PARAMETER :: DEBYEQ = -1.34504D0 ! UNITS FOR QUADRUPOLE MOMENTS
   CHARACTER(2),PARAMETER :: CATOM(36) = &
      (/'H ','He','Li','Be','B ','C ','N ','O ','F ','Ne','Na','Mg','Al',&
        'Si','P ','S ','Cl','Ar','K ','Ca','Sc','Ti','V ','Cr','Mn','Fe',&
        'Co','Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr'/)
   CHARACTER(5),PARAMETER :: CNUMBER(10) = &
      (/'  ONE','  TWO','THREE',' FOUR',' FIVE','  SIX','SEVEN','EIGHT',' NINE','  TEN'/)
END MODULE



MODULE CONTROL
! INPUT DATA FOR ALGORITHM CONTROL
   IMPLICIT NONE
   INTEGER :: IOPTN(256)             ! INTEGER ALGORITHM CONTROL VARIABLES
   DOUBLE PRECISION :: DOPTN(256)    ! DOUBLE PRECISION ALGORITHM CONTROL VARIABLES
   CHARACTER(100)   :: COPTN(256)    ! CHARACTER ALGORITHM CONTROL VARIABLES
   LOGICAL :: LOPTN(256)             ! LOGICAL ALGORITHM CONTROL VARIABLES
   LOGICAL :: LDFT,LGC               ! A DFT CALCULATION (LDFT == .TRUE.) / A GRADIENT CORRECTED DFT CALCULATION (LGC == .TRUE.)
END MODULE



MODULE STRUCTURE
! INPUT DATA FOR MOLECULAR STRUCTURES
   IMPLICIT NONE
   INTEGER :: NATOM                                     ! NUMBER OF NUCLEAI
   INTEGER :: CHARGE                                    ! CHARGE (NONZERO VALUE IS VALID ONLY FOR ATOMIC & MOLECULAR CALCULATIONS)
   INTEGER :: ICORE,IVIRTCORE,IOCC                      ! NUMBER OF CORE ORBITALS & OCCUPIED ORBITALS (INCLUDING CORE)
   INTEGER,ALLOCATABLE :: IALL(:,:,:)                   ! NUMBER OF ALL ORBITALS (NORMALLY EQUALS TO NCGS)
   INTEGER :: IALLMAX                                   ! MAXIMUM NUMBER OF ALL ORBITALS (NORMALLY EQUALS TO NCGS)
   INTEGER :: IATOM(256)                                ! ATOMIC NUMBER
   DOUBLE PRECISION :: PERIODX,PERIODY,PERIODZ          ! TRANSLATIONAL PERIODS
   LOGICAL :: LX,LY,LZ                                  ! TRUE IF THE DIMENSION EXISTS
   DOUBLE PRECISION :: HELIX                            ! HELICAL ANGLE (1D ONLY)
   DOUBLE PRECISION :: ATOMX(256),ATOMY(256),ATOMZ(256) ! CARTESIAN COORDINATES OF NUCLEAI
   DOUBLE PRECISION :: FERMI                            ! FERMI ENERGY
END MODULE



MODULE SYMMETRY
! INPUT DATA FOR MOLECULAR POINT SYMMETRY
   IMPLICIT NONE
   INTEGER :: NSYMM                                     ! NUMBER OF IRREDUCIBLE REPRESENTATIONS
   INTEGER :: ISYMM(256,256)                            ! SYMMETRY TABLE
END MODULE



MODULE BASISSET
! BASIS SET DATA
   IMPLICIT NONE
   INTEGER :: NPGS,NCGS ! NUMBER OF PRIMITIVE & CONTRACTED GAUSSIANS
   INTEGER :: NPSHELL   ! NUMBER OF SHELLS
   INTEGER,PARAMETER   :: BASIS_LMAX = 3                   ! MAXIMUM ANGULAR MOMENTUM
   INTEGER,ALLOCATABLE :: PAX(:),PAY(:),PAZ(:)             ! X, Y, Z COMPONENTS OF PRIMITIVE GAUSSIAN ANGULAR MOMENTA
   INTEGER,ALLOCATABLE :: P_SHELL(:,:,:,:),P_SHELL_ANG(:)  ! SHELLS TO PRIMITIVE GAUSSIANS & ANGULAR MOMENTA OF SHELLS
   INTEGER,ALLOCATABLE :: PGS_ATOM(:)                      ! PRIMITIVE GAUSSIANS TO NUCLEI
   DOUBLE PRECISION,ALLOCATABLE :: PGSX(:),PGSY(:),PGSZ(:) ! CARTESIAN COORDINATES OF PRIMITIVE GAUSSIANS
   DOUBLE PRECISION,ALLOCATABLE :: CGSX(:),CGSY(:),CGSZ(:) ! CARTESIAN COORDINATES OF CONTRACTED GAUSSIANS
   DOUBLE PRECISION,ALLOCATABLE :: ZT(:),CC(:,:)           ! EXPONENTS & CONTRACTION COEFFICIENTS
   DOUBLE PRECISION,ALLOCATABLE :: C2S(:,:)                ! CARTERSIAN TO SPHERICAL CONVERSION MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: C2H(:,:,:)              ! CONTRACTED CARTERSIAN TO HELICAL CONVERSION MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: P2H(:,:,:)              ! PRIMITIVE CARTERSIAN TO HELICAL CONVERSION MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: C2H_THETA(:,:,:)        ! CONTRACTED CARTERSIAN TO HELICAL CONVERSION MATRIX DERIV WRT THETA
   DOUBLE PRECISION,ALLOCATABLE :: P2H_THETA(:,:,:)        ! PRIMITIVE CARTERSIAN TO HELICAL CONVERSION MATRIX DERIV WRT THETA
END MODULE



MODULE AUXILIARY
! AUXILIARY BASIS SET DATA
   IMPLICIT NONE
   INTEGER :: NAGS    ! NUMBER OF (UNCONTRACTED) AUXILIARY GAUSSIANS
   INTEGER :: NASHELL ! NUMBER OF SHELLS
   INTEGER,ALLOCATABLE :: AAX(:),AAY(:),AAZ(:)             ! X, Y, Z COMPONENTS OF AUXILIARY GAUSSIAN ANGULAR MOMENTA
   INTEGER,ALLOCATABLE :: A_SHELL(:,:,:,:),A_SHELL_ANG(:)  ! SHELLS TO AUXILIARY GAUSSIANS & ANGULAR MOMENTA OF SHELLS
   INTEGER,ALLOCATABLE :: AGS_ATOM(:)                      ! AUXILIARY GAUSSIANS TO NUCLEI
   DOUBLE PRECISION,ALLOCATABLE :: AGSX(:),AGSY(:),AGSZ(:) ! CARTESIAN COORDINATES OF AUXILIARY GAUSSIANS
   DOUBLE PRECISION,ALLOCATABLE :: AZT(:)                  ! EXPONENTS
   DOUBLE PRECISION,ALLOCATABLE :: ANORM(:)                ! NORMALIZATION COEEFICIENTS
END MODULE



MODULE INTEGRAL
! MOLECULAR INTEGRALS
   IMPLICIT NONE
   INTEGER :: CEL1X,CEL2X,CEL3X
   INTEGER :: CEL1Y,CEL2Y,CEL3Y
   INTEGER :: CEL1Z,CEL2Z,CEL3Z
   INTEGER :: KVCX,KVCY,KVCZ
   INTEGER :: REDUCED_CEL1X,REDUCED_CEL1Y,REDUCED_CEL1Z
   INTEGER :: REDUCED_CEL1X_XC,REDUCED_CEL1Y_XC,REDUCED_CEL1Z_XC
   DOUBLE PRECISION,ALLOCATABLE :: S_P(:,:,:,:,:)                       ! OVERLAP INTEGRAL MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: S_C(:,:,:,:,:)                       ! OVERLAP INTEGRAL MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: F_C(:,:,:,:,:)                       ! FOCK MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: T_C(:,:,:,:,:)                       ! KINETIC INTEGRAL MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: N_C(:,:,:,:,:)                       ! NUCLEAR REPULSION INTEGRAL MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: C_C(:,:,:,:,:)                       ! COULOMB INTEGRAL MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: X_C(:,:,:,:,:)                       ! HF EXCHANGE INTEGRAL MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: O_C(:,:,:,:,:)                       ! OEP INTEGRAL MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: Y_C(:,:,:,:,:)                       ! DFT EXCHANGE-CORRELATION INTEGRAL MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: M_C(:,:,:,:,:,:)                     ! MOMENT INTEGRAL MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: MPE_C(:,:,:,:,:)                     ! MULTIPOLE EXPANSION CORRECTION MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: P_P(:,:,:,:,:)                       ! DENSITY MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: P_C(:,:,:,:,:)                       ! DENSITY MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: P_C_OUT(:,:,:,:,:)                   ! DENSITY MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: W_P(:,:,:,:,:)                       ! ENERGY-WEIGHTED DENSITY MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: W_C(:,:,:,:,:)                       ! ENERGY-WEIGHTED DENSITY MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: P_P_HELIX(:,:,:,:)                   ! DENSITY MATRIX FOR HELIX
   DOUBLE PRECISION,ALLOCATABLE :: P_C_HELIX(:,:,:,:)                   ! DENSITY MATRIX FOR HELIX
   DOUBLE PRECISION,ALLOCATABLE :: W_P_HELIX(:,:,:,:)                   ! ENERGY-WEIGHTED DENSITY MATRIX FOR HELIX
   DOUBLE PRECISION,ALLOCATABLE :: W_C_HELIX(:,:,:,:)                   ! ENERGY-WEIGHTED DENSITY MATRIX FOR HELIX
   DOUBLE PRECISION,ALLOCATABLE :: P_P_HELIX_THETA(:,:,:,:)             ! DENSITY MATRIX FOR HELIX DERIV WRT HELIX
   DOUBLE PRECISION,ALLOCATABLE :: P_C_HELIX_THETA(:,:,:,:)             ! DENSITY MATRIX FOR HELIX DERIV WRT HELIX
   DOUBLE PRECISION,ALLOCATABLE :: W_P_HELIX_THETA(:,:,:,:)             ! ENERGY-WEIGHTED DENSITY MATRIX FOR HELIX DERIV WRT HELIX
   DOUBLE PRECISION,ALLOCATABLE :: W_C_HELIX_THETA(:,:,:,:)             ! ENERGY-WEIGHTED DENSITY MATRIX FOR HELIX DERIV WRT HELIX
   DOUBLE PRECISION,ALLOCATABLE :: EPSILON(:,:,:,:)                     ! ONE-ELECTRON ENERGY
   DOUBLE PRECISION,ALLOCATABLE :: PULAY(:,:)                           ! PULAY MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: QEPSILON(:,:,:,:)                    ! MP2 QUASI-PARTICLE ONE-ELECTRON ENERGY
   DOUBLE PRECISION,ALLOCATABLE :: DEPSILON(:,:,:,:)                    ! DYSON QUASI-PARTICLE ONE-ELECTRON ENERGY
   DOUBLE PRECISION,ALLOCATABLE :: DPOLE(:,:,:,:)                       ! DYSON QUASI-PARTICLE ONE-ELECTRON POLE STRENGTH
   DOUBLE COMPLEX,ALLOCATABLE :: CO(:,:,:,:,:)                          ! CRYSTAL ORBITAL COEFFICIENT
END MODULE



MODULE GRADIENT
! ENERGY GRADIENTS
   IMPLICIT NONE
   DOUBLE PRECISION :: EHFKS,NUCLEAR_REPULSION
   DOUBLE PRECISION :: FORCEX(256),FORCEY(256),FORCEZ(256)
   DOUBLE PRECISION :: FORCETX,FORCETY,FORCETZ,FORCETA
END MODULE



MODULE FMT
! INCOMPLETE GAMMA FUNCTION
   IMPLICIT NONE
   DOUBLE PRECISION,PARAMETER :: TF(0:21) = &
     (/33.0D0,37.0D0,41.0D0,43.0D0,46.0D0,49.0D0,51.0D0,54.0D0,56.0D0, &
       58.0D0,61.0D0,63.0D0,66.0D0,68.0D0,70.0D0,72.0D0,74.0D0,76.0D0, &
       78.0D0,80.0D0,82.0D0,84.0D0/)
   DOUBLE PRECISION :: IGAMMA(0:1700,0:27)
END MODULE



MODULE MULTIPOLE
! DIPOLE AND QUADRUPOLE MOMENTS
   IMPLICIT NONE
   INTEGER,PARAMETER :: HUGECELL = 10000
   DOUBLE PRECISION :: DIPOLEX,DIPOLEY,DIPOLEZ
   DOUBLE PRECISION :: QPOLEXX,QPOLEYY,QPOLEZZ,QPOLEXY,QPOLEYZ,QPOLEZX
   DOUBLE PRECISION :: NDIPOLEX,NDIPOLEY,NDIPOLEZ
   DOUBLE PRECISION :: NQPOLEXX,NQPOLEYY,NQPOLEZZ,NQPOLEXY,NQPOLEYZ,NQPOLEZX
   DOUBLE PRECISION :: DIPOLEX_X(256),DIPOLEX_Y(256),DIPOLEX_Z(256),DIPOLEX_TX,DIPOLEX_TA
   DOUBLE PRECISION :: DIPOLEY_X(256),DIPOLEY_Y(256),DIPOLEY_Z(256),DIPOLEY_TX,DIPOLEY_TA
   DOUBLE PRECISION :: DIPOLEZ_X(256),DIPOLEZ_Y(256),DIPOLEZ_Z(256),DIPOLEZ_TX,DIPOLEZ_TA
END MODULE



MODULE DFT
! NUMERICAL QUADRUTURE USED IN DFT CALCULATIONS
   IMPLICIT NONE
   INTEGER :: MAXNGRID,MGRID
   INTEGER,ALLOCATABLE :: NGRID(:)
   DOUBLE PRECISION,ALLOCATABLE :: GRIDX(:,:),GRIDY(:,:),GRIDZ(:,:),GRIDW(:,:)    ! CARTESIAN COORDINATES & BECKE WEIGHTS FOR GRID POINTS
   DOUBLE PRECISION,ALLOCATABLE :: GRIDW_X(:,:,:),GRIDW_Y(:,:,:),GRIDW_Z(:,:,:)   ! GRID WEIGHT DERIVATIVES WRT ATOMIC X,Y,Z
   DOUBLE PRECISION,ALLOCATABLE :: GRIDW_TX(:,:),GRIDW_TY(:,:),GRIDW_TZ(:,:)      ! GRID WEIGHT DERIVATIVES WRT TRANSLATION X,Y,Z
   DOUBLE PRECISION,ALLOCATABLE :: GRIDW_TA(:,:)                                  ! GRID WEIGHT DERIVATIVES WRT HELICAL ANGLE
!  DOUBLE PRECISION,ALLOCATABLE :: GRIDXA(:),GRIDYA(:),GRIDZA(:),GRIDWA(:)        ! CARTESIAN COORDINATES & BECKE WEIGHTS FOR GRID POINTS
   DOUBLE PRECISION,ALLOCATABLE :: FUZZY(:,:),ATOMW(:,:)                          ! A FUZZY CELL WEIGHT FUNCTION
   DOUBLE PRECISION,ALLOCATABLE :: RHO(:,:)                                       ! ELECTRON DENSITY
!  DOUBLE PRECISION,ALLOCATABLE :: RHO_GTX(:,:),RHO_GTY(:,:),RHO_GTZ(:,:)         ! ELECTRON DENSITY TRANSLATION GRADIENTS
!  DOUBLE PRECISION,ALLOCATABLE :: RHO_GTA(:,:)                                   ! ELECTRON DENSITY HELICAL GRADIENT
   DOUBLE PRECISION,ALLOCATABLE :: RHO_GX(:,:),RHO_GY(:,:),RHO_GZ(:,:)            ! ELECRTRON DENSITY GRADIENTS
!  DOUBLE PRECISION,ALLOCATABLE :: RHO_GX_A(:,:),RHO_GY_A(:,:),RHO_GZ_A(:,:)      ! ELECRTRON DENSITY GRADIENTS HELIX DERIV
   DOUBLE PRECISION,ALLOCATABLE :: GAMMA(:,:)                                     ! ELECRTRON DENSITY GRADIENT INVARIANT
   DOUBLE PRECISION,ALLOCATABLE :: D1F1(:,:),D1F2(:,:),XCF(:,:)                   ! FUNCTIONAL VALUES & FUNCTIONAL FIRST DERIVATIVES
   DOUBLE PRECISION,ALLOCATABLE :: D2F1(:,:),D2F2(:,:),D2F3(:,:)                  ! FUNCTIONAL SECOND DERIVATIVES
   DOUBLE COMPLEX,ALLOCATABLE :: TRHO(:,:),TRHO_GX(:,:),TRHO_GY(:,:),TRHO_GZ(:,:) ! TRIAL ELECTRON DENSITY & ITS GRADIENTS
END MODULE



MODULE MP2GRADIENT
! SKELETON (CORE) DERIVATIVE MATRICES, CPHF SOLUTION VECTORS, ETC. FOR ANALYTICAL MP2 GRADIENT EVALUATION
   IMPLICIT NONE
   DOUBLE COMPLEX,ALLOCATABLE :: SMN(:,:,:,:,:,:) ! SKELETON (CORE) OVERLAP INTEGRAL DERIVATIVE MATRIX
   DOUBLE COMPLEX,ALLOCATABLE :: HMN(:,:,:,:,:,:) ! SKELETON (CORE) ONE-ELECTRON INTEGRAL DERIVATIVE MATRIX
   DOUBLE COMPLEX,ALLOCATABLE :: JMN(:,:,:,:,:,:) ! SKELETON (CORE) TWO-ELECTRON INTEGRAL DERIVATIVE MATRIX
   DOUBLE COMPLEX,ALLOCATABLE :: FMN(:,:,:,:,:,:) ! SKELETON (CORE) FOCK INTEGRAL DERIVATIVE MATRIX
END MODULE



MODULE CIS
! CONFIGURATION INTERACTION SINGLES & TIME DEPENDENT RESPONSE THEORY CALCULATIONS
   IMPLICIT NONE
   INTEGER :: NOV                    ! NUMBER OF OCCUPIED STATES TIMES NUMBER OF VIRTUAL STATES
   INTEGER :: NROOTS                 ! NUMBER OF CIS OR TDR ROOTS
   INTEGER :: NTRIALS                ! NUMBER OF TRIAL VECTORS
   INTEGER :: NCONVS                 ! NUMBER OF CONVERGED ROOTS
   INTEGER :: MAXTRIALS              ! MAXIMUM NUMBER OF TRIAL VECTORS ALLOWED BY MAXDISK
   INTEGER,PARAMETER :: MAXITR = 100 ! MAXIMUM NUMBER OF ITERATIONS
   DOUBLE PRECISION,PARAMETER :: THRESH = 0.001D0
END MODULE



MODULE OPTIMIZE
! GEOMETRY OPTIMIZATION
   IMPLICIT NONE
   INTEGER,PARAMETER :: MAXOPTCYCLES = 100
   DOUBLE PRECISION :: ATOMXHIST(256,MAXOPTCYCLES)
   DOUBLE PRECISION :: ATOMYHIST(256,MAXOPTCYCLES)
   DOUBLE PRECISION :: ATOMZHIST(256,MAXOPTCYCLES)
   DOUBLE PRECISION :: ATOMXGRADHIST(256,MAXOPTCYCLES)
   DOUBLE PRECISION :: ATOMYGRADHIST(256,MAXOPTCYCLES)
   DOUBLE PRECISION :: ATOMZGRADHIST(256,MAXOPTCYCLES)
   DOUBLE PRECISION :: PERIODXHIST(MAXOPTCYCLES)
   DOUBLE PRECISION :: PERIODYHIST(MAXOPTCYCLES)
   DOUBLE PRECISION :: PERIODZHIST(MAXOPTCYCLES)
   DOUBLE PRECISION :: PERIODXGRADHIST(MAXOPTCYCLES)
   DOUBLE PRECISION :: PERIODYGRADHIST(MAXOPTCYCLES)
   DOUBLE PRECISION :: PERIODZGRADHIST(MAXOPTCYCLES)
   DOUBLE PRECISION :: HELIXHIST(MAXOPTCYCLES)
   DOUBLE PRECISION :: HELIXGRADHIST(MAXOPTCYCLES)
   DOUBLE PRECISION :: OPTTHRESHOLD
   DOUBLE PRECISION :: RELAX1,RELAX2,RELAX3
   INTEGER :: IMAXGRAD,IMAXGRADXYZ
   INTEGER :: GDIISTERM
END MODULE



MODULE OEP
! OPTIMIZED EFFECTIVE POTENTIAL
   IMPLICIT NONE
   DOUBLE COMPLEX,ALLOCATABLE :: CHI_INVERSE(:,:)
   DOUBLE COMPLEX,ALLOCATABLE :: KERNEL_CORE(:,:)
   DOUBLE PRECISION,ALLOCATABLE :: D1F1_GUESS(:,:)
   DOUBLE PRECISION :: OEPSHIFT
END MODULE



MODULE FULLCI
! FULL AND TRUNCATED CI, GENERAL-ORDER MBPT, AND GENERAL-ORDER CC
   IMPLICIT NONE
   INTEGER :: NCF                             ! NUMBER OF CONFIGURATIONS FOR ALPHA (BETA) ELECTRONS
   INTEGER :: IP_NCF                          ! NUMBER OF CONFIGURATIONS FOR BETA (N-1) ELECTRONS
   INTEGER :: EA_NCF                          ! NUMBER OF CONFIGURATIONS FOR BETA (N+1) ELECTRONS
   DOUBLE PRECISION,ALLOCATABLE :: H(:,:)     ! ONE-ELECTRON PART OF THE HAMILTONIAN IN THE MO BASIS
   DOUBLE PRECISION,ALLOCATABLE :: G(:,:,:,:) ! TWO-ELECTRON PART OF THE HAMILTONIAN IN THE MO BASIS
   DOUBLE PRECISION :: ECC                    ! REFERENCE CC ENERGY
   INTEGER(4),ALLOCATABLE :: CFHALF(:)        ! CONTAINS CONFIGURATIONS AS BIT IN INTEGERS
   INTEGER,ALLOCATABLE :: ADDRSS(:)           ! RETURNS THE ADDRESS OF THE CF FROM THE INTEGER ASSOC WITH THE CF
   INTEGER,ALLOCATABLE :: NORDER(:)           ! NUMBER OF EXCITED ELECTRONS IN THE CF
   INTEGER(4),ALLOCATABLE :: IP_CFHALF(:)     ! CONTAINS CONFIGURATIONS AS BIT IN INTEGERS (N-1 ELECTRONS)
   INTEGER,ALLOCATABLE :: IP_ADDRSS(:)        ! RETURNS THE ADDRESS OF THE CF FROM THE INTEGER ASSOC WITH THE CF (N-1 ELECTRONS)
   INTEGER,ALLOCATABLE :: IP_NORDER(:)        ! NUMBER OF EXCITED ELECTRONS IN THE CF (N-1 ELECTRONS)
   INTEGER(4),ALLOCATABLE :: EA_CFHALF(:)     ! CONTAINS CONFIGURATIONS AS BIT IN INTEGERS (N+1 ELECTRONS)
   INTEGER,ALLOCATABLE :: EA_ADDRSS(:)        ! RETURNS THE ADDRESS OF THE CF FROM THE INTEGER ASSOC WITH THE CF (N+1 ELECTRONS)
   INTEGER,ALLOCATABLE :: EA_NORDER(:)        ! NUMBER OF EXCITED ELECTRONS IN THE CF (N+1 ELECTRONS)
   INTEGER :: N_DEGENERATE_ROOTS,DEGENERATE_ROOTS(10) ! RANK OF DEGENERACY OF THE REFERENCE ROOTS AND THE INDEXES OF THE DEGENERATE ROOTS
   DOUBLE PRECISION,ALLOCATABLE :: MP_STORED(:)       ! ENERGIES OF MP THEORY FOR NEUTRAL
END MODULE



MODULE REL_FULLCI
! FULL AND TRUNCATED CI, GENERAL-ORDER MBPT, AND GENERAL-ORDER CC
   IMPLICIT NONE
   INTEGER :: NCF                             ! NUMBER OF CONFIGURATIONS FOR ALPHA (BETA) ELECTRONS
   INTEGER :: IP_NCF                          ! NUMBER OF CONFIGURATIONS FOR BETA (N-1) ELECTRONS
   INTEGER :: EA_NCF                          ! NUMBER OF CONFIGURATIONS FOR BETA (N+1) ELECTRONS
   DOUBLE COMPLEX,ALLOCATABLE :: H(:,:)       ! ONE-ELECTRON PART OF THE HAMILTONIAN IN THE MO BASIS
   DOUBLE COMPLEX,ALLOCATABLE :: G(:,:,:,:)   ! TWO-ELECTRON PART OF THE HAMILTONIAN IN THE MO BASIS
   DOUBLE COMPLEX :: ECC                      ! REFERENCE CC ENERGY
   INTEGER(4),ALLOCATABLE :: CFHALF(:)        ! CONTAINS CONFIGURATIONS AS BIT IN INTEGERS
   INTEGER,ALLOCATABLE :: ADDRSS(:)           ! RETURNS THE ADDRESS OF THE CF FROM THE INTEGER ASSOC WITH THE CF
   INTEGER,ALLOCATABLE :: NORDER(:)           ! NUMBER OF EXCITED ELECTRONS IN THE CF
   INTEGER(4),ALLOCATABLE :: IP_CFHALF(:)     ! CONTAINS CONFIGURATIONS AS BIT IN INTEGERS (N-1 ELECTRONS)
   INTEGER,ALLOCATABLE :: IP_ADDRSS(:)        ! RETURNS THE ADDRESS OF THE CF FROM THE INTEGER ASSOC WITH THE CF (N-1 ELECTRONS)
   INTEGER,ALLOCATABLE :: IP_NORDER(:)        ! NUMBER OF EXCITED ELECTRONS IN THE CF (N-1 ELECTRONS)
   INTEGER(4),ALLOCATABLE :: EA_CFHALF(:)     ! CONTAINS CONFIGURATIONS AS BIT IN INTEGERS (N+1 ELECTRONS)
   INTEGER,ALLOCATABLE :: EA_ADDRSS(:)        ! RETURNS THE ADDRESS OF THE CF FROM THE INTEGER ASSOC WITH THE CF (N+1 ELECTRONS)
   INTEGER,ALLOCATABLE :: EA_NORDER(:)        ! NUMBER OF EXCITED ELECTRONS IN THE CF (N+1 ELECTRONS)
   DOUBLE PRECISION,ALLOCATABLE :: REPSILON(:,:)
   DOUBLE COMPLEX,ALLOCATABLE :: RHCORE(:,:)
   INTEGER :: N_DEGENERATE_ROOTS,DEGENERATE_ROOTS(10) ! RANK OF DEGENERACY OF THE REFERENCE ROOTS AND THE INDEXES OF THE DEGENERATE ROOTS
END MODULE



MODULE THR_FULLCI
! FULL AND TRUNCATED CI, GENERAL-ORDER MBPT, AND GENERAL-ORDER CC
   IMPLICIT NONE
   DOUBLE PRECISION,ALLOCATABLE :: H(:,:)     ! ONE-ELECTRON PART OF THE HAMILTONIAN IN THE MO BASIS
   DOUBLE PRECISION,ALLOCATABLE :: G(:,:,:,:) ! TWO-ELECTRON PART OF THE HAMILTONIAN IN THE MO BASIS
   INTEGER :: NELE,NELEA,NELEB                ! NUMBER OF ALL, ALPHA, BETA ELECTRONS
   INTEGER :: NCFA,NCFB                       ! NUMBER OF CONFIGURATIONS FOR ALPHA, BETA ELECTRONS
   INTEGER(4),ALLOCATABLE :: CFHALFA(:)       ! CONTAINS CONFIGURATIONS AS BIT IN INTEGERS
   INTEGER,ALLOCATABLE :: ADDRSSA(:)          ! RETURNS THE ADDRESS OF THE CF FROM THE INTEGER ASSOC WITH THE CF
   INTEGER,ALLOCATABLE :: NORDERA(:)          ! NUMBER OF EXCITED ELECTRONS IN THE CF
   INTEGER(4),ALLOCATABLE :: CFHALFB(:)       ! CONTAINS CONFIGURATIONS AS BIT IN INTEGERS
   INTEGER,ALLOCATABLE :: ADDRSSB(:)          ! RETURNS THE ADDRESS OF THE CF FROM THE INTEGER ASSOC WITH THE CF
   INTEGER,ALLOCATABLE :: NORDERB(:)          ! NUMBER OF EXCITED ELECTRONS IN THE CF
   INTEGER :: NALL                            ! NUMBER OF ALL STATES
   DOUBLE PRECISION,ALLOCATABLE :: ALLE(:)    ! ENERGIES OF ALL STATES
   INTEGER,ALLOCATABLE :: ALLN(:)             ! NUMBER OF ELECTRONS OF ALL STATES
   DOUBLE PRECISION,ALLOCATABLE :: ALL_M(:)   ! RHS OF MU RECURSION FOR EACH STATE
   DOUBLE PRECISION,ALLOCATABLE :: ALL_O(:)   ! RHS OF OMEGA RECURSION FOR EACH STATE
   DOUBLE PRECISION,ALLOCATABLE :: ALL_U(:)   ! RHS OF U RECURSION FOR EACH STATE
   DOUBLE PRECISION,ALLOCATABLE :: ALL_S(:)   ! RHS OF S RECURSION FOR EACH STATE
   DOUBLE PRECISION :: ESHIFT                 ! ENERGY SHIFT
   DOUBLE PRECISION,ALLOCATABLE :: E0TEST(:)  ! E(0) FOR COMPARISON PURPOSES
   DOUBLE PRECISION,ALLOCATABLE :: E1TEST(:)  ! E(1) FOR COMPARISON PURPOSES
   DOUBLE PRECISION,ALLOCATABLE :: E2TEST(:)  ! E(2) FOR COMPARISON PURPOSES
   DOUBLE PRECISION,ALLOCATABLE :: E3TEST(:)  ! E(1)**2 FOR COMPARISON PURPOSES
   DOUBLE PRECISION,ALLOCATABLE :: E0TEST2(:) ! E(0) FOR COMPARISON PURPOSES
   DOUBLE PRECISION,ALLOCATABLE :: E1TEST2(:) ! E(1) FOR COMPARISON PURPOSES
   DOUBLE PRECISION,ALLOCATABLE :: E2TEST2(:) ! E(2) FOR COMPARISON PURPOSES
   DOUBLE PRECISION,ALLOCATABLE :: E3TEST2(:) ! E(1)**2 FOR COMPARISON PURPOSES
   DOUBLE PRECISION,ALLOCATABLE :: E2S(:)     ! E(2) SINGLES
   DOUBLE PRECISION,ALLOCATABLE :: E2D(:)     ! E(2) DOUBLES
   DOUBLE PRECISION,ALLOCATABLE :: M_GEN(:)   ! GENERAL-ORDER MU 
   DOUBLE PRECISION,ALLOCATABLE :: O_GEN(:)   ! GENERAL-ORDER OMEGA
   DOUBLE PRECISION,ALLOCATABLE :: U_GEN(:)   ! GENERAL-ORDER U
   DOUBLE PRECISION,ALLOCATABLE :: S_GEN(:)   ! GENERAL-ORDER S
   DOUBLE PRECISION,ALLOCATABLE :: EHC(:,:,:) ! HCPT EFFECTIVE MATRIX 
   DOUBLE PRECISION,ALLOCATABLE :: VHC(:,:,:) ! HCPT WAVE FUNCTIONS
END MODULE



MODULE CARTESIANGRID
! CARTESIAN-GRID-BASED HF AND MP2 CALCULATIONS
   IMPLICIT NONE
   INTEGER :: MAXN 
   INTEGER :: MAXN3
   INTEGER,PARAMETER :: MAXNTRL = 3
   DOUBLE PRECISION :: DELTAH
   DOUBLE PRECISION,ALLOCATABLE :: ORB(:,:,:,:)
   DOUBLE PRECISION,ALLOCATABLE :: OCC(:,:,:,:)
   DOUBLE PRECISION,ALLOCATABLE :: DEL2(:,:,:,:,:,:)
   INTEGER,ALLOCATABLE :: IPIV(:)
END MODULE



MODULE SINANOGLU
! GRID-BASED ATOMIC SINANOGLU CALCULATIONS
   IMPLICIT NONE
   INTEGER :: SALG ! 1: TRAPEZOIDAL; 2: LOGARITHM; 3: BECKE
   INTEGER :: RG, AG                                       ! NUMBER OF RADIAL / ANGULAR GRID POINTS
   INTEGER :: LMAX                                         ! PRINCIPAL ANGULAR MOMENTUM
   INTEGER :: NAO                                          ! NUMBER OF SMALL AO
   INTEGER :: NAO2                                         ! NUMBER OF LARGE AO
   DOUBLE PRECISION,ALLOCATABLE :: FACTORIAL(:)            ! FACTORIAL
   DOUBLE PRECISION,ALLOCATABLE :: SGN(:)                  ! (-1)**I
   DOUBLE PRECISION,ALLOCATABLE :: SG_GAUSS_CHEV(:,:)      ! RADIAL GRID POINTS
   DOUBLE PRECISION,ALLOCATABLE :: SG_GAUSS_CHEV_W(:,:)    ! RADIAL GRID WEIGHTS
   DOUBLE PRECISION,ALLOCATABLE :: SG_LEBEDVX(:)           ! LEBEDEV GRID POINTS
   DOUBLE PRECISION,ALLOCATABLE :: SG_LEBEDVY(:)           ! LEBEDEV GRID POINTS
   DOUBLE PRECISION,ALLOCATABLE :: SG_LEBEDVZ(:)           ! LEBEDEV GRID POINTS
   DOUBLE PRECISION,ALLOCATABLE :: SG_LEBEDVW(:)           ! LEBEDEV GRID WEIGHTS
!  DOUBLE PRECISION,ALLOCATABLE :: R12(:,:,:,:)            ! DISTANCE MATRIX
!  DOUBLE PRECISION,ALLOCATABLE :: RECIPROCALR12(:,:,:,:)  ! RECIPROCAL DISTANCE MATRIX
   DOUBLE PRECISION,ALLOCATABLE :: ORBITALS(:,:,:)         ! HF ORBITAL AMPLITUDES AT GRID POINTS 
   DOUBLE PRECISION,ALLOCATABLE :: ORBITALS_SAVE(:,:,:)    ! HF ORBITAL AMPLITUDES AT GRID POINTS
   DOUBLE PRECISION,ALLOCATABLE :: DXORBITALS(:,:,:)       ! OCCUPIED ORBITAL X-DERIVATIVES AT GRID POINTS
   DOUBLE PRECISION,ALLOCATABLE :: DYORBITALS(:,:,:)       ! OCCUPIED ORBITAL Y-DERIVATIVES AT GRID POINTS
   DOUBLE PRECISION,ALLOCATABLE :: DZORBITALS(:,:,:)       ! OCCUPIED ORBITAL Z-DERIVATIVES AT GRID POINTS
   DOUBLE COMPLEX,ALLOCATABLE   :: RORB(:,:,:,:,:)         ! RADIAL FUNCTIONS FOR ORBITALS
   DOUBLE COMPLEX,ALLOCATABLE   :: RXORB(:,:,:,:,:)        ! D/DX RADIAL FUNCTIONS FOR ORBITALS
   DOUBLE COMPLEX,ALLOCATABLE   :: RYORB(:,:,:,:,:)        ! D/DY RADIAL FUNCTIONS FOR ORBITALS
   DOUBLE COMPLEX,ALLOCATABLE   :: RZORB(:,:,:,:,:)        ! D/DZ RADIAL FUNCTIONS FOR ORBITALS
   DOUBLE COMPLEX,ALLOCATABLE   :: RN(:,:,:,:)             ! RADIAL FUNCTIONS FOR NUCLEAR ATTRACTION
   DOUBLE COMPLEX,ALLOCATABLE   :: RJ(:,:,:,:)             ! RADIAL FUNCTIONS FOR COULOMB POTENTIAL
   DOUBLE COMPLEX,ALLOCATABLE   :: RRHO(:,:,:,:)           ! RADIAL FUNCTIONS FOR ELECTRON DENSITY
   DOUBLE COMPLEX,ALLOCATABLE   :: AORB(:,:,:,:,:)         ! RADIAL FUNCTIONS FOR AO (SMALL)
   DOUBLE COMPLEX,ALLOCATABLE   :: AORB2(:,:,:,:,:)        ! RADIAL FUNCTIONS FOR AO (LARGE)
!  DOUBLE COMPLEX,ALLOCATABLE   :: AXORB(:,:,:,:,:)        ! D/DX RADIAL FUNCTIONS FOR AO
!  DOUBLE COMPLEX,ALLOCATABLE   :: AYORB(:,:,:,:,:)        ! D/DY RADIAL FUNCTIONS FOR AO
!  DOUBLE COMPLEX,ALLOCATABLE   :: AZORB(:,:,:,:,:)        ! D/DZ RADIAL FUNCTIONS FOR AO
   DOUBLE PRECISION,ALLOCATABLE :: AOBASIS(:,:,:)          ! AO (SMALL)
   DOUBLE PRECISION,ALLOCATABLE :: AOBASIS2(:,:,:)         ! AO (LARGE)
   DOUBLE PRECISION,ALLOCATABLE :: POTENTIALJ(:,:)         ! COULOMB POTENTIAL 
   DOUBLE PRECISION,ALLOCATABLE :: PREVIOUS_J(:,:)         ! COULOMB POTENTIAL 
   DOUBLE PRECISION,ALLOCATABLE :: POTENTIALN(:,:)         ! NUCLEAR POTENTIAL 
   DOUBLE PRECISION,ALLOCATABLE :: SG_EPSILON(:)           ! ORBITAL ENERGIES
END MODULE
