SUBROUTINE MP2_ENERGY_ALG1
! TRANSFORM TWO-ELECTRON INTEGRALS BY O(N**5) ALGORITHM AND EVALUATE MP2 CORRECTION.
! AO-BASED TWO-ELECTRON INTEGRALS ARE RETRIEVED FROM DISK.

   USE MPI
   USE CONSTANTS
   USE CONTROL
   USE STRUCTURE
   USE BASISSET
   USE INTEGRAL
   USE GRADIENT
   
   IMPLICIT NONE
   INCLUDE "mpif.h"
   DOUBLE PRECISION :: ICPUS,ICPUE
   INTEGER,PARAMETER :: CASHESIZE = 1000 ! CASHE SIZE MUST BE EXACTLY THE SAME IN THE STORE & RESTORE SUBROUTINES
!  LOGICAL :: LKJOB
!  INTEGER :: KJOBS,KJOBE
   INTEGER :: MOI,MOJ,MOA,MOB,MOG
   INTEGER :: KIX,KIY,KIZ,KJX,KJY,KJZ,KAX,KAY,KAZ,KBX,KBY,KBZ,KGX,KGY,KGZ
   INTEGER :: Q1X,Q1Y,Q1Z,Q2X,Q2Y,Q2Z,Q3X,Q3Y,Q3Z
   INTEGER :: I,J,K,L,PX,PY,PZ,QX,QY,QZ,RX,RY,RZ
   INTEGER :: EOF
   INTEGER :: ICASHECOUNT
   DOUBLE PRECISION :: ICOUNT,ICOUNTTOTAL
   INTEGER(4),ALLOCATABLE :: ICASHE1X(:),ICASHE1Y(:),ICASHE1Z(:),ICASHE2(:)
   DOUBLE PRECISION,ALLOCATABLE :: DCASHE(:)
   DOUBLE PRECISION :: EMP2,EMP2S,EMP2T,EMP2S_TMP,EMP2T_TMP
   DOUBLE COMPLEX,ALLOCATABLE :: PHASEX(:),PHASEY(:),PHASEZ(:)
   DOUBLE COMPLEX,ALLOCATABLE :: TNNNKK(:,:,:,:,:),TOK(:,:)
   DOUBLE COMPLEX,ALLOCATABLE :: TVOKK(:,:,:,:),TOVOKK(:,:,:,:,:)
   DOUBLE PRECISION,ALLOCATABLE :: QEPSILON_TMP(:,:,:,:)
   INTEGER :: KVCX2,KVCY2,KVCZ2
   INTEGER :: NMOD
!  INTEGER,ALLOCATABLE :: KVC3(:)
!  LOGICAL,ALLOCATABLE :: LKVC(:,:)
   INTEGER :: TICKET
   INTEGER :: NFILES,IFILE,JFILE
   LOGICAL :: LEXIST
   CHARACTER(6) :: FILEAPPENDIX
! -- HELIX 
   DOUBLE COMPLEX,ALLOCATABLE :: CO_HELIX(:,:,:,:)
! -- HELIX

! -- HELIX 
   IF (HELIX /= 0.0D0) THEN
    ALLOCATE(CO_HELIX(NCGS,NCGS,-KVCX:KVCX,-CEL1X-CEL2X:CEL1X+CEL2X))
    DO KIX=-KVCX,MAX(0,KVCX-1)
     DO MOI=ICORE+1,IALL(KIX,0,0)
      DO PX=-CEL1X-CEL2X,CEL1X+CEL2X
       DO I=1,NCGS
        CO_HELIX(I,MOI,KIX,PX)=DCMPLX(0.0D0,0.0D0)
        DO J=1,NCGS
         CO_HELIX(I,MOI,KIX,PX)=CO_HELIX(I,MOI,KIX,PX)+CO(J,MOI,KIX,0,0)*C2H(J,I,PX)
        ENDDO
       ENDDO
      ENDDO
     ENDDO
    ENDDO
   ENDIF
! -- HELIX 

!  ALLOCATE(KVC3(ICORE+1:IALLMAX-IVIRTCORE),LKVC(ICORE+1:IALLMAX-IVIRTCORE,-KVC:KVC))
   NMOD = IOPTN(99)
   IF (NMOD < 1) CALL PABORT('ILLEGAL MODULO PARAMETER')
   IF (NMOD > 1) THEN
    IF (MYID == 0) WRITE(6,'(A)') '******************************************************************************'
    IF (MYID == 0) WRITE(6,'(A,I3,A)') '* MP2 ENERGY CORRECTION AND QUASI-PARTICLE ENERGY CORRECTIONS WITH MOD = ',NMOD,' *'
    IF (MYID == 0) WRITE(6,'(A)') '******************************************************************************'
    IF (KVCX/NMOD*NMOD /= KVCX) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG X')
    IF (KVCY/NMOD*NMOD /= KVCY) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG Y')
    IF (KVCZ/NMOD*NMOD /= KVCZ) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG Z')
    KVCX2=KVCX/NMOD
    KVCY2=KVCY/NMOD
    KVCZ2=KVCZ/NMOD
   ELSE
    KVCX2=KVCX
    KVCY2=KVCY
    KVCZ2=KVCZ
   ENDIF 

   ALLOCATE(ICASHE1X(CASHESIZE),ICASHE1Y(CASHESIZE),ICASHE1Z(CASHESIZE),ICASHE2(CASHESIZE),DCASHE(CASHESIZE))
   ALLOCATE(PHASEX(-(CEL1X+CEL2X)*KVCX2:(CEL1X+CEL2X)*KVCX2))
   ALLOCATE(PHASEY(-(CEL1Y+CEL2Y)*KVCY2:(CEL1Y+CEL2Y)*KVCY2))
   ALLOCATE(PHASEZ(-(CEL1Z+CEL2Z)*KVCZ2:(CEL1Z+CEL2Z)*KVCZ2))
   ALLOCATE(QEPSILON_TMP(NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))

   IF (MYID == 0) WRITE(6,'(A)') 'CALCULATE MP2 ENERGY (ALGORITHM 1)'
   IF (IOPTN(27) /= 0) CALL WARNING('FROZEN CORE APPROXIMATION WILL BE USED')
   IF (IOPTN(55) /= 0) CALL WARNING('FROZEN VIRTUAL APPROXIMATION WILL BE USED')
   IF (IALLMAX-IOCC-IVIRTCORE <= 0) THEN
    CALL WARNING('THERE IS NO VIRTUAL ORBITAL --- MP2 CORRECTION IS NULL')
    RETURN
   ENDIF
   IF (IOPTN(44) == 0) THEN
    IF (MYID == 0) WRITE(6,'(A)') 'NO QUASI-PARTICLE ENERGY CALCULATION REQUESTED'
   ELSE IF (IOPTN(44) <= NCGS) THEN
    IF (MYID == 0) WRITE(6,'(A,I3,A,I3,A)') 'MP2 QUASI-PARTICLE ENERGY CALCULATIONS FOR',IOPTN(44), &
     ' OCCUPIED AND ',IOPTN(44),' VIRTUAL BANDS WILL BE PERFORMED'
   ELSE
    IF (MYID == 0) WRITE(6,'(A)') 'MP2 QUASI-PARTICLE ENERGY CALCULATIONS FOR ALL OCCUPIED AND VIRTUAL BANDS WILL BE PERFORMED'
   ENDIF
   CALL PFLUSH(6)
!  KJOBS=IOPTN(47)
!  KJOBE=IOPTN(48)
!  IF ((KJOBS >= -KVC2).AND.(KJOBE <= MAX(0,KVC2-1)).AND.(KJOBS <= KJOBE)) THEN
!   LKJOB=.TRUE.
!   WRITE(6,'(A)') '*************************************************************************************'
!   WRITE(6,'(A,I3,A,I3,A)') '* MP2 ENERGY CORRECTION AND QUASI-PARTICLE ENERGY CORRECTIONS FROM KVC = ',KJOBS,' TO ',KJOBE,' *'
!   WRITE(6,'(A)') '*************************************************************************************'
!  ELSE
!   LKJOB=.FALSE.
!   KJOBS=-KVC2
!   KJOBE=MAX(0,KVC2-1)
!  ENDIF

   NFILES=0
   IF (MYID == 0) THEN
    DO WHILE (.TRUE.)
     WRITE(FILEAPPENDIX,'(I6)') 100000+NFILES
     INQUIRE(FILE=TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6),EXIST=LEXIST)
     IF (LEXIST) THEN
      WRITE(6,'(A)') TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6)//' IS FOUND'
      NFILES=NFILES+1
     ELSE
      EXIT
     ENDIF
    ENDDO
   ENDIF
   CALL MPI_BCAST(NFILES,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   IF (NFILES == 0) CALL PABORT('NO ERI FILES WAS FOUND')

   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT(NCGS**3*(2*CEL1X+1)*(2*CEL1Y+1)*(2*CEL1Z+1)*(2*CEL2X+1)*(2*CEL2Y+1)*(2*CEL2Z+1)) &
    /1.0D3,' K WORDS (TNNNKK)'
   CALL PFLUSH(6)
   ALLOCATE(TNNNKK(NCGS,NCGS,NCGS,(2*CEL1X+1)*(2*CEL1Y+1)*(2*CEL1Z+1),(2*CEL2X+1)*(2*CEL2Y+1)*(2*CEL2Z+1)))
   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT((MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE)-ICORE-2)*(2*KVCX2+1)*(2*KVCY2+1)*(2*KVCZ2+1)) &
    /1.0D3,' K WORDS (TOK)'
   CALL PFLUSH(6)
   ALLOCATE(TOK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2)))
   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT((IALLMAX-IVIRTCORE-MAX(IOCC+1-IOPTN(44),ICORE+1)-1) &
    *(MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE)-ICORE-2)*MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2) &
    *MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2))/1.0D3,' K WORDS (TVOKK)'
   CALL PFLUSH(6)
   ALLOCATE(TVOKK(MAX(IOCC+1-IOPTN(44),ICORE+1):IALLMAX-IVIRTCORE,ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),&
                  MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2),MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2)))
   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT(IALLMAX-IVIRTCORE-MAX(IOCC+1-IOPTN(44),ICORE+1)-1) &
                                      *DFLOAT(MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE)-ICORE-2)**2 &
                                      *DFLOAT(MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2) &
                                             *MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2))/1.0D3,' K WORDS (TOVOKK)'
   CALL PFLUSH(6)
   ALLOCATE(TOVOKK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),MAX(IOCC+1-IOPTN(44),ICORE+1):IALLMAX-IVIRTCORE, &
                   ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE), &
                   MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2),MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2)))

   DO I=-(CEL1X+CEL2X)*KVCX2,(CEL1X+CEL2X)*KVCX2
    IF (KVCX2 == 0) THEN
     PHASEX(I)=DCMPLX(1.0D0,0.0D0)
    ELSE
     PHASEX(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCX2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCX2)*PI))
    ENDIF
   ENDDO
   DO I=-(CEL1Y+CEL2Y)*KVCY2,(CEL1Y+CEL2Y)*KVCY2
    IF (KVCY2 == 0) THEN
     PHASEY(I)=DCMPLX(1.0D0,0.0D0)
    ELSE
     PHASEY(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCY2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCY2)*PI))
    ENDIF
   ENDDO
   DO I=-(CEL1Z+CEL2Z)*KVCZ2,(CEL1Z+CEL2Z)*KVCZ2
    IF (KVCZ2 == 0) THEN
     PHASEZ(I)=DCMPLX(1.0D0,0.0D0)
    ELSE
     PHASEZ(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCZ2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCZ2)*PI))
    ENDIF
   ENDDO

   EMP2S=0.0D0
   EMP2T=0.0D0
   EMP2S_TMP=0.0D0
   EMP2T_TMP=0.0D0
   QEPSILON=0.0D0
   QEPSILON_TMP=0.0D0

   ! COMPUTE E(2) AND QUASI-PARTICLE ENERGY BANDS
   CALL PCPU_TIME(ICPUS)
   TICKET=0
   DO KBX=-KVCX2,MAX(0,KVCX2-1)
   DO KBY=-KVCY2,MAX(0,KVCY2-1)
   DO KBZ=-KVCZ2,MAX(0,KVCZ2-1)
    DO MOB=IOCC+1,IALL(KBX,KBY,KBZ)-IVIRTCORE
! --- PARALLEL LOOP
     TICKET=TICKET+1
     IF (TICKET == NUMPROCS) TICKET=TICKET-NUMPROCS
     IF (MYID == TICKET) THEN
!write(*,*) 'Process:',myid,'KBs = ',KBX,KBY,KBZ,'MOB = ',MOB
! --- PARALLEL LOOP
     TNNNKK=DCMPLX(0.0D0,0.0D0)
     DO IFILE=1,NFILES
     JFILE=IFILE+MYID-1
     JFILE=JFILE-JFILE/NFILES*NFILES
     WRITE(FILEAPPENDIX,'(I6)') 100000+JFILE
!write(*,*) 'Process:',myid,' reading from ',TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6)
     OPEN(31,FILE=TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6),FORM='UNFORMATTED')
     REWIND(31)
     ICOUNT=0.0D0
     DO
      READ(31,IOSTAT=EOF) ICASHE1X,ICASHE1Y,ICASHE1Z,ICASHE2,DCASHE
      IF (EOF /= 0) EXIT
      DO ICASHECOUNT=1,CASHESIZE
       IF (ICASHE1X(ICASHECOUNT) == -1) EXIT
       ICOUNT=ICOUNT+1.0D0
       PX=0
       QX=0
       RX=0
       PY=0
       QY=0
       RY=0
       PZ=0
       QZ=0
       RZ=0
       I=0
       J=0
       K=0
       L=0
       CALL MVBITS(ICASHE1X(ICASHECOUNT),16,8,PX,0)
       CALL MVBITS(ICASHE1X(ICASHECOUNT), 8,8,QX,0)
       CALL MVBITS(ICASHE1X(ICASHECOUNT), 0,8,RX,0)
       CALL MVBITS(ICASHE1Y(ICASHECOUNT),16,8,PY,0)
       CALL MVBITS(ICASHE1Y(ICASHECOUNT), 8,8,QY,0)
       CALL MVBITS(ICASHE1Y(ICASHECOUNT), 0,8,RY,0)
       CALL MVBITS(ICASHE1Z(ICASHECOUNT),16,8,PZ,0)
       CALL MVBITS(ICASHE1Z(ICASHECOUNT), 8,8,QZ,0)
       CALL MVBITS(ICASHE1Z(ICASHECOUNT), 0,8,RZ,0)
       CALL MVBITS(ICASHE2(ICASHECOUNT),24,8,I,0)
       CALL MVBITS(ICASHE2(ICASHECOUNT),16,8,J,0)
       CALL MVBITS(ICASHE2(ICASHECOUNT), 8,8,K,0)
       CALL MVBITS(ICASHE2(ICASHECOUNT), 0,8,L,0)
       Q1X=PX-CEL1X
       Q2X=QX-CEL1X
       Q3X=RX-CEL2X
       Q1Y=PY-CEL1Y
       Q2Y=QY-CEL1Y
       Q3Y=RY-CEL2Y
       Q1Z=PZ-CEL1Z
       Q2Z=QZ-CEL1Z
       Q3Z=RZ-CEL2Z
       IF ((Q1X < -REDUCED_CEL1X).OR.(Q1X > REDUCED_CEL1X).OR.(Q2X < -REDUCED_CEL1X).OR.(Q2X > REDUCED_CEL1X).OR. &
           (Q1Y < -REDUCED_CEL1Y).OR.(Q1Y > REDUCED_CEL1Y).OR.(Q2Y < -REDUCED_CEL1Y).OR.(Q2Y > REDUCED_CEL1Y).OR. &
           (Q1Z < -REDUCED_CEL1Z).OR.(Q1Z > REDUCED_CEL1Z).OR.(Q2Z < -REDUCED_CEL1Z).OR.(Q2Z > REDUCED_CEL1Z).OR. &
           (Q3X < -CEL2X).OR.(Q3X > CEL2X).OR.(Q3Y < -CEL2Y).OR.(Q3Y > CEL2Y).OR.(Q3Z < -CEL2Z).OR.(Q3Z > CEL2Z)) &
       CALL PABORT('INTEGRAL FILE HAS BEEN DEGRADED')
       IF (HELIX == 0.0D0) THEN
        TNNNKK(I,J,K,((Q1X+CEL1X)*(2*CEL1Y+1)+(Q1Y+CEL1Y))*(2*CEL1Z+1)+(Q1Z+CEL1Z)+1, &
                     ((Q3X+CEL2X)*(2*CEL2Y+1)+(Q3Y+CEL2Y))*(2*CEL2Z+1)+(Q3Z+CEL2Z)+1)= &
        TNNNKK(I,J,K,((Q1X+CEL1X)*(2*CEL1Y+1)+(Q1Y+CEL1Y))*(2*CEL1Z+1)+(Q1Z+CEL1Z)+1, &
                     ((Q3X+CEL2X)*(2*CEL2Y+1)+(Q3Y+CEL2Y))*(2*CEL2Z+1)+(Q3Z+CEL2Z)+1) &
                     +CO(L,MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD) &
                     *PHASEX(KBX*(Q2X+Q3X))*PHASEY(KBY*(Q2Y+Q3Y))*PHASEZ(KBZ*(Q2Z+Q3Z))*DCMPLX(DCASHE(ICASHECOUNT),0.0D0)
       ELSE ! -- HELIX
        TNNNKK(I,J,K,((Q1X+CEL1X)*(2*CEL1Y+1)+(Q1Y+CEL1Y))*(2*CEL1Z+1)+(Q1Z+CEL1Z)+1, &
                     ((Q3X+CEL2X)*(2*CEL2Y+1)+(Q3Y+CEL2Y))*(2*CEL2Z+1)+(Q3Z+CEL2Z)+1)= &
        TNNNKK(I,J,K,((Q1X+CEL1X)*(2*CEL1Y+1)+(Q1Y+CEL1Y))*(2*CEL1Z+1)+(Q1Z+CEL1Z)+1, &
                     ((Q3X+CEL2X)*(2*CEL2Y+1)+(Q3Y+CEL2Y))*(2*CEL2Z+1)+(Q3Z+CEL2Z)+1) &
                     +CO_HELIX(L,MOB,KBX*NMOD,Q2X+Q3X) &
                     *PHASEX(KBX*(Q2X+Q3X))*PHASEY(KBY*(Q2Y+Q3Y))*PHASEZ(KBZ*(Q2Z+Q3Z))*DCMPLX(DCASHE(ICASHECOUNT),0.0D0)
       ENDIF ! -- HELIX
      ENDDO
     ENDDO
     CLOSE(31)
     ENDDO
     IF ((IOPTN(9) >= 2).AND.(MYID == 0)) WRITE(6,'(F20.0,A,F7.3,A)') ICOUNT, &
     ' ERIS (',ICOUNT/DFLOAT((CEL1X*2+1)**2*(CEL2X+1)*(CEL1Y*2+1)**2*(CEL2Y+1)*(CEL1Z*2+1)**2*(CEL2Z+1)*NCGS**4)*100.0, &
     '% OF TOTAL ERIS) HAVE BEEN RESTORED'
     TOVOKK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),MAX(IOCC+1-IOPTN(44),ICORE+1):IALLMAX-IVIRTCORE, &
            ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE), &
            1:MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2),1:MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2))=DCMPLX(0.0D0,0.0D0)
     DO I=1,NCGS
      TVOKK(MAX(IOCC+1-IOPTN(44),ICORE+1):IALLMAX-IVIRTCORE,ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE), &
      1:MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2),1:MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2))=DCMPLX(0.0D0,0.0D0)
      DO Q1X=-CEL1X,CEL1X
      DO Q1Y=-CEL1Y,CEL1Y
      DO Q1Z=-CEL1Z,CEL1Z
       DO J=1,NCGS
        TOK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),1:MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2))=DCMPLX(0.0D0,0.0D0)
        DO Q3X=-CEL2X,CEL2X
        DO Q3Y=-CEL2Y,CEL2Y
        DO Q3Z=-CEL2Z,CEL2Z
         DO K=1,NCGS
          DO KJX=-KVCX2,MAX(0,KVCX2-1)
          DO KJY=-KVCY2,MAX(0,KVCY2-1)
          DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
           DO MOJ=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KJX,KJY,KJZ)-IVIRTCORE)
            IF (HELIX == 0.0D0) THEN
             TOK(MOJ,((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)= &
             TOK(MOJ,((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)+ &
             TNNNKK(I,J,K,((Q1X+CEL1X)*(2*CEL1Y+1)+(Q1Y+CEL1Y))*(2*CEL1Z+1)+(Q1Z+CEL1Z)+1, &
                          ((Q3X+CEL2X)*(2*CEL2Y+1)+(Q3Y+CEL2Y))*(2*CEL2Z+1)+(Q3Z+CEL2Z)+1) &
             *DCONJG(CO(K,MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD))*PHASEX(-KJX*Q3X)*PHASEY(-KJY*Q3Y)*PHASEZ(-KJZ*Q3Z)
            ELSE ! -- HELIX
             TOK(MOJ,((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)= &
             TOK(MOJ,((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)+ &
             TNNNKK(I,J,K,((Q1X+CEL1X)*(2*CEL1Y+1)+(Q1Y+CEL1Y))*(2*CEL1Z+1)+(Q1Z+CEL1Z)+1, &
                          ((Q3X+CEL2X)*(2*CEL2Y+1)+(Q3Y+CEL2Y))*(2*CEL2Z+1)+(Q3Z+CEL2Z)+1) &
             *DCONJG(CO_HELIX(K,MOJ,KJX*NMOD,Q3X))*PHASEX(-KJX*Q3X)*PHASEY(-KJY*Q3Y)*PHASEZ(-KJZ*Q3Z)
            ENDIF ! -- HELIX
           ENDDO
          ENDDO
          ENDDO
          ENDDO
         ENDDO
        ENDDO
        ENDDO
        ENDDO
        DO KJX=-KVCX2,MAX(0,KVCX2-1)
        DO KJY=-KVCY2,MAX(0,KVCY2-1)
        DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
         DO KAX=-KVCX2,MAX(0,KVCX2-1)
         DO KAY=-KVCY2,MAX(0,KVCY2-1)
         DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
          DO MOJ=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KJX,KJY,KJZ)-IVIRTCORE)
           DO MOA=MAX(IOCC+1-IOPTN(44),ICORE+1),IALL(KAX,KAY,KAZ)-IVIRTCORE
            IF (HELIX == 0.0D0) THEN
             TVOKK(MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                           ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)= &
             TVOKK(MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                           ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
             +TOK(MOJ,((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
             *CO(J,MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)*PHASEX(KAX*Q1X)*PHASEY(KAY*Q1Y)*PHASEZ(KAZ*Q1Z)
            ELSE ! -- HELIX
             TVOKK(MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                           ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)= &
             TVOKK(MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                           ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
             +TOK(MOJ,((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
             *CO_HELIX(J,MOA,KAX*NMOD,Q1X)*PHASEX(KAX*Q1X)*PHASEY(KAY*Q1Y)*PHASEZ(KAZ*Q1Z)
            ENDIF ! -- HELIX
           ENDDO
          ENDDO
         ENDDO
         ENDDO
         ENDDO
        ENDDO
        ENDDO
        ENDDO
       ENDDO
      ENDDO
      ENDDO
      ENDDO
      DO KJX=-KVCX2,MAX(0,KVCX2-1)
      DO KJY=-KVCY2,MAX(0,KVCY2-1)
      DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
       DO KAX=-KVCX2,MAX(0,KVCX2-1)
       DO KAY=-KVCY2,MAX(0,KVCY2-1)
       DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
        KIX=KAX-KJX+KBX
        KIY=KAY-KJY+KBY
        KIZ=KAZ-KJZ+KBZ
        IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
        IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
        IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
        IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
        IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
        IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
        DO MOJ=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KJX,KJY,KJZ)-IVIRTCORE)
         DO MOA=MAX(IOCC+1-IOPTN(44),ICORE+1),IALL(KAX,KAY,KAZ)-IVIRTCORE
          DO MOI=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KIX,KIY,KIZ)-IVIRTCORE)
           IF (HELIX == 0.0D0) THEN
            TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                               ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)= &
            TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                               ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
            +TVOKK(MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                           ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
            *DCONJG(CO(I,MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD))
           ELSE ! -- HELIX
            TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                               ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)= &
            TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                               ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
            +TVOKK(MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                           ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
            *DCONJG(CO_HELIX(I,MOI,KIX*NMOD,0))
           ENDIF ! -- HELIX
          ENDDO
         ENDDO
        ENDDO
       ENDDO
       ENDDO
       ENDDO
      ENDDO
      ENDDO
      ENDDO
     ENDDO
     DO KJX=-KVCX2,MAX(0,KVCX2-1)
     DO KJY=-KVCY2,MAX(0,KVCY2-1)
     DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
      DO KAX=-KVCX2,MAX(0,KVCX2-1)
      DO KAY=-KVCY2,MAX(0,KVCY2-1)
      DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
       KIX=KAX-KJX+KBX
       KIY=KAY-KJY+KBY
       KIZ=KAZ-KJZ+KBZ
       IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
       IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
       IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
       IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
       IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
       IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
       DO MOJ=ICORE+1,IOCC
        DO MOA=IOCC+1,IALL(KAX,KAY,KAZ)-IVIRTCORE
         DO MOI=ICORE+1,IOCC
!write(*,'(8i3,2f20.10)') kix,kjx,kax,kbx,moi,moj,moa,mob,tovokk(moi,moa,moj,kax,kay,kaz,kjx,kjy,kjz)
          EMP2S_TMP=EMP2S_TMP &
            +(0.5D0*TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                       ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
                   *DCONJG(TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                              ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
            + 0.5D0*DREAL(TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                             ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
                   *DCONJG(TOVOKK(MOJ,MOA,MOI,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                              ((KIX+KVCX2)*MAX(1,2*KVCY2)+(KIY+KVCY2))*MAX(1,2*KVCZ2)+KIZ+KVCZ2+1)))) &
            /(EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
             -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))
          EMP2T_TMP=EMP2T_TMP &
            +(1.5D0*TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                       ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
                   *DCONJG(TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                              ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
            - 1.5D0*DREAL(TOVOKK(MOI,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                             ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
                   *DCONJG(TOVOKK(MOJ,MOA,MOI,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                              ((KIX+KVCX2)*MAX(1,2*KVCY2)+(KIY+KVCY2))*MAX(1,2*KVCZ2)+KIZ+KVCZ2+1)))) &
            /(EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
             -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))
         ENDDO
        ENDDO
       ENDDO
      ENDDO
      ENDDO
      ENDDO
     ENDDO
     ENDDO
     ENDDO
     IF (IOPTN(44) > 0) THEN
      DO KJX=-KVCX2,MAX(0,KVCX2-1)
      DO KJY=-KVCY2,MAX(0,KVCY2-1)
      DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
       DO KAX=-KVCX2,MAX(0,KVCX2-1)
       DO KAY=-KVCY2,MAX(0,KVCY2-1)
       DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
        KGX=KAX-KJX+KBX
        KGY=KAY-KJY+KBY
        KGZ=KAZ-KJZ+KBZ
        IF (KGX >= KVCX2) KGX=KGX-2*KVCX2
        IF (KGY >= KVCY2) KGY=KGY-2*KVCY2
        IF (KGZ >= KVCZ2) KGZ=KGZ-2*KVCZ2
        IF (KGX < -KVCX2) KGX=KGX+2*KVCX2
        IF (KGY < -KVCY2) KGY=KGY+2*KVCY2
        IF (KGZ < -KVCZ2) KGZ=KGZ+2*KVCZ2
        DO MOJ=ICORE+1,IOCC
         DO MOA=IOCC+1,IALL(KAX,KAY,KAZ)-IVIRTCORE
          DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
           QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
             +(2.0D0*TOVOKK(MOG,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                        ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
                    *DCONJG(TOVOKK(MOG,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                               ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
             -DREAL(TOVOKK(MOG,MOA,MOJ,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                       ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
             *DCONJG(TOVOKK(MOJ,MOA,MOG,((KAX+KVCX2)*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+KAZ+KVCZ2+1, &
                                        ((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1)))) &
             /(EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
              -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))
          ENDDO
         ENDDO
        ENDDO
       ENDDO
       ENDDO
       ENDDO
      ENDDO
      ENDDO
      ENDDO
      DO KJX=-KVCX2,MAX(0,KVCX2-1)
      DO KJY=-KVCY2,MAX(0,KVCY2-1)
      DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
       DO KGX=-KVCX2,MAX(0,KVCX2-1)
       DO KGY=-KVCY2,MAX(0,KVCY2-1)
       DO KGZ=-KVCZ2,MAX(0,KVCZ2-1)
        KIX=KGX-KJX+KBX
        KIY=KGY-KJY+KBY
        KIZ=KGZ-KJZ+KBZ
        IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
        IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
        IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
        IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
        IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
        IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
        DO MOJ=ICORE+1,IOCC
         DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
          DO MOI=ICORE+1,IOCC
           QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
             +(2.0D0*TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                        ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
                    *DCONJG(TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                               ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1)) &
             -DREAL(TOVOKK(MOI,MOG,MOJ,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                       ((KJX+KVCX2)*MAX(1,2*KVCY2)+(KJY+KVCY2))*MAX(1,2*KVCZ2)+KJZ+KVCZ2+1) &
             *DCONJG(TOVOKK(MOJ,MOG,MOI,((KGX+KVCX2)*MAX(1,2*KVCY2)+(KGY+KVCY2))*MAX(1,2*KVCZ2)+KGZ+KVCZ2+1, &
                                        ((KIX+KVCX2)*MAX(1,2*KVCY2)+(KIY+KVCY2))*MAX(1,2*KVCZ2)+KIZ+KVCZ2+1)))) &
             /(EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD) &
              -EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)-EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD))
          ENDDO
         ENDDO
        ENDDO
       ENDDO
       ENDDO
       ENDDO
      ENDDO
      ENDDO
      ENDDO
     ENDIF
! --- PARALLEL LOOP
     CALL PCPU_TIME(ICPUE)
     IF (MYID == 0) WRITE(6,'(A,F6.2,A,F10.1,A)') ' ... ', &
       DFLOAT((((KBX+KVCX2)*MAX(1,2*KVCY2)+(KBY+KVCY2))*MAX(1,2*KVCZ2)+(KBZ+KVCZ2))*(IALL(KBX,KBY,KBZ)-IVIRTCORE-IOCC) &
       +(MOB-IOCC))/DFLOAT((IALL(KBX,KBY,KBZ)-IVIRTCORE-IOCC)*MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2))*100.0D0, &
       ' % OF MP2 ENERGY EVALUATION (CPU / SEC = ',ICPUE-ICPUS,')'
     CALL PCPU_TIME(ICPUS)
     CALL PFLUSH(6)
     ENDIF
! --- PARALLEL LOOP
!write(*,*) emp2s_tmp,emp2t_tmp
    ENDDO
   ENDDO
   ENDDO
   ENDDO

   CALL MPI_ALLREDUCE(EMP2S_TMP,EMP2S,1,MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERR)
   CALL MPI_ALLREDUCE(EMP2T_TMP,EMP2T,1,MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERR)

   EMP2S=EMP2S/DFLOAT(MAX(1,8*KVCX2**3))/DFLOAT(MAX(1,8*KVCY2**3))/DFLOAT(MAX(1,8*KVCZ2**3))
   EMP2T=EMP2T/DFLOAT(MAX(1,8*KVCX2**3))/DFLOAT(MAX(1,8*KVCY2**3))/DFLOAT(MAX(1,8*KVCZ2**3))
   EMP2=EMP2S+EMP2T
   IF (MYID == 0) WRITE(6,'(A,F20.15,A)') 'E(2) SINGLET = ',EMP2S,' HARTREE'
   IF (MYID == 0) WRITE(6,'(A,F20.15,A)') 'E(2) TRIPLET = ',EMP2T,' HARTREE'
   IF (MYID == 0) WRITE(6,'(A,F20.15,A)') 'E(2)         = ',EMP2, ' HARTREE'
   IF (MYID == 0) WRITE(6,'(A,F20.15,A)') 'EMP2         = ',EHFKS+EMP2,' HARTREE'

   IF (IOPTN(44) > 0) THEN
    CALL MPI_ALLREDUCE(QEPSILON_TMP,QEPSILON,NCGS*(KVCX*2+1)*(KVCY*2+1)*(KVCZ*2+1),MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERR)
    DO KGX=-KVCX2,MAX(0,KVCX2-1)
    DO KGY=-KVCY2,MAX(0,KVCY2-1)
    DO KGZ=-KVCZ2,MAX(0,KVCZ2-1)
     DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
      QEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
       +QEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)/DFLOAT(MAX(1,4*KVCX2**2))/DFLOAT(MAX(1,4*KVCY2**2))/DFLOAT(MAX(1,4*KVCZ2**2))
     ENDDO
    ENDDO
    ENDDO
    ENDDO
   ENDIF

   DEALLOCATE(QEPSILON_TMP)
   DEALLOCATE(ICASHE1X,ICASHE1Y,ICASHE1Z,ICASHE2,DCASHE)
   DEALLOCATE(PHASEX,PHASEY,PHASEZ,TNNNKK)
   DEALLOCATE(TOK,TVOKK,TOVOKK)
   IF (HELIX /= 0.0D0) DEALLOCATE(CO_HELIX)

   RETURN
END SUBROUTINE



SUBROUTINE MP2_ENERGY_ALG2
! SAME AS ABOVE BUT USES MUCH LESS MEMORY BY SPACE-TIME TRADEOFF.

   USE MPI
   USE CONSTANTS
   USE CONTROL
   USE STRUCTURE
   USE BASISSET
   USE INTEGRAL
   USE GRADIENT
   
   IMPLICIT NONE
   INCLUDE "mpif.h"
   DOUBLE PRECISION :: ICPUS,ICPUE
   INTEGER,PARAMETER :: CASHESIZE = 1000 ! CASHE SIZE MUST BE EXACTLY THE SAME IN THE STORE & RESTORE SUBROUTINES
!  LOGICAL :: LKJOB
!  INTEGER :: KJOBS,KJOBE
   INTEGER :: MOI,MOJ,MOA,MOB,MOG
   INTEGER :: KIX,KIY,KIZ,KJX,KJY,KJZ,KAX,KAY,KAZ,KBX,KBY,KBZ,KGX,KGY,KGZ
   INTEGER :: Q1X,Q1Y,Q1Z,Q2X,Q2Y,Q2Z,Q3X,Q3Y,Q3Z
   INTEGER :: I,J,K,L,PX,PY,PZ,QX,QY,QZ,RX,RY,RZ
   INTEGER :: EOF
   INTEGER :: ICASHECOUNT
   DOUBLE PRECISION :: ICOUNT,ICOUNTTOTAL
   INTEGER(4),ALLOCATABLE :: ICASHE1X(:),ICASHE1Y(:),ICASHE1Z(:),ICASHE2(:)
   DOUBLE PRECISION,ALLOCATABLE :: DCASHE(:)
   DOUBLE PRECISION :: EMP2,EMP2S,EMP2T,EMP2S_TMP,EMP2T_TMP
   DOUBLE COMPLEX,ALLOCATABLE :: PHASEX(:),PHASEY(:),PHASEZ(:)
   DOUBLE COMPLEX,ALLOCATABLE :: TNNNK(:,:,:,:,:,:)
   DOUBLE COMPLEX,ALLOCATABLE :: TNNOK(:,:,:,:,:,:)
   DOUBLE COMPLEX,ALLOCATABLE :: TNVOK(:,:,:,:,:,:)
   DOUBLE COMPLEX,ALLOCATABLE :: TOVOK(:,:,:,:,:,:)
   DOUBLE PRECISION,ALLOCATABLE :: QEPSILON_TMP(:,:,:,:)
   INTEGER :: KVCX2,KVCY2,KVCZ2
   INTEGER :: NMOD
!  INTEGER,ALLOCATABLE :: KVC3(:)
!  LOGICAL,ALLOCATABLE :: LKVC(:,:)
   INTEGER :: TICKET
   INTEGER :: NFILES,IFILE,JFILE
   LOGICAL :: LEXIST
   CHARACTER(6) :: FILEAPPENDIX

   IF (HELIX /= 0.0D0) CALL PABORT('ALG2 IS INCOMPATIBLE WITH HELIX')

!  ALLOCATE(KVC3(ICORE+1:IALLMAX-IVIRTCORE),LKVC(ICORE+1:IALLMAX-IVIRTCORE,-KVC:KVC))
   NMOD = IOPTN(99)
   IF (NMOD < 1) CALL PABORT('ILLEGAL MODULO PARAMETER')
   IF (NMOD > 1) THEN
    IF (MYID == 0) WRITE(6,'(A)') '******************************************************************************'
    IF (MYID == 0) WRITE(6,'(A,I3,A)') '* MP2 ENERGY CORRECTION AND QUASI-PARTICLE ENERGY CORRECTIONS WITH MOD = ',NMOD,' *'
    IF (MYID == 0) WRITE(6,'(A)') '******************************************************************************'
    IF (KVCX/NMOD*NMOD /= KVCX) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG X')
    IF (KVCY/NMOD*NMOD /= KVCY) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG Y')
    IF (KVCZ/NMOD*NMOD /= KVCZ) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG Z')
    KVCX2=KVCX/NMOD
    KVCY2=KVCY/NMOD
    KVCZ2=KVCZ/NMOD
   ELSE
    KVCX2=KVCX
    KVCY2=KVCY
    KVCZ2=KVCZ
   ENDIF 

   ALLOCATE(ICASHE1X(CASHESIZE),ICASHE1Y(CASHESIZE),ICASHE1Z(CASHESIZE),ICASHE2(CASHESIZE),DCASHE(CASHESIZE))
   ALLOCATE(PHASEX(-(CEL1X+CEL2X)*KVCX2:(CEL1X+CEL2X)*KVCX2))
   ALLOCATE(PHASEY(-(CEL1Y+CEL2Y)*KVCY2:(CEL1Y+CEL2Y)*KVCY2))
   ALLOCATE(PHASEZ(-(CEL1Z+CEL2Z)*KVCZ2:(CEL1Z+CEL2Z)*KVCZ2))
   ALLOCATE(QEPSILON_TMP(NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))

   IF (MYID == 0) WRITE(6,'(A)') 'CALCULATE MP2 ENERGY (ALGORITHM 2)'
   IF (IOPTN(27) /= 0) CALL WARNING('FROZEN CORE APPROXIMATION WILL BE USED')
   IF (IOPTN(55) /= 0) CALL WARNING('FROZEN VIRTUAL APPROXIMATION WILL BE USED')
   IF (IALLMAX-IOCC-IVIRTCORE <= 0) THEN
    CALL WARNING('THERE IS NO VIRTUAL ORBITAL --- MP2 CORRECTION IS NULL')
    RETURN
   ENDIF
   IF (IOPTN(44) == 0) THEN
    IF (MYID == 0) WRITE(6,'(A)') 'NO QUASI-PARTICLE ENERGY CALCULATION REQUESTED'
   ELSE IF (IOPTN(44) <= NCGS) THEN
    IF (MYID == 0) WRITE(6,'(A,I3,A,I3,A)') 'MP2 QUASI-PARTICLE ENERGY CALCULATIONS FOR',IOPTN(44), &
     ' OCCUPIED AND ',IOPTN(44),' VIRTUAL BANDS WILL BE PERFORMED'
   ELSE
    IF (MYID == 0) WRITE(6,'(A)') 'MP2 QUASI-PARTICLE ENERGY CALCULATIONS FOR ALL OCCUPIED AND VIRTUAL BANDS WILL BE PERFORMED'
   ENDIF
   CALL PFLUSH(6)
!  KJOBS=IOPTN(47)
!  KJOBE=IOPTN(48)
!  IF ((KJOBS >= -KVC2).AND.(KJOBE <= MAX(0,KVC2-1)).AND.(KJOBS <= KJOBE)) THEN
!   LKJOB=.TRUE.
!   WRITE(6,'(A)') '*************************************************************************************'
!   WRITE(6,'(A,I3,A,I3,A)') '* MP2 ENERGY CORRECTION AND QUASI-PARTICLE ENERGY CORRECTIONS FROM KVC = ',KJOBS,' TO ',KJOBE,' *'
!   WRITE(6,'(A)') '*************************************************************************************'
!  ELSE
!   LKJOB=.FALSE.
!   KJOBS=-KVC2
!   KJOBE=MAX(0,KVC2-1)
!  ENDIF

   NFILES=0
   IF (MYID == 0) THEN
    DO WHILE (.TRUE.)
     WRITE(FILEAPPENDIX,'(I6)') 100000+NFILES
     INQUIRE(FILE=TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6),EXIST=LEXIST)
     IF (LEXIST) THEN
      WRITE(6,'(A)') TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6)//' IS FOUND'
      NFILES=NFILES+1
     ELSE
      EXIT
     ENDIF
    ENDDO
   ENDIF
   CALL MPI_BCAST(NFILES,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   IF (NFILES == 0) CALL PABORT('NO ERI FILES WAS FOUND')

   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT(NCGS**3*(2*CEL2X+1)*(2*CEL2Y+1)*(2*CEL2Z+1))/1.0D3,' K WORDS (TNNNK)'
   CALL PFLUSH(6)
   ALLOCATE(TNNNK(NCGS,NCGS,NCGS,-CEL2X:CEL2X,-CEL2Y:CEL2Y,-CEL2Z:CEL2Z))
   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT(NCGS**2*(MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE)-ICORE) &
    *(2*KVCX2+1)*(2*KVCY2+1)*(2*KVCZ2+1))/1.0D3,' K WORDS (TNNOK)'
   CALL PFLUSH(6)
   ALLOCATE(TNNOK(NCGS,NCGS,ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),-KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2))
   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT(NCGS*(MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE)-ICORE) &
    *(IALLMAX-IVIRTCORE-MAX(IOCC+1-IOPTN(44),ICORE+1)+1) &
    *(2*KVCX2+1)*(2*KVCY2+1)*(2*KVCZ2+1))/1.0D3,' K WORDS (TNVOK)'
   CALL PFLUSH(6)
   ALLOCATE(TNVOK(NCGS,MAX(IOCC+1-IOPTN(44),ICORE+1):IALLMAX-IVIRTCORE, &
            ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),-KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2))
   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT((MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE)-ICORE)**2 &
    *(IALLMAX-IVIRTCORE-MAX(IOCC+1-IOPTN(44),ICORE+1)+1) &
    *(2*KVCX2+1)*(2*KVCY2+1)*(2*KVCZ2+1))/1.0D3,' K WORDS (TOVOK)'
   CALL PFLUSH(6)
   ALLOCATE(TOVOK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),MAX(IOCC+1-IOPTN(44),ICORE+1):IALLMAX-IVIRTCORE, &
            ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),-KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2))

   DO I=-(CEL1X+CEL2X)*KVCX2,(CEL1X+CEL2X)*KVCX2
    IF (KVCX2 == 0) THEN
     PHASEX(I)=DCMPLX(1.0D0,0.0D0)
    ELSE
     PHASEX(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCX2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCX2)*PI))
    ENDIF
   ENDDO
   DO I=-(CEL1Y+CEL2Y)*KVCY2,(CEL1Y+CEL2Y)*KVCY2
    IF (KVCY2 == 0) THEN
     PHASEY(I)=DCMPLX(1.0D0,0.0D0)
    ELSE
     PHASEY(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCY2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCY2)*PI))
    ENDIF
   ENDDO
   DO I=-(CEL1Z+CEL2Z)*KVCZ2,(CEL1Z+CEL2Z)*KVCZ2
    IF (KVCZ2 == 0) THEN
     PHASEZ(I)=DCMPLX(1.0D0,0.0D0)
    ELSE
     PHASEZ(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCZ2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCZ2)*PI))
    ENDIF
   ENDDO

   EMP2S=0.0D0
   EMP2T=0.0D0
   EMP2S_TMP=0.0D0
   EMP2T_TMP=0.0D0
   QEPSILON=0.0D0
   QEPSILON_TMP=0.0D0

   ! COMPUTE E(2) AND QUASI-PARTICLE ENERGY BANDS
   CALL PCPU_TIME(ICPUS)
   TICKET=0
   DO KBX=-KVCX2,MAX(0,KVCX2-1)
   DO KBY=-KVCY2,MAX(0,KVCY2-1)
   DO KBZ=-KVCZ2,MAX(0,KVCZ2-1)
    DO MOB=IOCC+1,IALL(KBX,KBY,KBZ)-IVIRTCORE
     DO KAX=-KVCX2,MAX(0,KVCX2-1)
     DO KAY=-KVCY2,MAX(0,KVCY2-1)
     DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
! ---- PARALLEL LOOP
      TICKET=TICKET+1
      IF (TICKET == NUMPROCS) TICKET=TICKET-NUMPROCS
      IF (MYID == TICKET) THEN
!write(*,*) 'Process:',myid,'KBs = ',KBX,KBY,KBZ,'MOB = ',MOB
! ---- PARALLEL LOOP
       TNNNK=DCMPLX(0.0D0,0.0D0)
       DO IFILE=1,NFILES
        JFILE=IFILE+MYID-1
        JFILE=JFILE-JFILE/NFILES*NFILES
        WRITE(FILEAPPENDIX,'(I6)') 100000+JFILE
!write(*,*) 'Process:',myid,' reading from ',TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6)
        OPEN(31,FILE=TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6),FORM='UNFORMATTED')
        REWIND(31)
        ICOUNT=0.0D0
        DO
         READ(31,IOSTAT=EOF) ICASHE1X,ICASHE1Y,ICASHE1Z,ICASHE2,DCASHE
         IF (EOF /= 0) EXIT
         DO ICASHECOUNT=1,CASHESIZE
          IF (ICASHE1X(ICASHECOUNT) == -1) EXIT
          ICOUNT=ICOUNT+1.0D0
          PX=0
          QX=0
          RX=0
          PY=0
          QY=0
          RY=0
          PZ=0
          QZ=0
          RZ=0
          I=0
          J=0
          K=0
          L=0
          CALL MVBITS(ICASHE1X(ICASHECOUNT),16,8,PX,0)
          CALL MVBITS(ICASHE1X(ICASHECOUNT), 8,8,QX,0)
          CALL MVBITS(ICASHE1X(ICASHECOUNT), 0,8,RX,0)
          CALL MVBITS(ICASHE1Y(ICASHECOUNT),16,8,PY,0)
          CALL MVBITS(ICASHE1Y(ICASHECOUNT), 8,8,QY,0)
          CALL MVBITS(ICASHE1Y(ICASHECOUNT), 0,8,RY,0)
          CALL MVBITS(ICASHE1Z(ICASHECOUNT),16,8,PZ,0)
          CALL MVBITS(ICASHE1Z(ICASHECOUNT), 8,8,QZ,0)
          CALL MVBITS(ICASHE1Z(ICASHECOUNT), 0,8,RZ,0)
          CALL MVBITS(ICASHE2(ICASHECOUNT),24,8,I,0)
          CALL MVBITS(ICASHE2(ICASHECOUNT),16,8,J,0)
          CALL MVBITS(ICASHE2(ICASHECOUNT), 8,8,K,0)
          CALL MVBITS(ICASHE2(ICASHECOUNT), 0,8,L,0)
          Q1X=PX-CEL1X
          Q2X=QX-CEL1X
          Q3X=RX-CEL2X
          Q1Y=PY-CEL1Y
          Q2Y=QY-CEL1Y
          Q3Y=RY-CEL2Y
          Q1Z=PZ-CEL1Z
          Q2Z=QZ-CEL1Z
          Q3Z=RZ-CEL2Z
          IF ((Q1X < -REDUCED_CEL1X).OR.(Q1X > REDUCED_CEL1X).OR.(Q2X < -REDUCED_CEL1X).OR.(Q2X > REDUCED_CEL1X).OR. &
              (Q1Y < -REDUCED_CEL1Y).OR.(Q1Y > REDUCED_CEL1Y).OR.(Q2Y < -REDUCED_CEL1Y).OR.(Q2Y > REDUCED_CEL1Y).OR. &
              (Q1Z < -REDUCED_CEL1Z).OR.(Q1Z > REDUCED_CEL1Z).OR.(Q2Z < -REDUCED_CEL1Z).OR.(Q2Z > REDUCED_CEL1Z).OR. &
              (Q3X < -CEL2X).OR.(Q3X > CEL2X).OR.(Q3Y < -CEL2Y).OR.(Q3Y > CEL2Y).OR.(Q3Z < -CEL2Z).OR.(Q3Z > CEL2Z)) &
          CALL PABORT('INTEGRAL FILE HAS BEEN DEGRADED')
          TNNNK(I,J,K,Q3X,Q3Y,Q3Z)=TNNNK(I,J,K,Q3X,Q3Y,Q3Z) &
           +CO(L,MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD)*PHASEX(KBX*(Q2X+Q3X))*PHASEY(KBY*(Q2Y+Q3Y))*PHASEZ(KBZ*(Q2Z+Q3Z)) &
           *PHASEX(KAX*Q1X)*PHASEY(KAY*Q1Y)*PHASEZ(KAZ*Q1Z)*DCMPLX(DCASHE(ICASHECOUNT),0.0D0)
         ENDDO
        ENDDO
        CLOSE(31)
       ENDDO
       IF ((IOPTN(9) >= 2).AND.(MYID == 0)) WRITE(6,'(F20.0,A,F7.3,A)') ICOUNT, &
       ' ERIS (',ICOUNT/DFLOAT((CEL1X*2+1)**2*(CEL2X+1)*(CEL1Y*2+1)**2*(CEL2Y+1)*(CEL1Z*2+1)**2*(CEL2Z+1)*NCGS**4)*100.0, &
       '% OF TOTAL ERIS) HAVE BEEN RESTORED'
       DO KJX=-KVCX2,MAX(0,KVCX2-1)
       DO KJY=-KVCY2,MAX(0,KVCY2-1)
       DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
        KIX=KAX-KJX+KBX
        KIY=KAY-KJY+KBY
        KIZ=KAZ-KJZ+KBZ
        IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
        IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
        IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
        IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
        IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
        IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
        DO MOJ=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KJX,KJY,KJZ)-IVIRTCORE)
         DO I=1,NCGS
          DO J=1,NCGS
           TNNOK(I,J,MOJ,KJX,KJY,KJZ)=DCMPLX(0.0D0,0.0D0)
           DO Q3X=-CEL2X,CEL2X
           DO Q3Y=-CEL2Y,CEL2Y
           DO Q3Z=-CEL2Z,CEL2Z
            DO K=1,NCGS
             TNNOK(I,J,MOJ,KJX,KJY,KJZ)=TNNOK(I,J,MOJ,KJX,KJY,KJZ)+TNNNK(I,J,K,Q3X,Q3Y,Q3Z) &
              *DCONJG(CO(K,MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD))*PHASEX(-KJX*Q3X)*PHASEY(-KJY*Q3Y)*PHASEZ(-KJZ*Q3Z)
            ENDDO
           ENDDO
           ENDDO
           ENDDO
          ENDDO
!write(*,*) i,j,moj,kjx,kjy,kjz,TNNOK(I,J,MOJ,KJX,KJY,KJZ)
          DO MOA=MAX(IOCC+1-IOPTN(44),ICORE+1),IALL(KAX,KAY,KAZ)-IVIRTCORE
           TNVOK(I,MOA,MOJ,KJX,KJY,KJZ)=DCMPLX(0.0D0,0.0D0)
           DO J=1,NCGS
            TNVOK(I,MOA,MOJ,KJX,KJY,KJZ)=TNVOK(I,MOA,MOJ,KJX,KJY,KJZ)+TNNOK(I,J,MOJ,KJX,KJY,KJZ) &
             *CO(J,MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)
           ENDDO
          ENDDO
!write(*,*) i,moa,moj,kjx,kjy,kjz,TNVOK(I,moa,MOJ,KJX,KJY,KJZ)
         ENDDO
         DO MOA=MAX(IOCC+1-IOPTN(44),ICORE+1),IALL(KAX,KAY,KAZ)-IVIRTCORE
          DO MOI=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KIX,KIY,KIZ)-IVIRTCORE)
           TOVOK(MOI,MOA,MOJ,KJX,KJY,KJZ)=DCMPLX(0.0D0,0.0D0)
           DO I=1,NCGS
            TOVOK(MOI,MOA,MOJ,KJX,KJY,KJZ)=TOVOK(MOI,MOA,MOJ,KJX,KJY,KJZ)+TNVOK(I,MOA,MOJ,KJX,KJY,KJZ) &
             *DCONJG(CO(I,MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD))
           ENDDO
!write(*,'(6i3,2f20.10)') moi,moa,moj,kjx,kjy,kjz,ToVOK(moi,moa,MOJ,KJX,KJY,KJZ)
          ENDDO
         ENDDO
        ENDDO
       ENDDO
       ENDDO
       ENDDO
!----- ACCUMULATE E(2)
       DO KJX=-KVCX2,MAX(0,KVCX2-1)
       DO KJY=-KVCY2,MAX(0,KVCY2-1)
       DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
        KIX=KAX-KJX+KBX
        KIY=KAY-KJY+KBY
        KIZ=KAZ-KJZ+KBZ
        IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
        IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
        IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
        IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
        IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
        IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
        DO MOA=IOCC+1,IALL(KAX,KAY,KAZ)-IVIRTCORE
         DO MOI=ICORE+1,IOCC
          DO MOJ=ICORE+1,IOCC
!write(*,'(8i3,2f20.10)') kix,kjx,kax,kbx,moi,moj,moa,mob,tovok(moi,moa,moj,kjx,kjy,kjz)
           EMP2S_TMP=EMP2S_TMP &
            +(0.5D0*TOVOK(MOI,MOA,MOJ,KJX,KJY,KJZ)*DCONJG(TOVOK(MOI,MOA,MOJ,KJX,KJY,KJZ)) &
            + 0.5D0*DREAL(TOVOK(MOI,MOA,MOJ,KJX,KJY,KJZ)*DCONJG(TOVOK(MOJ,MOA,MOI,KIX,KIY,KIZ)))) &
            /(EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
             -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))
           EMP2T_TMP=EMP2T_TMP &
            +(1.5D0*TOVOK(MOI,MOA,MOJ,KJX,KJY,KJZ)*DCONJG(TOVOK(MOI,MOA,MOJ,KJX,KJY,KJZ)) &
            - 1.5D0*DREAL(TOVOK(MOI,MOA,MOJ,KJX,KJY,KJZ)*DCONJG(TOVOK(MOJ,MOA,MOI,KIX,KIY,KIZ)))) &
            /(EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
             -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))
          ENDDO
         ENDDO
        ENDDO
       ENDDO
       ENDDO
       ENDDO
! ---- ACCUMULATE EPSILON(2)
       IF (IOPTN(44) > 0) THEN
        DO KJX=-KVCX2,MAX(0,KVCX2-1)
        DO KJY=-KVCY2,MAX(0,KVCY2-1)
        DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
         KGX=KAX-KJX+KBX
         KGY=KAY-KJY+KBY
         KGZ=KAZ-KJZ+KBZ
         IF (KGX >= KVCX2) KGX=KGX-2*KVCX2
         IF (KGY >= KVCY2) KGY=KGY-2*KVCY2
         IF (KGZ >= KVCZ2) KGZ=KGZ-2*KVCZ2
         IF (KGX < -KVCX2) KGX=KGX+2*KVCX2
         IF (KGY < -KVCY2) KGY=KGY+2*KVCY2
         IF (KGZ < -KVCZ2) KGZ=KGZ+2*KVCZ2
         IF (MOA >= IOCC+1) THEN
          DO MOJ=ICORE+1,IOCC
           DO MOA=IOCC+1,IALL(KAX,KAY,KAZ)-IVIRTCORE
            DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
             QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
              +(2.0D0*TOVOK(MOG,MOA,MOJ,KJX,KJY,KJZ)*DCONJG(TOVOK(MOG,MOA,MOJ,KJX,KJY,KJZ)) &
              - DREAL(TOVOK(MOG,MOA,MOJ,KJX,KJY,KJZ)*DCONJG(TOVOK(MOJ,MOA,MOG,KGX,KGY,KGZ)))) &
              /(EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
               -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))
            ENDDO
           ENDDO
          ENDDO
         ENDIF
        ENDDO
        ENDDO
        ENDDO
        KGX=KAX
        KGY=KAY
        KGZ=KAZ
        DO KJX=-KVCX2,MAX(0,KVCX2-1)
        DO KJY=-KVCY2,MAX(0,KVCY2-1)
        DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
         KIX=KGX-KJX+KBX
         KIY=KGY-KJY+KBY
         KIZ=KGZ-KJZ+KBZ
         IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
         IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
         IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
         IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
         IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
         IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
         DO MOJ=ICORE+1,IOCC
          DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
           DO MOI=ICORE+1,IOCC
            QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
             +(2.0D0*TOVOK(MOI,MOG,MOJ,KJX,KJY,KJZ)*DCONJG(TOVOK(MOI,MOG,MOJ,KJX,KJY,KJZ)) &
             - DREAL(TOVOK(MOI,MOG,MOJ,KJX,KJY,KJZ)*DCONJG(TOVOK(MOJ,MOG,MOI,KIX,KIY,KIZ)))) &
             /(EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD) &
              -EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)-EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD))
           ENDDO
          ENDDO
         ENDDO
        ENDDO
        ENDDO
        ENDDO
       ENDIF
! ---- END ACCUMULATE
! ---- PARALLEL LOOP
       CALL PCPU_TIME(ICPUE)
       IF (MYID == 0) WRITE(6,'(A,F6.2,A,F10.1,A)') ' ... ', &
         DFLOAT(((((((KBX+KVCX2)*MAX(1,2*KVCY2)+(KBY+KVCY2))*MAX(1,2*KVCZ2)+(KBZ+KVCZ2))*(IALL(KBX,KBY,KBZ)-IVIRTCORE-IOCC) &
         +(MOB-IOCC))*MAX(1,2*KVCX2)+(KAX+KVCX2))*MAX(1,2*KVCY2)+(KAY+KVCY2))*MAX(1,2*KVCZ2)+(KAZ+KVCZ2)) &
         /DFLOAT((IALL(KBX,KBY,KBZ)-IVIRTCORE-IOCC)*MAX(1,2*KVCX2)**2*MAX(1,2*KVCY2)**2*MAX(1,2*KVCZ2)**2)*100.0D0, &
         ' % OF MP2 ENERGY EVALUATION (CPU / SEC = ',ICPUE-ICPUS,')'
       CALL PCPU_TIME(ICPUS)
       CALL PFLUSH(6)
      ENDIF
! ---- PARALLEL LOOP
     ENDDO
     ENDDO
     ENDDO
    ENDDO
   ENDDO
   ENDDO
   ENDDO

   CALL MPI_ALLREDUCE(EMP2S_TMP,EMP2S,1,MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERR)
   CALL MPI_ALLREDUCE(EMP2T_TMP,EMP2T,1,MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERR)

   EMP2S=EMP2S/DFLOAT(MAX(1,8*KVCX2**3))/DFLOAT(MAX(1,8*KVCY2**3))/DFLOAT(MAX(1,8*KVCZ2**3))
   EMP2T=EMP2T/DFLOAT(MAX(1,8*KVCX2**3))/DFLOAT(MAX(1,8*KVCY2**3))/DFLOAT(MAX(1,8*KVCZ2**3))
   EMP2=EMP2S+EMP2T
   IF (MYID == 0) WRITE(6,'(A,F20.15,A)') 'E(2) SINGLET = ',EMP2S,' HARTREE'
   IF (MYID == 0) WRITE(6,'(A,F20.15,A)') 'E(2) TRIPLET = ',EMP2T,' HARTREE'
   IF (MYID == 0) WRITE(6,'(A,F20.15,A)') 'E(2)         = ',EMP2, ' HARTREE'
   IF (MYID == 0) WRITE(6,'(A,F20.15,A)') 'EMP2         = ',EHFKS+EMP2,' HARTREE'

   IF (IOPTN(44) > 0) THEN
    CALL MPI_ALLREDUCE(QEPSILON_TMP,QEPSILON,NCGS*(KVCX*2+1)*(KVCY*2+1)*(KVCZ*2+1),MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERR)
    DO KGX=-KVCX2,MAX(0,KVCX2-1)
    DO KGY=-KVCY2,MAX(0,KVCY2-1)
    DO KGZ=-KVCZ2,MAX(0,KVCZ2-1)
     DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
      QEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
       +QEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)/DFLOAT(MAX(1,4*KVCX2**2))/DFLOAT(MAX(1,4*KVCY2**2))/DFLOAT(MAX(1,4*KVCZ2**2))
     ENDDO
    ENDDO
    ENDDO
    ENDDO
   ENDIF

   DEALLOCATE(QEPSILON_TMP)
   DEALLOCATE(ICASHE1X,ICASHE1Y,ICASHE1Z,ICASHE2,DCASHE)
   DEALLOCATE(PHASEX,PHASEY,PHASEZ)
   DEALLOCATE(TOVOK,TNVOK,TNNOK,TNNNK)

   RETURN
END SUBROUTINE



SUBROUTINE MP2_ENERGY_ALG3
! SAME AS ABOVE BUT USES MUCH LESS MEMORY BY SPACE-TIME TRADEOFF.

   USE MPI
   USE CONSTANTS
   USE CONTROL
   USE STRUCTURE
   USE BASISSET
   USE INTEGRAL
   USE GRADIENT
   
   IMPLICIT NONE
   INCLUDE "mpif.h"
   DOUBLE PRECISION :: ICPUS,ICPUE
   INTEGER,PARAMETER :: CASHESIZE = 1000 ! CASHE SIZE MUST BE EXACTLY THE SAME IN THE STORE & RESTORE SUBROUTINES
!  LOGICAL :: LKJOB
!  INTEGER :: KJOBS,KJOBE
   INTEGER :: MOI,MOJ,MOA,MOB,MOG
   INTEGER :: KIX,KIY,KIZ,KJX,KJY,KJZ,KAX,KAY,KAZ,KBX,KBY,KBZ,KGX,KGY,KGZ
   INTEGER :: Q1X,Q1Y,Q1Z,Q2X,Q2Y,Q2Z,Q3X,Q3Y,Q3Z
   INTEGER :: I,J,K,L,PX,PY,PZ,QX,QY,QZ,RX,RY,RZ
   INTEGER :: EOF
   INTEGER :: ICASHECOUNT
   DOUBLE PRECISION :: ICOUNT,ICOUNTTOTAL
   INTEGER(4),ALLOCATABLE :: ICASHE1X(:),ICASHE1Y(:),ICASHE1Z(:),ICASHE2(:)
   DOUBLE PRECISION,ALLOCATABLE :: DCASHE(:)
   DOUBLE PRECISION :: EMP2,EMP2S,EMP2T,EMP2S_TMP,EMP2T_TMP
   DOUBLE COMPLEX,ALLOCATABLE :: PHASEX(:),PHASEY(:),PHASEZ(:)
   DOUBLE COMPLEX,ALLOCATABLE :: TNNK(:,:,:,:,:),TOK(:,:,:,:),TOOK(:,:,:,:,:)
   DOUBLE PRECISION,ALLOCATABLE :: QEPSILON_TMP(:,:,:,:)
   INTEGER :: KVCX2,KVCY2,KVCZ2
   INTEGER :: NMOD
!  INTEGER,ALLOCATABLE :: KVC3(:)
!  LOGICAL,ALLOCATABLE :: LKVC(:,:)
   INTEGER :: TICKET
   INTEGER :: NFILES,IFILE,JFILE
   LOGICAL :: LEXIST
   CHARACTER(6) :: FILEAPPENDIX
! -- HELIX 
   DOUBLE COMPLEX,ALLOCATABLE :: CO_HELIX(:,:,:,:)
! -- HELIX

! -- HELIX 
   IF (HELIX /= 0.0D0) THEN
    ALLOCATE(CO_HELIX(NCGS,NCGS,-KVCX:KVCX,-CEL1X-CEL2X:CEL1X+CEL2X))
    DO KIX=-KVCX,MAX(0,KVCX-1)
     DO MOI=ICORE+1,IALL(KIX,0,0)
      DO PX=-CEL1X-CEL2X,CEL1X+CEL2X
       DO I=1,NCGS
        CO_HELIX(I,MOI,KIX,PX)=DCMPLX(0.0D0,0.0D0)
        DO J=1,NCGS
         CO_HELIX(I,MOI,KIX,PX)=CO_HELIX(I,MOI,KIX,PX)+CO(J,MOI,KIX,0,0)*C2H(J,I,PX)
        ENDDO
       ENDDO
      ENDDO
     ENDDO
    ENDDO
   ENDIF
! -- HELIX 

!  ALLOCATE(KVC3(ICORE+1:IALLMAX-IVIRTCORE),LKVC(ICORE+1:IALLMAX-IVIRTCORE,-KVC:KVC))
   NMOD = IOPTN(99)
   IF (NMOD < 1) CALL PABORT('ILLEGAL MODULO PARAMETER')
   IF (NMOD > 1) THEN
    IF (MYID == 0) WRITE(6,'(A)') '******************************************************************************'
    IF (MYID == 0) WRITE(6,'(A,I3,A)') '* MP2 ENERGY CORRECTION AND QUASI-PARTICLE ENERGY CORRECTIONS WITH MOD = ',NMOD,' *'
    IF (MYID == 0) WRITE(6,'(A)') '******************************************************************************'
    IF (KVCX/NMOD*NMOD /= KVCX) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG X')
    IF (KVCY/NMOD*NMOD /= KVCY) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG Y')
    IF (KVCZ/NMOD*NMOD /= KVCZ) CALL PABORT('MODULO MUST EVENLY DIVIDE KPOINTS ALONG Z')
    KVCX2=KVCX/NMOD
    KVCY2=KVCY/NMOD
    KVCZ2=KVCZ/NMOD
   ELSE
    KVCX2=KVCX
    KVCY2=KVCY
    KVCZ2=KVCZ
   ENDIF 

   ALLOCATE(ICASHE1X(CASHESIZE),ICASHE1Y(CASHESIZE),ICASHE1Z(CASHESIZE),ICASHE2(CASHESIZE),DCASHE(CASHESIZE))
   ALLOCATE(PHASEX(-(CEL1X+CEL2X)*KVCX2:(CEL1X+CEL2X)*KVCX2))
   ALLOCATE(PHASEY(-(CEL1Y+CEL2Y)*KVCY2:(CEL1Y+CEL2Y)*KVCY2))
   ALLOCATE(PHASEZ(-(CEL1Z+CEL2Z)*KVCZ2:(CEL1Z+CEL2Z)*KVCZ2))
   ALLOCATE(QEPSILON_TMP(NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))

   IF (MYID == 0) WRITE(6,'(A)') 'CALCULATE MP2 ENERGY (ALGORITHM 3)'
   IF (IOPTN(27) /= 0) CALL WARNING('FROZEN CORE APPROXIMATION WILL BE USED')
   IF (IOPTN(55) /= 0) CALL WARNING('FROZEN VIRTUAL APPROXIMATION WILL BE USED')
   IF (IALLMAX-IOCC-IVIRTCORE <= 0) THEN
    CALL WARNING('THERE IS NO VIRTUAL ORBITAL --- MP2 CORRECTION IS NULL')
    RETURN
   ENDIF
   IF (IOPTN(44) == 0) THEN
    IF (MYID == 0) WRITE(6,'(A)') 'NO QUASI-PARTICLE ENERGY CALCULATION REQUESTED'
   ELSE IF (IOPTN(44) <= NCGS) THEN
    IF (MYID == 0) WRITE(6,'(A,I3,A,I3,A)') 'MP2 QUASI-PARTICLE ENERGY CALCULATIONS FOR',IOPTN(44), &
     ' OCCUPIED AND ',IOPTN(44),' VIRTUAL BANDS WILL BE PERFORMED'
   ELSE
    IF (MYID == 0) WRITE(6,'(A)') 'MP2 QUASI-PARTICLE ENERGY CALCULATIONS FOR ALL OCCUPIED AND VIRTUAL BANDS WILL BE PERFORMED'
   ENDIF
   CALL PFLUSH(6)
!  KJOBS=IOPTN(47)
!  KJOBE=IOPTN(48)
!  IF ((KJOBS >= -KVC2).AND.(KJOBE <= MAX(0,KVC2-1)).AND.(KJOBS <= KJOBE)) THEN
!   LKJOB=.TRUE.
!   WRITE(6,'(A)') '*************************************************************************************'
!   WRITE(6,'(A,I3,A,I3,A)') '* MP2 ENERGY CORRECTION AND QUASI-PARTICLE ENERGY CORRECTIONS FROM KVC = ',KJOBS,' TO ',KJOBE,' *'
!   WRITE(6,'(A)') '*************************************************************************************'
!  ELSE
!   LKJOB=.FALSE.
!   KJOBS=-KVC2
!   KJOBE=MAX(0,KVC2-1)
!  ENDIF

   NFILES=0
   IF (MYID == 0) THEN
    DO WHILE (.TRUE.)
     WRITE(FILEAPPENDIX,'(I6)') 100000+NFILES
     INQUIRE(FILE=TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6),EXIST=LEXIST)
     IF (LEXIST) THEN
      WRITE(6,'(A)') TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6)//' IS FOUND'
      NFILES=NFILES+1
     ELSE
      EXIT
     ENDIF
    ENDDO
   ENDIF
   CALL MPI_BCAST(NFILES,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   IF (NFILES == 0) CALL PABORT('NO ERI FILES WAS FOUND')

   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT(NCGS**2*(2*CEL2X+1)*(2*CEL2Y+1)*(2*CEL2Z+1))/1.0D3,' K WORDS (TNNK)'
   CALL PFLUSH(6)
   ALLOCATE(TNNK(NCGS,NCGS,-CEL2X:CEL2X,-CEL2Y:CEL2Y,-CEL2Z:CEL2Z))
   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT((MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE)-ICORE-2)*(2*KVCX2+1)*(2*KVCY2+1)*(2*KVCZ2+1)) &
    /1.0D3,' K WORDS (TOK)'
   CALL PFLUSH(6)
   ALLOCATE(TOK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),-KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2))
   IF (MYID == 0) WRITE(6,'(F20.0,A)') DFLOAT((MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE)-ICORE-2)**2 &
    *(2*KVCX2+1)*(2*KVCY2+1)*(2*KVCZ2+1))/1.0D3,' K WORDS (TOOK)'
   CALL PFLUSH(6)
   ALLOCATE(TOOK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),&
            -KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2))

   DO I=-(CEL1X+CEL2X)*KVCX2,(CEL1X+CEL2X)*KVCX2
    IF (KVCX2 == 0) THEN
     PHASEX(I)=DCMPLX(1.0D0,0.0D0)
    ELSE
     PHASEX(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCX2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCX2)*PI))
    ENDIF
   ENDDO
   DO I=-(CEL1Y+CEL2Y)*KVCY2,(CEL1Y+CEL2Y)*KVCY2
    IF (KVCY2 == 0) THEN
     PHASEY(I)=DCMPLX(1.0D0,0.0D0)
    ELSE
     PHASEY(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCY2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCY2)*PI))
    ENDIF
   ENDDO
   DO I=-(CEL1Z+CEL2Z)*KVCZ2,(CEL1Z+CEL2Z)*KVCZ2
    IF (KVCZ2 == 0) THEN
     PHASEZ(I)=DCMPLX(1.0D0,0.0D0)
    ELSE
     PHASEZ(I)=DCMPLX(DCOS(DFLOAT(I)/DFLOAT(KVCZ2)*PI),DSIN(DFLOAT(I)/DFLOAT(KVCZ2)*PI))
    ENDIF
   ENDDO

   EMP2S=0.0D0
   EMP2T=0.0D0
   EMP2S_TMP=0.0D0
   EMP2T_TMP=0.0D0
   QEPSILON=0.0D0
   QEPSILON_TMP=0.0D0

   ! COMPUTE E(2) AND QUASI-PARTICLE ENERGY BANDS
   CALL PCPU_TIME(ICPUS)
   TICKET=0
   DO KBX=-KVCX2,MAX(0,KVCX2-1)
   DO KBY=-KVCY2,MAX(0,KVCY2-1)
   DO KBZ=-KVCZ2,MAX(0,KVCZ2-1)
    DO MOB=IOCC+1,IALL(KBX,KBY,KBZ)-IVIRTCORE
     DO KAX=-KVCX2,MAX(0,KVCX2-1)
     DO KAY=-KVCY2,MAX(0,KVCY2-1)
     DO KAZ=-KVCZ2,MAX(0,KVCZ2-1)
      DO MOA=MAX(IOCC+1-IOPTN(44),ICORE+1),IALL(KAX,KAY,KAZ)-IVIRTCORE
! ---- PARALLEL LOOP
       TICKET=TICKET+1
       IF (TICKET == NUMPROCS) TICKET=TICKET-NUMPROCS
       IF (MYID == TICKET) THEN
!write(*,*) 'Process:',myid,'KBs = ',KBX,KBY,KBZ,'MOB = ',MOB
! ---- PARALLEL LOOP
        TNNK=DCMPLX(0.0D0,0.0D0)
        DO IFILE=1,NFILES
         JFILE=IFILE+MYID-1
         JFILE=JFILE-JFILE/NFILES*NFILES
         WRITE(FILEAPPENDIX,'(I6)') 100000+JFILE
!write(*,*) 'Process:',myid,' reading from ',TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6)
         OPEN(31,FILE=TRIM(COPTN(1))//'.ao.'//FILEAPPENDIX(2:6),FORM='UNFORMATTED')
         REWIND(31)
         ICOUNT=0.0D0
         DO
          READ(31,IOSTAT=EOF) ICASHE1X,ICASHE1Y,ICASHE1Z,ICASHE2,DCASHE
          IF (EOF /= 0) EXIT
          DO ICASHECOUNT=1,CASHESIZE
           IF (ICASHE1X(ICASHECOUNT) == -1) EXIT
           ICOUNT=ICOUNT+1.0D0
           PX=0
           QX=0
           RX=0
           PY=0
           QY=0
           RY=0
           PZ=0
           QZ=0
           RZ=0
           I=0
           J=0
           K=0
           L=0
           CALL MVBITS(ICASHE1X(ICASHECOUNT),16,8,PX,0)
           CALL MVBITS(ICASHE1X(ICASHECOUNT), 8,8,QX,0)
           CALL MVBITS(ICASHE1X(ICASHECOUNT), 0,8,RX,0)
           CALL MVBITS(ICASHE1Y(ICASHECOUNT),16,8,PY,0)
           CALL MVBITS(ICASHE1Y(ICASHECOUNT), 8,8,QY,0)
           CALL MVBITS(ICASHE1Y(ICASHECOUNT), 0,8,RY,0)
           CALL MVBITS(ICASHE1Z(ICASHECOUNT),16,8,PZ,0)
           CALL MVBITS(ICASHE1Z(ICASHECOUNT), 8,8,QZ,0)
           CALL MVBITS(ICASHE1Z(ICASHECOUNT), 0,8,RZ,0)
           CALL MVBITS(ICASHE2(ICASHECOUNT),24,8,I,0)
           CALL MVBITS(ICASHE2(ICASHECOUNT),16,8,J,0)
           CALL MVBITS(ICASHE2(ICASHECOUNT), 8,8,K,0)
           CALL MVBITS(ICASHE2(ICASHECOUNT), 0,8,L,0)
           Q1X=PX-CEL1X
           Q2X=QX-CEL1X
           Q3X=RX-CEL2X
           Q1Y=PY-CEL1Y
           Q2Y=QY-CEL1Y
           Q3Y=RY-CEL2Y
           Q1Z=PZ-CEL1Z
           Q2Z=QZ-CEL1Z
           Q3Z=RZ-CEL2Z
           IF ((Q1X < -REDUCED_CEL1X).OR.(Q1X > REDUCED_CEL1X).OR.(Q2X < -REDUCED_CEL1X).OR.(Q2X > REDUCED_CEL1X).OR. &
               (Q1Y < -REDUCED_CEL1Y).OR.(Q1Y > REDUCED_CEL1Y).OR.(Q2Y < -REDUCED_CEL1Y).OR.(Q2Y > REDUCED_CEL1Y).OR. &
               (Q1Z < -REDUCED_CEL1Z).OR.(Q1Z > REDUCED_CEL1Z).OR.(Q2Z < -REDUCED_CEL1Z).OR.(Q2Z > REDUCED_CEL1Z).OR. &
               (Q3X < -CEL2X).OR.(Q3X > CEL2X).OR.(Q3Y < -CEL2Y).OR.(Q3Y > CEL2Y).OR.(Q3Z < -CEL2Z).OR.(Q3Z > CEL2Z)) &
           CALL PABORT('INTEGRAL FILE HAS BEEN DEGRADED')
           IF (HELIX == 0.0D0) THEN
            TNNK(I,K,Q3X,Q3Y,Q3Z)=TNNK(I,K,Q3X,Q3Y,Q3Z) &
            +CO(L,MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD)*PHASEX(KBX*(Q2X+Q3X))*PHASEY(KBY*(Q2Y+Q3Y))*PHASEZ(KBZ*(Q2Z+Q3Z)) &
            *CO(J,MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)*PHASEX(KAX*Q1X)*PHASEY(KAY*Q1Y)*PHASEZ(KAZ*Q1Z) &
            *DCMPLX(DCASHE(ICASHECOUNT),0.0D0)
           ELSE ! -- HELIX
            TNNK(I,K,Q3X,Q3Y,Q3Z)=TNNK(I,K,Q3X,Q3Y,Q3Z) &
            +CO_HELIX(L,MOB,KBX*NMOD,Q2X+Q3X)*PHASEX(KBX*(Q2X+Q3X))*PHASEY(KBY*(Q2Y+Q3Y))*PHASEZ(KBZ*(Q2Z+Q3Z)) &
            *CO_HELIX(J,MOA,KAX*NMOD,Q1X)*PHASEX(KAX*Q1X)*PHASEY(KAY*Q1Y)*PHASEZ(KAZ*Q1Z) &
            *DCMPLX(DCASHE(ICASHECOUNT),0.0D0)
           ENDIF ! -- HELIX
          ENDDO
         ENDDO
         CLOSE(31)
        ENDDO
        IF ((IOPTN(9) >= 2).AND.(MYID == 0)) WRITE(6,'(F20.0,A,F7.3,A)') ICOUNT, &
        ' ERIS (',ICOUNT/DFLOAT((CEL1X*2+1)**2*(CEL2X+1)*(CEL1Y*2+1)**2*(CEL2Y+1)*(CEL1Z*2+1)**2*(CEL2Z+1)*NCGS**4)*100.0, &
        '% OF TOTAL ERIS) HAVE BEEN RESTORED'
        TOOK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE), &
             -KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2)=DCMPLX(0.0D0,0.0D0)
        DO I=1,NCGS
         TOK(ICORE+1:MIN(IOCC+IOPTN(44),IALLMAX-IVIRTCORE),-KVCX2:KVCX2,-KVCY2:KVCY2,-KVCZ2:KVCZ2)=DCMPLX(0.0D0,0.0D0)
         DO KJX=-KVCX2,MAX(0,KVCX2-1)
         DO KJY=-KVCY2,MAX(0,KVCY2-1)
         DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
          DO Q3X=-CEL2X,CEL2X
          DO Q3Y=-CEL2Y,CEL2Y
          DO Q3Z=-CEL2Z,CEL2Z
           DO K=1,NCGS
            DO MOJ=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KJX,KJY,KJZ)-IVIRTCORE)
             IF (HELIX == 0.0D0) THEN
              TOK(MOJ,KJX,KJY,KJZ)=TOK(MOJ,KJX,KJY,KJZ)+TNNK(I,K,Q3X,Q3Y,Q3Z) &
              *DCONJG(CO(K,MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD))*PHASEX(-KJX*Q3X)*PHASEY(-KJY*Q3Y)*PHASEZ(-KJZ*Q3Z)
             ELSE ! -- HELIX
              TOK(MOJ,KJX,KJY,KJZ)=TOK(MOJ,KJX,KJY,KJZ)+TNNK(I,K,Q3X,Q3Y,Q3Z) &
              *DCONJG(CO_HELIX(K,MOJ,KJX*NMOD,Q3X))*PHASEX(-KJX*Q3X)*PHASEY(-KJY*Q3Y)*PHASEZ(-KJZ*Q3Z)
             ENDIF ! -- HELIX
            ENDDO
           ENDDO
          ENDDO
          ENDDO
          ENDDO
         ENDDO
         ENDDO
         ENDDO
         DO KJX=-KVCX2,MAX(0,KVCX2-1)
         DO KJY=-KVCY2,MAX(0,KVCY2-1)
         DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
          KIX=KAX-KJX+KBX
          KIY=KAY-KJY+KBY
          KIZ=KAZ-KJZ+KBZ
          IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
          IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
          IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
          IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
          IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
          IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
          DO MOJ=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KJX,KJY,KJZ)-IVIRTCORE)
           DO MOI=ICORE+1,MIN(IOCC+IOPTN(44),IALL(KIX,KIY,KIZ)-IVIRTCORE)
            IF (HELIX == 0.0D0) THEN
             TOOK(MOI,MOJ,KJX,KJY,KJZ)=TOOK(MOI,MOJ,KJX,KJY,KJZ) &
             +TOK(MOJ,KJX,KJY,KJZ)*DCONJG(CO(I,MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD))
            ELSE ! -- HELIX
             TOOK(MOI,MOJ,KJX,KJY,KJZ)=TOOK(MOI,MOJ,KJX,KJY,KJZ) &
             +TOK(MOJ,KJX,KJY,KJZ)*DCONJG(CO_HELIX(I,MOI,KIX*NMOD,0))
            ENDIF ! -- HELIX
           ENDDO
          ENDDO
         ENDDO
         ENDDO
         ENDDO
        ENDDO
! ----- ACCUMULATE E(2)
        DO KJX=-KVCX2,MAX(0,KVCX2-1)
        DO KJY=-KVCY2,MAX(0,KVCY2-1)
        DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
         KIX=KAX-KJX+KBX
         KIY=KAY-KJY+KBY
         KIZ=KAZ-KJZ+KBZ
         IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
         IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
         IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
         IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
         IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
         IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
         IF (MOA >= IOCC+1) THEN
          DO MOI=ICORE+1,IOCC
           DO MOJ=ICORE+1,IOCC
!write(*,'(8i3,2f20.10)') kix,kjx,kax,kbx,moi,moj,moa,mob,took(moi,moj,kjx,kjy,kjz)
            EMP2S_TMP=EMP2S_TMP &
              +(0.5D0*TOOK(MOI,MOJ,KJX,KJY,KJZ)*DCONJG(TOOK(MOI,MOJ,KJX,KJY,KJZ)) &
              + 0.5D0*DREAL(TOOK(MOI,MOJ,KJX,KJY,KJZ)*DCONJG(TOOK(MOJ,MOI,KIX,KIY,KIZ)))) &
              /(EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
               -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))
            EMP2T_TMP=EMP2T_TMP &
              +(1.5D0*TOOK(MOI,MOJ,KJX,KJY,KJZ)*DCONJG(TOOK(MOI,MOJ,KJX,KJY,KJZ)) &
              - 1.5D0*DREAL(TOOK(MOI,MOJ,KJX,KJY,KJZ)*DCONJG(TOOK(MOJ,MOI,KIX,KIY,KIZ)))) &
              /(EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
               -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))
           ENDDO
          ENDDO
         ENDIF
        ENDDO
        ENDDO
        ENDDO
! ----- ACCUMULATE EPSILON(2)
        IF (IOPTN(44) > 0) THEN
         DO KJX=-KVCX2,MAX(0,KVCX2-1)
         DO KJY=-KVCY2,MAX(0,KVCY2-1)
         DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
          KGX=KAX-KJX+KBX
          KGY=KAY-KJY+KBY
          KGZ=KAZ-KJZ+KBZ
          IF (KGX >= KVCX2) KGX=KGX-2*KVCX2
          IF (KGY >= KVCY2) KGY=KGY-2*KVCY2
          IF (KGZ >= KVCZ2) KGZ=KGZ-2*KVCZ2
          IF (KGX < -KVCX2) KGX=KGX+2*KVCX2
          IF (KGY < -KVCY2) KGY=KGY+2*KVCY2
          IF (KGZ < -KVCZ2) KGZ=KGZ+2*KVCZ2
          IF (MOA >= IOCC+1) THEN
           DO MOJ=ICORE+1,IOCC
            DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
             QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
              +(2.0D0*TOOK(MOG,MOJ,KJX,KJY,KJZ)*DCONJG(TOOK(MOG,MOJ,KJX,KJY,KJZ)) &
              - DREAL(TOOK(MOG,MOJ,KJX,KJY,KJZ)*DCONJG(TOOK(MOJ,MOG,KGX,KGY,KGZ)))) &
              /(EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD) &
               -EPSILON(MOA,KAX*NMOD,KAY*NMOD,KAZ*NMOD)-EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD))
            ENDDO
           ENDDO
          ENDIF
         ENDDO
         ENDDO
         ENDDO
         MOG=MOA
         KGX=KAX
         KGY=KAY
         KGZ=KAZ
         DO KJX=-KVCX2,MAX(0,KVCX2-1)
         DO KJY=-KVCY2,MAX(0,KVCY2-1)
         DO KJZ=-KVCZ2,MAX(0,KVCZ2-1)
          KIX=KGX-KJX+KBX
          KIY=KGY-KJY+KBY
          KIZ=KGZ-KJZ+KBZ
          IF (KIX >= KVCX2) KIX=KIX-2*KVCX2
          IF (KIY >= KVCY2) KIY=KIY-2*KVCY2
          IF (KIZ >= KVCZ2) KIZ=KIZ-2*KVCZ2
          IF (KIX < -KVCX2) KIX=KIX+2*KVCX2
          IF (KIY < -KVCY2) KIY=KIY+2*KVCY2
          IF (KIZ < -KVCZ2) KIZ=KIZ+2*KVCZ2
          DO MOJ=ICORE+1,IOCC
           DO MOI=ICORE+1,IOCC
            QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=QEPSILON_TMP(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
             +(2.0D0*TOOK(MOI,MOJ,KJX,KJY,KJZ)*DCONJG(TOOK(MOI,MOJ,KJX,KJY,KJZ)) &
             - DREAL(TOOK(MOI,MOJ,KJX,KJY,KJZ)*DCONJG(TOOK(MOJ,MOI,KIX,KIY,KIZ)))) &
             /(EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)+EPSILON(MOB,KBX*NMOD,KBY*NMOD,KBZ*NMOD) &
              -EPSILON(MOI,KIX*NMOD,KIY*NMOD,KIZ*NMOD)-EPSILON(MOJ,KJX*NMOD,KJY*NMOD,KJZ*NMOD))
           ENDDO
          ENDDO
         ENDDO
         ENDDO
         ENDDO
        ENDIF
! ----- END ACCUMULATE
! ----- PARALLEL LOOP
       ENDIF
! ----- PARALLEL LOOP
      ENDDO
     ENDDO
     ENDDO
     ENDDO
     CALL PCPU_TIME(ICPUE)
     IF (MYID == 0) WRITE(6,'(A,F6.2,A,F10.1,A)') ' ... ', &
       DFLOAT((((KBX+KVCX2)*MAX(1,2*KVCY2)+(KBY+KVCY2))*MAX(1,2*KVCZ2)+(KBZ+KVCZ2))*(IALL(KBX,KBY,KBZ)-IVIRTCORE-IOCC) &
       +(MOB-IOCC))/DFLOAT((IALL(KBX,KBY,KBZ)-IVIRTCORE-IOCC)*MAX(1,2*KVCX2)*MAX(1,2*KVCY2)*MAX(1,2*KVCZ2))*100.0D0, &
       ' % OF MP2 ENERGY EVALUATION (CPU / SEC = ',ICPUE-ICPUS,')'
     CALL PCPU_TIME(ICPUS)
     CALL PFLUSH(6)
    ENDDO
   ENDDO
   ENDDO
   ENDDO

   CALL MPI_ALLREDUCE(EMP2S_TMP,EMP2S,1,MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERR)
   CALL MPI_ALLREDUCE(EMP2T_TMP,EMP2T,1,MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERR)

   EMP2S=EMP2S/DFLOAT(MAX(1,8*KVCX2**3))/DFLOAT(MAX(1,8*KVCY2**3))/DFLOAT(MAX(1,8*KVCZ2**3))
   EMP2T=EMP2T/DFLOAT(MAX(1,8*KVCX2**3))/DFLOAT(MAX(1,8*KVCY2**3))/DFLOAT(MAX(1,8*KVCZ2**3))
   EMP2=EMP2S+EMP2T
   IF (MYID == 0) WRITE(6,'(A,F20.15,A)') 'E(2) SINGLET = ',EMP2S,' HARTREE'
   IF (MYID == 0) WRITE(6,'(A,F20.15,A)') 'E(2) TRIPLET = ',EMP2T,' HARTREE'
   IF (MYID == 0) WRITE(6,'(A,F20.15,A)') 'E(2)         = ',EMP2, ' HARTREE'
   IF (MYID == 0) WRITE(6,'(A,F20.15,A)') 'EMP2         = ',EHFKS+EMP2,' HARTREE'

   IF (IOPTN(44) > 0) THEN
    CALL MPI_ALLREDUCE(QEPSILON_TMP,QEPSILON,NCGS*(KVCX*2+1)*(KVCY*2+1)*(KVCZ*2+1),MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERR)
    DO KGX=-KVCX2,MAX(0,KVCX2-1)
    DO KGY=-KVCY2,MAX(0,KVCY2-1)
    DO KGZ=-KVCZ2,MAX(0,KVCZ2-1)
     DO MOG=MAX(IOCC+1-IOPTN(44),ICORE+1),MIN(IOCC+IOPTN(44),IALL(KGX,KGY,KGZ)-IVIRTCORE)
      QEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)=EPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD) &
       +QEPSILON(MOG,KGX*NMOD,KGY*NMOD,KGZ*NMOD)/DFLOAT(MAX(1,4*KVCX2**2))/DFLOAT(MAX(1,4*KVCY2**2))/DFLOAT(MAX(1,4*KVCZ2**2))
     ENDDO
    ENDDO
    ENDDO
    ENDDO
   ENDIF

   DEALLOCATE(QEPSILON_TMP)
   DEALLOCATE(ICASHE1X,ICASHE1Y,ICASHE1Z,ICASHE2,DCASHE)
   DEALLOCATE(PHASEX,PHASEY,PHASEZ)
   DEALLOCATE(TOK,TOOK,TNNK)
   IF (HELIX /= 0.0D0) DEALLOCATE(CO_HELIX)

   RETURN
END SUBROUTINE



SUBROUTINE FINITE_MP2_ENERGY
! TRANSFORM TWO-ELECTRON INTEGRALS BY O(N**5) ALGORITHM AND EVALUATE MP2 CORRECTION AT NONZERO TEMPERATURE.
! AO-BASED TWO-ELECTRON INTEGRALS ARE RETRIEVED FROM DISK. FOR MOLECULES ONLY!

   USE CONSTANTS
   USE CONTROL
   USE STRUCTURE
   USE BASISSET
   USE INTEGRAL
   USE GRADIENT
   
   IMPLICIT NONE
   DOUBLE PRECISION :: ICPUS,ICPUE
   INTEGER,PARAMETER :: CASHESIZE = 1000 ! CASHE SIZE MUST BE EXACTLY THE SAME IN THE STORE & RESTORE SUBROUTINES
!  LOGICAL :: LKJOB
!  INTEGER :: KJOBS,KJOBE
   INTEGER :: MOI,MOJ,MOA,MOB,MOG
   INTEGER :: KI,KJ,KA,KB,KG
   INTEGER :: Q1,Q2,Q3
   INTEGER :: I,J,K,L,PX,PY,PZ,QX,QY,QZ,RX,RY,RZ
   INTEGER :: EOF
   INTEGER :: ICASHECOUNT
   DOUBLE PRECISION :: ICOUNT,ICOUNTTOTAL
   INTEGER(4),ALLOCATABLE :: ICASHE1X(:),ICASHE1Y(:),ICASHE1Z(:),ICASHE2(:)
   DOUBLE PRECISION,ALLOCATABLE :: DCASHE(:)
   DOUBLE COMPLEX,ALLOCATABLE :: TNNNKK(:,:,:,:,:),TOK(:,:),TVOKK(:,:,:,:),TOVOKK(:,:,:,:,:)
   DOUBLE COMPLEX,ALLOCATABLE :: TALL(:,:,:,:)
   INTEGER :: KVC2
   INTEGER :: NMOD
   INTEGER,ALLOCATABLE :: KVC3(:)
   LOGICAL,ALLOCATABLE :: LKVC(:,:)
   DOUBLE PRECISION :: FI,FJ,FA,FB,D
   DOUBLE PRECISION :: MP0_OMEGA,MP0_U
   DOUBLE PRECISION :: MP1_OMEGA
   DOUBLE PRECISION :: MP2_N1,MP2_N2,MP2_A1,MP2_A2,MP2_K1,MP2_K2,MP2_R1,MP2_R2
   DOUBLE PRECISION,ALLOCATABLE :: FT(:,:),KL(:,:)

   KVC2=KVCX
   IF (KVCX /= 0) CALL PABORT('FINITE_MP2_ENERGY: MOLECULES ONLY!')
   IF (KVCY /= 0) CALL PABORT('FINITE_MP2_ENERGY: MOLECULES ONLY!')
   IF (KVCZ /= 0) CALL PABORT('FINITE_MP2_ENERGY: MOLECULES ONLY!')
   IF (KVC2 /= 0) CALL PABORT('FINITE_MP2_ENERGY: MOLECULES ONLY!')
   IF (CEL1X /= 0) CALL PABORT('FINITE_MP2_ENERGY: MOLECULES ONLY!')
   IF (CEL1Y /= 0) CALL PABORT('FINITE_MP2_ENERGY: MOLECULES ONLY!')
   IF (CEL1Z /= 0) CALL PABORT('FINITE_MP2_ENERGY: MOLECULES ONLY!')
   IF (CEL2X /= 0) CALL PABORT('FINITE_MP2_ENERGY: MOLECULES ONLY!')
   IF (CEL2Y /= 0) CALL PABORT('FINITE_MP2_ENERGY: MOLECULES ONLY!')
   IF (CEL2Z /= 0) CALL PABORT('FINITE_MP2_ENERGY: MOLECULES ONLY!')

   WRITE(6,'(A)') '*************************************************************'
   WRITE(6,'(A)') '* FIRST & SECOND-ORDER CORRECTIONS AT A NONZERO TEMPERATURE *'
   WRITE(6,'(A)') '*************************************************************'
   WRITE(6,'(A,E20.6,A)') 'TEMP      = ',DOPTN(98),' K'
   WRITE(6,'(A,F20.6,A)') 'FERMI     = ',FERMI,' HARTREE'

   ALLOCATE(ICASHE1X(CASHESIZE),ICASHE1Y(CASHESIZE),ICASHE1Z(CASHESIZE),ICASHE2(CASHESIZE),DCASHE(CASHESIZE))

   IF (IOPTN(27) /= 0) CALL WARNING('FROZEN CORE APPROXIMATION WILL BE USED')
   IF (IOPTN(55) /= 0) CALL WARNING('FROZEN VIRTUAL APPROXIMATION WILL BE USED')
   IF (IALLMAX-IOCC-IVIRTCORE <= 0) THEN
    CALL WARNING('THERE IS NO VIRTUAL ORBITAL --- MP2 CORRECTION IS NULL')
    RETURN
   ENDIF

   ALLOCATE(TNNNKK(NCGS,NCGS,NCGS,0:0,0:0))
   ALLOCATE(TOK(ICORE+1:IALLMAX-IVIRTCORE,0:0))
   ALLOCATE(TVOKK(ICORE+1:IALLMAX-IVIRTCORE,ICORE+1:IALLMAX-IVIRTCORE,0:0,0:0))
   ALLOCATE(TOVOKK(ICORE+1:IALLMAX-IVIRTCORE,ICORE+1:IALLMAX-IVIRTCORE,ICORE+1:IALLMAX-IVIRTCORE,0:0,0:0))
   ALLOCATE(TALL(ICORE+1:IALLMAX-IVIRTCORE,ICORE+1:IALLMAX-IVIRTCORE,ICORE+1:IALLMAX-IVIRTCORE,ICORE+1:IALLMAX-IVIRTCORE))
   ALLOCATE(FT(ICORE+1:IALLMAX-IVIRTCORE,ICORE+1:IALLMAX-IVIRTCORE),KL(ICORE+1:IALLMAX-IVIRTCORE,ICORE+1:IALLMAX-IVIRTCORE))

   CALL PCPU_TIME(ICPUS)
   DO KB=0,0
    DO MOB=ICORE+1,IALL(0,0,0)-IVIRTCORE
     REWIND(31)
     ICOUNT=0.0D0
     TNNNKK=DCMPLX(0.0D0,0.0D0)
     DO
      READ(31,IOSTAT=EOF) ICASHE1X,ICASHE1Y,ICASHE1Z,ICASHE2,DCASHE
      IF (EOF /= 0) EXIT
      DO ICASHECOUNT=1,CASHESIZE
       IF (ICASHE1X(ICASHECOUNT) == -1) EXIT
       ICOUNT=ICOUNT+1.0D0
       PX=0
       QX=0
       RX=0
       PY=0
       QY=0
       RY=0
       PZ=0
       QZ=0
       RZ=0
       I=0
       J=0
       K=0
       L=0
       CALL MVBITS(ICASHE1X(ICASHECOUNT),16,8,PX,0)
       CALL MVBITS(ICASHE1X(ICASHECOUNT), 8,8,QX,0)
       CALL MVBITS(ICASHE1X(ICASHECOUNT), 0,8,RX,0)
       CALL MVBITS(ICASHE1Y(ICASHECOUNT),16,8,PY,0)
       CALL MVBITS(ICASHE1Y(ICASHECOUNT), 8,8,QY,0)
       CALL MVBITS(ICASHE1Y(ICASHECOUNT), 0,8,RY,0)
       CALL MVBITS(ICASHE1Z(ICASHECOUNT),16,8,PZ,0)
       CALL MVBITS(ICASHE1Z(ICASHECOUNT), 8,8,QZ,0)
       CALL MVBITS(ICASHE1Z(ICASHECOUNT), 0,8,RZ,0)
       CALL MVBITS(ICASHE2(ICASHECOUNT),24,8,I,0)
       CALL MVBITS(ICASHE2(ICASHECOUNT),16,8,J,0)
       CALL MVBITS(ICASHE2(ICASHECOUNT), 8,8,K,0)
       CALL MVBITS(ICASHE2(ICASHECOUNT), 0,8,L,0)
       TNNNKK(I,J,K,0,0)=TNNNKK(I,J,K,0,0)+CO(L,MOB,KB*NMOD,0,0)*DCMPLX(DCASHE(ICASHECOUNT),0.0D0)
      ENDDO
     ENDDO
     IF (IOPTN(9) >= 2) WRITE(6,'(F20.0,A,F7.3,A)') ICOUNT, &
     ' ERIS (',ICOUNT/DFLOAT(NCGS**4)*100.0,'% OF TOTAL ERIS) HAVE BEEN RESTORED'
     TOVOKK(ICORE+1:IALLMAX-IVIRTCORE,ICORE+1:IALLMAX-IVIRTCORE, &
            ICORE+1:IALLMAX-IVIRTCORE,0:0,0:0)=DCMPLX(0.0D0,0.0D0)
     DO I=1,NCGS
      TVOKK(ICORE+1:IALLMAX-IVIRTCORE,ICORE+1:IALLMAX-IVIRTCORE,0:0,0:0)= DCMPLX(0.0D0,0.0D0)
      DO Q1=0,0
       DO J=1,NCGS
        TOK(ICORE+1:IALLMAX-IVIRTCORE,0:0)=DCMPLX(0.0D0,0.0D0)
        DO Q3=0,0
         DO K=1,NCGS
          DO KJ=0,0
           DO MOJ=ICORE+1,IALL(0,0,0)-IVIRTCORE
            TOK(MOJ,KJ)=TOK(MOJ,KJ)+TNNNKK(I,J,K,Q1,Q3)*DCONJG(CO(K,MOJ,KJ*NMOD,0,0))
           ENDDO
          ENDDO
         ENDDO
        ENDDO
        DO KJ=-KVC2,MAX(0,KVC2-1)
         DO KA=-KVC2,MAX(0,KVC2-1)
          DO MOJ=ICORE+1,IALL(0,0,0)-IVIRTCORE
           DO MOA=ICORE+1,IALL(0,0,0)-IVIRTCORE
            TVOKK(MOA,MOJ,KA,KJ)=TVOKK(MOA,MOJ,KA,KJ)+TOK(MOJ,KJ)*CO(J,MOA,KA*NMOD,0,0)
           ENDDO
          ENDDO
         ENDDO
        ENDDO
       ENDDO
      ENDDO
      DO KJ=-KVC2,MAX(0,KVC2-1)
       DO KA=-KVC2,MAX(0,KVC2-1)
        KI=KA-KJ+KB
        IF (KI >= KVC2) KI=KI-2*KVC2
        IF (KI < -KVC2) KI=KI+2*KVC2
        DO MOJ=ICORE+1,IALL(0,0,0)-IVIRTCORE
         DO MOA=ICORE+1,IALL(0,0,0)-IVIRTCORE
          DO MOI=ICORE+1,IALL(0,0,0)-IVIRTCORE
           TOVOKK(MOI,MOA,MOJ,KA,KJ)=TOVOKK(MOI,MOA,MOJ,KA,KJ)+TVOKK(MOA,MOJ,KA,KJ)*DCONJG(CO(I,MOI,KI*NMOD,0,0))
          ENDDO
         ENDDO
        ENDDO
       ENDDO
      ENDDO
     ENDDO
     DO MOJ=ICORE+1,IALL(0,0,0)-IVIRTCORE
      DO MOA=ICORE+1,IALL(0,0,0)-IVIRTCORE
       DO MOI=ICORE+1,IALL(0,0,0)-IVIRTCORE
        TALL(MOI,MOA,MOJ,MOB)=TOVOKK(MOI,MOA,MOJ,0,0)
       ENDDO
      ENDDO
     ENDDO
    ENDDO
   ENDDO

   DO MOI=ICORE+1,IALL(0,0,0)-IVIRTCORE
    DO MOJ=ICORE+1,IALL(0,0,0)-IVIRTCORE
     KL(MOI,MOJ)=0.0D0
     DO MOA=ICORE+1,IALL(0,0,0)-IVIRTCORE
      FA=1.0D0/(DEXP((EPSILON(MOA,0,0,0)-FERMI)/BOLTZMANN/DOPTN(98))+1.0D0)
      KL(MOI,MOJ)=KL(MOI,MOJ)+(2.0D0*DREAL(TALL(MOI,MOJ,MOA,MOA))-DREAL(TALL(MOI,MOA,MOA,MOJ))) &
       *FA
     ENDDO
    ENDDO
   ENDDO
   
   FT=0.0D0
   DO MOI=ICORE+1,IALL(0,0,0)-IVIRTCORE
!   FT(MOI,MOI)=EPSILON(MOI,0)
    DO MOJ=ICORE+1,IALL(0,0,0)-IVIRTCORE
     DO MOA=ICORE+1,IALL(0,0,0)-IVIRTCORE
      FB=0.0D0
      IF (MOA <= IOCC) FB=1.0D0
      FA=1.0D0/(DEXP((EPSILON(MOA,0,0,0)-FERMI)/BOLTZMANN/DOPTN(98))+1.0D0)
      FT(MOI,MOJ)=FT(MOI,MOJ)+(2.0D0*DREAL(TALL(MOI,MOJ,MOA,MOA))-DREAL(TALL(MOI,MOA,MOA,MOJ))) &
       *(FA-FB)
     ENDDO
    ENDDO
   ENDDO

   MP0_OMEGA=NUCLEAR_REPULSION
   MP0_U=NUCLEAR_REPULSION
   DO MOI=ICORE+1,IALL(0,0,0)-IVIRTCORE
    FI=1.0D0/(DEXP((EPSILON(MOI,0,0,0)-FERMI)/BOLTZMANN/DOPTN(98))+1.0D0)
    MP0_U=MP0_U+2.0D0*EPSILON(MOI,0,0,0)*FI
    MP0_OMEGA=MP0_OMEGA+2.0D0*(EPSILON(MOI,0,0,0)-FERMI) &
     +2.0D0*DLOG(FI)*BOLTZMANN*DOPTN(98)
   ENDDO
   WRITE(6,'(A,F20.6,A)') 'MP0_OMEGA = ',MP0_OMEGA,' HARTREE'
   WRITE(6,'(A,F20.6,A)') 'MP0_U     = ',MP0_U,' HARTREE'

   MP1_OMEGA=0.0D0
   DO MOI=ICORE+1,IALL(0,0,0)-IVIRTCORE
    FI=1.0D0/(DEXP((EPSILON(MOI,0,0,0)-FERMI)/BOLTZMANN/DOPTN(98))+1.0D0)
    MP1_OMEGA=MP1_OMEGA+FT(MOI,MOI)*2.0D0*FI
   ENDDO
   DO MOJ=ICORE+1,IALL(0,0,0)-IVIRTCORE
    DO MOI=ICORE+1,IALL(0,0,0)-IVIRTCORE
     FI=1.0D0/(DEXP((EPSILON(MOI,0,0,0)-FERMI)/BOLTZMANN/DOPTN(98))+1.0D0)
     FJ=1.0D0/(DEXP((EPSILON(MOJ,0,0,0)-FERMI)/BOLTZMANN/DOPTN(98))+1.0D0)
     MP1_OMEGA=MP1_OMEGA-(2.0D0*DREAL(TALL(MOI,MOI,MOJ,MOJ))-DREAL(TALL(MOI,MOJ,MOJ,MOI))) &
      *FI*FJ
    ENDDO
   ENDDO
   WRITE(6,'(A,F20.6,A)') 'MP1_OMEGA = ',MP1_OMEGA,' HARTREE'

   MP2_N1=0.0D0
   MP2_N2=0.0D0
   MP2_R1=0.0D0
   DO MOB=ICORE+1,IALL(0,0,0)-IVIRTCORE
    DO MOJ=ICORE+1,IALL(0,0,0)-IVIRTCORE
     DO MOA=ICORE+1,IALL(0,0,0)-IVIRTCORE
      DO MOI=ICORE+1,IALL(0,0,0)-IVIRTCORE
       FI=1.0D0/(DEXP((EPSILON(MOI,0,0,0)-FERMI)/BOLTZMANN/DOPTN(98))+1.0D0)
       FJ=1.0D0/(DEXP((EPSILON(MOJ,0,0,0)-FERMI)/BOLTZMANN/DOPTN(98))+1.0D0)
       FA=1.0D0/(DEXP((-EPSILON(MOA,0,0,0)+FERMI)/BOLTZMANN/DOPTN(98))+1.0D0)
       FB=1.0D0/(DEXP((-EPSILON(MOB,0,0,0)+FERMI)/BOLTZMANN/DOPTN(98))+1.0D0)
       D=EPSILON(MOI,0,0,0)+EPSILON(MOJ,0,0,0)-EPSILON(MOA,0,0,0)-EPSILON(MOB,0,0,0)
       IF (DABS(D) > 1.0D-10) THEN
        MP2_N1=MP2_N1+(2.0D0*TALL(MOI,MOA,MOJ,MOB)*DCONJG(TALL(MOI,MOA,MOJ,MOB)) &
         -DREAL(TALL(MOI,MOA,MOJ,MOB)*DCONJG(TALL(MOJ,MOA,MOI,MOB)))) &
         /D*FI*FJ*FA*FB
        MP2_N2=MP2_N2+(2.0D0*TALL(MOI,MOA,MOJ,MOB)*DCONJG(TALL(MOI,MOA,MOJ,MOB)) &
         -DREAL(TALL(MOI,MOA,MOJ,MOB)*DCONJG(TALL(MOJ,MOA,MOI,MOB)))) &
         /D*FI*FJ*FA*FB
       ELSE
        MP2_N2=MP2_N2-(2.0D0*TALL(MOI,MOA,MOJ,MOB)*DCONJG(TALL(MOI,MOA,MOJ,MOB)) &
         -DREAL(TALL(MOI,MOA,MOJ,MOB)*DCONJG(TALL(MOJ,MOA,MOI,MOB)))) &
         *FI*FJ*FA*FB/BOLTZMANN/DOPTN(98)/2.0D0
       ENDIF
       D=FI*EPSILON(MOI,0,0,0)+FJ*EPSILON(MOJ,0,0,0)-FA*EPSILON(MOA,0,0,0)-FB*EPSILON(MOB,0,0,0)
       IF (D.NE.0.0D0) &
        MP2_R1=MP2_R1+(2.0D0*TALL(MOI,MOA,MOJ,MOB)*DCONJG(TALL(MOI,MOA,MOJ,MOB)) &
         -DREAL(TALL(MOI,MOA,MOJ,MOB)*DCONJG(TALL(MOJ,MOA,MOI,MOB)))) &
         /D*FI*FJ*FA*FB
      ENDDO
     ENDDO
    ENDDO
   ENDDO
   WRITE(6,'(A,F20.6,A)') 'MP2_N1    = ',MP2_N1,' HARTREE'
   WRITE(6,'(A,F20.6,A)') 'MP2_N2    = ',MP2_N2,' HARTREE'
!  WRITE(6,'(A,F20.6,A)') 'MP2_R1    = ',MP2_R1,' HARTREE'

   MP2_A1=MP2_N1
   MP2_A2=MP2_N2
   DO MOA=ICORE+1,IALL(0,0,0)-IVIRTCORE
    DO MOI=ICORE+1,IALL(0,0,0)-IVIRTCORE
     FI=1.0D0/(DEXP((EPSILON(MOI,0,0,0)-FERMI)/BOLTZMANN/DOPTN(98))+1.0D0)
     FA=1.0D0/(DEXP((-EPSILON(MOA,0,0,0)+FERMI)/BOLTZMANN/DOPTN(98))+1.0D0)
     D=EPSILON(MOI,0,0,0)-EPSILON(MOA,0,0,0)
     IF (DABS(D) > 1.0D-10) THEN
      MP2_A1=MP2_A1+2.0D0*FT(MOI,MOA)*FT(MOI,MOA)/D*FI*FA
      MP2_A2=MP2_A2+2.0D0*FT(MOI,MOA)*FT(MOI,MOA)/D*FI*FA
     ELSE
      MP2_A2=MP2_A2-FT(MOI,MOA)*FT(MOI,MOA)*FI*FA/BOLTZMANN/DOPTN(98)
     ENDIF
    ENDDO
   ENDDO
   WRITE(6,'(A,F20.6,A)') 'MP2_A1    = ',MP2_A1,' HARTREE'
   WRITE(6,'(A,F20.6,A)') 'MP2_A2    = ',MP2_A2,' HARTREE'

   MP2_R2=MP2_R1
   DO MOA=ICORE+1,IALL(0,0,0)-IVIRTCORE
    DO MOI=ICORE+1,IALL(0,0,0)-IVIRTCORE
     FI=1.0D0/(DEXP((EPSILON(MOI,0,0,0)-FERMI)/BOLTZMANN/DOPTN(98))+1.0D0)
     FA=1.0D0/(DEXP((-EPSILON(MOA,0,0,0)+FERMI)/BOLTZMANN/DOPTN(98))+1.0D0)
     D=FI*EPSILON(MOI,0,0,0)-FA*EPSILON(MOA,0,0,0)
     IF (D.NE.0.0D0) &
      MP2_R2=MP2_R2+2.0D0*FT(MOI,MOA)*FT(MOI,MOA)/D*FI*FA
    ENDDO
   ENDDO
   WRITE(6,'(A,F20.6,A)') 'MP2_R1    = ',MP2_R1,' HARTREE'
   WRITE(6,'(A,F20.6,A)') 'MP2_R2    = ',MP2_R2,' HARTREE'


   DEALLOCATE(ICASHE1X,ICASHE1Y,ICASHE1Z,ICASHE2,DCASHE)
   DEALLOCATE(TNNNKK,TALL,FT,KL)
   DEALLOCATE(TOK,TVOKK,TOVOKK)

   RETURN
END SUBROUTINE
