SUBROUTINE READ1
! READ INPUT DATA AND MOLECULAR GEOMETRY FROM STANDARD INPUT.

   USE MPI_F08
   USE CONSTANTS
   USE CONTROL
   USE STRUCTURE
   USE SYMMETRY
   USE INTEGRAL
   USE DFT

   IMPLICIT NONE
!  INCLUDE "mpif.h"
   INTEGER,PARAMETER :: NOPTN = 108
   INTEGER,PARAMETER :: NTHEORY = 10
   CHARACTER(10),PARAMETER :: CNAME(NOPTN) = &
      (/'JOBNAME   ','BASISSET  ','PERIOD    ','HELIX     ','CHARGE    ',& !   1 -   5
        'KPOINTS   ','JOBTYPE   ','UNITS     ','PRINT     ','CUTOFF1   ',& !   6 -  10
        'CUTOFF2   ','INTTOL    ','SCFCYCLES ','SCFCONV   ','SCFRELAX  ',& !  11 -  15
        'DIIS      ','AUXILIARY ','MULTIPOLE ','HFEXCHANGE','SLATER    ',& !  16 -  20
        'VWN       ','BECKE88   ','LYP       ','MP2       ','DIRECT    ',& !  21 -  25
        'MAXDISK   ','FROZENCORE','MAXMEMORY ','CUTOFF3   ','VAPPROX   ',& !  26 -  30
        'SAPPROX   ','DYSON     ','RI_SCF    ','RI_MP2    ','THEORY    ',& !  31 -  35
        'CIS_ROOTS ','RPA_ROOTS ','DAVIDSON  ','SINGLET   ','TRIPLET   ',& !  36 -  40
        'OPTCONV   ','GDIIS     ','CISQP     ','QPBANDS   ','DYSONDAMP ',& !  41 -  45
        'OEP       ','MP2KJOBS  ','MP2KJOBE  ','HIGHMP    ','HIGHCIS   ',& !  46 -  50
        'HIGHCIE   ','HIGHCCS   ','HIGHCCE   ','CCDIIS    ','FROZENVIRT',& !  51 -  55
        'HIGHCIROOT','EOMORDERS ','EOMORDERE ','EOMROOT   ','IP        ',& !  56 -  60
        'EA        ','CCCONV    ','CCRELAX   ','CCALG     ','XCC       ',& !  61 -  65
        'CCPTROOT  ','CICONV    ','CCPTCONV  ','SPHERICAL ','CCTHEORY  ',& !  66 -  70
        'OEPALG    ','SLATER51  ','KLI       ','POTDUMP   ','DENDUMP   ',& !  71 -  75
        'KERNEL_HF ','KERNEL_S  ','KERNEL_VWN','KERNEL_B88','KERNEL_LYP',& !  76 -  80
        'RADIAL    ','ANGULAR   ','AC        ','KERNEL_OEP','LINDEP    ',& !  81 -  85
        'POLAR     ','OMEGA     ','POLARALG  ','POLARX    ','POLARY    ',& !  86 -  90
        'POLARZ    ','SOS       ','RELATIVITY','SINANOGLU ','SALG      ',& !  91 -  95
        'SINGULAR  ','HIGHGF    ','TEMP      ','MODULO    ','NGRID     ',& !  96 - 100
        'DELTAH    ','GEMINAL   ','LMAX      ','MBGFALG   ','MP2ALG    ',& ! 101 - 105
        'DIAGONAL  ','DYSONCONV ','TEMPHF    '                          /) ! 106 - 108
   CHARACTER(10),PARAMETER :: CTHEORYNAME(NTHEORY) = &
      (/'HF        ','SNULL     ','BNULL     ','SVWN      ','BLYP      ',&
        'SLYP      ','BVWN      ','B3LYP     ','MP2FC     ','MP2FULL   '/)
   ! 1 = INTEGER ; 2 = DOUBLE PRECISION ; 3 = CHARACTER ; 4 = LOGICAL ; NEGATIVE = OMISSIBLE
   INTEGER,PARAMETER :: ITYPE(NOPTN) = (/-3,3,2,-2,-1,1,-1,-3,-1,1,1,-2,-1,-2,-2,-1,-3,-1,-2,-2,-2, &
   -2,-2,-2,-4,-2,-1,-2,-1,-4,-4,-4,-4,-4,-3,-1,-1,-2,-4,-4,-2,-1,-4,-1,-2,-4,-1,-1,-1,-1,-1,-1,-1, &
   -1,-1,-1,-1,-1,-1,-4,-4,-2,-2,-1,-4,-1,-2,-2,-4,-3,-1,-4,-4,-1,-1,-2,-2,-2,-2,-2,-1,-1,-4,-2,-2, &
   -4,-2,-1,-4,-4,-4,-4,-4,-4,-1,-2,-1,-2,-1,-1,-2,-3,-1,-1,-1,-4,-2,-2/)
   ! 1 = FORMAT(I3) ; 20 = FORMAT(F20.15) ; 21 = FORMAT(E24.15) ; 22 = FORMAT(F20.15/E24.15) ; 3 = FORMAT(A100)
   ! 4 = .TRUE. OR .FALSE.
   INTEGER,PARAMETER :: PRINT_TYPE(NOPTN) = (/3,3,22,22,1,1,1,3,1,1,1,21,1,21,20,1,3,1,20,20,20,20,20, &
   20,4,20,1,20,1,4,4,4,4,4,3,1,1,21,4,4,21,1,4,1,20,4,1,1,1,1,1,1,1,1,1,1,1,1,1,4,4,21,20,1,4,1,21,21,4,3, &
   1,4,4,1,1,20,20,20,20,20,1,1,4,20,21,4,21,1,4,4,4,4,4,4,1,21,1,21,1,1,21,3,1,1,1,4,21,21/)
   INTEGER,PARAMETER :: PRINT_ORDER(NOPTN) = (/1,7,35,2,17,69,5,3,4,8,9,6,99,10,11,29,19,20,21,22,23,76,77,78,79,80,84,&
   24,12,85,14,15,41,38,13,16,42,18,36,37,28,26,25,27,55,33,34,30,31,32,39,40,43,44,45,46,49,50,51,52,53,54,63,64,&
   65,66,56,57,58,59,60,61,47,48,67,62,68,70,71,72,73,74,75,81,82,83,86,87,88,89,90,91,92,93,94,95,96,97,108,98,100,101,&
   102,103,104,105,106,107/)
   INTEGER :: ITHEORY(NTHEORY)
   INTEGER :: I,J,L,M,EOF
   INTEGER :: K(NOPTN)
   DOUBLE PRECISION :: X,Y,Z,TMP
   CHARACTER(10) :: C
   CHARACTER(2)  :: D
   INTEGER :: IOERR

   !DEFAULT VALUES
   ITHEORY=0
   COPTN(1)='NONE'
   IOPTN(5)=0
   IOPTN(7)=0
   COPTN(8)='BOHR'
   IOPTN(9)=0
   DOPTN(12)=1.0D-10
   IOPTN(13)=50
   DOPTN(14)=1.0D-8
   DOPTN(15)=1.0D0
   IOPTN(16)=5
   COPTN(17)='NONE'
   IOPTN(18)=0
   DOPTN(19)=1.0D0
   DOPTN(20)=0.0D0
   DOPTN(21)=0.0D0
   DOPTN(22)=0.0D0
   DOPTN(23)=0.0D0
   DOPTN(24)=0.0D0
   LOPTN(25)=.TRUE.
   DOPTN(26)=1.0D99
   IOPTN(27)=0
   DOPTN(28)=1.0D99
   IOPTN(29)=0
   LOPTN(30)=.FALSE.
   LOPTN(31)=.FALSE.
   LOPTN(32)=.FALSE.
   LOPTN(33)=.FALSE.
   LOPTN(34)=.FALSE.
   COPTN(35)='SPECIFIED BELOW'
   IOPTN(36)=0
   IOPTN(37)=0
   DOPTN(38)=1.0D-6
   LOPTN(39)=.TRUE.
   LOPTN(40)=.TRUE.
   DOPTN(41)=0.4D-3
   IOPTN(42)=4
   LOPTN(43)=.FALSE.
   IOPTN(44)=0
   DOPTN(45)=0.0D0
   LOPTN(46)=.FALSE.
   IOPTN(47)=99999
   IOPTN(48)=99999
   IOPTN(49)=0
   IOPTN(50)=2
   IOPTN(51)=0
   IOPTN(52)=2
   IOPTN(53)=0
   IOPTN(54)=3
   IOPTN(55)=0
   IOPTN(56)=1
   IOPTN(57)=0
   IOPTN(58)=0
   IOPTN(59)=0
   LOPTN(60)=.FALSE.
   LOPTN(61)=.FALSE.
   DOPTN(62)=1.0D-6
   DOPTN(63)=1.0D0
   IOPTN(64)=1
   LOPTN(65)=.FALSE.
   IOPTN(66)=0
   DOPTN(67)=1.0D-5
   DOPTN(68)=1.0D-8
   LOPTN(69)=.FALSE.
   COPTN(70)='NONE'
   IOPTN(71)=1
   LOPTN(72)=.FALSE.
   LOPTN(73)=.FALSE.
   IOPTN(74)=0
   IOPTN(75)=0
   DOPTN(76)=1.0D99
   DOPTN(77)=1.0D99
   DOPTN(78)=1.0D99
   DOPTN(79)=1.0D99
   DOPTN(80)=1.0D99
   IOPTN(81)=0
   IOPTN(82)=0
   LOPTN(83)=.FALSE.
   DOPTN(84)=1.0D99
   DOPTN(85)=1.0D-6
   LOPTN(86)=.FALSE.
   DOPTN(87)=0.0D0
   IOPTN(88)=1
   LOPTN(89)=.TRUE.
   LOPTN(90)=.TRUE.
   LOPTN(91)=.TRUE.
   LOPTN(92)=.FALSE.
   LOPTN(93)=.FALSE.
   LOPTN(94)=.FALSE.
   IOPTN(95)=3
   DOPTN(96)=1.0D-7
   IOPTN(97)=0
   DOPTN(98)=0.0D0
   IOPTN(99)=1
   IOPTN(100)=3
   DOPTN(101)=0.3D0
   COPTN(102)='F12'
   IOPTN(103)=-1
   IOPTN(104)=4 ! MBGFALG = 1 (RECURSION1); 2 (RECURSION1&2); 3 (RECURSION1&2&3); -1 (RECURSION1SCAN); 4 (LAMBDA VARIATION)
   IOPTN(105)=1 ! MP2ALG = 1 (FAST BIG MEMORY); 2 (MEDIUM MEDIUM MEMORY); 3 (SLOW SMALL MEMORY)
   LOPTN(106)=.TRUE. ! DIAGONAL APPROXIMATION TO SELF-ENERGY = T
   DOPTN(107)=0.0001D0
   DOPTN(108)=1.0D-4

   DO I=1,NOPTN
    K(I)=0
   ENDDO

   NSYMM=0
   IF (MYID == 0) THEN
   OPEN(50,FILE="inputfile")
   REWIND(50)
   DO
    READ(50,*,IOSTAT=EOF) C
!   WRITE(6,'(A,I3)') C,EOF
    L=0
    IF (EOF /= 0) EXIT
    IF (SCAN(C,'!') == 1) CYCLE
    IF (C == 'GEOMETRY  ') THEN
!    WRITE(6,*) 'Reading GEOMETRY  '
     L=1
     NATOM=0
     NSYMM=0
     DO
     READ(50,*) D,X,Y,Z
      J=0
      DO I=1,36
       IF (CATOM(I) == D) THEN
        J=1
        NATOM=NATOM+1
        IATOM(NATOM)=I
        ATOMX(NATOM)=X
        ATOMY(NATOM)=Y
        ATOMZ(NATOM)=Z
       ENDIF
      ENDDO
      IF (J == 0) EXIT
     ENDDO
!3  ELSE IF (C == 'SYMMETRY  ') THEN
!3   WRITE(6,*) 'SYMMETRY  '
!3   READ(50,*) NSYMM
!3   IF (NSYMM > 1024) CALL PABORT('NUMBER OF IRREPS EXCEEDS 1024')
!3   DO I=1,NSYMM
!3    READ(50,*) (ISYMM(J,I),J=1,NSYMM)
!3   ENDDO
!3   DO I=1,NSYMM
!3    DO J=1,NSYMM
!3     IF (ISYMM(J,I) /= ISYMM(I,J)) CALL PABORT('SYMMETRY TABLE IS NOT CORRECT')
!3    ENDDO
!3   ENDDO
    ELSE IF (C == 'PERIOD    ') THEN
!    WRITE(6,*) 'Reading PERIOD    '
     READ(50,*,IOSTAT=EOF) PERIODX,PERIODY,PERIODZ
     IF (EOF /= 0) CALL PABORT('PERIOD ENTRY IS INCORRECT')
     K(3)=1
    ELSE IF (C == 'KPOINTS   ') THEN
!    WRITE(6,*) 'Reading KPOINTS   '
     READ(50,*,IOSTAT=EOF) KVCX,KVCY,KVCZ
     IF (EOF /= 0) CALL PABORT('KPOINTS ENTRY IS INCORRECT')
     K(6)=1
    ELSE IF (C == 'HELIX     ') THEN
!    WRITE(6,*) 'Reading HELIX     '
     READ(50,*) HELIX
     K(4)=1
    ELSE
     DO I=1,NOPTN
      IF (C == CNAME(I)) THEN
       L=1
!      WRITE(6,*) 'Reading ',C
       IF (ITYPE(I) == 1)  READ(50,*) IOPTN(I)
       IF (ITYPE(I) == -1) READ(50,*) IOPTN(I)
       IF (ITYPE(I) == 2)  READ(50,*) DOPTN(I)
       IF (ITYPE(I) == -2) READ(50,*) DOPTN(I)
       IF (ITYPE(I) == 3)  READ(50,*) COPTN(I)
       IF (ITYPE(I) == -3) READ(50,*) COPTN(I)
       IF (ITYPE(I) == 4)  READ(50,*) LOPTN(I)
       IF (ITYPE(I) == -4) READ(50,*) LOPTN(I)
       K(I)=1
      ENDIF
     ENDDO
     IF (L == 0) THEN
      WRITE(6,'(A,A,A)') '***** PABORT : A SYNTAX ERROR : ',C,' ?'
      STOP
     ENDIF
    ENDIF
   ENDDO
   IF (NATOM == 0) THEN
    CALL PABORT('GEOMETRY NOT FOUND IN INPUT STREAM')
   ELSE IF (NATOM > 1024) THEN
    CALL PABORT('NUMBER OF ATOMS EXCEEDS 1024')
   ENDIF
   DO I=1,NOPTN
    IF ((ITYPE(I) >= 1).AND.(K(I) == 0)) THEN
     WRITE(6,'(A,A,A)') '***** PABORT : ',CNAME(I),' NOT FOUND IN INPUT STREAM'
     STOP
    ENDIF
    IF ((ITYPE(I) == 3).OR.(ITYPE(I) == -3)) &
    COPTN(I)=ADJUSTL(COPTN(I))
   ENDDO
   CLOSE(50)
   ENDIF

   CALL MPI_BCAST(NATOM,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(IATOM,NATOM,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(ATOMX,NATOM,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(ATOMY,NATOM,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(ATOMZ,NATOM,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(PERIODX,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(PERIODY,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(PERIODZ,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(HELIX,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(KVCX,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(KVCY,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(KVCZ,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(IOPTN,NOPTN,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(DOPTN,NOPTN,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(COPTN,NOPTN*100,MPI_CHARACTER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(LOPTN,NOPTN,MPI_LOGICAL,0,MPI_COMM_WORLD,IERR)
!  write(6,*) 'proc = ',myid
!  do i=1,natom
!   write(6,'(i3,3f10.5)') iatom(i),atomx(i),atomy(i),atomz(i)
!  enddo
!  do i=1,noptn
!  if ((itype(i) == 3).or.(itype(i) == -3)) write(6,*) coptn(i)
!  enddo

   IF (COPTN(8) == 'ANGSTROM') THEN
    DO I=1,NATOM
     ATOMX(I)=ATOMX(I)/ANG_BOHR
     ATOMY(I)=ATOMY(I)/ANG_BOHR
     ATOMZ(I)=ATOMZ(I)/ANG_BOHR
    ENDDO
    PERIODX=PERIODX/ANG_BOHR
    PERIODY=PERIODY/ANG_BOHR
    PERIODZ=PERIODZ/ANG_BOHR
   ELSE IF (COPTN(8) /= 'BOHR') THEN
    CALL PABORT('UNIT OF LENGTH MUST BE BOHR OR ANGSTROM')
   ENDIF
   HELIX=HELIX*PI/180.0D0

   J=0
   DO I=1,NTHEORY
    IF (COPTN(35) == CTHEORYNAME(I)) THEN
     J=J+1
     ITHEORY(I)=1
    ENDIF
   ENDDO
   IF (J > 1) CALL PABORT('MORE THAN ONE THEORETICAL LEVELS HAVE BEEN SPECIFIED')
   IF ((ITHEORY(1) == 1).OR.(LOPTN(46)).OR.(LOPTN(72)).OR.(LOPTN(73))) THEN
    DOPTN(19)=1.0D0
    DOPTN(20)=0.0D0
    DOPTN(21)=0.0D0
    DOPTN(22)=0.0D0
    DOPTN(23)=0.0D0
    DOPTN(24)=0.0D0
   ELSE IF (ITHEORY(2) == 1) THEN
    DOPTN(19)=0.0D0
    DOPTN(20)=1.0D0
    DOPTN(21)=0.0D0
    DOPTN(22)=0.0D0
    DOPTN(23)=0.0D0
    DOPTN(24)=0.0D0
   ELSE IF (ITHEORY(3) == 1) THEN
    DOPTN(19)=0.0D0
    DOPTN(20)=0.0D0
    DOPTN(21)=0.0D0
    DOPTN(22)=1.0D0
    DOPTN(23)=0.0D0
    DOPTN(24)=0.0D0
   ELSE IF (ITHEORY(4) == 1) THEN
    DOPTN(19)=0.0D0
    DOPTN(20)=1.0D0
    DOPTN(21)=1.0D0
    DOPTN(22)=0.0D0
    DOPTN(23)=0.0D0
    DOPTN(24)=0.0D0
   ELSE IF (ITHEORY(5) == 1) THEN
    DOPTN(19)=0.0D0
    DOPTN(20)=0.0D0
    DOPTN(21)=0.0D0
    DOPTN(22)=1.0D0
    DOPTN(23)=1.0D0
    DOPTN(24)=0.0D0
   ELSE IF (ITHEORY(6) == 1) THEN
    DOPTN(19)=0.0D0
    DOPTN(20)=1.0D0
    DOPTN(21)=0.0D0
    DOPTN(22)=0.0D0
    DOPTN(23)=1.0D0
    DOPTN(24)=0.0D0
   ELSE IF (ITHEORY(7) == 1) THEN
    DOPTN(19)=0.0D0
    DOPTN(20)=0.0D0
    DOPTN(21)=1.0D0
    DOPTN(22)=1.0D0
    DOPTN(23)=0.0D0
    DOPTN(24)=0.0D0
   ELSE IF (ITHEORY(8) == 1) THEN
    DOPTN(19)=0.20D0
    DOPTN(20)=0.08D0
    DOPTN(21)=0.19D0
    DOPTN(22)=0.72D0
    DOPTN(23)=0.81D0
    DOPTN(24)=0.0D0
   ELSE IF (ITHEORY(9) == 1) THEN
    DOPTN(19)=1.0D0
    DOPTN(20)=0.0D0
    DOPTN(21)=0.0D0
    DOPTN(22)=0.0D0
    DOPTN(23)=0.0D0
    DOPTN(24)=1.0D0
    LOPTN(25)=.FALSE.
    IOPTN(27)=-1
   ELSE IF (ITHEORY(10) == 1) THEN
    DOPTN(19)=1.0D0
    DOPTN(20)=0.0D0
    DOPTN(21)=0.0D0
    DOPTN(22)=0.0D0
    DOPTN(23)=0.0D0
    DOPTN(24)=1.0D0
    LOPTN(25)=.FALSE.
    IOPTN(27)=0
   ENDIF
   IF ((DOPTN(76) == 1.0D99).OR.(DOPTN(77) == 1.0D99).OR.(DOPTN(78) == 1.0D99) &
   .OR.(DOPTN(79) == 1.0D99).OR.(DOPTN(80) == 1.0D99).OR.(DOPTN(84) == 1.0D99)) THEN
    IF (LOPTN(46)) THEN
     DOPTN(76)=0.0D0
     DOPTN(77)=0.0D0
     DOPTN(78)=0.0D0
     DOPTN(79)=0.0D0
     DOPTN(80)=0.0D0
     DOPTN(84)=1.0D0
    ELSE
     DOPTN(76)=DOPTN(19)
     DOPTN(77)=DOPTN(20)
     DOPTN(78)=DOPTN(21)
     DOPTN(79)=DOPTN(22)
     DOPTN(80)=DOPTN(23)
     DOPTN(84)=0.0D0
    ENDIF
   ENDIF
   IF ((DOPTN(20) /= 0.0D0).OR.(DOPTN(21) /= 0.0D0).OR.(DOPTN(22) /= 0.0D0).OR.(DOPTN(23) /= 0.0D0) &
   .OR.(DOPTN(77) /= 0.0D0).OR.(DOPTN(78) /= 0.0D0).OR.(DOPTN(79) /= 0.0D0).OR.(DOPTN(80) /= 0.0D0)) THEN
    LDFT=.TRUE.
   ELSE
    LDFT=.FALSE.
   ENDIF
   IF ((DOPTN(22) /= 0.0D0).OR.(DOPTN(23) /= 0.0D0).OR.(DOPTN(79) /= 0.0D0).OR.(DOPTN(80) /= 0.0D0)) THEN
    LGC=.TRUE.
   ELSE
    LGC=.FALSE.
   ENDIF
   IF (DOPTN(24) /= 0.0D0) LOPTN(25)=.FALSE.
   IF (IOPTN(44) < 0) THEN
    CALL WARNING('INVALID QPBANDS, THE PARAMETER VALUE HAS BEEN RESET TO THE DEFAULT VALUE OF ZERO')
    IOPTN(44)=0
   ENDIF
   IF (LOPTN(33).OR.LOPTN(34).OR.LOPTN(46).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0)) THEN
    IF (COPTN(17) == 'NONE') CALL PABORT('SPECIFY AN AUXILIARY BASIS SET')
    IF ((LOPTN(30)).AND.(LOPTN(31))) THEN
     LOPTN(30)=.TRUE.
     LOPTN(31)=.FALSE.
    ELSE IF ((.NOT.LOPTN(30)).AND.(.NOT.LOPTN(31))) THEN
     LOPTN(30)=.TRUE.
     LOPTN(31)=.FALSE.
    ENDIF
   ELSE
    COPTN(17)='NONE'
    LOPTN(30)=.FALSE.
    LOPTN(31)=.FALSE.
   ENDIF
   IF ((IOPTN(81) == 0).AND.(IOPTN(82) == 0)) THEN
    MAXNGRID=8656
   ELSE
    MAXNGRID=IOPTN(81)*IOPTN(82)
   ENDIF
   IF (IOPTN(97) > 0) THEN
    LOPTN(60)=.TRUE.
    LOPTN(61)=.TRUE.
   ENDIF
   IF (DOPTN(108) == 0.0D0) THEN
    DOPTN(108)=1.0D-4
   ENDIF
   FERMI = 0.0D0

   IF (MYID == 0) THEN
   WRITE(6,'(A,I3)') 'NUMBER OF ATOMS =',NATOM
   DO I=1,NATOM
    WRITE(6,'(A2,3F20.15,A)') CATOM(IATOM(I)),ATOMX(I),ATOMY(I),ATOMZ(I),' BOHR'
   ENDDO
   IF (NSYMM > 0) THEN
    WRITE(6,'(A)') 'SYMMETRY TABLE'
    DO I=1,NSYMM
     WRITE(6,'(1024I3:)') (ISYMM(J,I),J=1,NSYMM)
    ENDDO
   ENDIF
   ENDIF
   CHARGE=IOPTN(5)
   DO I=1,NOPTN
    J=PRINT_ORDER(I)
    IF (J==3) THEN
     L=0
     LX=.FALSE.
     LY=.FALSE.
     LZ=.FALSE.
     IF (PERIODX /= 0.0D0) THEN 
      L=L+1
      LX=.TRUE.
     ENDIF
     IF (PERIODY /= 0.0D0) THEN
      L=L+1
      LY=.TRUE.
     ENDIF
     IF (PERIODZ /= 0.0D0) THEN
      L=L+1
      LZ=.TRUE.
     ENDIF
     IF (MYID == 0) WRITE(6,'(A10,A3,3F20.15,A,I1,A)') CNAME(J),' = ',PERIODX,PERIODY,PERIODZ,' BOHR (',L,'D CRYSTAL)'
    ELSE IF (J==4) THEN
     IF (HELIX /= 0.0D0) THEN
      IF (LX.AND.LY.AND.LZ) CALL PABORT('HELICAL SYMMETRY FOR 1D CRYSTAL ONLY')
      IF (LX.AND.LY) CALL PABORT('HELICAL SYMMETRY FOR 1D CRYSTAL ONLY')
      IF (LY.AND.LZ) CALL PABORT('HELICAL SYMMETRY FOR 1D CRYSTAL ONLY')
      IF (LZ.AND.LX) CALL PABORT('HELICAL SYMMETRY FOR 1D CRYSTAL ONLY')
     ENDIF
     IF (MYID == 0) WRITE(6,'(A10,A3,F20.15,A)') CNAME(J),' = ',HELIX,' RADIAN'
    ELSE IF (J==6) THEN
     IF (MYID == 0) WRITE(6,'(A10,A3,3I20)') CNAME(J),' = ',KVCX,KVCY,KVCZ
    ELSE
     IF (MYID == 0) THEN
     IF (PRINT_TYPE(J) == 1) THEN
      WRITE(6,'(A10,A3,I4)') CNAME(J),' = ',IOPTN(J)
     ELSE IF (PRINT_TYPE(J) == 20) THEN
      WRITE(6,'(A10,A3,F20.15)') CNAME(J),' = ',DOPTN(J)
     ELSE IF (PRINT_TYPE(J) == 21) THEN
      WRITE(6,'(A10,A3,E24.15)') CNAME(J),' = ',DOPTN(J)
     ELSE IF (PRINT_TYPE(J) == 22) THEN
      IF (DABS(DOPTN(J)) >= 1.0D3) WRITE(6,'(A10,A3,E24.15)') CNAME(J),' = ',DOPTN(J)
      IF (DABS(DOPTN(J)) <  1.0D3) WRITE(6,'(A10,A3,F20.15)') CNAME(J),' = ',DOPTN(J)
     ELSE IF (PRINT_TYPE(J) == 3) THEN
      WRITE(6,'(A10,A3,A100)') CNAME(J),' = ',COPTN(J)
     ELSE IF (PRINT_TYPE(J) == 4) THEN
      IF (LOPTN(J)) WRITE(6,'(A10,A)') CNAME(J),' = .TRUE.'
      IF (.NOT.LOPTN(J)) WRITE(6,'(A10,A)') CNAME(J),' = .FALSE.'
     ENDIF
     ENDIF
    ENDIF
   ENDDO

   RETURN
END SUBROUTINE



SUBROUTINE READ2
! READ THE TOTAL NUMBER OF ORBITAL (PRIMITIVE AND CONTRACTED) BASIS FUNCTIONS AND
! AUXILIARY (PRIMITIVE) BASIS FUNCTIONS IN ORDER TO DETERMINE NPGS, NCGS, AND NAGS
! BEFORE ALLOCATION OF BASIS FUNCTION ARRAYS.

   USE MPI_F08
   USE CONSTANTS
   USE CONTROL
   USE STRUCTURE
   USE BASISSET
   USE AUXILIARY

   IMPLICIT NONE
!  INCLUDE "mpif.h"
   INTEGER :: I,J,K,EOF
   CHARACTER(2) :: C
   LOGICAL :: LATOM

   CALL PABORT('OBSOLETE')

   NPGS=0
   NCGS=0
   NAGS=0

   IF (MYID == 0) THEN
   OPEN(10,FILE=COPTN(2))
   DO I=1,NATOM
    REWIND(10)
    DO
     READ(10,'(A2,2I4)',IOSTAT=EOF) C,J,K
     IF (EOF /= 0) THEN
      CALL PABORT('ORBITAL BASIS SET NOT FOUND')
     ELSE IF (C == '**') THEN
      LATOM=.TRUE.
     ELSE IF (C == CATOM(IATOM(I))) THEN
      IF (LATOM) THEN
       NPGS=NPGS+J
       NCGS=NCGS+K
       EXIT
      ENDIF
     ELSE 
      LATOM=.FALSE.
     ENDIF
    ENDDO
   ENDDO
   CLOSE(10)
   ENDIF
   CALL MPI_BCAST(NPGS,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(NCGS,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   IF (MYID == 0) WRITE(6,'(A,I5)') 'NUMBER OF PRIMITIVE GAUSSIANS  = ',NPGS
   IF (MYID == 0) WRITE(6,'(A,I5)') 'NUMBER OF CONTRACTED GAUSSIANS = ',NCGS

   IF (COPTN(17) /= 'NONE') THEN
    IF (MYID == 0) THEN
    OPEN(11,FILE=COPTN(17))
    DO I=1,NATOM
     REWIND(11)
     DO
      READ(11,'(A2,I4)',IOSTAT=EOF) C,J
      IF (EOF /= 0) THEN
       CALL PABORT('AUXILIARY BASIS SET NOT FOUND')
      ELSE IF (C == CATOM(IATOM(I))) THEN
       NAGS=NAGS+J
       EXIT
      ENDIF
     ENDDO
    ENDDO
    CLOSE(11)
    ENDIF
    CALL MPI_BCAST(NAGS,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
    IF (MYID == 0) WRITE(6,'(A,I5)') 'NUMBER OF AUXILIARY GAUSSIANS  = ',NAGS
   ENDIF

   RETURN
END SUBROUTINE



SUBROUTINE READ3
! READ ORBITAL BASIS FUNCTIONS FROM AN EXTERNAL BASIS-SET FILE.

   USE MPI_F08
   USE CONSTANTS
   USE CONTROL
   USE STRUCTURE
   USE BASISSET
   USE INTEGRAL

   IMPLICIT NONE
!  INCLUDE "mpif.h"
   INTEGER :: I,J,K,L,EOF,FLAG,IX,IY,IZ
   DOUBLE PRECISION :: S,A,B,D,X,Y,Z
   DOUBLE PRECISION :: CGSX_TMP(1024),CGSY_TMP(1024),CGSZ_TMP(1024)
   INTEGER :: PAX_TMP(1024),PAY_TMP(1024),PAZ_TMP(1024),PGS_ATOM_TMP(1024)
   DOUBLE PRECISION :: PGSX_TMP(1024),PGSY_TMP(1024),PGSZ_TMP(1024),ZT_TMP(1024),CC_TMP(1024,1024)
   INTEGER :: P_SHELL_TMP(1024,0:BASIS_LMAX+1,0:BASIS_LMAX+1,0:BASIS_LMAX+1),P_SHELL_ANG_TMP(1024)
   CHARACTER(2) :: C
   LOGICAL :: LATOM
   
   NPGS=0
   NCGS=0
   NPSHELL=0
   CC_TMP=0.0D0

   IF (MYID == 0) THEN
   OPEN(10,FILE=COPTN(2))
   DO I=1,NATOM
    REWIND(10)
    DO
     READ(10,'(A2)',IOSTAT=EOF) C
     IF (EOF /= 0) THEN
      CALL PABORT('ORBITAL BASIS SET NOT FOUND')
     ELSE IF (C == CATOM(IATOM(I))) THEN
      IF (LATOM) THEN
      DO
       READ(10,*,IOSTAT=EOF) C,J,S
       IF (EOF /= 0) EXIT
       IF (C == 'S ') THEN
        NCGS=NCGS+1
        IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        DO K=1,J
         READ(10,*) A,B
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=0
         PAY_TMP(NPGS)=0
         PAZ_TMP(NPGS)=0
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))
        ENDDO
       ELSE IF (C == 'P ') THEN
        NCGS=NCGS+1
        IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        DO K=1,J
         READ(10,*) A,B
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=1
         PAY_TMP(NPGS)=0
         PAZ_TMP(NPGS)=0
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-2,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=0
         PAY_TMP(NPGS)=1
         PAZ_TMP(NPGS)=0
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-1,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=0
         PAY_TMP(NPGS)=0
         PAZ_TMP(NPGS)=1
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS,  NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)
        ENDDO
       ELSE IF (C == 'SP') THEN
        NCGS=NCGS+1
        IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        IF (NPGS+4*J > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        DO K=1,J
         READ(10,*) A,B,D
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=0
         PAY_TMP(NPGS)=0
         PAZ_TMP(NPGS)=0
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-3,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))
!
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=1
         PAY_TMP(NPGS)=0
         PAZ_TMP(NPGS)=0
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-2,NPGS)=D*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)
!
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=0
         PAY_TMP(NPGS)=1
         PAZ_TMP(NPGS)=0
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-1,NPGS)=D*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)
!
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=0
         PAY_TMP(NPGS)=0
         PAZ_TMP(NPGS)=1
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS,  NPGS)=D*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)
!
        ENDDO
       ELSE IF (C == 'D ') THEN
        NCGS=NCGS+1
        IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        DO K=1,J
         READ(10,*) A,B
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=2
         PAY_TMP(NPGS)=0
         PAZ_TMP(NPGS)=0
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-5,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**2/DSQRT(3.0D0)
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=0
         PAY_TMP(NPGS)=2
         PAZ_TMP(NPGS)=0
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-4,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**2/DSQRT(3.0D0)
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=0
         PAY_TMP(NPGS)=0
         PAZ_TMP(NPGS)=2
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-3,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**2/DSQRT(3.0D0)
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=1
         PAY_TMP(NPGS)=1
         PAZ_TMP(NPGS)=0
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-2,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**2
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=0
         PAY_TMP(NPGS)=1
         PAZ_TMP(NPGS)=1
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-1,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**2
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=1
         PAY_TMP(NPGS)=0
         PAZ_TMP(NPGS)=1
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS,  NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**2
        ENDDO
       ELSE IF (C == 'F ') THEN
        NCGS=NCGS+1
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        NCGS=NCGS+1
        CGSX_TMP(NCGS)=ATOMX(I)
        CGSY_TMP(NCGS)=ATOMY(I)
        CGSZ_TMP(NCGS)=ATOMZ(I)
        DO K=1,J
         READ(10,*) A,B
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=3
         PAY_TMP(NPGS)=0
         PAZ_TMP(NPGS)=0
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-9,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(15.0D0)
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=0
         PAY_TMP(NPGS)=3
         PAZ_TMP(NPGS)=0
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-8,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(15.0D0)
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=0
         PAY_TMP(NPGS)=0
         PAZ_TMP(NPGS)=3
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-7,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(15.0D0)
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=2
         PAY_TMP(NPGS)=1
         PAZ_TMP(NPGS)=0
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-6,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(3.0D0)
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=0
         PAY_TMP(NPGS)=2
         PAZ_TMP(NPGS)=1
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-5,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(3.0D0)
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=1
         PAY_TMP(NPGS)=0
         PAZ_TMP(NPGS)=2
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-4,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(3.0D0)
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=1
         PAY_TMP(NPGS)=2
         PAZ_TMP(NPGS)=0
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-3,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(3.0D0)
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=0
         PAY_TMP(NPGS)=1
         PAZ_TMP(NPGS)=2
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-2,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(3.0D0)
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=2
         PAY_TMP(NPGS)=0
         PAZ_TMP(NPGS)=1
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS-1,NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(3.0D0)
         NPGS=NPGS+1
         IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
         PAX_TMP(NPGS)=1
         PAY_TMP(NPGS)=1
         PAZ_TMP(NPGS)=1
         PGSX_TMP(NPGS)=ATOMX(I)
         PGSY_TMP(NPGS)=ATOMY(I)
         PGSZ_TMP(NPGS)=ATOMZ(I)
         PGS_ATOM_TMP(NPGS)=I
         ZT_TMP(NPGS)=A*S
         CC_TMP(NCGS,  NPGS)=B*DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3
        ENDDO
       ELSE IF (C == '**') THEN
        EXIT
       ELSE
        CALL PABORT('ANGULAR MOMENTUM NOT YET SUPPORTED')
       ENDIF
      ENDDO
      EXIT
      ENDIF
     ELSE IF (C == '**') THEN
      LATOM=.TRUE.
     ELSE
      LATOM=.FALSE.
     ENDIF
    ENDDO
   ENDDO
   CLOSE(10)
   ENDIF

   CALL MPI_BCAST(NPGS,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(NCGS,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(PGS_ATOM_TMP,1024,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(CC_TMP,1024*1024,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(PAX_TMP,1024,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(PAY_TMP,1024,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(PAZ_TMP,1024,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(PGSX_TMP,1024,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(PGSY_TMP,1024,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(PGSZ_TMP,1024,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(ZT_TMP,1024,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(CGSX_TMP,1024,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(CGSY_TMP,1024,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(CGSZ_TMP,1024,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)

   IF (MYID == 0) WRITE(6,'(A,I5)') 'NUMBER OF PRIMITIVE GAUSSIANS  = ',NPGS
   IF (MYID == 0) WRITE(6,'(A,I5)') 'NUMBER OF CONTRACTED GAUSSIANS = ',NCGS
   
   IF (IOPTN(9) >= 2) THEN
    IF (MYID == 0) THEN
    WRITE(6,'(A)') 'CONTRACTED GAUSSIAN FUNCTIONS'
    WRITE(6,'(A)') 'Cgs-No.  Pgs-No.    Coefficient'
    DO I=1,NCGS
     WRITE(6,'(I4)') I
     DO J=1,NPGS
      IF (CC_TMP(I,J) /= 0.0D0) WRITE(6,'(10X,I3,F18.10,I3,A2)') J,CC_TMP(I,J),PGS_ATOM_TMP(J),CATOM(IATOM(PGS_ATOM_TMP(J)))
     ENDDO
    ENDDO
    WRITE(6,'(A)') 'PRIMITIVE GAUSSIAN FUNCTIONS'
    WRITE(6,'(A)') 'No. Ax Ay Az       X         Y         Z         Exponent'
    DO I=1,NPGS
     WRITE(6,'(4I3,3F10.4,F17.8)') I,PAX_TMP(I),PAY_TMP(I),PAZ_TMP(I),PGSX_TMP(I),PGSY_TMP(I),PGSZ_TMP(I),ZT_TMP(I)
    ENDDO
    ENDIF
   ENDIF

   ! DETERMINE SHELL STRUCTURE
   P_SHELL_TMP=-1
   NPSHELL=0
   DO I=1,NPGS
    K=PAX_TMP(I)+PAY_TMP(I)+PAZ_TMP(I)
    IF (K == 0) THEN
     NPSHELL=NPSHELL+1
     P_SHELL_TMP(NPSHELL,0,0,0)=I
     P_SHELL_ANG_TMP(NPSHELL)=0
    ENDIF
   ENDDO

   DO I=1,NPGS
    J=PAX_TMP(I)+PAY_TMP(I)+PAZ_TMP(I)
    IF (J==1) THEN ! P ORBITAL
     FLAG=0
     DO K=1,NPSHELL
      IF ((PGSX_TMP(P_SHELL_TMP(K,0,0,0)) == PGSX_TMP(I)).AND.(PGSY_TMP(P_SHELL_TMP(K,0,0,0)) == PGSY_TMP(I)).AND. &
          (PGSZ_TMP(P_SHELL_TMP(K,0,0,0)) == PGSZ_TMP(I)).AND.(ZT_TMP(P_SHELL_TMP(K,0,0,0)) == ZT_TMP(I)).AND. &
          (P_SHELL_TMP(K,PAX_TMP(I),PAY_TMP(I),PAZ_TMP(I))==-1)) THEN
       FLAG=1
       P_SHELL_TMP(K,PAX_TMP(I),PAY_TMP(I),PAZ_TMP(I))=I
       P_SHELL_ANG_TMP(K)=1
      ENDIF
     ENDDO
     IF (FLAG == 0) THEN
!     WRITE(6,'(I3,A)') I,'TH P-ORBITAL DOES NOT HAVE A SHELL; GHOST S-ORBITAL IS ADDED' 
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I)
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=0
      PAY_TMP(NPGS)=0
      PAZ_TMP(NPGS)=0
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      NPSHELL=NPSHELL+1
      P_SHELL_TMP(NPSHELL,0,0,0)=NPGS
      P_SHELL_TMP(NPSHELL,PAX_TMP(I),PAY_TMP(I),PAZ_TMP(I))=I
      P_SHELL_ANG_TMP(NPSHELL)=1
     ENDIF
    ELSE IF (J==2) THEN ! D ORBITAL
     FLAG=0
     DO K=1,NPSHELL
      IF ((PGSX_TMP(P_SHELL_TMP(K,0,0,0)) == PGSX_TMP(I)).AND.(PGSY_TMP(P_SHELL_TMP(K,0,0,0)) == PGSY_TMP(I)).AND. &
          (PGSZ_TMP(P_SHELL_TMP(K,0,0,0)) == PGSZ_TMP(I)).AND.(ZT_TMP(P_SHELL_TMP(K,0,0,0)) == ZT_TMP(I)).AND. &
          (P_SHELL_TMP(K,PAX_TMP(I),PAY_TMP(I),PAZ_TMP(I))==-1)) THEN
       FLAG=1
       P_SHELL_TMP(K,PAX_TMP(I),PAY_TMP(I),PAZ_TMP(I))=I
       P_SHELL_ANG_TMP(K)=2
      ENDIF
     ENDDO
     IF (FLAG == 0) THEN
!     WRITE(6,'(I3,A)') I,'TH D-ORBITAL DOES NOT HAVE A SHELL; GHOST S-, P-ORBITALS ARE ADDED'
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I)
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=0
      PAY_TMP(NPGS)=0
      PAZ_TMP(NPGS)=0
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      NPSHELL=NPSHELL+1
      P_SHELL_TMP(NPSHELL,0,0,0)=NPGS
      P_SHELL_TMP(NPSHELL,PAX_TMP(I),PAY_TMP(I),PAZ_TMP(I))=I
      P_SHELL_ANG_TMP(NPSHELL)=2
!
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I)
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=1
      PAY_TMP(NPGS)=0
      PAZ_TMP(NPGS)=0
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      P_SHELL_TMP(NPSHELL,1,0,0)=NPGS
      P_SHELL_ANG_TMP(NPSHELL)=2
!
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I) 
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=0
      PAY_TMP(NPGS)=1
      PAZ_TMP(NPGS)=0
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      P_SHELL_TMP(NPSHELL,0,1,0)=NPGS
      P_SHELL_ANG_TMP(NPSHELL)=2
!
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I)
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=0
      PAY_TMP(NPGS)=0  
      PAZ_TMP(NPGS)=1
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      P_SHELL_TMP(NPSHELL,0,0,1)=NPGS
      P_SHELL_ANG_TMP(NPSHELL)=2
     ENDIF 
    ELSE IF (J==3) THEN ! F ORBITAL
     FLAG=0
     DO K=1,NPSHELL
      IF ((PGSX_TMP(P_SHELL_TMP(K,0,0,0)) == PGSX_TMP(I)).AND.(PGSY_TMP(P_SHELL_TMP(K,0,0,0)) == PGSY_TMP(I)).AND. &
          (PGSZ_TMP(P_SHELL_TMP(K,0,0,0)) == PGSZ_TMP(I)).AND.(ZT_TMP(P_SHELL_TMP(K,0,0,0)) == ZT_TMP(I)).AND. &
          (P_SHELL_TMP(K,PAX_TMP(I),PAY_TMP(I),PAZ_TMP(I))==-1)) THEN
       FLAG=1
       P_SHELL_TMP(K,PAX_TMP(I),PAY_TMP(I),PAZ_TMP(I))=I
       P_SHELL_ANG_TMP(K)=3
      ENDIF
     ENDDO
     IF (FLAG == 0) THEN
!     WRITE(6,'(I3,A)') I,'TH D-ORBITAL DOES NOT HAVE A SHELL; GHOST S-, P-, D-ORBITALS ARE ADDED'
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I)
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=0
      PAY_TMP(NPGS)=0
      PAZ_TMP(NPGS)=0
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      NPSHELL=NPSHELL+1
      P_SHELL_TMP(NPSHELL,0,0,0)=NPGS
      P_SHELL_TMP(NPSHELL,PAX_TMP(I),PAY_TMP(I),PAZ_TMP(I))=I
      P_SHELL_ANG_TMP(NPSHELL)=3
!
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I)
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=1
      PAY_TMP(NPGS)=0
      PAZ_TMP(NPGS)=0
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      P_SHELL_TMP(NPSHELL,1,0,0)=NPGS
      P_SHELL_ANG_TMP(NPSHELL)=3
!
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I) 
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=0
      PAY_TMP(NPGS)=1
      PAZ_TMP(NPGS)=0
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      P_SHELL_TMP(NPSHELL,0,1,0)=NPGS
      P_SHELL_ANG_TMP(NPSHELL)=3
!
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I)
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=0
      PAY_TMP(NPGS)=0  
      PAZ_TMP(NPGS)=1
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      P_SHELL_TMP(NPSHELL,0,0,1)=NPGS
      P_SHELL_ANG_TMP(NPSHELL)=3
!
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I)
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=2
      PAY_TMP(NPGS)=0
      PAZ_TMP(NPGS)=0
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      P_SHELL_TMP(NPSHELL,2,0,0)=NPGS
      P_SHELL_ANG_TMP(NPSHELL)=3
!
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I)
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=0
      PAY_TMP(NPGS)=2
      PAZ_TMP(NPGS)=0
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      P_SHELL_TMP(NPSHELL,0,2,0)=NPGS
      P_SHELL_ANG_TMP(NPSHELL)=3
!
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I)
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=0
      PAY_TMP(NPGS)=0 
      PAZ_TMP(NPGS)=2
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      P_SHELL_TMP(NPSHELL,0,0,2)=NPGS
      P_SHELL_ANG_TMP(NPSHELL)=3
!
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I)
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=1
      PAY_TMP(NPGS)=1
      PAZ_TMP(NPGS)=0
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      P_SHELL_TMP(NPSHELL,1,1,0)=NPGS
      P_SHELL_ANG_TMP(NPSHELL)=3
!
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I)
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=0
      PAY_TMP(NPGS)=1
      PAZ_TMP(NPGS)=1
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      P_SHELL_TMP(NPSHELL,0,1,1)=NPGS
      P_SHELL_ANG_TMP(NPSHELL)=3
!
      NCGS=NCGS+1
      IF (NCGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      CGSX_TMP(NCGS)=PGSX_TMP(I)
      CGSY_TMP(NCGS)=PGSY_TMP(I)
      CGSZ_TMP(NCGS)=PGSZ_TMP(I)
      NPGS=NPGS+1
      IF (NPGS > 1024) CALL PABORT('TOO MANY BASIS FUNCTIONS')
      PAX_TMP(NPGS)=1
      PAY_TMP(NPGS)=0 
      PAZ_TMP(NPGS)=1
      PGSX_TMP(NPGS)=PGSX_TMP(I)
      PGSY_TMP(NPGS)=PGSY_TMP(I)
      PGSZ_TMP(NPGS)=PGSZ_TMP(I)
      PGS_ATOM_TMP(NPGS)=PGS_ATOM_TMP(I)
      ZT_TMP(NPGS)=ZT_TMP(I)
      CC_TMP(NCGS,NPGS)=0.0D0
      P_SHELL_TMP(NPSHELL,1,0,1)=NPGS
      P_SHELL_ANG_TMP(NPSHELL)=3
     ENDIF 
    ENDIF
   ENDDO

   IF ((IOPTN(9) >= 1).AND.(MYID==0)) THEN
    WRITE(6,'(A)') 'BASIS SET SHELL STRUCTURE'
    DO I=1,NPSHELL
     SELECT CASE(P_SHELL_ANG_TMP(I))
      CASE(0)
       WRITE(6,'(I3,A3,I3)') I,'S',P_SHELL_TMP(I,0,0,0)
      CASE(1)
       WRITE(6,'(I3,A3,I3,A3,3I3)') I,'S',P_SHELL_TMP(I,0,0,0), &
       'P',P_SHELL_TMP(I,1,0,0),P_SHELL_TMP(I,0,1,0),P_SHELL_TMP(I,0,0,1)
      CASE(2)
       WRITE(6,'(I3,A3,I3,A3,3I3,A3,6I3)') I,'S',P_SHELL_TMP(I,0,0,0), &
       'P',P_SHELL_TMP(I,1,0,0),P_SHELL_TMP(I,0,1,0),P_SHELL_TMP(I,0,0,1), &
       'D',P_SHELL_TMP(I,2,0,0),P_SHELL_TMP(I,0,2,0),P_SHELL_TMP(I,0,0,2), &
       P_SHELL_TMP(I,1,1,0),P_SHELL_TMP(I,0,1,1),P_SHELL_TMP(I,1,0,1)
      CASE(3)
       WRITE(6,'(I3,A3,I3,A3,3I3,A3,6I3,A3,10I3)') I,'S',P_SHELL_TMP(I,0,0,0), &
       'P',P_SHELL_TMP(I,1,0,0),P_SHELL_TMP(I,0,1,0),P_SHELL_TMP(I,0,0,1), &
       'D',P_SHELL_TMP(I,2,0,0),P_SHELL_TMP(I,0,2,0),P_SHELL_TMP(I,0,0,2), &
       P_SHELL_TMP(I,1,1,0),P_SHELL_TMP(I,0,1,1),P_SHELL_TMP(I,1,0,1), &
       'F',P_SHELL_TMP(I,3,0,0),P_SHELL_TMP(I,0,3,0),P_SHELL_TMP(I,0,0,3), &
       P_SHELL_TMP(I,2,1,0),P_SHELL_TMP(I,0,2,1),P_SHELL_TMP(I,1,0,2), &
       P_SHELL_TMP(I,1,2,0),P_SHELL_TMP(I,0,1,2),P_SHELL_TMP(I,2,0,1), &
       P_SHELL_TMP(I,1,1,1)
     END SELECT
    ENDDO
   ENDIF

   IF (MYID == 0) WRITE(6,'(A,I5)') 'NUMBER OF PRIMITIVE GAUSSIANS  (INCLUDING GHOST FUNCTIONS) = ',NPGS
   IF (MYID == 0) WRITE(6,'(A,I5)') 'NUMBER OF CONTRACTED GAUSSIANS (INCLUDING GHOST FUNCTIONS) = ',NCGS
   IF (MYID == 0) WRITE(6,'(A,I5)') 'NUMBER OF SHELLS               (INCLUDING GHOST FUNCTIONS) = ',NPSHELL

   ALLOCATE(PAX(NPGS),PAY(NPGS),PAZ(NPGS))
   ALLOCATE(PGSX(NPGS),PGSY(NPGS),PGSZ(NPGS))
   ALLOCATE(PGS_ATOM(NPGS))
   ALLOCATE(CGSX(NCGS),CGSY(NCGS),CGSZ(NCGS))
   ALLOCATE(ZT(NPGS))
   ALLOCATE(CC(NCGS,NPGS))
   ALLOCATE(C2S(NCGS,NCGS))
   ALLOCATE(C2H(NCGS,NCGS,-CEL2X-CEL1X:CEL2X+CEL1X))
   ALLOCATE(P2H(NPGS,NPGS,-CEL2X-CEL1X:CEL2X+CEL1X))
   ALLOCATE(C2H_THETA(NCGS,NCGS,-CEL2X-CEL1X:CEL2X+CEL1X))
   ALLOCATE(P2H_THETA(NPGS,NPGS,-CEL2X-CEL1X:CEL2X+CEL1X))
   ALLOCATE(P_SHELL(NPSHELL,0:BASIS_LMAX+1,0:BASIS_LMAX+1,0:BASIS_LMAX+1),P_SHELL_ANG(NPSHELL))
   PAX(1:NPGS)=PAX_TMP(1:NPGS)
   PAY(1:NPGS)=PAY_TMP(1:NPGS)
   PAZ(1:NPGS)=PAZ_TMP(1:NPGS)
   PGSX(1:NPGS)=PGSX_TMP(1:NPGS)
   PGSY(1:NPGS)=PGSY_TMP(1:NPGS)
   PGSZ(1:NPGS)=PGSZ_TMP(1:NPGS)
   PGS_ATOM(1:NPGS)=PGS_ATOM_TMP(1:NPGS)
   CGSX(1:NCGS)=CGSX_TMP(1:NCGS)
   CGSY(1:NCGS)=CGSY_TMP(1:NCGS)
   CGSZ(1:NCGS)=CGSZ_TMP(1:NCGS)
   ZT(1:NPGS)=ZT_TMP(1:NPGS)
   CC(1:NCGS,1:NPGS)=CC_TMP(1:NCGS,1:NPGS)
   P_SHELL(1:NPSHELL,:,:,:)=P_SHELL_TMP(1:NPSHELL,:,:,:)
   P_SHELL_ANG(1:NPSHELL)=P_SHELL_ANG_TMP(1:NPSHELL)

   RETURN
END SUBROUTINE



SUBROUTINE READ4
! READ AUXILIARY BASIS FUNCTIONS FROM AN EXTERNAL BASIS-SET FILE.
   
   USE MPI_F08
   USE CONSTANTS
   USE CONTROL
   USE STRUCTURE
   USE AUXILIARY
   USE CONSTANTS

   IMPLICIT NONE
!  INCLUDE "mpif.h"
   INTEGER :: NAGS_CHK
   INTEGER :: I,J,K,EOF
   DOUBLE PRECISION :: A,B
   CHARACTER(2) :: C

   NAGS_CHK=0
   NASHELL=0

   IF (MYID == 0) THEN
   OPEN(11,FILE=COPTN(17))
   DO I=1,NATOM
    REWIND(11)
    DO
     READ(11,'(A2)',IOSTAT=EOF) C
     IF (EOF /= 0) THEN
      CALL PABORT('AUXILIARY BASIS SET NOT FOUND')
     ELSE IF (C == CATOM(IATOM(I))) THEN
      DO
       READ(11,'(A2,I4)',IOSTAT=EOF) C,J
       IF (EOF /= 0) EXIT
       IF (C == ' S') THEN
        DO K=1,J
         READ(11,*) A,B
         NAGS_CHK=NAGS_CHK+1
         NASHELL=NASHELL+1
         AAX(NAGS_CHK)=0
         AAY(NAGS_CHK)=0
         AAZ(NAGS_CHK)=0
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
        ENDDO
       ELSE IF (C == ' P') THEN
        DO K=1,J
         READ(11,*) A,B
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=1
         AAY(NAGS_CHK)=0
         AAZ(NAGS_CHK)=0
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=0
         AAY(NAGS_CHK)=1
         AAZ(NAGS_CHK)=0
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=0
         AAY(NAGS_CHK)=0
         AAZ(NAGS_CHK)=1
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
        ENDDO
       ELSE IF (C == ' D') THEN
        DO K=1,J
         READ(11,*) A,B
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=2
         AAY(NAGS_CHK)=0
         AAZ(NAGS_CHK)=0
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**2/DSQRT(3.0D0)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=0
         AAY(NAGS_CHK)=2
         AAZ(NAGS_CHK)=0
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**2/DSQRT(3.0D0)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=0
         AAY(NAGS_CHK)=0
         AAZ(NAGS_CHK)=2
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**2/DSQRT(3.0D0)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=1
         AAY(NAGS_CHK)=1
         AAZ(NAGS_CHK)=0
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**2
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=0
         AAY(NAGS_CHK)=1
         AAZ(NAGS_CHK)=1
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**2
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=1
         AAY(NAGS_CHK)=0
         AAZ(NAGS_CHK)=1
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**2
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
        ENDDO
       ELSE IF (C == ' F') THEN
        DO K=1,J
         READ(11,*) A,B
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=3
         AAY(NAGS_CHK)=0
         AAZ(NAGS_CHK)=0
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(15.00D0)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=0
         AAY(NAGS_CHK)=3
         AAZ(NAGS_CHK)=0
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(15.00D0)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=0
         AAY(NAGS_CHK)=0
         AAZ(NAGS_CHK)=3
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(15.00D0)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=2
         AAY(NAGS_CHK)=1
         AAZ(NAGS_CHK)=0
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(3.0D0)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=0
         AAY(NAGS_CHK)=2
         AAZ(NAGS_CHK)=1
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(3.0D0)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=1
         AAY(NAGS_CHK)=0
         AAZ(NAGS_CHK)=2
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(3.0D0)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=1
         AAY(NAGS_CHK)=2
         AAZ(NAGS_CHK)=0
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(3.0D0)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=0
         AAY(NAGS_CHK)=1
         AAZ(NAGS_CHK)=2
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(3.0D0)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=2
         AAY(NAGS_CHK)=0
         AAZ(NAGS_CHK)=1
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3/DSQRT(3.0D0)
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
         NAGS_CHK=NAGS_CHK+1
         AAX(NAGS_CHK)=1
         AAY(NAGS_CHK)=1
         AAZ(NAGS_CHK)=1
         AGSX(NAGS_CHK)=ATOMX(I)
         AGSY(NAGS_CHK)=ATOMY(I)
         AGSZ(NAGS_CHK)=ATOMZ(I)
         AGS_ATOM(NAGS_CHK)=I
         AZT(NAGS_CHK)=A
         ANORM(NAGS_CHK)=DEXP(0.75D0*DLOG(2.0D0*A/PI))*DSQRT(4.0D0*A)**3
         IF (B == 0.0D0) ANORM(NAGS_CHK)=0.0D0
        ENDDO
       ELSE
        EXIT
       ENDIF
      ENDDO
      EXIT
     ENDIF
    ENDDO
   ENDDO
   CLOSE(11)
   IF (NAGS_CHK /= NAGS) CALL PABORT('AN ERROR IS DETECTED IN THE AUXILIARY BASIS-SET FILE')
   ENDIF

   CALL MPI_BCAST(NASHELL,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(AGS_ATOM,NAGS,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(AAX,NAGS,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(AAY,NAGS,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(AAZ,NAGS,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(AGSX,NAGS,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(AGSY,NAGS,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(AGSZ,NAGS,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(AZT,NAGS,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(ANORM,NAGS,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)

   IF (IOPTN(9) >= 2) THEN
    IF (MYID == 0) THEN
    WRITE(6,'(A)') 'AUXILIARY GAUSSIAN FUNCTIONS'
    WRITE(6,'(A)') 'No. Ax Ay Az       X         Y         Z         Exponent'
    DO I=1,NAGS
     WRITE(6,'(4I3,3F10.4,F17.8)') I,AAX(I),AAY(I),AAZ(I),AGSX(I),AGSY(I),AGSZ(I),AZT(I)
    ENDDO
    ENDIF
   ENDIF
END SUBROUTINE



SUBROUTINE CHECK_GEOMETRY
! CHECK IF THE INPUT MOLECULAR GEOMETRY ASSUMES TOO SHORT A BOND DISTANCE.

   USE MPI_F08
   USE CONSTANTS
   USE CONTROL
   USE STRUCTURE
   USE INTEGRAL
   USE SYMMETRY

   IMPLICIT NONE
!  INCLUDE "mpif.h"
   INTEGER :: I,J,KX,KY,KZ
   DOUBLE PRECISION :: X0,Y0,Z0,X1,Y1,Z1,X2,Y2,Z2,R
   DOUBLE PRECISION :: TMP
   DOUBLE PRECISION :: ANGLE,CS,SN

!  REORIENT POLYMER
   IF (LY.AND.(.NOT.LX).AND.(.NOT.LZ).AND.(HELIX /= 0.0D0)) THEN
    IF (MYID == 0) WRITE(6,'(A)') 'HELICAL POLYMER IS (RE)ORIENTED ALONG X-AXIS'
    DO I=1,NATOM
     TMP=ATOMX(I)
     ATOMX(I)=ATOMY(I)
     ATOMY(I)=ATOMZ(I)
     ATOMZ(I)=TMP
    ENDDO
    TMP=PERIODX
    PERIODX=PERIODY
    PERIODY=PERIODZ
    PERIODZ=TMP
    J=KVCX
    KVCX=KVCY
    KVCY=KVCZ
    KVCZ=J
    J=CEL1X
    CEL1X=CEL1Y
    CEL1Y=CEL1Z
    CEL1Z=J
    J=CEL2X
    CEL2X=CEL2Y
    CEL2Y=CEL2Z
    CEL2Z=J
    J=CEL3X
    CEL3X=CEL3Y
    CEL3Y=CEL3Z
    CEL3Z=J
    LX=.TRUE.
    LY=.FALSE.
    LZ=.FALSE.
   ELSE IF (LZ.AND.(.NOT.LX).AND.(.NOT.LY).AND.(HELIX /= 0.0D0)) THEN
    IF (MYID == 0) WRITE(6,'(A)') 'HELICAL POLYMER IS (RE)ORIENTED ALONG X-AXIS'
    DO I=1,NATOM
     TMP=ATOMX(I)
     ATOMX(I)=ATOMZ(I)
     ATOMZ(I)=ATOMY(I)
     ATOMY(I)=TMP
    ENDDO
    TMP=PERIODX
    PERIODX=PERIODZ
    PERIODZ=PERIODY
    PERIODY=TMP
    J=KVCX
    KVCX=KVCZ
    KVCZ=KVCY
    KVCY=J
    J=CEL1X
    CEL1X=CEL1Z
    CEL1Z=CEL1Y
    CEL1Y=J
    J=CEL2X
    CEL2X=CEL2Z
    CEL2Z=CEL2Y
    CEL2Y=J
    J=CEL3X
    CEL3X=CEL3Z
    CEL3Z=CEL3Y
    CEL3Y=J
    LX=.TRUE.
    LY=.FALSE.
    LZ=.FALSE.
   ENDIF

   DO I=1,NATOM
    X0=ATOMX(I)
    Y0=ATOMY(I)
    Z0=ATOMZ(I)
    DO J=1,NATOM
     X1=ATOMX(J)
     Y1=ATOMY(J)
     Z1=ATOMZ(J)
     DO KX=-CEL2X,CEL2X
     DO KY=-CEL2Y,CEL2Y
     DO KZ=-CEL2Z,CEL2Z
      ANGLE=DFLOAT(KX)*HELIX
      CS=DCOS(ANGLE)
      SN=DSIN(ANGLE)
      X2=X1+DFLOAT(KX)*PERIODX
      Y2=Y1*CS-Z1*SN+DFLOAT(KY)*PERIODY
      Z2=Y1*SN+Z1*CS+DFLOAT(KZ)*PERIODZ
      IF ((KX**2+KY**2+KZ**2 /= 0).OR.(I /= J)) THEN
       R=DSQRT((X2-X0)**2+(Y2-Y0)**2+(Z2-Z0)**2)
       IF (R == 0.0D0) THEN
        WRITE(6,'(I3,A2,A,I3,A2,A,3I0,A,F15.10,A)') I,CATOM(IATOM(I)),'(000) -',J,CATOM(IATOM(J)),'(',KX,KY,KZ,') = ',R,' BOHR'
        CALL PABORT('ZERO INTERNUCLEAR SEPARATION')
       ELSE IF (R < 1.0D0) THEN
        CALL WARNING('VERY SHORT BOND DISTANCE')
        WRITE(6,'(I3,A2,A,I3,A2,A,3I0,A,F15.10,A)') I,CATOM(IATOM(I)),'(000) -',J,CATOM(IATOM(J)),'(',KX,KY,KZ,') = ',R,' BOHR'
       ENDIF
      ENDIF
     ENDDO
     ENDDO
     ENDDO
    ENDDO
   ENDDO

   RETURN
END SUBROUTINE



SUBROUTINE CHECK_STORAGE
! ESTIMATE THE MAXIMUM MEMORY AND DISK SPACE USAGE BEFORE ENTERING HEAVY CALCULATIONS.

   USE MPI_F08
   USE CONSTANTS
   USE CONTROL
   USE STRUCTURE
   USE BASISSET
   USE INTEGRAL
   USE AUXILIARY

   IMPLICIT NONE
!  INCLUDE "mpif.h"
   DOUBLE PRECISION :: MEM,DISK

   ! FOUR-INDEX INTEGRALS
   IF ((.NOT.LOPTN(25)).AND.(.NOT.LOPTN(33))) THEN
    MEM=DFLOAT(16*NCGS**4)
    DISK=16.0*DFLOAT((2*CEL1X+1)**2*(2*CEL1Y+1)**2*(2*CEL1Z+1)**2*(CEL2X+1)*(CEL2Y+1)*(CEL2Z+1))*DFLOAT(NCGS**4)
    IF (MEM > 1000000.0D0) THEN
     IF (MYID == 0) WRITE(6,'(A,F9.1,A)') 'MEMORY REQUIRED (INTEGRALS) ',MEM/1000000.0D0,' MB'
    ELSE 
     IF (MYID == 0) WRITE(6,'(A,F9.1,A)') 'MEMORY REQUIRED (INTEGRALS) ',MEM/1000.0D0,' KB'
    ENDIF
    IF (DISK > 1000000000.0D0) THEN
     IF (MYID == 0) WRITE(6,'(A,F9.1,A)') 'DISK   REQUIRED (INTEGRALS) ',DISK/1000000000.0D0,' GB X A FEW PERCENTS'
    ELSE IF (DISK > 1000000.0D0) THEN
     IF (MYID == 0) WRITE(6,'(A,F9.1,A)') 'DISK   REQUIRED (INTEGRALS) ',DISK/1000000.0D0,' MB X A FEW PERCENTS'
    ELSE 
     IF (MYID == 0) WRITE(6,'(A,F9.1,A)') 'DISK   REQUIRED (INTEGRALS) ',DISK/1000.0D0,' KB X A FEW PERCENTS'
    ENDIF
   ENDIF 

   ! MP2/DYSON ENERGY
   IF (DOPTN(24) /= 0.0D0) THEN
    MEM=32.0D0*DFLOAT((NCGS**3*(2*CEL1X+1)*(2*CEL1Y+1)*(2*CEL1Z+1)*(2*CEL2X+1)*(2*CEL2Y+1)*(2*CEL2Z+1) &
    +(MIN(IOCC+IOPTN(44),IALLMAX)-ICORE)*2*KVCX*2*KVCY*2*KVCZ+ &
    (IALLMAX-MAX(IOCC-IOPTN(44),ICORE))*(MIN(IOCC+IOPTN(44),IALLMAX)-ICORE)*4*KVCX**2*4*KVCY**2*4*KVCZ**2+ &
    (MIN(IOCC+IOPTN(44),IALLMAX)-ICORE)**2*(IALLMAX-MAX(IOCC-IOPTN(44),ICORE))*4*KVCX**2*4*KVCY**2*4*KVCZ**2))
    IF (MEM > 1.0D9) THEN
     IF (MYID == 0) WRITE(6,'(A,F9.1,A)') 'MEMORY REQUIRED (MP2/DYSON) ',MEM/1.0D9,' GB'
    ELSE IF (MEM > 1.0D6) THEN
     IF (MYID == 0) WRITE(6,'(A,F9.1,A)') 'MEMORY REQUIRED (MP2/DYSON) ',MEM/1.0D6,' MB'
    ELSE 
     IF (MYID == 0) WRITE(6,'(A,F9.1,A)') 'MEMORY REQUIRED (MP2/DYSON) ',MEM/1.0D3,' KB'
    ENDIF
   ENDIF

   RETURN
END SUBROUTINE
