SUBROUTINE SELFCONSISTENTDYSON
! PERFORM HIGH-ORDER RECURSIVE MP FOR N AND N+/-1 ELECTRON SYSTEMS

   USE CONTROL
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI

   IMPLICIT NONE
   INTEGER,PARAMETER :: MAXLOOP=2
   INTEGER :: I,MOP
   DOUBLE PRECISION :: OMEGA,OMEGAOLD

   IF (KVC /= 0) CALL PABORT('FOR MOLECULES ONLY')
   IF (LOPTN(25)) CALL PABORT('USE NON-DIRECT ALGORITHM')
   IF (IALL(0)-IOCC-IVIRTCORE <= 0) CALL PABORT('NO VIRTUAL ORBITAL')

   ALLOCATE(H(IALLMAX-IVIRTCORE,IALLMAX-IVIRTCORE))
   ALLOCATE(G(IALLMAX-IVIRTCORE,IALLMAX-IVIRTCORE,IALLMAX-IVIRTCORE,IALLMAX-IVIRTCORE))
   ALLOCATE(MP_STORED(0:IOPTN(97)))
   CALL ONE_ELECTRON_INTEGRALS
   CALL TWO_ELECTRON_INTEGRALS
   CALL GENERATE_CONFIGURATIONS(MIN(IOCC-ICORE,IALL(0)-IOCC-IVIRTCORE))
   CALL GENERATE_IP_CONFIGURATIONS(MIN(IOCC-ICORE,IALL(0)-IOCC-IVIRTCORE+1))
   CALL GENERATE_EA_CONFIGURATIONS(MIN(IOCC-ICORE+1,IALL(0)-IOCC-IVIRTCORE))
   ! MBPT
   DO MOP=ICORE+1,IOCC
    OMEGA=EPSILON(MOP,0)
    DO I=1,MAXLOOP
write(*,*) '####### MO = ',MOP,' ITER =',i,' OMEGA = ',omega
     OMEGAOLD=OMEGA
     CALL SC_HIGHORDER_MP(IOPTN(97),MOP,OMEGA)
     CALL SC_HIGHORDER_MP_IP(IOPTN(97),MOP,OMEGA)
!    IF (DABS(OMEGAOLD-OMEGA).LT.1.0D-6) EXIT
    ENDDO
   ENDDO
!  DO MOP=IOCC+1,IALL-IVIRTCORE
!   OMEGA=EPSILON(MOP,0)
!   DO I=1,MAXLOOP
!    OMEGAOLD=OMEGA
!    CALL SC_HIGHORDER_MP(IOPTN(97),MOP,OMEGA)
!    CALL SC_HIGHORDER_MP_EA(IOPTN(97),MOP,OMEGA)
!    IF (DABS(OMEGAOLD-OMEGA).LT.1.0D-6) EXIT
!   ENDDO
!  ENDDO
   DEALLOCATE(MP_STORED)
   DEALLOCATE(IP_CFHALF,IP_NORDER,IP_ADDRSS)
   DEALLOCATE(EA_CFHALF,EA_NORDER,EA_ADDRSS)
   DEALLOCATE(CFHALF,ADDRSS,NORDER)
   DEALLOCATE(H,G)

   RETURN
END SUBROUTINE



SUBROUTINE SC_HIGHORDER_MP(ORDER,MOP,OMEGA)
! PERFORM HIGH-ORDER MOELLER-PLESSET PERTURBATION CALCULATIONS IN A RECURSIVE ALGORITHM.

   USE CONTROL
   USE GRADIENT
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI

   IMPLICIT NONE
   INTEGER :: MOP
   DOUBLE PRECISION :: OMEGA
   INTEGER,PARAMETER :: MAXFILE = 100
   INTEGER :: ORDER
   INTEGER :: MOI,MOJ
   INTEGER :: IA,IB
   INTEGER :: I,J,K,IFILE
   REAL :: MEM,ICPUS,ICPUE
   DOUBLE PRECISION :: HA,HB
   DOUBLE PRECISION :: EMP,DMP(0:ORDER)
   DOUBLE PRECISION,ALLOCATABLE :: VEC1(:,:),VEC2(:,:)

   CALL PCPU_TIME(ICPUS)
   WRITE(6,'(A)') 'RECURSIVE HIGH-ORDER MOELLER-PLESSET PERTURBATION CALCULATIONS WILL BE PERFORMED'
   MEM=16.0*2.0*NCF**2
   IF (MEM > 1000000.0) THEN
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000000.0,' MB'
   ELSE IF (MEM > 1000.0) THEN
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000.0,' KB'
   ELSE
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM,' B'
   ENDIF
   IF (MEM > DOPTN(28)*1000000.0) CALL PABORT('OUT OF MEMORY') 
   WRITE(6,'(A)') '------------------------------------------------------'
   WRITE(6,'(A)') 'ORDER      CORRELATION        TOTAL ENERGY   CPU / SEC'
   ALLOCATE(VEC1(NCF,NCF),VEC2(NCF,NCF))
   OPEN(50,FILE=TRIM(COPTN(1))//'.fi0',FORM='UNFORMATTED')
   OPEN(51,FILE=TRIM(COPTN(1))//'.fo0',FORM='UNFORMATTED')

   ! INITIALIZE WAVEFUNCTION TO THE HARTREE-FOCK DETERMINANT
   EMP=NUCLEAR_REPULSION
   VEC1=0.0D0
   VEC1(1,1)=1.0D0
   REWIND(50)
   WRITE(50) VEC1

   ! DMP(0)
   DMP(0)=0.0D0
   DO MOI=1,IOCC
    IF (MOI==MOP) DMP(0)=DMP(0)+EPSILON(MOI,0)+OMEGA
    IF (MOI/=MOP) DMP(0)=DMP(0)+2.0D0*EPSILON(MOI,0)
   ENDDO
   EMP=EMP+DMP(0)
   WRITE(6,'(I2,F20.10,F20.10,F12.1)') 0,DMP(0),EMP,0.0
   MP_STORED(0)=EMP

   ! DMP(1) ONWARD
   DO IFILE=0,ORDER-1
    IF (IOPTN(9) >= 3) THEN
     REWIND(50)
     DO I=0,IFILE
      READ(50) VEC1
     ENDDO
     WRITE(6,'(I3,A)') IFILE,'TH ORDER WAVE FUNCTION'
     CALL DUMP5(VEC1,NCF)
    ENDIF
    DEALLOCATE(VEC1,VEC2)
    CALL HAMILTONIAN_PRODUCT(50,51,IFILE,2*MIN(IOCC-ICORE,IALL(0)-IOCC-IVIRTCORE))
    ALLOCATE(VEC1(NCF,NCF),VEC2(NCF,NCF))
    REWIND(51)
    DO I=0,IFILE
     READ(51) VEC1
    ENDDO
    IF (IOPTN(9) >= 3) THEN
     WRITE(6,'(A,I1,A)') 'H|',IFILE,'>'
     CALL DUMP5(VEC1,NCF)
    ENDIF
!   IF (IFILE == 0) THEN
!    DMP(1)=-DMP(0)
!    DO MOI=1,IOCC
!     DMP(1)=DMP(1)+2.0D0*H(MOI,MOI)
!    ENDDO
!    DO MOI=1,IOCC
!     DO MOJ=1,IOCC
!      DMP(1)=DMP(1)+(2.0D0*G(MOI,MOI,MOJ,MOJ)-G(MOI,MOJ,MOJ,MOI))
!     ENDDO
!    ENDDO
!   ELSE
!    DMP(IFILE+1)=VEC1(1,1)
!   ENDIF
    DMP(IFILE+1)=VEC1(1,1)
    IF (IFILE == 0) DMP(1)=DMP(1)-DMP(0)
    EMP=EMP+DMP(IFILE+1)
    CALL PCPU_TIME(ICPUE)
    WRITE(6,'(I2,F20.10,F20.10,F12.1)') IFILE+1,DMP(IFILE+1),EMP,ICPUE-ICPUS
    MP_STORED(IFILE+1)=EMP
    CALL PCPU_TIME(ICPUS)
    CALL PFLUSH(6)
    IF (DABS(DMP(IFILE+1)) < 1.0D-15) EXIT
    VEC1=-VEC1
    REWIND(50)
    DO K=0,IFILE
     READ(50) VEC2
     DO IA=1,NCF
      HA=0.0D0
      IF (K == IFILE) THEN
       DO I=1,IALL(0)-IVIRTCORE
!       IF ((I==MOP).AND.(BTEST(CFHALF(IA),I-1))) HA=HA+OMEGA
!       IF ((I/=MOP).AND.(BTEST(CFHALF(IA),I-1))) HA=HA+EPSILON(I,0)
        IF (BTEST(CFHALF(IA),I-1)) HA=HA+EPSILON(I,0)
       ENDDO
      ENDIF
      DO IB=1,NCF
       HB=0.0D0
       IF (K == IFILE) THEN
        DO I=1,IALL(0)-IVIRTCORE
!        IF ((I==MOP).AND.(BTEST(CFHALF(IB),I-1))) HB=HB+OMEGA
!        IF ((I/=MOP).AND.(BTEST(CFHALF(IB),I-1))) HB=HB+EPSILON(I,0)
         IF (BTEST(CFHALF(IB),I-1)) HB=HB+EPSILON(I,0)
        ENDDO
       ENDIF
       IF (K == IFILE) THEN
        VEC1(IB,IA)=VEC1(IB,IA)+(DMP(IFILE-K+1)+HA+HB)*VEC2(IB,IA)
       ELSE
        VEC1(IB,IA)=VEC1(IB,IA)+DMP(IFILE-K+1)*VEC2(IB,IA)
       ENDIF
!write(*,*) "debug !!!!!!!!!!!!"
!VEC1(IB,IA)=VEC1(IB,IA)+(HA+HB)*VEC2(IB,IA)
      ENDDO
     ENDDO
    ENDDO
    DO IA=1,NCF
     HA=0.0D0
     DO I=1,IALL(0)-IVIRTCORE
!     IF ((I==MOP).AND.(BTEST(CFHALF(IA),I-1))) HA=HA+OMEGA
!     IF ((I/=MOP).AND.(BTEST(CFHALF(IA),I-1))) HA=HA+EPSILON(I,0)
      IF (BTEST(CFHALF(IA),I-1)) HA=HA+EPSILON(I,0)
     ENDDO
     DO IB=1,NCF
      HB=0.0D0
      DO I=1,IALL(0)-IVIRTCORE
       IF ((I==MOP).AND.(BTEST(CFHALF(IB),I-1))) HB=HB+OMEGA
       IF ((I/=MOP).AND.(BTEST(CFHALF(IB),I-1))) HB=HB+EPSILON(I,0)
!      IF (BTEST(CFHALF(IB),I-1)) HB=HB+EPSILON(I,0)
      ENDDO
      IF ((IA == 1).AND.(IB == 1)) THEN
       VEC2(IB,IA)=0.0D0
      ELSE
       VEC2(IB,IA)=VEC1(IB,IA)/(HA+HB-DMP(0))
!if ((dabs(vec1(ib,ia))>1.0d-8)) write(*,*) vec1(ib,ia),ha+hb-dmp(0),omega
!if ((dabs(vec1(ib,ia))>1.0d-8)) write(*,*) ia,ib,ha,hb,dmp(0),omega
      ENDIF
     ENDDO
    ENDDO
    IF (IFILE == MAXFILE) EXIT
    WRITE(50) VEC2
   ENDDO

   WRITE(6,'(A)') '------------------------------------------------------'
   IF (IOPTN(97) > 0) THEN
    OPEN(97,FILE=TRIM(COPTN(1))//'.gf0',FORM='UNFORMATTED')
    VEC2=0.0D0
    REWIND(50)
    DO I=0,ORDER-1
     READ(50) VEC1
     VEC2=VEC2+VEC1
    ENDDO
    REWIND(97)
    WRITE(97) VEC2
    CLOSE(97)
    WRITE(6,'(A,A)') 'REFERENCE WAVE FUNCTION FOR MBGF STORED IN ',TRIM(COPTN(1))//'.gf0'
   ENDIF

   DEALLOCATE(VEC1,VEC2)
   CLOSE(50)
   CLOSE(51)
   RETURN
END SUBROUTINE



SUBROUTINE SC_HIGHORDER_MP_IP(ORDER,MOP,OMEGA)
! PERFORM HIGH-ORDER MOELLER-PLESSET PERTURBATION CALCULATIONS IN A RECURSIVE ALGORITHM
! FOR KOOPMANS-IONIZED INITIAL DETERMINANT TO BE USED TO DETERMINE THE DYSON SELF-ENERGY
! AT OMEGA = EPSILON_P.

   USE CONTROL
   USE GRADIENT
   USE STRUCTURE
   USE INTEGRAL
   USE BASISSET
   USE FULLCI

   IMPLICIT NONE
   INTEGER :: MOP
   DOUBLE PRECISION :: OMEGA,OMEGANEW
   INTEGER,PARAMETER :: MAXFILE = 100
   INTEGER :: ORDER
   INTEGER :: MOI,MOJ
   INTEGER :: IA,IB,IR
   INTEGER :: I,J,K,IFILE
   REAL :: MEM,ICPUS,ICPUE
   DOUBLE PRECISION :: HA,HB
   DOUBLE PRECISION :: EMP,DMP(0:ORDER)
   DOUBLE PRECISION,ALLOCATABLE :: VEC1(:,:),VEC2(:,:)
   INTEGER :: NQP

   CALL PCPU_TIME(ICPUS)
   WRITE(6,'(A)') 'RECURSIVE HIGH-ORDER MOELLER-PLESSET PERTURBATION CALCULATIONS WILL BE PERFORMED'
   MEM=16.0*2.0*NCF*IP_NCF
   IF (MEM > 1000000.0) THEN
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000000.0,' MB'
   ELSE IF (MEM > 1000.0) THEN
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM/1000.0,' KB'
   ELSE
    WRITE(6,'(A,F7.1,A)') 'ESTIMATED MEMORY USAGE WILL BE ',MEM,' B'
   ENDIF
   IF (MEM > DOPTN(28)*1000000.0) CALL PABORT('OUT OF MEMORY')

   NQP=IOPTN(44)
   IF (NQP < 1) NQP=IOCC-ICORE

   EMP=NUCLEAR_REPULSION
   WRITE(6,'(A,I3)') 'STATE IONIZED FROM ORBITAL ',MOP
   WRITE(6,'(A)') '--------------------------------------------------------------------------'
   WRITE(6,'(A)') 'ORDER      CORRELATION        TOTAL ENERGY         SELF-ENERGY   CPU / SEC'
   ALLOCATE(VEC1(IP_NCF,NCF),VEC2(IP_NCF,NCF))
   OPEN(50,FILE=TRIM(COPTN(1))//'.fi0',FORM='UNFORMATTED')
   OPEN(51,FILE=TRIM(COPTN(1))//'.fo0',FORM='UNFORMATTED')

   ! INITIALIZE WAVEFUNCTION TO THE HARTREE-FOCK DETERMINANT
   IR=IP_ADDRSS(IBCLR(CFHALF(1),MOP-1))
   VEC1=0.0D0
   VEC1(IR,1)=1.0D0
   REWIND(50)
   WRITE(50) VEC1
   !CALL DUMP14(50,1)

   ! DMP(0)
   DMP(0)=0.0D0
   DO MOI=1,IOCC
    IF (MOI==MOP) DMP(0)=DMP(0)+EPSILON(MOI,0)+OMEGA
    IF (MOI/=MOP) DMP(0)=DMP(0)+2.0D0*EPSILON(MOI,0)
   ENDDO
   DMP(0)=DMP(0)-OMEGA
   EMP=EMP+DMP(0)
   WRITE(6,'(I2,F20.10,2F20.10,F12.1)') 0,DMP(0),EMP,MP_STORED(0)-EMP,0.0

   ! DMP(1) ONWARD
   DO IFILE=0,ORDER-1
    IF (IOPTN(9) >= 3) THEN
     REWIND(50)
     DO I=0,IFILE
      READ(50) VEC1
     ENDDO
     WRITE(6,'(I3,A)') IFILE,'TH ORDER WAVE FUNCTION'
     CALL DUMP5(VEC1,NCF)
    ENDIF
    DEALLOCATE(VEC1,VEC2)
    CALL IP_HAMILTONIAN_PRODUCT(50,51,IFILE,MIN(IOCC-ICORE,IALL(0)-IOCC-IVIRTCORE)+MIN(IOCC-ICORE,IALL(0)-IOCC-IVIRTCORE+1))
    ALLOCATE(VEC1(IP_NCF,NCF),VEC2(IP_NCF,NCF))
    REWIND(51)
    DO I=0,IFILE
     READ(51) VEC1
    ENDDO
    IF (IOPTN(9) >= 3) THEN
     WRITE(6,'(A,I1,A)') 'H|',IFILE,'>'
     CALL DUMP5(VEC1,NCF)
    ENDIF
!   IF (IFILE == 0) THEN
!    DMP(1)=-DMP(0)
!    DO MOI=1,IOCC
!     DMP(1)=DMP(1)+2.0D0*H(MOI,MOI)
!    ENDDO
!    DMP(1)=DMP(1)-H(MOP,MOP)
!    DO MOI=1,IOCC
!     DO MOJ=1,IOCC
!      DMP(1)=DMP(1)+(2.0D0*G(MOI,MOI,MOJ,MOJ)-G(MOI,MOJ,MOJ,MOI))
!     ENDDO
!    ENDDO
!    DO MOJ=1,IOCC
!     DMP(1)=DMP(1)-(G(MOP,MOP,MOJ,MOJ)-0.5D0*G(MOP,MOJ,MOJ,MOP))
!    ENDDO
!   ELSE
!    DMP(IFILE+1)=VEC1(IR,1)
!   ENDIF
    DMP(IFILE+1)=VEC1(IR,1)
    IF (IFILE == 0) DMP(1)=DMP(1)-DMP(0)
    EMP=EMP+DMP(IFILE+1)
    CALL PCPU_TIME(ICPUE)
    WRITE(6,'(I2,F20.10,2F20.10,F12.1)') IFILE+1,DMP(IFILE+1),EMP,MP_STORED(IFILE+1)-EMP,ICPUE-ICPUS
    OMEGANEW=MP_STORED(IFILE+1)-EMP
    CALL PCPU_TIME(ICPUS)
    CALL PFLUSH(6)
    IF (DABS(DMP(IFILE+1)) < 1.0D-15) THEN
     OMEGA=OMEGANEW
     EXIT
    ENDIF
    VEC1=-VEC1
    REWIND(50)
    DO K=0,IFILE
     READ(50) VEC2
     DO IA=1,NCF
      HA=0.0D0
      IF (K == IFILE) THEN
       DO I=1,IALL(0)-IVIRTCORE
!       IF ((I==MOP).AND.(BTEST(CFHALF(IA),I-1))) HA=HA+OMEGA
!       IF ((I/=MOP).AND.(BTEST(CFHALF(IA),I-1))) HA=HA+EPSILON(I,0)
        IF (BTEST(CFHALF(IA),I-1)) HA=HA+EPSILON(I,0)
       ENDDO
      ENDIF
      DO IB=1,IP_NCF
       HB=0.0D0
       IF (K == IFILE) THEN
        DO I=1,IALL(0)-IVIRTCORE
!        IF ((I==MOP).AND.(BTEST(IP_CFHALF(IB),I-1))) HB=HB+OMEGA
!        IF ((I/=MOP).AND.(BTEST(IP_CFHALF(IB),I-1))) HB=HB+EPSILON(I,0)
         IF (BTEST(IP_CFHALF(IB),I-1)) HB=HB+EPSILON(I,0)
        ENDDO
       ENDIF
       IF (K == IFILE) THEN
        VEC1(IB,IA)=VEC1(IB,IA)+(DMP(IFILE-K+1)+HA+HB)*VEC2(IB,IA)
       ELSE
        VEC1(IB,IA)=VEC1(IB,IA)+DMP(IFILE-K+1)*VEC2(IB,IA)
       ENDIF
!write(*,*) "debug !!!!!!!!!!!!"
!VEC1(IB,IA)=VEC1(IB,IA)+(HA+HB)*VEC2(IB,IA)
      ENDDO
     ENDDO
    ENDDO
    DO IA=1,NCF
     HA=0.0D0
     DO I=1,IALL(0)-IVIRTCORE
!     IF ((I==MOP).AND.(BTEST(CFHALF(IA),I-1))) HA=HA+OMEGA
!     IF ((I/=MOP).AND.(BTEST(CFHALF(IA),I-1))) HA=HA+EPSILON(I,0)
      IF (BTEST(CFHALF(IA),I-1)) HA=HA+EPSILON(I,0)
     ENDDO
     DO IB=1,IP_NCF
      HB=0.0D0
      DO I=1,IALL(0)-IVIRTCORE
       IF ((I==MOP).AND.(BTEST(IP_CFHALF(IB),I-1))) HB=HB+OMEGA
       IF ((I/=MOP).AND.(BTEST(IP_CFHALF(IB),I-1))) HB=HB+EPSILON(I,0)
!      IF (BTEST(IP_CFHALF(IB),I-1)) HB=HB+EPSILON(I,0)
      ENDDO
      IF ((IA == 1).AND.(IB == IR)) THEN
       VEC2(IB,IA)=0.0D0
!SPECULATIVE 
      ELSE IF (DABS(HA+HB-DMP(0)) < 1.0D-10) THEN
       WRITE(6,'(A)') 'DEGENERACY DETECTED'
       VEC2(IB,IA)=0.0D0
      ELSE
       VEC2(IB,IA)=VEC1(IB,IA)/(HA+HB-DMP(0))
      ENDIF
     ENDDO
    ENDDO
    IF (IFILE == MAXFILE) EXIT
    WRITE(50) VEC2
   ENDDO

   WRITE(6,'(A)') '--------------------------------------------------------------------------'
   DEALLOCATE(VEC1,VEC2)
   OMEGA=OMEGANEW
   CLOSE(50)
   CLOSE(51)

!  IF (IOPTN(97) > 0) THEN
!   OPEN(97,FILE=TRIM(COPTN(1))//'.gf0',FORM='UNFORMATTED')
!   VEC2=0.0D0
!   REWIND(50)
!   DO I=0,ORDER-1
!    READ(50) VEC1
!    VEC2=VEC2+VEC1
!   ENDDO
!   REWIND(97)
!   WRITE(97) VEC2
!   CLOSE(97)
!   WRITE(6,'(A,A)') 'REFERENCE WAVE FUNCTION FOR MBGF STORED IN ',TRIM(COPTN(1))//'.gf0'
!  ENDIF

   RETURN
END SUBROUTINE
