SUBROUTINE SINGLEPOINT
! CALCULATE SINGLE-POINT ENERGY IF IOPTN(7)=0, AND
! SINGLE-POINT ENERGY GRADIENTS IF IOPTN(7)>=1.

   USE MPI
   USE CONTROL
   USE STRUCTURE
   USE BASISSET
   USE AUXILIARY
   USE GRADIENT
   USE INTEGRAL
   USE GRADIENT
   USE DFT
   USE MP2GRADIENT
   USE CIS
   USE OEP
   USE OPTIMIZE
   
   IMPLICIT NONE
   INCLUDE "mpif.h"
   INTEGER :: ISCF,IDIIS
   DOUBLE PRECISION :: ICPUS,ICPUE
   DOUBLE PRECISION :: DISK
   DOUBLE PRECISION :: ASYMMETRY,DENSITYCHANGE,OLDENERGY
   INTEGER :: I
   
   ! READ BASIS SETS
   IF (LX) THEN
    CEL1X=IOPTN(10)
    CEL2X=IOPTN(11)
    CEL3X=IOPTN(29)
!   KVCX=IOPTN(6)
   ELSE
    CEL1X=0
    CEL2X=0
    CEL3X=0
    IF (KVCX /= 0) CALL WARNING('KVCX IS SET TO ZERO')
    KVCX=0
   ENDIF
   IF (LY) THEN
    CEL1Y=IOPTN(10)
    CEL2Y=IOPTN(11)
    CEL3Y=IOPTN(29)
!   KVCY=IOPTN(6)
   ELSE
    CEL1Y=0
    CEL2Y=0
    CEL3Y=0
    IF (KVCY /= 0) CALL WARNING('KVCY IS SET TO ZERO')
    KVCY=0
   ENDIF
   IF (LZ) THEN
    CEL1Z=IOPTN(10)
    CEL2Z=IOPTN(11)
    CEL3Z=IOPTN(29)
!   KVCZ=IOPTN(6)
   ELSE
    CEL1Z=0
    CEL2Z=0
    CEL3Z=0
    IF (KVCZ /= 0) CALL WARNING('KVCZ IS SET TO ZERO')
    KVCZ=0
   ENDIF
   CALL CHECK_GEOMETRY
   CALL DUMPGEOMETRY(MAXOPTCYCLES)
   IF (MYID == 0) CALL DUMP0
   CALL READ3
   CALL FORM_C2S
   CALL FORM_C2H
!  CALL SHELL1
   IF (LOPTN(33).OR.LOPTN(34).OR.LOPTN(46).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0)) THEN
    ALLOCATE(AAX(NAGS),AAY(NAGS),AAZ(NAGS))
    ALLOCATE(AGSX(NAGS),AGSY(NAGS),AGSZ(NAGS))
    ALLOCATE(AGS_ATOM(NAGS))
    ALLOCATE(AZT(NAGS),ANORM(NAGS))
    CALL READ4
    ALLOCATE(A_SHELL(NASHELL,0:BASIS_LMAX+1,0:BASIS_LMAX+1,0:BASIS_LMAX+1),A_SHELL_ANG(NASHELL))
    CALL SHELL2
   ENDIF
   ! A SCRATCH FILE FOR OEP
   IF (LOPTN(46).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0)) THEN
    IF (IOPTN(71) == 1) OPEN(32,FILE=TRIM(COPTN(1))//'.er3',FORM='UNFORMATTED')
    IF (IOPTN(71) >= 2) OPEN(35,FILE=TRIM(COPTN(1))//'.ov3',FORM='UNFORMATTED')
   ENDIF
   ! A SCRATCH FILE FOR RI-SCF & RI-MP2
   IF (LOPTN(33).OR.LOPTN(34)) THEN
    OPEN(32,FILE=TRIM(COPTN(1))//'.ao3',FORM='UNFORMATTED')
    CALL PABORT('RI APPROXIMATION SUPPRESSED')
   ENDIF
!3 ! SCRATCH FILES FOR RI-MP2
!3 IF (LOPTN(34)) THEN
!3  OPEN(33,FILE=TRIM(COPTN(1))//'.co3',FORM='UNFORMATTED')
!3  OPEN(34,FILE=TRIM(COPTN(1))//'.v1', FORM='UNFORMATTED')
!3  OPEN(35,FILE=TRIM(COPTN(1))//'.ov3',FORM='UNFORMATTED')
!3 ENDIF
   ! SCRATCH FILES FOR SINGLE-EXCITATION THEORIES OR POLARIZABILITY
   IF ((IOPTN(36) > 0).OR.(IOPTN(37) > 0).OR.LOPTN(86)) THEN
    OPEN(36,FILE=TRIM(COPTN(1))//'.tri',FORM='UNFORMATTED')
    OPEN(37,FILE=TRIM(COPTN(1))//'.tro',FORM='UNFORMATTED')
    OPEN(38,FILE=TRIM(COPTN(1))//'.trr',FORM='UNFORMATTED')
   ENDIF
   ! SINGLE-POINT ENERGY CALCULATIONS / GRADIENT CALCULATIONS /
   ! GEOMETRY OPTIMIZATIONS / VIBRATIONAL FREQUENCY CALCULATIONS
   IF ((IOPTN(10) < 0).OR.(IOPTN(11) < 0).OR.(IOPTN(29) < 0)) THEN
    CALL PABORT('INVALID CUTOFF PARAMETERS')
   ELSE IF (KVCX**2+KVCY**2+KVCZ**2 == 0) THEN
    CALL WARNING('GAMMA APPROXIMATION IS INVOKED')
    IF (IOPTN(18) > 0) THEN
     CALL WARNING('MULTIPOLE EXPANSION IS SUPPRESSED')
     IOPTN(18)=0
    ENDIF
   ELSE IF ((KVCX < 0).OR.(KVCY < 0).OR.(KVCZ < 0)) THEN
    CALL PABORT('INVALID WAVEVECTOR SAMPLING POINTS')
   ELSE IF ((KVCX < CEL1X).OR.(KVCY < CEL1Y).OR.(KVCZ < CEL1Z)) THEN
    CALL WARNING('WAVEVECTOR SAMPLING POINTS &
    &ARE FEWER THAN THE NUMBER OF NEIGHBORS IN LATTICE SUMMATIONS')
   ENDIF
   ! ALLOCATE INTEGRAL AND NUMERICAL INTEGRATION RELATED ARRAYS
   ALLOCATE(S_P(NPGS,NPGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
   ALLOCATE(S_C(NCGS,NCGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
   ALLOCATE(F_C(NCGS,NCGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
   ALLOCATE(T_C(NCGS,NCGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
   ALLOCATE(N_C(NCGS,NCGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
   ALLOCATE(C_C(NCGS,NCGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
   ALLOCATE(X_C(NCGS,NCGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
   IF (LOPTN(46).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0)) ALLOCATE(O_C(NCGS,NCGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
   IF (LOPTN(46).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0)) ALLOCATE(CHI_INVERSE(NAGS,NAGS))
   ALLOCATE(M_C(NCGS,NCGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z,9))
   ALLOCATE(MPE_C(NCGS,NCGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
   ALLOCATE(P_P(NPGS,NPGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
   ALLOCATE(P_C(NCGS,NCGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
   ALLOCATE(P_C_OUT(NCGS,NCGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
   ALLOCATE(W_P(NPGS,NPGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
   ALLOCATE(W_C(NCGS,NCGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
   ALLOCATE(P_P_HELIX(NPGS,NPGS,-CEL2X:CEL2X,-CEL2X-CEL1X:CEL2X+CEL1X))
   ALLOCATE(W_P_HELIX(NPGS,NPGS,-CEL2X:CEL2X,-CEL2X-CEL1X:CEL2X+CEL1X))
   ALLOCATE(P_C_HELIX(NCGS,NCGS,-CEL2X:CEL2X,-CEL2X-CEL1X:CEL2X+CEL1X))
   ALLOCATE(W_C_HELIX(NCGS,NCGS,-CEL2X:CEL2X,-CEL2X-CEL1X:CEL2X+CEL1X))
   ALLOCATE(P_P_HELIX_THETA(NPGS,NPGS,-CEL2X:CEL2X,-CEL2X-CEL1X:CEL2X+CEL1X))
   ALLOCATE(W_P_HELIX_THETA(NPGS,NPGS,-CEL2X:CEL2X,-CEL2X-CEL1X:CEL2X+CEL1X))
   ALLOCATE(P_C_HELIX_THETA(NCGS,NCGS,-CEL2X:CEL2X,-CEL2X-CEL1X:CEL2X+CEL1X))
   ALLOCATE(W_C_HELIX_THETA(NCGS,NCGS,-CEL2X:CEL2X,-CEL2X-CEL1X:CEL2X+CEL1X))
   ALLOCATE(CO(NCGS,NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))
   ALLOCATE(EPSILON(NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))
   ALLOCATE(PULAY(IOPTN(13),IOPTN(13)))
   IF (LDFT.OR.LOPTN(72).OR.LOPTN(73).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0).OR.(LOPTN(46).AND.(IOPTN(71) >= 3))) THEN
    ALLOCATE(NGRID(NATOM),GRIDX(MAXNGRID,NATOM),GRIDY(MAXNGRID,NATOM),GRIDZ(MAXNGRID,NATOM))
    ALLOCATE(ATOMW(MAXNGRID,NATOM),FUZZY(MAXNGRID,NATOM),GRIDW(MAXNGRID,NATOM))
    ALLOCATE(GRIDW_X(MAXNGRID,NATOM,NATOM),GRIDW_Y(MAXNGRID,NATOM,NATOM),GRIDW_Z(MAXNGRID,NATOM,NATOM))
    ALLOCATE(GRIDW_TX(MAXNGRID,NATOM),GRIDW_TY(MAXNGRID,NATOM),GRIDW_TZ(MAXNGRID,NATOM),GRIDW_TA(MAXNGRID,NATOM))
    ALLOCATE(RHO(MAXNGRID,NATOM),D1F1(MAXNGRID,NATOM),XCF(MAXNGRID,NATOM))
!   ALLOCATE(RHO_GTX(MAXNGRID,NATOM),RHO_GTY(MAXNGRID,NATOM),RHO_GTZ(MAXNGRID,NATOM),RHO_GTA(MAXNGRID,NATOM))
    ALLOCATE(Y_C(NCGS,NCGS,-CEL1X:CEL1X,-CEL1Y:CEL1Y,-CEL1Z:CEL1Z))
    IF ((IOPTN(36) > 0).OR.(IOPTN(37) > 0).OR.LOPTN(86)) THEN
     ALLOCATE(TRHO(MAXNGRID,NATOM))
     ALLOCATE(D2F1(MAXNGRID,NATOM))
    ENDIF
   ENDIF
   IF ((LOPTN(46).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0)).AND.(IOPTN(71) >= 3)) ALLOCATE(D1F1_GUESS(MAXNGRID,NATOM))
   IF ((LGC).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0)) THEN
    ALLOCATE(RHO_GX(MAXNGRID,NATOM),RHO_GY(MAXNGRID,NATOM),RHO_GZ(MAXNGRID,NATOM),GAMMA(MAXNGRID,NATOM),D1F2(MAXNGRID,NATOM))
!   ALLOCATE(RHO_GX_A(MAXNGRID,NATOM),RHO_GY_A(MAXNGRID,NATOM),RHO_GZ_A(MAXNGRID,NATOM))
    IF ((IOPTN(36) > 0).OR.(IOPTN(37) > 0).OR.LOPTN(86)) THEN
     ALLOCATE(TRHO_GX(MAXNGRID,NATOM),TRHO_GY(MAXNGRID,NATOM),TRHO_GZ(MAXNGRID,NATOM))
     ALLOCATE(D2F2(MAXNGRID,NATOM),D2F3(MAXNGRID,NATOM))
    ENDIF
   ENDIF
   IF ((DOPTN(24) /= 0.0D0).AND.(IOPTN(7) >= 1)) THEN
    ALLOCATE(SMN(NCGS,NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ,NATOM*3+1),&
             HMN(NCGS,NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ,NATOM*3+1),&
             JMN(NCGS,NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ,NATOM*3+1),&
             FMN(NCGS,NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ,NATOM*3+1))
   ENDIF
   IF (DOPTN(24) /= 0.0D0) ALLOCATE(QEPSILON(NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))
   IF (LOPTN(32)) THEN
    ALLOCATE(DEPSILON(NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))
    ALLOCATE(DPOLE(NCGS,-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))
   ENDIF
   ALLOCATE(IALL(-KVCX:KVCX,-KVCY:KVCY,-KVCZ:KVCZ))

   ! OVERLAP AND KINETIC INTEGRALS
   CALL PCPU_TIME(ICPUS)
   CALL OVERLAP_KINETIC(0)
   CALL LINEAR_DEPENDENCE
   CALL CLASSIFY_ORBITALS
   CALL CHECK_STORAGE
   CALL PCPU_TIME(ICPUE)
   IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (OVERLAP & KINETIC INTEGRALS) = ',ICPUE-ICPUS
   CALL PFLUSH(6)

   ! INITIAL GUESS
   CALL PCPU_TIME(ICPUS)
   CALL RESTORE_DENSITYMATRIX
   CALL PCPU_TIME(ICPUE)
   IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (RESTORE DENSITY MATRICES) = ',ICPUE-ICPUS
   CALL PCPU_TIME(ICPUS)
   CALL DECONTRACT_DENSITYMATRIX
   CALL PCPU_TIME(ICPUE)
   IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (DECONTRACT DENSITY MATRICES) = ',ICPUE-ICPUS
   CALL PCPU_TIME(ICPUS)
   CALL ROTATE_DENSITYMATRIX
   CALL PCPU_TIME(ICPUE)
   IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (ROTATE DENSITY MATRICES) = ',ICPUE-ICPUS
   CALL PFLUSH(6)

   ! NUCLEAR REPULSION ENERGY
   CALL NUCLEAR_REPULSION_CALC

   ! NUCLEAR ATTRACTION INTEGRALS
   CALL PCPU_TIME(ICPUS)
   CALL FMT_PRELIMINARY
   CALL NUCLEAR_ATTRACTION(0)
   CALL PCPU_TIME(ICPUE)
   IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (NUCLEAR ATTRACTION INTEGRALS) = ',ICPUE-ICPUS
   CALL PFLUSH(6)
   CALL PCPU_TIME(ICPUS)
   IF ((IOPTN(18) == 1).OR.LOPTN(86)) THEN
    CALL MOMENT(0)
    CALL PCPU_TIME(ICPUE)
    IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (MOMENT INTEGRALS) = ',ICPUE-ICPUS
    CALL PFLUSH(6)
   ENDIF

   ! TWO-ELECTRON INTEGRALS
!3 IF (LOPTN(46).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0)) THEN
!3  CALL PCPU_TIME(ICPUS)
!3  IF (IOPTN(71) == 1) CALL STORE_THREEINDEX_V
!3  IF (IOPTN(71) >= 2) CALL STORE_THREEINDEX_S
!3  CALL PCPU_TIME(ICPUE)
!3  WRITE(6,'(A,F10.1)') 'CPU / SEC (THREE-INDEX INTEGRALS) = ',ICPUE-ICPUS
!3 ENDIF
   IF ((.NOT.LOPTN(25)).AND.(.NOT.LOPTN(33))) THEN
    CALL PCPU_TIME(ICPUS)
!o  IF (NCGS == NPGS) THEN
!o   CALL STORE_FOURINDEX_ERI_PRIMITIVE
!o  ELSE 
     CALL STORE_FOURINDEX_ERI
!o  ENDIF
    CALL PCPU_TIME(ICPUE)
    IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (FOUR-INDEX TWO-ELECTRON INTEGRALS) = ',ICPUE-ICPUS
    CALL PFLUSH(6)
   ELSE IF (LOPTN(33)) THEN
    CALL PCPU_TIME(ICPUS)
!3  CALL STORE_THREEINDEX_V
!3  IF (LOPTN(31)) CALL STORE_THREEINDEX_S
    CALL PCPU_TIME(ICPUE)
    IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (THREE-INDEX INTEGRALS) = ',ICPUE-ICPUS
    CALL PFLUSH(6)
   ENDIF

   ! NUMERICAL QUADRATURE & INITIAL ELECTRON DENSITY
   IF ((LDFT).OR.(LOPTN(72)).OR.(LOPTN(73)).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0).OR.(LOPTN(46).AND.(IOPTN(71) >= 3))) THEN
    CALL PCPU_TIME(ICPUS)
    CALL CONSTRUCT_GRID
    CALL GRID_WEIGHT
    CALL INITIAL_ELECTRON_DENSITY
    CALL ELECTRON_DENSITY
    CALL INTEGRATE_ELECTRON_DENSITY
    D1F1=0.0D0
    XCF=0.0D0
    IF ((LGC).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0)) THEN
     CALL ELECTRON_DENSITY_GRADIENT
     D1F2=0.0D0
    ENDIF
    IF (DOPTN(20) /= 0.0D0) CALL SLATER_EXCHANGE(0)
    IF (DOPTN(21) /= 0.0D0) CALL VOSKO_WILK_NUSAIR_CORRELATION(0)
    IF (DOPTN(22) /= 0.0D0) CALL BECKE88_EXCHANGE(0)
    IF (DOPTN(23) /= 0.0D0) CALL LEE_YANG_PARR_CORRELATION(0)
    CALL PCPU_TIME(ICPUE)
    IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (DFT PRELIMINARY) = ',ICPUE-ICPUS
    CALL PFLUSH(6)
   ENDIF
   CALL PFLUSH(6)
   
   ! SELF-CONSISTENT FIELD
   IF (.NOT.LOPTN(33)) THEN
    IF ((DOPTN(98) > 0.0D0).AND.(MYID == 0)) THEN
     WRITE(6,'(A)') '******************************************'
     WRITE(6,'(A,E22.15,A)') '* TEMPERATURE = ',DOPTN(98),' K *'
     WRITE(6,'(A)') '******************************************'
    ENDIF
    CALL SELF_CONSISTENT_FIELD(.FALSE.,.FALSE.,.FALSE.,.FALSE.)
    IF (LOPTN(83)) THEN
     IF (DOPTN(98) > 0.0D0) CALL PABORT('NONZERO TEMPERATURE NOT YET TESTED FOR ASYMP KS-DFT')
     IF (MYID == 0) WRITE(6,'(A)') 'ASYMPTOTICALLY CORRECTED KS-DFT CALCULATION WILL BE PERFORMED'
     CALL SELF_CONSISTENT_FIELD(.FALSE.,.FALSE.,.FALSE.,.TRUE.)
    ENDIF
!o  IF (LOPTN(46)) THEN
!o   IF (DOPTN(98) > 0.0D0) CALL PABORT('NONZERO TEMPERATURE NOT YET TESTED FOR OEP')
!o   WRITE(6,'(A)') 'AN OPTIMIZED EFFECTIVE POTENTIAL CALCULATION WILL BE PERFORMED'
!o   IF (IOPTN(71) == 1) THEN
!o    WRITE(6,'(A)') 'V ALGORITHM WILL BE USED'
!o   ELSE IF (IOPTN(71) == 2) THEN
!o    WRITE(6,'(A)') 'S ALGORITHM WILL BE USED'
!o   ELSE IF (IOPTN(71) == 3) THEN
!o    WRITE(6,'(A)') 'GRID-S ALGORITHM WILL BE USED'
!o    WRITE(6,'(A)') 'GENERATE AN INITIAL SLATER POTENTIAL'
!o    CALL ELECTRON_DENSITY
!o    D1F1=0.0D0
!o    CALL SLATER51_EXCHANGE
!o    D1F1_GUESS=D1F1
!o   ELSE IF (IOPTN(71) == 4) THEN
!o    WRITE(6,'(A)') 'GRID-S ALGORITHM WILL BE USED'
!o    WRITE(6,'(A)') 'GENERATE AN INITIAL KLI POTENTIAL'
!o    CALL ELECTRON_DENSITY
!o    D1F1=0.0D0
!o    CALL KLI_EXCHANGE
!o    D1F1_GUESS=D1F1
!o   ELSE
!o    CALL PABORT('UNKNOWN ALGORITHM')
!o   ENDIF
!o   DOPTN(14)=DOPTN(14)*10.0D0
!o   WRITE(6,'(A,E24.15)') 'THRESHOLD OF CONVERGENCE WILL BE LOOSENED TO ',DOPTN(14)
!o   CALL SELF_CONSISTENT_FIELD(.TRUE.,.FALSE.,.FALSE.,.FALSE.)
!o   DOPTN(14)=DOPTN(14)*0.1D0
!o   WRITE(6,'(A,E24.15)') 'THRESHOLD OF CONVERGENCE IS BACK TO ',DOPTN(14)
!o  ENDIF
!o  IF (LOPTN(72)) THEN
!o   IF (DOPTN(98) > 0.0D0) CALL PABORT('NONZERO TEMPERATURE NOT YET TESTED FOR SLATER51')
!o   CALL ELECTRON_DENSITY
!o   D1F1=0.0D0
!o   CALL SLATER51_EXCHANGE
!o   WRITE(6,'(A)') 'A SLATER 1951 CALCULATION WILL BE PERFORMED'
!o   DOPTN(14)=DOPTN(14)*10.0D0
!o   WRITE(6,'(A,E24.15)') 'THRESHOLD OF CONVERGENCE WILL BE LOOSENED TO ',DOPTN(14)
!o   CALL SELF_CONSISTENT_FIELD(.FALSE.,.TRUE.,.FALSE.,.FALSE.)
!o   DOPTN(14)=DOPTN(14)*0.1D0
!o   WRITE(6,'(A,E24.15)') 'THRESHOLD OF CONVERGENCE IS BACK TO ',DOPTN(14)
!o  ENDIF
!o  IF (LOPTN(73)) THEN
!o   IF (DOPTN(98) > 0.0D0) CALL PABORT('NONZERO TEMPERATURE NOT YET TESTED FOR KLI')
!o   CALL ELECTRON_DENSITY
!o   D1F1=0.0D0
!o   CALL KLI_EXCHANGE
!o   WRITE(6,'(A)') 'A KRIEGER-LI-IAFRATE CALCULATION WILL BE PERFORMED'
!o   DOPTN(14)=DOPTN(14)*10.0D0
!o   WRITE(6,'(A,E24.15)') 'THRESHOLD OF CONVERGENCE WILL BE LOOSENED TO ',DOPTN(14)
!o   CALL SELF_CONSISTENT_FIELD(.FALSE.,.FALSE.,.TRUE.,.FALSE.)
!o   DOPTN(14)=DOPTN(14)*0.1D0
!o   WRITE(6,'(A,E24.15)') 'THRESHOLD OF CONVERGENCE IS BACK TO ',DOPTN(14)
!o  ENDIF
!o ELSE
!o  IF (DOPTN(98) > 0.0D0) CALL PABORT('NONZERO TEMPERATURE NOT YET TESTED FOR RI')
!o  IF (LOPTN(46).OR.LOPTN(72).OR.LOPTN(73)) CALL PABORT('RI FOR OEP, SLATER51, KLI IS NOT IMPLEMENTED')
!o  CALL RI_SELF_CONSISTENT_FIELD
    IF ((KVCX > 0).OR.(KVCY > 0).OR.(KVCZ > 0)) THEN
     CALL CALC_ENERGYBANDS(1)
    ENDIF
    CALL PRINT_ENERGYBANDS(1)
    IF ((PERIODX > 0.0D0).AND.(PERIODX == PERIODY).AND.(PERIODX == PERIODZ)) CALL DUMP_ENERGYBANDS_FCC
    IF (IOPTN(9) == 3) CALL DUMP_CRYSTALORBITALS
   ENDIF
   CLOSE(30) ! CLOSE CHECKPOINT FILE TO PROTECT DENSITY MATRIX

   ! ANALYTICAL ENERGY GRADIENTS FOR HF,DFT & MP2 THEORY
   IF (IOPTN(7) >= 1) THEN
    IF (MYID == 0) WRITE(6,'(A)') 'CALCULATE ENERGY GRADIENTS'
    CALL ROTATE_DENSITYMATRIX
    ! HELLMANN-FEYNMAN FORCES
    CALL PCPU_TIME(ICPUS)
    CALL HELLMANN_FEYNMAN_REPULSION
    CALL HELLMANN_FEYNMAN_ATTRACTION
    CALL PCPU_TIME(ICPUE)
    IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (HELLMANN-FEYNMAN FORCES) = ',ICPUE-ICPUS
    CALL PFLUSH(6)
    ! ONE-ELECTRON INTEGRAL DERIVATIVES
    CALL PCPU_TIME(ICPUS)
    CALL OVERLAP_KINETIC(1)
    CALL PCPU_TIME(ICPUE)
    IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (OVERLAP & KINETIC INTEGRAL GRADIENTS) = ',ICPUE-ICPUS
    CALL PFLUSH(6)
    CALL PCPU_TIME(ICPUS)
    CALL NUCLEAR_ATTRACTION(1)
    CALL PCPU_TIME(ICPUE)
    IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (NUCLEAR ATTRACTION INTEGRAL GRADIENTS) = ',ICPUE-ICPUS
    CALL PFLUSH(6)
    ! TWO-ELECTRON INTEGRAL DERIVATIVES
    CALL PCPU_TIME(ICPUS)
    CALL FOURINDEX_ERI_GRADIENT
    CALL PCPU_TIME(ICPUE)
    IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (ERI GRADIENTS) = ',ICPUE-ICPUS
    CALL PFLUSH(6)
    ! MULTIPOLE EXPANSION DERIVATIVES
    IF (IOPTN(18) == 1) THEN
     CALL PCPU_TIME(ICPUS)
     CALL MOMENT(1)
     CALL PCPU_TIME(ICPUE)
     IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (MULTIPOLE EXPANSION GRADIENTS) = ',ICPUE-ICPUS
     CALL PFLUSH(6)
    ENDIF
    CALL PFLUSH(6)
    ! EXCHANGE-CORRELATION INTEGRAL DERIVATIVES
    IF (LDFT) THEN
     CALL PCPU_TIME(ICPUS)
     IF (.NOT.LGC) CALL LOCAL_XC_GRADIENT
     IF (LGC) CALL GC_XC_GRADIENT
     CALL PCPU_TIME(ICPUE)
     IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (XC INTEGRAL GRADIENTS) = ',ICPUE-ICPUS
     CALL PFLUSH(6)
    ENDIF
    IF (MYID == 0) CALL DUMP0
    IF (MYID == 0) CALL DUMP2
    CALL PFLUSH(6)

   ! SINGLE-POINT MP2 ENERGY CALCULATIONS
   ELSE IF (DOPTN(24) /= 0.0D0) THEN
    IF (LOPTN(32)) THEN
     IF (DOPTN(98) > 0.0D0) CALL PABORT('NONZERO TEMPERATURE NOT YET TESTED FOR DYSON')
!call dyson_debug
!call pabort('debug stop')
     CALL DYSON
     IF ((KVCX > 0).OR.(KVCY > 0).OR.(KVCZ > 0)) THEN
      CALL CALC_ENERGYBANDS(3)
     ENDIF
     CALL PRINT_ENERGYBANDS(2)
     CALL PRINT_ENERGYBANDS(3)
    ELSE
     IF (DOPTN(98)==0.0D0) THEN
      IF (IOPTN(105) == 1) THEN
       CALL PCPU_TIME(ICPUS)
       CALL MP2_ENERGY_ALG1
       CALL PCPU_TIME(ICPUE)
       IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (TOTAL MP2 TIME) = ',ICPUE-ICPUS
       CALL PFLUSH(6)
      ELSE IF (IOPTN(105) == 2) THEN
       CALL PCPU_TIME(ICPUS)
       CALL MP2_ENERGY_ALG2
       CALL PCPU_TIME(ICPUE)
       IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (TOTAL MP2 TIME) = ',ICPUE-ICPUS
       CALL PFLUSH(6)
      ELSE IF (IOPTN(105) == 3) THEN
       CALL PCPU_TIME(ICPUS)
       CALL MP2_ENERGY_ALG3
       CALL PCPU_TIME(ICPUE)
       IF (MYID == 0) WRITE(6,'(A,F10.1)') 'CPU / SEC (TOTAL MP2 TIME) = ',ICPUE-ICPUS
       CALL PFLUSH(6)
      ELSE
       CALL PABORT('UNKNOWN MP2 ALGORITHM')
      ENDIF
     ELSE
!3    CALL FINITE_MP2_ENERGY
     ENDIF
     IF (IOPTN(44) > 0) THEN
      IF ((KVCX > 0).OR.(KVCY > 0).OR.(KVCZ > 0)) THEN
       CALL CALC_ENERGYBANDS(2)
      ENDIF
      CALL PRINT_ENERGYBANDS(2)
     ENDIF
    ENDIF
   ENDIF

   ! SINGLE-POINT CC ENERGY CALCULATIONS
   IF (COPTN(70) /= 'NONE') CALL COUPLED_CLUSTER_ENERGY

   ! CONFIGURATION INTERATION SINGLES CALCULATIONS
!3 IF (((IOPTN(36) > 0).OR.(IOPTN(37) > 0).OR.LOPTN(86)).AND.LOPTN(46)) ALLOCATE(KERNEL_CORE(NAGS,NAGS))
!3 IF (IOPTN(36) > 0) THEN
!3  IF (LOPTN(46)) CALL MAKE_KERNEL_CORE
!3  IF ((DOPTN(24) == 0.0D0).AND.(.NOT.LOPTN(43))) THEN
!3   IF (LOPTN(39)) THEN
!3    CALL GUESS_CISTRIALVECTOR
!3    CALL DAVIDSON_DIAGONALIZATION(1)
!3   ENDIF
!3   IF (LOPTN(40)) THEN
!3    CALL GUESS_CISTRIALVECTOR
!3    CALL DAVIDSON_DIAGONALIZATION(2)
!3   ENDIF
!3  ELSE
!3   IF (LOPTN(39)) THEN
!3    CALL GUESS_TRIALVECTOR(.FALSE.,LOPTN(43))
!3    CALL OLSEN_DIAGONALIZATION(.FALSE.,1,LOPTN(43))
!3   ENDIF
!3   IF (LOPTN(40)) THEN
!3    CALL GUESS_TRIALVECTOR(.FALSE.,LOPTN(43))
!3    CALL OLSEN_DIAGONALIZATION(.FALSE.,2,LOPTN(43))
!3   ENDIF
!3  ENDIF
!3 ENDIF

   ! TIME DEPENDENT RESPONSE THEORY CALCULATIONS
!3 IF (IOPTN(37) > 0) THEN
!3  IF (LOPTN(46)) CALL MAKE_KERNEL_CORE
!3  IF (LOPTN(39)) THEN
!3   CALL GUESS_TRIALVECTOR(.TRUE.,LOPTN(43))
!3   CALL OLSEN_DIAGONALIZATION(.TRUE.,1,LOPTN(43))
!3  ENDIF
!3  IF (LOPTN(40)) THEN
!3   CALL GUESS_TRIALVECTOR(.TRUE.,LOPTN(43))
!3   CALL OLSEN_DIAGONALIZATION(.TRUE.,2,LOPTN(43))
!3  ENDIF
!3 ENDIF

   ! POLARIZABILITY CALCULATIONS
!3 IF (LOPTN(86)) THEN
!3  IF (LOPTN(46)) CALL MAKE_KERNEL_CORE
!3  CALL MAKE_MULTIPOLE
!3  IF (LOPTN(89)) CALL POLARIZABILITY('X')
!3  IF (LOPTN(90)) CALL POLARIZABILITY('Y')
!3  IF (LOPTN(91)) CALL POLARIZABILITY('Z')
!3 ENDIF
!3 IF (((IOPTN(36) > 0).OR.(IOPTN(37) > 0).OR.LOPTN(86)).AND.LOPTN(46)) DEALLOCATE(KERNEL_CORE)

   ! HIGH-ORDER MP, CI, AND CC THEORIES
   IF ((IOPTN(49) > 0).OR.(IOPTN(51) > 0).OR.(IOPTN(53) > 0).OR.(IOPTN(97) > 0)) THEN
     IF (DOPTN(98)==0.0D0) THEN
      IF (.NOT.LOPTN(93)) CALL HIGHORDER_CORRELATION
!     IF (LOPTN(93))      CALL REL_HIGHORDER_CORRELATION
     ELSE
      CALL HIGHORDER_CORRELATION
      CALL THERMAL_CORRELATION
  !   CALL THERMAL_MBPT_HYBRID
      CALL THERMAL_MBPT_ANALYTICAL
      CALL THERMAL_MBPT_GENERALORDER
     ENDIF
   ENDIF

!  CALL SELFCONSISTENTDYSON

   ! SINANOGLU THEORY
   IF (LOPTN(94)) THEN
!    CALL CART_GRIDHF
!    CALL CART_GRIDMP2
!    CALL GRIDHF2
     CALL GRIDHF
     CALL GRIDMP2
   ENDIF

   ! DUMP POTENTIALS AND/OR DENSITIES
!3 IF (IOPTN(74) /= 0) THEN
!3  CALL ELECTRON_DENSITY
!3  CALL ELECTRON_DENSITY_GRADIENT
!3  CALL INTEGRATE_ELECTRON_DENSITY
!3  CALL POTENTIAL_DUMP
!3 ENDIF
!3 IF ((IOPTN(75) /= 0).AND.((IOPTN(74) == 0).OR.(IOPTN(71) <= 2))) THEN
!3  CALL ELECTRON_DENSITY
!3  CALL ELECTRON_DENSITY_GRADIENT
!3  CALL INTEGRATE_ELECTRON_DENSITY
!3  CALL DENSITY_DUMP
!3 ENDIF

   ! DEALLOCATE ARRAYS
   DEALLOCATE(PAX,PAY,PAZ)
   DEALLOCATE(PGSX,PGSY,PGSZ)
   DEALLOCATE(PGS_ATOM)
   DEALLOCATE(CGSX,CGSY,CGSZ)
   DEALLOCATE(ZT)
   DEALLOCATE(CC)
   DEALLOCATE(C2S)
   DEALLOCATE(C2H,P2H,C2H_THETA,P2H_THETA)
   DEALLOCATE(P_SHELL,P_SHELL_ANG)
   IF (LOPTN(33).OR.LOPTN(34)) THEN
    DEALLOCATE(AAX,AAY,AAZ)
    DEALLOCATE(AGSX,AGSY,AGSZ)
    DEALLOCATE(AGS_ATOM)
    DEALLOCATE(AZT,ANORM)
    DEALLOCATE(A_SHELL,A_SHELL_ANG)
   ENDIF
   DEALLOCATE(S_P,S_C)
   DEALLOCATE(F_C)
   DEALLOCATE(T_C)
   DEALLOCATE(N_C)
   DEALLOCATE(C_C)
   DEALLOCATE(X_C)
   IF (LOPTN(46).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0)) DEALLOCATE(O_C)
   IF (LOPTN(46).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0)) DEALLOCATE(CHI_INVERSE)
   DEALLOCATE(M_C,MPE_C)
   DEALLOCATE(P_P,P_C,P_C_OUT,W_P,W_C)
   DEALLOCATE(P_P_HELIX,P_C_HELIX,W_P_HELIX,W_C_HELIX,P_P_HELIX_THETA,P_C_HELIX_THETA,W_P_HELIX_THETA,W_C_HELIX_THETA)
   DEALLOCATE(CO,EPSILON)
   DEALLOCATE(PULAY)
   IF ((LDFT).OR.(LOPTN(72)).OR.(LOPTN(73)).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0).OR.(LOPTN(46).AND.(IOPTN(71) >= 3))) THEN
    DEALLOCATE(NGRID,GRIDX,GRIDY,GRIDZ,ATOMW,FUZZY,GRIDW)
    DEALLOCATE(GRIDW_X,GRIDW_Y,GRIDW_Z)
    DEALLOCATE(GRIDW_TX,GRIDW_TY,GRIDW_TZ,GRIDW_TA)
    DEALLOCATE(RHO,D1F1,XCF)
!   DEALLOCATE(RHO_GTX,RHO_GTY,RHO_GTZ,RHO_GTA)
    DEALLOCATE(Y_C)
    IF ((IOPTN(36) > 0).OR.(IOPTN(37) > 0).OR.LOPTN(86)) THEN
     DEALLOCATE(TRHO)
     DEALLOCATE(D2F1)
    ENDIF
   ENDIF
   IF ((LOPTN(46).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0)).AND.(IOPTN(71) >= 3)) DEALLOCATE(D1F1_GUESS)
   IF ((LGC).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0)) THEN
    DEALLOCATE(RHO_GX,RHO_GY,RHO_GZ,GAMMA,D1F2)
!   DEALLOCATE(RHO_GX_A,RHO_GY_A,RHO_GZ_A)
    IF ((IOPTN(36) > 0).OR.(IOPTN(37) > 0).OR.LOPTN(86)) THEN
     DEALLOCATE(TRHO_GX,TRHO_GY,TRHO_GZ)
     DEALLOCATE(D2F2,D2F3)
    ENDIF
   ENDIF
   IF ((DOPTN(24) /= 0.0D0).AND.(IOPTN(7) >= 1)) THEN
    DEALLOCATE(SMN,HMN,JMN,FMN)
   ENDIF
   IF (DOPTN(24) /= 0.0D0) DEALLOCATE(QEPSILON)
   IF (LOPTN(32)) DEALLOCATE(DEPSILON,DPOLE)
   DEALLOCATE(IALL)

   ! CLOSE FILES
   IF (.NOT.LOPTN(25)) CLOSE(31)
   IF (LOPTN(33).OR.LOPTN(34)) CLOSE(32)
   IF (LOPTN(34)) THEN
    CLOSE(33)
    CLOSE(34)
    CLOSE(35)
   ENDIF
   IF ((IOPTN(36) > 0).OR.(IOPTN(37) > 0).OR.LOPTN(86)) THEN
    CLOSE(36)
    CLOSE(37)
    CLOSE(38)
   ENDIF
   IF (LOPTN(46).OR.(IOPTN(74) /= 0).OR.(IOPTN(75) /= 0)) THEN
    IF (IOPTN(71) == 1) CLOSE(32)
    IF (IOPTN(71) >= 2) CLOSE(35)
   ENDIF

   RETURN
END SUBROUTINE
